### ISSUE TITLE
Add single card focus with back button

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#102]
Remove the accordion style opening and closing of items in the issues and instead open individual issues as well as "new issue" creation into a separate view within the same card. Add back button to the top bar as needed. Also, when at it, move the three dot burger button to the left side and change it to the arrow button as and when needed.

Get inspiration from this (as usual)
![image](https://cloud.githubusercontent.com/assets/3008807/11712226/7d1ab7b6-9f23-11e5-8c9d-378fa3cae5bd.png)

**Comment by camden-kid** [comment]
Done and merged into master.
