### ISSUE TITLE
Installation issue on Windows 

### ISSUE THREAD

**Issue by webdada** [3drepo/3drepo.io#1029]
### Description

Following the Installation guide on 3drepo.io Web server, installation Step 6 failed. 

gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build,
please add the \"/m\" switch.
TRACKER : error TRK0005: Failed to locate: \"CL.exe\". The system cannot find th
e file specified. [C:\\dev\\3drepo\\3drepo.io\\backend\\node_modules\\utf-8-vali
date\\build\\validation.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\msbuild.exe`
 failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\\tools\\nvm\\v9.2.0\\node_modules\
\npm\\node_modules\\node-gyp\\lib\\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:209:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command \"C:\\\\nodejs\\\\node.exe\" \"C:\\\\nodejs\\\\node_modules\\\\
npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"
gyp ERR! cwd C:\\dev\\3drepo\\3drepo.io\\backend\\node_modules\\utf-8-validate
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok"
success Saved lockfile.
Done in 25.22s.

### Steps to replicate

cd backend
yarn install

**Comment by webdada** [comment]
I have used nvm to switch node.js to version 6.11.2 as specified in the Installation document. Ran the backend installation again and got same error:

gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0

**Comment by carmenfan** [comment]
Hi,
Apologies, the README is a bit out of date. You need the LTS version of Node (8.11.3) - though it probably still runs on v6, it is not supported.

Also, you can ignore these errors as they are optional dependencies:
![image](https://user-images.githubusercontent.com/11945337/41427724-ba5ac152-6fff-11e8-8e72-0a8e025eea0b.png)

**Comment by webdada** [comment]
Thanks Carmen.

Would Node 9.2.0, or 10.0.0 work ? How about Python 3.6.0 (instead of v 2.7) ?

Dependencies
Python (v 2.7)
Node.js (v 6.11.2)
npm + yarn
MongoDB
RabbitMQ
3DRepoBouncer

**Comment by carmenfan** [comment]
Hi,

Node versions higher may work, but I cannot support this. The current LTS is 8.11.3 and as a company decision we've decided to stick to LTS versions and will not consider upgrades until they become LTS.

I don't think Python is a dependency anymore. It is a need from x3dom, which we have deprecated as of v2.12 (latest release)

Hope this helps.
Carmen
