### ISSUE TITLE
Move edit button

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#105]
As much as I don't like it, I propose we move the edit button to the bottom of a card with a massive round clickable coloured icon on top of the issues, as done in gmail and other apps. This will save space at the top bar and would make it far more obvious for users to find.

See here
![image](https://cloud.githubusercontent.com/assets/3008807/11712226/7d1ab7b6-9f23-11e5-8c9d-378fa3cae5bd.png)

**Comment by camden-kid** [comment]
This is done but with a plus symbol on a green button.
