### ISSUE TITLE
Bugs http://35.177.78.92

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1061]
- [ ] Views card doesn't load https://github.com/3drepo/3drepo.io/issues/1061#issuecomment-406299737

**Comment by paloknapo** [comment]
**Show closed and sub-model issues toggle works the other way round **

**Comment by paloknapo** [comment]
**Views card doesn't load**

Message "Loading viewpoints" never goes away and + button doesn't show up. I can't create views.

**Comment by carmenfan** [comment]
staging was using old version of code. Reopen if you see it again but I think it's fixed by upgrading
