### ISSUE TITLE
Reduce timestamp on issues

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#107]
Display timestamp on issues in a reduced format as follows:
- if it is the same date as today, display only time (as AM, PM however make note for localisation as in other languages time would be listed as 3:00 in the morning and 15:00 in the afternoon)
- if it is within the same year, display day and month, eg 29 Sep
- if not within the same year, display month and abbreviated year, eg Sep '15

See this for inspiration
![image](https://cloud.githubusercontent.com/assets/3008807/11712226/7d1ab7b6-9f23-11e5-8c9d-378fa3cae5bd.png)

**Comment by camden-kid** [comment]
Done, shown and approved.
