### ISSUE TITLE
Make top card bar double as searchbar

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#108]
Same as on adroid, make the top bar in each card (those that need search) into a search bar. Upon pressing the magnifying glass, the text of the top bar should be replaced with words like Filter or Search and the colour of the bar should also change. The three dot burger button should be on the left and magnifying glass on the right.

![image](https://cloud.githubusercontent.com/assets/3008807/11712226/7d1ab7b6-9f23-11e5-8c9d-378fa3cae5bd.png)

**Comment by camden-kid** [comment]
This is done but the burger button is still on the right. I think it's nice to have the card icon on the left but let's leave it like that for now until further UI redesign discussions.
