### ISSUE TITLE
User Management: Redirection from Teamspaces

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1086]
### Description
We should maintain the current functionality and add the possibility of redirection from the "Teamspaces" view to the "User Management" view for a specific model or federation - to manage permissions.

### Goals
- [x] Admins can go to permissions settings directly from "Teamspace" view

### Tasks
- [x] Teamspaces to User Management navigation

**Comment by carmenfan** [comment]
Merged into #1085
