### ISSUE TITLE
User panel: UI improvements

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1087]
### Description
User panel (panel on the left side) should be narrower. Avatar should be removed.

### Goals
- [x] Refreshed panel

### Tasks
- [x] Add new styles to the panel

**Comment by carmenfan** [comment]
Can we keep the avatar for now? I think you can narrow the panel to as narrow as you need it without removing the avatar.

**Comment by simplypixi** [comment]
Sure, we can ;)
