### ISSUE TITLE
Notifications first version

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1168]
### Description
Adding notifications so the user con be fully aware of the state of the projects and his responsibilities in them.

### Goals
- [x] Users can see a new bell icon through out the application in the top right
![image](https://user-images.githubusercontent.com/42032433/45955918-1be48580-c009-11e8-9cde-d2731fa9101a.png)

- [x] The bell icon will have a number showing the amount of unread notifications.

- [x] Clicking on this bell will display a list of the notifications 
![image](https://user-images.githubusercontent.com/42032433/45955932-2e5ebf00-c009-11e8-9d26-5314b4b304b7.png)

- [ ] There will be several types of notifications : 
  - **New Issues**
  - **Assigned Issues**
  - **Updated Issues**
  - **Model Update**

- [x] The issues will ordered chronologically and divided by weeks
- [x] The amount / type of issues will depend on the role of the user.
- [x] The Issue has the status of unread or read.

- [x] Once the user clicked on the issue inside the list, the notification is mark as read and the application should redirect to the view of the application related to that issue. E.g. : If the notification involves a new assignment on an issue you click the notification and the application redirects to the model -> issue-list -> issue that the notification refers to.

- [ ] The notifications can be filtered by team space or by model through a hamburger menu 
- [x] The users will be able to mark a notification as read
- [x] The users will be able to delete a notification

#### Frontend
- [x] Bell button with unread notifications number
- [x] Notification list with data from the database
- [x] Hookup to notifications from chat server
- [ ] Hamburger menu with
  - Filter options
  - Delete option
 - Mark as read option
- [x] URL routing to specific notification data (this will come in handy when we make the email notification stuff)
- [x] Link notification to specific url and when clicked mark it as read

#### Backend
- [x] Minor refactor so it will be easy to hook up to model data changes and create new notifications.
- [x] Notifications db model, the model file that allows to create/update/delete/query notifications.
- [x] Notifications middleware: create/update/delete notifications according to the applications objects model data being modified (for example a update of an issue that changes who is assigned to it -> create an issue_assigned notification).
- [x] Chat service middleware refactor: convert chat service used in the backend to a middleware that is easy to hookup to data models being modified
- [x] Chat service for notifications.

**Comment by carmenfan** [comment]
Feedback from show and tell:
- Remove Assign notification if issue is closed
- Add teamspace on the notification (`teamspace.model`? or `model(teamspace)`)?
- Change model without reloading viewer on clicking notification?
- less padding around the notification? (squish the height)
- tooltip on the label to show the name 
- change mark as read icon? (ask pavol)
