### ISSUE TITLE
Race condition on mongo save causing federations/models to occasionally fail in saving

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1174]
- [ ] [Can't save federation](https://github.com/3drepo/3drepo.io/issues/1174#issuecomment-425377207)

**Comment by horandago** [comment]
This is the error in the web server's log message
![screenshot from 2018-10-02 16-29-03](https://user-images.githubusercontent.com/23435379/46359454-3b129100-c661-11e8-8ea3-2a504be4b564.png)

**Comment by horandago** [comment]
Carmen: "Version error is from mongoose,, it puts in a version property where it increments every time it updates that file and it complains if say you update a file with a v:1 after it's saved as v:2"
My work around of increasing the network speed will work until the code is fixed
