### ISSUE TITLE
Migration: Profile

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1184]
#### Description
This issue includes migration of Profile view.

#### Goals
Migration of Profile view to ReactJS

#### Tasks

- Main route
- Component to edit profile data
- Refactor and move old logic to new component

**Comment by simplypixi** [comment]
@carmenfan 
Like I said before, this view requires a few design fixes. So I prepared for you design for Profile view.

![image](https://user-images.githubusercontent.com/5683490/46479481-6a570880-c7ef-11e8-89dc-4d9073cdd56b.png)

I'll add editable avatar in the first section
Is the design ok for you? Do you have different idea?

**Comment by carmenfan** [comment]
@simplypixi yea looks fine, if we can have the "Must be at least 8 characters" message in red and only appears if the user typed something in there (i.e. more like an error message) that'd be great

**Comment by simplypixi** [comment]
> @simplypixi yea looks fine, if we can have the "Must be at least 8 characters" message in red and only appears if the user typed something in there (i.e. more like an error message) that'd be great

Sure, it's a piece of cake
