### ISSUE TITLE
Migration: Billing

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1185]
#### Description
This issue includes migration of Billing view.

#### Goals
Migration of Billing view to ReactJS

#### Tasks

- Main route
- Component to edit profile data
- Component to display history
- Refactor and move old logic to new components

**Comment by simplypixi** [comment]
@carmenfan  I have a few questions about this page. ;)

1. Could you describe to me how this page works (mainly "Subscription" tab)? 
2. What should happen after sending the form with new data e.g with a changed number of licences?
3. Could you send me access data to paypal sandbox? I'll need to test the subscription update after migration.

**Comment by simplypixi** [comment]
> There are 3 types of licenses:
> 
> 1. paypal - which cames from paypal, added and removed from the subscription page.
> 2. discretionary - promotional, free ones that we add on by hand
> 3. enterprise - paid licenses that are done through the business department negotiating with customer face to face, add on by hand

Ok, so I have one extra questions.
What is happening with form fields, if the user has an enterprise or discretionary licenses?
What is the general purpose of the plans? Are they dedicated to handling PayPal licenses?

![image](https://user-images.githubusercontent.com/5683490/46943956-270f5c00-d071-11e8-9bbc-7e424a388dfc.png)

> Yes, let me send it to you via email :)
Hehe, sure! ;)

**Comment by carmenfan** [comment]
> What is happening with form fields, if the user has an enterprise or discretionary license?
Absolutely nothing. enterprise licenses and discretionary licenses doesn't show up on the license count at the moment. Having said that, it's also very unlikely that a paypal user has any discretionary/enterprise licenses.

> What is the general purpose of the plans? Are they dedicated to handling PayPal license?
They map to paypal license's quota and price. for e.g. we have just launched the 2018 plan, so the old plan is no longer active, but it will still be supported for any existing users holding that license type.
