### ISSUE TITLE
Migration: Dashboard

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1186]
#### Description
This issue includes migration of Dashboard view.

#### Goals
Migration of Dashboard view to ReactJS

#### Tasks

- Main route
- Refactor and move old logic to new route
- Component to display menu on the left side (current accountInfo)
- Component to display menu top (current accountMenu)
- Move routing from UI-Router (and ngIf’s) to React Router

**Comment by simplypixi** [comment]
@carmenfan I would like to change the routing in this step of migration, because it'll be hard to change it later (without big issues).
Did you think about how it should looks like?

In my opinion it should be something like this:
- `/:username/viewer`
    with sub-routes e.g `/:username/viewer/:modelId`

- `/:username/dashboard/:teamspace`
   with sub-routes e.g `/:username/dashboard/:teamspace/projects-permissions/:projectName`

It will provide url structure related (more or less) with components structure. Moreover, we will can manage views/routes using native React solutions (same functionality, far less code, faster development). We shouldn't parse query string each time we want to decide which view/route should be visible. Whats more, using this solution we can still use query string to pass extra data to views.

**Comment by carmenfan** [comment]
@simplypixi that's fine, but what I'd propose is currently the left panel adds a query string to the url (i.e. `?page=teamspace`, `?page=UserManagment` etc), so if we can infuse that within the route so we can avoid having a mix and match that'd be great.

Maybe something like `/:username/dashboard/teamspace-view/:teamspace...`, `/:username/dashboard/userManagement/:teamspace...` etc? (whatever naming works best)

**Comment by simplypixi** [comment]
> that's fine, but what I'd propose is currently the left panel adds a query string to the url (i.e. ?page=teamspace, ?page=UserManagment etc), so if we can infuse that within the route so we can avoid having a mix and match that'd be great.

@carmenfan Yes, I know about it. I'll migrate the left panel in this step too. After migration of nested dashboard's views.
We can (and we should) place most of params directly in route. 

So... are you in? :)

**Comment by carmenfan** [comment]
@simplypixi My only worry is that the state manager currently in our code base is quite a beast and it might break a lot of things. If you're confident about this then sure 😛

**Comment by carmenfan** [comment]
@simplypixi thinking about it do we even need `:username` in the route?

**Comment by simplypixi** [comment]
@carmenfan I'working now on new routing and I have two questions:
1. Which requirements should the `legalPages` meet to be visible? Are they visible for all users (logged in and logged out) 

2. Which requirements should the `loggedOutPages` meet to be visible? Are they visible only for logged out users?

3. What is the use case of preparing app states on backend side? Is it mandatory?
![image](https://user-images.githubusercontent.com/5683490/47490985-1b2e5180-d84a-11e8-960d-bdb78a2b7652.png)

**Comment by carmenfan** [comment]
> @carmenfan I'working now on new routing and I have two questions:
> 
> 1. Which requirements should the `legalPages` meet to be visible? Are they visible for all users (logged in and logged out)
Legal pages(which are the bottom right links you can see on our production server) should be visible for any users

> 2. Which requirements should the `loggedOutPages` meet to be visible? Are they visible only for logged out users?
Yes

> 3. What is the use case of preparing app states on backend side? Is it mandatory?
>    ![image](https://user-images.githubusercontent.com/5683490/47490985-1b2e5180-d84a-11e8-960d-bdb78a2b7652.png)
I believe it was some legacy design that we have ditched, so there isn't any reason that the app states are prepared on the backend. The whole team here agrees that it should be done by the frontend side. :)

**Comment by simplypixi** [comment]
@carmenfan Do you know why it's happening? I have always the same situation while loading the model locally (regardless of a branch)
![image](https://user-images.githubusercontent.com/5683490/47505191-f5b33f00-d86d-11e8-8ebc-7cb62822b551.png)

Thanks in advance ;)

**Comment by carmenfan** [comment]
@simplypixi 

Not something that' sbeen happening here, but I believe it's related to the 404 error on `unity.data`. Which is weird, as the actual filename is unity.data.unityweb...

This is defined in frontend/unity/Build/unity.json as the `dataUrl`. If you trace through your code to see why / where it's getting this `unity.data` as the `dataUrl` it should give you some clues...

**Comment by simplypixi** [comment]
> @simplypixi
> 
> Not something that's been happening here, but I believe it's related to the 404 error on `unity.data`. Which is weird, as the actual filename is `unity.data.unityweb`...
> 
> This is defined in `frontend/unity/Build/unity.json` as the `dataUrl`. If you trace through your code to see why / where it's getting this `unity.data` as the `dataUrl` it should give you some clues.

@carmenfan I've investigated that issue and... it's weird but I think that unity settings are loaded from config file - not from unity.json. When I set proper URLs here, everything started to work ok.

![image](https://user-images.githubusercontent.com/5683490/47650722-68c7f880-db81-11e8-8086-0d3a1d8bbffc.png)

**Comment by carmenfan** [comment]
@simplypixi  you can remove the whole thing and just use default settings, it should work fine.

**Comment by simplypixi** [comment]
@carmenfan Ok! ;)
