### ISSUE TITLE
Add card for revision history

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#120]
The card should list available branches (eg a dropdown or something) and then the list of available revisions that can be clicked. This same card can also integrate ability to select revisions for diff (how to do so visually I'm not yet sure).

Use this icon:  fa-code-fork [&#xf126;]

**Comment by jozefdobos** [comment]
This has now been also requested by client:

"Is there a way of adding a means of determining what dates the individual NWC files where issued within the 3D Repo model?"

**Comment by timscully1983** [comment]
Complete by in drop-down menu.
