### ISSUE TITLE
Build-analyzing tools

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1231]
#### Goals
Control over the build size and building time while migration and development. Moreover, it'll be used to decrease build size when the app will be fully migrated to React.

#### Tasks
- Add new run-command `yarn build:analyze`
- Add new webpack config
- Add `Webpack Bundle Analyzer` plugin

**Comment by simplypixi** [comment]
@carmenfan I've checked the issue on my Mac and everything seems to be fine. I think it's because of building time. Webpack is starting to watch changes **after** initial incremental build (webpack needs to build the whole app for the first time). Building time (and size) for the production build increased, so also for the development build. But most of the build time takes typescript's type-checking.

I have three solutions for this issue:

1. Trying to speed up the build before we remove Angular from the stack (which is a bit complicated)
2. Disabling type-checking for development build (But we should do this only if your IDE's provide type-checking out of the box - e.g VSCode does)
3. Increasing performance after migration of the app

Which approach do you prefer?

**Comment by carmenfan** [comment]
@simplypixi 

Is it possible to do no.2 but make it type check on travis? In that case we can speed up the turn around time whilst development but we can still catch the problems @ auto test

**Comment by simplypixi** [comment]
@carmenfan 
Yes, it's possible. I'll disable type-checking only for the development build. I saw in `.travis.yml` that build is run on production mode on Travis, so everything will work as you suggest.

Are you in? :)

**Comment by carmenfan** [comment]
Yea let's try that :)

**Comment by simplypixi** [comment]
@carmenfan 
I've added changes to this branch. Please, check `watch` one more time on this branch (and run `yarn` if you didn't before because I updated webpack version to the newest). 🤞 
Thanks!

**Comment by carmenfan** [comment]
working! 🎊

**Comment by simplypixi** [comment]
Great! ;)
