### ISSUE TITLE
Migration: Login

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1233]
### Description
Migration of login page, connected subpages (forgot password, password change) and user session to React.

### Tasks
- Create a new login container
- Move user session to redux store (remove any connections with stateManager)
- Create a new password forgot' container
- Create a new password change' container

**Comment by simplypixi** [comment]
@carmenfan I prepared the refreshed layout for login page. Do you like it? Or maybe should I revert to the previous version?

![image](https://user-images.githubusercontent.com/5683490/48207599-4d26d400-e371-11e8-83b0-75106f2a26f3.png)

**Comment by carmenfan** [comment]
Looks good! I sent it around the company and everyone agreed :)

**Comment by simplypixi** [comment]
> Looks good! I sent it around the company and everyone agreed :)

Cool!
