### ISSUE TITLE
Migration: GIS

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1249]
### Description
Migration of GIS panel.

### Tasks
- Create a new panel component
- Create a new GIS component
- Adapt the panel service and component to handling React components

### Extras 
- design: https://xd.adobe.com/view/8a6b23f1-36b6-4419-5fe3-78a60d7ee17d-fc5a/
- if maps are configured show map layers as it is now
- if maps are not configured display model settings with save button in the toolbar at the bottom of the card as shown in prototype
- add menu button in the header
- menu has only one option "Settings" to open settings in card again in case user wants to change them

**Comment by carmenfan** [comment]
@

> Hi @paloknapo !
> 
> You wrote: "if maps are not configured display model settings with save button in the toolbar at the bottom of the card as shown in prototype"
> 
> ![screenshot 2018-11-26 at 10 14 02](https://user-images.githubusercontent.com/17221890/49004213-10761d80-f164-11e8-9407-538954681c19.png)
> 
> But, should it be a form, right? I ask because i can see only dislaying some data with no any inputs.

Yes it should be a form, it's basically the GIS part within model settings 

also, we should probably remove elevation from this. As it is not used right now and we don't plan to add anything that requires it in the near future.

**Comment by dleszcz** [comment]
Thanks @carmenfan 
And if maps are not configured it should be a default view with disabled menu button? or hidden?

**Comment by carmenfan** [comment]
> Thanks @carmenfan ,
> Also:
> 
> 1. If maps are not configured. Settings should be a default view with disabled menu button? or hidden? or with link to map layers?
> 2. If maps are configured and user go to settings. How to get back to the map layers view? By link in menu list?  or some back arrow?
> 
> cc: @paloknapo

1. Settings should be a default view, with the back arrow disabled. 
2. I think we should have a back arrow like the other tabs on the settings page.

In general once the user saved the settings with GIS values they should be directed to the map layers view.

**Comment by dleszcz** [comment]
Thanks @carmenfan @paloknapo, everything is clear now 👍
