### ISSUE TITLE
Stash generation should use relative paths

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#126]
It seems that Pavol had a stash with example.org hardcoded in the paths. Therefore, his 3D model was not showing up. Deleting the stash and letting the server regenerate fixed Pavol's problem at least. In ideal world all urls should be relative I would have thought.

**Comment by carmenfan** [comment]
Just to elaborate what we found, Pavol was trying to load the 3D Repo logo on rackspace server and the selection tree showed up but not the model. Looking into the console it was showing up with an error saying something along the lines of you cannot have a http request in https or something, and the url is http://example.org/....../ . The situation was very similar to the other week when i couldn't see the clinic model so i suggested Pavol to delete the stash.src.* and stash.x3d.* ... and the logo magically appeared.

**Comment by timscully1983** [comment]
Not applicable
