### ISSUE TITLE
Add docs card to new UI

### ISSUE THREAD

**Issue by camden-kid** [3drepo/3drepo.io#127]

**Comment by timscully1983** [comment]
Done.

**Comment by jozefdobos** [comment]
It would be good to have some kind of + button there to be able to add docs using drag and drop and attach to selected geometry.

**Comment by timscully1983** [comment]
Extra functionality marked will be added after this next release.

**Comment by camden-kid** [comment]
Can I close this as we will probably rethink this for the MVP?

**Comment by jozefdobos** [comment]
You can close this but do open a new issue for the ability to add (plus button or drag 'n drop) more data to docs card
