### ISSUE TITLE
 Clicking on notification reloads even if model is opened

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1290]
**Clicking on notification reloads even if model is opened**

Clicking on the notification should only load the model if the model is not already loaded.

![project](https://user-images.githubusercontent.com/760452/49954149-b614e500-fef7-11e8-8dee-b61614afa332.gif)

**Comment by carmenfan** [comment]
@simplypixi 

At the moment clicking on the notifications reload the viewer regardless of the state. Ideally we'd only want to reload if:
- We are not on viewer
- We are on the viewer but the teamspace/modelId doesn't match.

We tried looking at it and we're a bit clueless, and wondered if it's because the viewer is still in angular whereas the notification service is now on react. Is this possible at the moment?

**Comment by simplypixi** [comment]
@carmenfan 
It's because of the difference between UI Router and React Router in managing browser history. ;)

It's possible, but the solution will be very dirty.

**Comment by carmenfan** [comment]
This is fixed with the ReactRouter update
