### ISSUE TITLE
Rid of the "there's a new version of 3drepo" message once and for all.

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1292]
### Description
We want to get rid of this message and just load the latest when available. Things that may help: setting cache control to no-cache policy ?

My theory : we currently have no cache control policy, which means we're under the mercy of the browsers. Which result in occasionally, if we update the servers too frequently, there are times when the cache is not invalidated and thus the message doesn't pop up.

### Goals
- Is there a way to ensure the client doesn't load the cache if it's invalid? `no-cache` is suppose to check for validation before loading, so maybe that's the way
- if the above happens, we can get rid of the dialog asking for refresh.

**Comment by simplypixi** [comment]
Three ideas:
1. Well-prepared service-worker.
2. Adding `chunkhash` or `contenthash` to production build. You can easily achieve that using webpack (15min of work ;)).
3. (old way) Adding `version` at the end of URL e.g. `/3drepo.js?123`, which changes on each build.

**Comment by simplypixi** [comment]
@carmenfan Resolved here #1590 (using service worker)

**Comment by carmenfan** [comment]
closing in favour of #1590
