### ISSUE TITLE
Settings menu

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1316]
### Description
We need to add a settings menu to user. Configurations to add:

- 3drepo Lite mode
- Shadows (hard/soft/none)
- Show statistics
- XRay highlighting
- Memory for Unity

Advanced options (probably never used by users but may be useful exposed for admins/troubleshooting):
- minimum near plane 
- Sphere/box collider algorithm
- far plane sampling points

Things we don't have but it will be viable to add in:
- Quality option - allowing user to turn off anti aliasing
- Artistic rendering mode
- Different Skybox
- Colour scheme
- Ability to tweak light intensity(?)
(More to follow)

**Comment by sanmont3drepo** [comment]
Mockup:

https://xd.adobe.com/view/0f70aec7-fde1-4538-4b12-57d056bae899-7941/

**Comment by carmenfan** [comment]
@paloknapo  @sanmont3drepo  re: mockup. I think it's important to make the tab a distinct grouping within the panel. As it stands it looks like the the 3 buttons at the bottom is associated with the tabs (i.e. clicking save in the advance tab looks like has nothign to do with saving settings in basic tab).

I.e. something like this:
![image](https://user-images.githubusercontent.com/11945337/52781932-ad4ea580-3045-11e9-8911-ee6801523a51.png)

**Comment by carmenfan** [comment]
Also we should change the colouring of reset to something else. It's useful to have different colouring/styling system for [positive/neutral/negative actions](https://uxmovement.com/buttons/how-button-color-contrast-guides-users-to-action/).

**Comment by carmenfan** [comment]
![image](https://user-images.githubusercontent.com/11945337/52942772-8bb22e80-3363-11e9-9623-c4411480b933.png)

Sphere algorithm doesn't mean anything to anyone.
It should be `Far plane algorithm` with a selection of `Bounding box` (default) and `Bounding Sphere`
