### ISSUE TITLE
Can't save Risk on Prod

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1320]
I can't save Risk with collaborator's permissions in someone else's teamspace. 
(I was able to save Issue in the same model)

1. open model in other teamspace with collaborator permissions
2. create risk
3. this error pops up

![image](https://user-images.githubusercontent.com/760452/50894244-a5726480-13fa-11e9-900f-cc4fd927e0f4.png)

**Comment by carmenfan** [comment]
I just found out we can't save views either.

**Comment by carmenfan** [comment]
@Charence  if it helps to identify where you need to make the change, here's a bunch of stack traces:
![image](https://user-images.githubusercontent.com/11945337/50900395-f723ea80-140c-11e9-857a-c75761c43b77.png)

**Comment by Charence** [comment]
@Charence Remember to upgrade amqplib
