### ISSUE TITLE
Improve error message for unverified users

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1327]
### Description
Improved error message for unverified users

### Steps to replicate
- Sign up
- Ignore verification e-mail
- Attempt to login

### Pictures/ Gifs of the error
A 400 error is thrown at the moment. This does not inform the user that the problem is due to the account being inactive and that the activation link in the e-mail should be clicked.

![screenshot 2019-01-14 17 58 54 2](https://user-images.githubusercontent.com/1438332/51131062-86bf0400-1826-11e9-86cd-5b8de0a9b1ce.png)

**Comment by carmenfan** [comment]
![image](https://user-images.githubusercontent.com/11945337/51178617-ff6fa000-18ba-11e9-9f66-b37b7350ce2d.png)
This is the culprit in `backend/response_codes.js`
