### ISSUE TITLE
Cleanup Tasks

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepo.io#134]
- [x] Convert all Javascript objects to use prototype 
- [x] Remove all magic constants
- [x] JSLint configuration

**Comment by thenrikie** [comment]
Done. But after I merged master there are some new jshint errors. We have to run grunt jshint:backend to check the our new code every time before we commit.

**Comment by timscully1983** [comment]
- [ ] Add some tests for db_interface.js and db.js
