### ISSUE TITLE
Bugs from View migration

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1344]
### Bugs
- [x] [Cannot create views if the views component has no entry](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457215895)
- [x] [When you exit an existing model and enter a different mode, the last model is being loaded](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457178131)

**Comment by carmenfan** [comment]
@simplypixi Regarding [this](https://github.com/3drepo/3drepo.io/issues/1342#issuecomment-457178131). What I observe is that the culprit is the new function `mapPropsToThis`

First model it loads it's fine (let's call this modelA), everything works fine.
When you exit the viewer and select another model from teamspace (let's call this modelB), I see that `mapPropsToThis` triggers `handleSettingsChange` with modelA again, then it triggers it with modelB. The 2 commands seems to trigger pretty much simultaneously which causes some race conditiosn within the unity viewer. all in all `handleSettingsChange` should only be called once with modelB settings.

Side note:
`mapPropsToThis` is a pretty terrible naming, can we change it? It's also kind of inaccurate for maps to depict what model to be loading (perhaps it's a temporary setup before it's fully migrated?) The settings in question is the model settings, and it should really be the model component retrieving this and passing it to whoever need it.

**Comment by simplypixi** [comment]
> Side note:
> `mapPropsToThis` is a pretty terrible naming, can we change it? It's also kind of inaccurate for maps to depict what model to be loading (perhaps it's a temporary setup before it's fully migrated?) The settings in question is the model settings, and it should really be the model component retrieving this and passing it to whoever need it.

I think this name is good, because is created in react/redux stack naming convention (mapStateToProps, mapDispatchToProps). We wanted to emphasize that this method bind values from React store to model component. And yes, is a temporary method.
Nevertheless, we can change the name if you have a better idea. :)

**Comment by carmenfan** [comment]
> > Side note:
> > `mapPropsToThis` is a pretty terrible naming, can we change it? It's also kind of inaccurate for maps to depict what model to be loading (perhaps it's a temporary setup before it's fully migrated?) The settings in question is the model settings, and it should really be the model component retrieving this and passing it to whoever need it.
> 
> I think this name is good, because is created in react/redux stack naming convention (mapStateToProps, mapDispatchToProps). We wanted to emphasize that this method bind values from React store to model component. And yes, is a temporary method.
> Nevertheless, we can change the name if you have a better idea. :)

Yea I talked to @sanmont3drepo about this and he figured it's to do with the redux namings.

I guess the main problem for us is when we look at this and it's in the angular side of the system, it doesn't make too much sense and it's not immediately clear that it's basically subscribing to the modelSettings data within the state. Afterall the function should really be describing what the function is doing, which seems to be checking whether there has been a change in model settings. So we think it is probably better read as `OnModelSettingsChange` ?

We were also wondering why it's returning `{settings}`, initially we were thinking maybe because the model component is updating the state, but it doesn't seem to be the case?

**Comment by simplypixi** [comment]
> Yea I talked to @sanmont3drepo about this and he figured it's to do with the redux namings.
> 
> I guess the main problem for us is when we look at this and it's in the angular side of the system, it doesn't make too much sense and it's not immediately clear that it's basically subscribing to the modelSettings data within the state. Afterall the function should really be describing what the function is doing, which seems to be checking whether there has been a change in model settings. So we think it is probably better read as `OnModelSettingsChange` ?

Ok! Sounds good ;)

> We were also wondering why it's returning {settings}, initially we were thinking maybe because the model component is updating the state, but it doesn't seem to be the case?

It's the way, how the `mapStateToProps` works. Behind the scenes, `mapStateToProps` selects required values from the store, modifies them (or not) and then returns to Redux subscriber. Returned values are bound to component props - in this case to model component context (because is not React component).
In short: this return statement defines, what should be merged into component context.

This solution seems to be weird but I think is the only proper bridge between Angular and Redux Store - if you don't want to increase app size using extra libraries like ngRedux.
