### ISSUE TITLE
Dev 3.3.0 bugs

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1377]
### Bugs
- [x] Can't copy API key in Firefox
- [x] [Model doesn't load or loads wrong one](https://github.com/3drepo/3drepo.io/issues/1377#issuecomment-463314834)
- [x] [Filter Issues by Issue Name](https://github.com/3drepo/3drepo.io/issues/1377#issuecomment-463626652)

**Comment by paloknapo** [comment]
**Can't copy API key in Firefox**

![image](https://user-images.githubusercontent.com/760452/52715533-956b1900-2f94-11e9-86ad-fe38e89510de.png)

**Comment by paloknapo** [comment]
**Model doesn't load**

1. log in and open a model
2. go back to teamspaces
3. open the same model

issues, views, ... load OK but model doesn't load, there is no progress bar, no error in console 
reload helps

**Comment by carmenfan** [comment]
> 
> 
> **Model doesn't load or loads wrong one**
> 
>     1. log in and open a model
> 
>     2. go back to teamspaces
> 
>     3. open the same model; issues, views load OK but model, tree doesn't load, there is no progress bar, no error in console
> 
>     4. go back to teamspaces
> 
>     5. open other model; sometimes the previous model loads on top of the current one
> 
> 
> reload helps

@simplypixi I think this is related to your change on how the viewer loads the model? (Detection of model ID change within the settings?) I guess if the user goes back to the same model, the model ID is unchanged thus it doesn't trigger a reload. What do you think is the best way to solve this?

**Comment by BDavydov** [comment]
### Filter Issues by Issue Name
Open a model or Federation. Create some issues and start filtering the list by Issue names. 

### Pictures/ Gifs of the error
![image 1](https://user-images.githubusercontent.com/19904513/52789578-1e00bc80-305c-11e9-912c-ee5af15c228f.jpg)

![image 2](https://user-images.githubusercontent.com/19904513/52789641-4d172e00-305c-11e9-8453-67a5502b7064.jpg)

**Comment by simplypixi** [comment]
> > **Model doesn't load or loads wrong one**
> > ```
> > 1. log in and open a model
> > 
> > 2. go back to teamspaces
> > 
> > 3. open the same model; issues, views load OK but model, tree doesn't load, there is no progress bar, no error in console
> > 
> > 4. go back to teamspaces
> > 
> > 5. open other model; sometimes the previous model loads on top of the current one
> > ```
> > reload helps
> 
> @simplypixi I think this is related to your change on how the viewer loads the model? (Detection of model ID change within the settings?) I guess if the user goes back to the same model, the model ID is unchanged thus it doesn't trigger a reload. What do you think is the best way to solve this?

Yes, it is. I'm working on fix. ;)

**Comment by simplypixi** [comment]
> **Can't copy API key in Firefox**
> ![01](https://user-images.githubusercontent.com/760452/52715563-a74cbc00-2f94-11e9-8106-3a2081dea5d5.gif)

Fixed. You used `disabled` instead of `readonly`. ;)

**Comment by simplypixi** [comment]
> > > **Model doesn't load or loads wrong one**
> > > ```
> > > 1. log in and open a model
> > > 
> > > 2. go back to teamspaces
> > > 
> > > 3. open the same model; issues, views load OK but model, tree doesn't load, there is no progress bar, no error in console
> > > 
> > > 4. go back to teamspaces
> > > 
> > > 5. open other model; sometimes the previous model loads on top of the current one
> > > ```
> > > reload helps
> > 
> > 
> > @simplypixi I think this is related to your change on how the viewer loads the model? (Detection of model ID change within the settings?) I guess if the user goes back to the same model, the model ID is unchanged thus it doesn't trigger a reload. What do you think is the best way to solve this?
> 
> Yes, it is. I'm working on a fix. ;)

Fixed ;)
I've tested it on models from Assorted Models Selection (T_E_S_T)
