### ISSUE TITLE
Smart Groups - details/new

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1387]
- [x] Add/Edit form
- [x] Display selected group logic
- [x] Set color (ColorPicker) logic
- [x] Reloading logic
- [x] Save logic
- [x] Listening on click on object (Selection mode)
- [x] Permissions
- [x] Creating criteria component
   - [x] fields autocomplete (fetching used fields included)
   - [x] Creating a constant with possible operations + showing list
   - [x] Component for adding many fields
   - [x] Add criteria logic
   - [x] Options menu (copy, paste, deselect, clear)
- [x] Edit existing criteria
- [x] Switching between groups (header)
- [x] Chat Events

### Extra notes
General
- Slight change in the layout of the group details
- A new group type on ui : Selection (normal), by criteria (smart)
- UI changes depending on group type
- do not add bin/attachment icon on edit group tab.
- add previous/next buttons on the top header like issues/risks
- “reset” button  for selection type: it should re-highlight what was last saved
- for criteria: it should highlight base on what are the current criteria
- Upon save, smart groups should update highlight with the latest criteria.
- Reuse colour picker for groups colour.

Criteria display:
- Criteria area contains existing rules as chips, unlike issue/risk search, but user cannot type new ones directly.
- User selects a chip -> rule info gets filled in the grey area (edit rule mode)
- User can deselect a chip by clicking on the background of the criteria area, which empties the values in the grey area (new rule mode)
- There can only be 1 rule per field.
- See operations tab on sketch  to see how the chips should be formatted
- long chips should shorten with “...”
- User can copy rules clicking on “copy” in hamburger button, but instead of copy the chip string, it should copy the json array of criterias.
- User can paste JSON array that will populate the chips area with new rules (paste should be in hamburger menu, with a pop up text box to take in the json)

Rule creation edit area:
- Field names are based on a API endpoint that gives you the list of metadata fields, but user can also put in something that doesn’t exist.
- Field textbox should function similar like user search in user management.
- operation is a determined list as shown
- Hit confirm button to add new criteria in chips area
- grey area should be scrollable separately to the whole tab.

Operations characteristics:
- Exists/ not exists should not have a value textbox.
- text operations should start with 1 value text box, with the ability to add more multiple text boxes, which can be deleted (apart from the last one)
- Regex Only allow 1 textbox, with an “i” button which links to the blog about it.
- Greater/smaller should only have 1 text box.
- range values should only have 2 text box in the same line.

**Comment by simplypixi** [comment]
@paloknapo @carmenfan 
I've noticed one feature, which we are not able to implement properly. I mean "Paste critieria".

![image](https://user-images.githubusercontent.com/5683490/53403638-4e2d5100-39b4-11e9-9bf9-f15c014736a3.png)

It's because of security reasons. Browsers block direct access to the clipboard. It's possible to get clipboard data only when the user calls `paste` event e.g using keyboard's shortcut. So, we can't get copied data on mouse click.
To achieve a similar effect, we can use localSotrage/sessionStorage, but then we'll lose the capability to cross-browser pasting.

What do you think about it?

**Comment by carmenfan** [comment]
@simplypixi  I think I wrote on the notes, but the idea was to pop up a text box for the user to paste in the criteria.

Would that help the situation?

**Comment by simplypixi** [comment]
@carmenfan I had to overlook it. 

Sure, we can do this in this way. ;)

**Comment by dleszcz** [comment]
Hello @paloknapo @carmenfan 
Is this search input necessary? We have Select component that allows searching (without input). Can we use it?

**Comment by carmenfan** [comment]
@dleszcz I'm not 100% sure what/which one you mean. Do you mean the field input on the edit/add criteria bit? If that's the it's a yes as we need to allow user to type in something that may not necessary exist.

I know Pavol drew a drop down menu there but it probably should just be a plain text field. basically We need what we already have on `User Management`: 
![1](https://user-images.githubusercontent.com/11945337/53566302-afd7f180-3b53-11e9-8819-442033b08f5f.gif)


Is this too complicated?

**Comment by dleszcz** [comment]
@carmenfan I edited my question (screenshot attached) Its about Field
![screenshot 2019-02-28 at 13 29 38](https://user-images.githubusercontent.com/17221890/53566609-f4b45600-3b5c-11e9-83e2-05add331027d.png)

**Comment by carmenfan** [comment]
@dleszcz in that case Yes my last reply stands. But I think we don't need the additional search field. It should just be an inline search like the user management example on my previous reply.

**Comment by dleszcz** [comment]
> @dleszcz in that case Yes my last reply stands. But I think we don't need the additional search field. It should just be an inline search like the user management example on my previous reply.

ok, thanks @carmenfan ;)

**Comment by dleszcz** [comment]
> Regex Only allow 1 textbox, with an “i” button which links to the blog about it.

@carmenfan Where is the link? ;) we should provide some tooltip?

**Comment by carmenfan** [comment]
> > Regex Only allow 1 textbox, with an “i” button which links to the blog about it.
> 
> @carmenfan Where is the link? ;) should we provide some tooltip?

@dleszcz  use https://3drepo.com/blog/ for now

@paloknapo  is in the midst of making a blog post for this which will include explanations etc. We can change the link when it's online :)

What kind of tooltip do you have in mind?

**Comment by dleszcz** [comment]
> What kind of tooltip do you have in mind?
Something like this 
![screenshot 2019-03-01 at 12 00 09](https://user-images.githubusercontent.com/17221890/53634203-db251400-3c19-11e9-9d23-0da71839c3bc.png)

**Comment by carmenfan** [comment]
> > What kind of tooltip do you have in mind?
> 
> Something like this
> ![screenshot 2019-03-01 at 12 00 09](https://user-images.githubusercontent.com/17221890/53634203-db251400-3c19-11e9-9d23-0da71839c3bc.png)

sure! sounds good :)

**Comment by dleszcz** [comment]
Ok, what is the content of this button? for clarity, I'm asking for Regex info button tooltip text ;)

**Comment by carmenfan** [comment]
I'd say "Regex Cheat Sheet"

But let me confirm with @paloknapo

**Comment by dleszcz** [comment]
![screenshot 2019-03-04 at 10 42 14](https://user-images.githubusercontent.com/17221890/53724496-4b29d900-3e6a-11e9-982e-c1e53308a4e2.png)

Hello @carmenfan 
After creating group in returned object from Chat event some data is missing.
 - _Author_  property
 - _shared_ids_ is empty array

Could you look at it? :)

**Comment by carmenfan** [comment]
@Charence Can you take a look?

**Comment by carmenfan** [comment]
@dleszcz this should now be fixed in #1326 ! :)
