### ISSUE TITLE
Email validation regex needs to be relaxed

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1398]
### Description
We have some clients trying to register with a email address that ends with `.global`

Our current regex is as follows:
````js
  emailRegex = /^(['a-zA-Z0-9_\-.]+)@([a-zA-Z0-9_\-.]+)\.([a-zA-Z]{2,5})$/;
````
Which restrict the text behind the last set of . to be between 2-5 characters.
We should probably relax this rule (2+ characters?)

**Comment by Charence** [comment]
Apparently you can also have ".travelersinsurance" or ".northwesternmutual" as a TLD. They are 18 chars long [[source]](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains).
