### ISSUE TITLE
Blank page after selecting country for sign-up

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1404]
### Description
Page sometimes goes blank when selecting a country from the sign-up dropdown

This doesn't always happen. Problem seems to exist on master as well.

### Steps to replicate
- Go to Sign-Up page
- Complete details (not sure if this is necessary)
- Select Country from drop down
- _Page goes blank_

### Pictures/ Gifs of the error
![feb-27-2019 16-52-45](https://user-images.githubusercontent.com/1438332/53507766-61bde200-3ab0-11e9-9432-5819d6c01e2a.gif)
![feb-27-2019 16-59-15](https://user-images.githubusercontent.com/1438332/53508134-122be600-3ab1-11e9-80fb-0c2bd02e9b0a.gif)

**Comment by dleszcz** [comment]
@Charence  Does this issue still occur?

**Comment by carmenfan** [comment]
I don't think i've seen it for a while. closing it
