### ISSUE TITLE
run_app.cmd can not work

### ISSUE THREAD

**Issue by wsdflink** [3drepo/3drepo.io#141]
![12](https://cloud.githubusercontent.com/assets/4362868/12229915/0a72703c-b887-11e5-884b-46ee22e744a5.png)
And after i change the values of "cookie_secret" and "cookie_parser_secret" in config\dev\config.js , it still not seem to work. What's the problem?
    cookie_secret: "MySecret",
    cookie_parser_secret : "MyAnothersecret",

**Comment by timscully1983** [comment]
The configuration section for cookies has slightly changed, due to an increasing number of options.

I have now updated the config_sample.js on the master branch, and also updated the online wiki documentation.

**Comment by timscully1983** [comment]
Complete. Sent instructions.
