### ISSUE TITLE
As MC I want to create project so I can input summary about a bid

### ISSUE THREAD

**Issue by camden-kid** [3drepo/3drepo.io#142]
UI
- [ ] Change projects display to list of projects with a possible add/edit B4F project
- [ ] Above button takes user to new page
- [ ] New page has list of B4F projects
- [ ] New page has a form with title and summary text input plus a button to create/edit project

BE
- [ ] add flag to current project listing API to tell if a project has a bid
- [ ] API to create a bid for a project
- [ ] API to view a bid

**Comment by timscully1983** [comment]
Complete.
