### ISSUE TITLE
PDF Issues Print

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepo.io#143]
Add the ability to print a PDF of the issues.

**Comment by jozefdobos** [comment]
Just generate raw plain text HTML output on a single page (don't even need any fancy CSS). Once a page, this can be conveniently saved as PDF via the web browser printer functionality.

**Comment by timscully1983** [comment]
This sounds like more effort than what I was thinking which was just to implant the card in a separate tab.  In your suggestion I would have to convert the JSON format from the rest API into a html page.

**Comment by jozefdobos** [comment]
It needs to be a jade template with a few for loops, one for open and one for closed issues and inside each issue, loop over all comments. Just listing the card and printing it won't show the comments I think.

**Comment by timscully1983** [comment]
Ok, if you insist. It's either that three loops or two variables. I prefer two variables.

**Comment by timscully1983** [comment]
What information do you want to show on the issues ?

**Comment by jozefdobos** [comment]
Same as on the web, ie the number and name of the issue, timestamp, user who created it, assigned roles, comments underneath with their respective authors and timestamps. That should be it I think (assuming you split open and closed issues into two separate groups).
