### ISSUE TITLE
MetaKeys are being fetched when we fetch modelsettings

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1465]
### Description
It looks like when we get model settings, it automatically fetches metaKeys.
![image](https://user-images.githubusercontent.com/11945337/55732951-d3c10980-5a14-11e9-9b1c-744b96a5be70.png)

This is currently causing errors for models that are brand new, as the collection that stores the metadata doesn't exist yet:

### Pictures/ Gifs of the error
![2](https://user-images.githubusercontent.com/11945337/55734444-7ed2c280-5a17-11e9-9d91-7921e7ee4ee2.gif)

**Comment by carmenfan** [comment]
@Charence Can you look into checking if the collection exists to prevent the error?

@simplypixi  @dleszcz Can we detach the meta Keys from model Settings? The meta keys is actually quite an intensive query if the model is big, and we definitely don't need to run it everytime we fetch model settings (like on the teamspace UI).

**Comment by simplypixi** [comment]
> @Charence Can you look into checking if the collection exists to prevent the error?
> 
> @simplypixi @dleszcz Can we detach the meta Keys from model Settings? The meta keys is actually quite an intensive query if the model is big, and we definitely don't need to run it everytime we fetch model settings (like on the teamspace UI).

Ok!

**Comment by dleszcz** [comment]
@carmenfan @simplypixi @sanmont3drepo 
https://github.com/3drepo/3drepo.io/pull/1466
