### ISSUE TITLE
Hyperlinks don't work

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1503]
Hyperlinks are not highlighted and don't work across viewer UI. 

![image](https://user-images.githubusercontent.com/760452/57517393-a5ce2e00-730e-11e9-9273-286e5ad6a724.png)

**Comment by sanmont3drepo** [comment]
> Hyperlinks are not highlighted and don't work across viewer UI.
> 
> ![image](https://user-images.githubusercontent.com/760452/57517393-a5ce2e00-730e-11e9-9273-286e5ad6a724.png)

just one note: in mitigation is an editable field so there the hyperlinksshould not work
