### ISSUE TITLE
yarn build randomly fails catastrophically

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1507]
### Description
Sometimes `yarn build` fails with a very long list of errors.

E.g.
- `Module parse failed: Unexpected token (56:16)`
- `TS2686: 'angular' refers to a UMD global, but the current file is a module. Consider adding an import instead.`
- `TS6142: Module '../../../helpers/migration' was resolved to '/Users/charencewong/Workspace/3drepo.io/frontend/helpers/migration.tsx', but '--jsx' is not set.`

The problem disappears if you run `yarn build` again. It also happens on Travis.

@simplypixi @dleszcz Any ideas?

### Steps to replicate
- `cd frontend`
- `yarn build`

### Pictures/ Gifs of the error

![Screenshot 2019-05-10 11 25 06(2)](https://user-images.githubusercontent.com/1438332/57520869-b08cc100-7316-11e9-8a93-9de42f5abbe0.png)
![Screenshot 2019-05-10 11 25 00(2)](https://user-images.githubusercontent.com/1438332/57520876-b4204800-7316-11e9-8c31-ae2fd523b5c4.png)
![Screenshot 2019-05-10 11 24 49(2)](https://user-images.githubusercontent.com/1438332/57520882-b682a200-7316-11e9-8a9f-d0200aceb142.png)

**Comment by simplypixi** [comment]
@Charence Did you change something in build's config recently?

**Comment by Charence** [comment]
@simplypixi 

I didn't change the build's config. It started happening around 3-4 weeks ago, presumably after something updated in staging?

- webpack 4.24.0
- node v10.15.1
- ts-loader 6.0.0
- typescript 3.4.5

`yarn build:dev` works fine.

**Comment by carmenfan** [comment]
@simplypixi  here's [one ](https://travis-ci.org/3drepo/3drepo.io/builds/531849408)that failed on travis

**Comment by simplypixi** [comment]
> * ts-loader 6.0.0

In `package.json` ts-loader version is set to: `4.3.0`. :) I'll check if it's the reason.

**Comment by simplypixi** [comment]
> @simplypixi here's [one ](https://travis-ci.org/3drepo/3drepo.io/builds/531849408)that failed on travis

I built that commit locally - and it doesn't work.
I start the investigation. ;)

**Comment by simplypixi** [comment]
@carmenfan It stopped showing... How important is it for you?

**Comment by carmenfan** [comment]
> @carmenfan It stopped showing... How important is it for you?

Like Charence says, it happens sometimes and if you rerun it may work. I am wondering if its something to do with an asynchronous problem? Because sometimes it understands tsx and sometimes it doesn't.

It's not the end of the world, but it's quite disruptive as `yarn build` takes forever to run so we end up babysitting travis quite a bit to ensure test passes before we merge :s

**Comment by simplypixi** [comment]
> > @carmenfan It stopped showing... How important is it for you?
> 
> Like Charence says, it happens sometimes and if you rerun it may work again. I am wondering if its something to do with an asynchronous problem? Because it looks like sometimes it understands tsx and sometimes it doesn't.

I think is something on the library level. I'll try to update loaders and webpack. Then, we will have to observe the situation. If it won't work, I'll create an issue in webpack's and ts-loader's repository.

**Comment by Charence** [comment]
@simplypixi @carmenfan It looks like it still happens https://travis-ci.org/3drepo/3drepo.io/builds/533867793?utm_source=github_status&utm_medium=notification

**Comment by simplypixi** [comment]
Ugh 😞
