### ISSUE TITLE
Compare doesn't reset

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1509]
1. open model with revisions
2. click on Compare button to 3D Diff, wait for the result
3. leave to Teamspaces
4. open some other model - Diff is still active

It's the same with Clash.

**Comment by carmenfan** [comment]
This is fixed here https://github.com/3drepo/3drepo.io/commit/f38f2ca6abe7f3b14ab11cd9c614d9ece6f7dc45

patched into production along with the last patch.
