### ISSUE TITLE
We're not really deleting entries from sharedData.

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1518]
![image](https://user-images.githubusercontent.com/11945337/57785681-1e2b5980-772a-11e9-90cf-f2630dc010fb.png)

It's complaining about us trying to remove a directory that has data in it.

**Comment by Charence** [comment]
This is an io log?

**Comment by carmenfan** [comment]
This is io log when after a successful upload of a new revision. When it tries to clear up the data that was plonked into nfs to share with bouncer.

**Comment by Charence** [comment]
I was only able to replicate failure to delete non-empty directories. Sometimes it attempts to delete the directory before the files within get deleted. I'm using `fs-extra` to remove non-empty directories. Not sure if this is desirable.
