### ISSUE TITLE
Model Options Response (Teamspaces)

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1519]
### Description
No response when hovering over the options bar for individual models in the teamspaces. Federation options seem to keep floating without disappearing..

### Steps to replicate
- Log in to your account and open a project in the teamspaces. 
- Hover over the pop-up options list for individual models

![Model Options](https://user-images.githubusercontent.com/19904513/57860487-dc171c00-77ec-11e9-94df-7a7ac9f4b612.gif)

**Comment by carmenfan** [comment]
@simplypixi @dleszcz any idea what this may be?

**Comment by simplypixi** [comment]
> @simplypixi @dleszcz any idea what this may be?
@carmenfan 
Probably it's racing of event handlers.
Should we start fixing this? Can we wait until we finished tree migration?

**Comment by carmenfan** [comment]
@simplypixi 
It's not mission critical. If you want a break from tree then feel free, if not then maybe concentrate on the tree :)

**Comment by carmenfan** [comment]
Closing this issue as teamspaces is getting revamped.
