### ISSUE TITLE
Cache-Control on UnityWeb

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#1522]
### Description

It would be good if the client could cache the unityViewer as it's downloading 28.6 mb each time and the viewer's not changing often.

/unity/Build/unity.asm.code.unityweb

it appear to be setting cache-control to 0 

Cache-Control: public, max-age=0

### Goals

- [ ] UnityWeb is cached appropriately

### Tasks

- [ ] Update cache-control in the app?

**Comment by simplypixi** [comment]
@carmenfan Resolved here #1590 (using service worker)

**Comment by carmenfan** [comment]
closing in favour of #1590
