### ISSUE TITLE
Disable clipping plane card when not visible

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#154]
The UI selectors should be set as disabled when the eye icon is set as not visible. The user should not be able to drag the value nor change the axis, etc.

Something along these lines:
![image](https://cloud.githubusercontent.com/assets/3008807/12389537/50bc717e-bdd1-11e5-88f8-26d24bb0ef92.png)

**Comment by camden-kid** [comment]
Done and merged into pilot.
