### ISSUE TITLE
models/federations not honouring helicopter speed after a refresh

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1548]
### Description
The user changes the  helicopter speed, It looks like the speed is saved and retrieved upon refresh, but it is not being set on the actual helicopter speed.

### Steps to replicate
- load a model
- Change into helicopter mode
- Increase/decrease speed significantly
- hit refresh
- change into helictoper mode, the speed is still set to 1

### Pictures/ Gifs of the error
![2](https://user-images.githubusercontent.com/11945337/58698777-e102d080-8393-11e9-8f56-0ec538186482.gif)

**Comment by carmenfan** [comment]
@simplypixi @dleszcz 

Our clients reported this bug. Can you guys take a look at it?

**Comment by simplypixi** [comment]
> @simplypixi @dleszcz
> 
> Our clients reported this bug. Can you guys take a look at it?

Sure ;)

**Comment by dleszcz** [comment]
@simplypixi @carmenfan @sanmont3drepo 
https://github.com/3drepo/3drepo.io/pull/1552
