### ISSUE TITLE
Pin isn't saved with an Issue on slow connection

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#1554]
Pin isn't saved with an Issue on slow connection. This doesn't happen always but often user has to create pin twice. 

1. throttle connection (Slow 3G in Chrome)
2. create issue
3. create and save pin
4. submit issue

![01](https://user-images.githubusercontent.com/760452/58810038-00f4f700-8615-11e9-952a-fcfbeb3c826c.gif)

https://www.3drepo.io/viewer/pavol/43b988d9-5525-4b70-a898-9692ffa39a20?issueId=32540f10-860c-11e9-b179-79856ea5b1f8

**Comment by carmenfan** [comment]
I think this is solved by https://github.com/3drepo/3drepo.io/issues/1527

Reopen if you found it on any version after 3.7.2
