### ISSUE TITLE
Issue pins should colour by Priority/status

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1600]
### Description
Similar to Risks. issue pins should be coloured by priority. The only exception is if the issue is closed.

`None` or empty or unknown value(through BCF): Black
`Low`: Yellow
`Medum`: Orange
`High`: Red
Closed issue: Green

**Comment by Charence** [comment]
Pin not displayed if issue is closed even if it is being viewed

**Comment by Charence** [comment]
Need to check if the new pin colours look ok
