### ISSUE TITLE
BIM Card Layout improvement

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1601]
### Description
BIM Cart needs to extend a bit more to the right, since livechat icon is now on the left side. Text is hard to read when it is too long. Place the word on the next line if possible. Trailing letters become confusing to read when there is a lot of text and looks messy.

### Tasks

- [x] Update the size of BIM Card.
- [x] Clean up text layout in parameter & value fields

### Picture of the error

![BIM Cart](https://user-images.githubusercontent.com/19904513/60664376-aa6c1a00-9e59-11e9-9076-fbb8805f8e80.jpg)

**Comment by carmenfan** [comment]
@dleszcz @simplypixi Can you guys look into this please? :)

**Comment by simplypixi** [comment]
@carmenfan Yep. We can do that while model/viewer migration (which is happening now ;)). Is it ok for you or do you need those fixes earlier?

**Comment by carmenfan** [comment]
@simplypixi  that's fine, it's not super urgent :)

**Comment by simplypixi** [comment]
Resolved here: #1539
