### ISSUE TITLE
Add a config to allow get the front end to talk in https when the server actually uses http

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1611]
### Description
For deployment situations where we want to the load balancer to deal with SSL traffic and certificates, we want to spin up a web server that listens to http traffic, but the outside world (i.e. front end) still thinks we're using https.

Adding a new config for load balancer config that states the external port and protocol, that doesn't get influenced by internal traffic type/port

**Config changes**:
- following items in config.servers are no longer taken into account (i.e. it will be ignored):
    - http_port
    - https_port
    - port (unless it's chat server)
    - public_port
    - public_protocol
- Chat server configuration will take in a number in `port`  instead of `http_port`
- Chat now has a boolean flag `chatOnPublicPort` to allow chat to use the same public port as other servers (default: `false`)
- there are new configurations on the root level of the config file:
    - public_protocol: `http` or `https` (default: `https`  if ssl is configured)
    - public_port: the port the end users need to connect to (default: same as port)

**Comment by keifgwinn** [comment]
#1515 around the same area?

**Comment by carmenfan** [comment]
> #1515 around the same area?
Changes the same files but not the same section of code.
