### ISSUE TITLE
Can not attach Resource to issues assigned to me

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1613]
### Description
Can not attach resource to the issue. It has been assigned to me by another user and I am a collaborator. Also does not work for Commenter

### Steps to replicate
- Get another user to create an issue and assign it to your account.
- Open the issue and try attaching resource

### Pictures/ Gifs of the error

![Attach Resource](https://user-images.githubusercontent.com/19904513/61471308-770dad00-a97a-11e9-91c3-7c8db6941372.gif)

**Comment by carmenfan** [comment]
Closing this in favour of #1614
