### ISSUE TITLE
Issue pins sometimes don't appear

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1630]
### Description
Issue pins sometimes don't appear

### Steps to replicate
1. Go to teamspace
2. Find a model with issue pins
3. Go to Step 1 if pins appear
4. Click on an issue with pins and all pins should appear

### Pictures/ Gifs of the error
![Jul-24-2019 13-52-28](https://user-images.githubusercontent.com/1438332/61795039-6ea1f000-ae1a-11e9-87e6-edfdc2b6f505.gif)

**Comment by carmenfan** [comment]
@simplypixi  any ideas? could this be an async problem?

**Comment by simplypixi** [comment]
> @simplypixi any ideas? could this be an async problem?

Yes, it's the async problem. Is it happening on model/viewer migration branch?

**Comment by carmenfan** [comment]
We're seeing it in staging. @Charence  can you check?

**Comment by carmenfan** [comment]
I'm closing this. Reopen if we see it again
