### ISSUE TITLE
Teamspaces: Searching

### ISSUE THREAD

**Issue by simplypixi** [3drepo/3drepo.io#1639]

**Comment by simplypixi** [comment]
@carmenfan I have some questions about the searching 

1. BE doesn't return any information about the model type (`GET /:teamspace`). Could you add it on this branch?

2. Can we merge selected filters into a new one called `By data type`? (less work)
![image](https://user-images.githubusercontent.com/5683490/62126925-19118b80-b2d1-11e9-8ed8-e61d1c536a56.png)

**Comment by simplypixi** [comment]
> 2. Can we merge selected filters into a new one called `By data type`? (less work)
>    ![image](https://user-images.githubusercontent.com/5683490/62126925-19118b80-b2d1-11e9-8ed8-e61d1c536a56.png)

To be sure, these filters show/hide specific data type on the list. Am I right?

**Comment by simplypixi** [comment]
@carmenfan Friendly reminder ^ :P

**Comment by carmenfan** [comment]
> > 1. Can we merge selected filters into a new one called `By data type`? (less work)
> >    ![image](https://user-images.githubusercontent.com/5683490/62126925-19118b80-b2d1-11e9-8ed8-e61d1c536a56.png)
> 
> To be sure, these filters show/hide specific data type on the list. Am I right?

Those checks were for pure text search. The ticks is to show at what level we search on. e.g. if I am searching for "a", with all ticked, it will show (and highlight the found text) where the name of the ts/project/model satisfy this search. Unchecking ts would only search on project/model etc.

So it shouldn't hide the data types, it just doesn't run the search on them.

So it kind of works differently to the bottom bit i guess?

I'm not really sure what's the best layout to be honest.

**Comment by carmenfan** [comment]
> BE doesn't return any information about the model type (GET /:teamspace). Could you add it on this branch?

Yes. probably friday

**Comment by simplypixi** [comment]
> So it kind of works differently to the bottom bit i guess?
> 
> I'm not really sure what's the best layout to be honest.

Yes and ok ;)
I'll try to achieve the same result as presented on the mockup

**Comment by simplypixi** [comment]
@carmenfan Lets assume we have a project called `Lego` with a model called `Architecture`.
What if I'm searching for 'Lego` with all options ticked?
Should we show an empty project (this is completely opposite to behavior that we implemented on "Starred" tab)? Or hide it?

**Comment by carmenfan** [comment]
> @carmenfan Lets assume we have a project called `Lego` with a model called `Architecture`.
> What if I'm searching for 'Lego` with all options ticked?
> Should we show an empty project (this is completely opposite to behavior that we implemented on "Starred" tab)? Or hide it?
> 
> I think it's the only edge-case that I found.

No, we should show the project collapsed, if the user expands it, it should have all the the models inside.

Unless the user is searching under the starred tab, then it should only show if it contained any starred models

**Comment by simplypixi** [comment]
> No, we should show the project collapsed, if the user expands it, it should have all the the models inside.



> > @carmenfan Lets assume we have a project called `Lego` with a model called `Architecture`.
> > What if I'm searching for 'Lego` with all options ticked?
> > Should we show an empty project (this is completely opposite to behavior that we implemented on "Starred" tab)? Or hide it?
> > I think it's the only edge-case that I found.
> 
> No, we should show the project collapsed, if the user expands it, it should have all the the models inside.
> 
> Unless the user is searching under the starred tab, then it should only show if it contained any starred models

ok ;)

**Comment by carmenfan** [comment]
![image](https://user-images.githubusercontent.com/11945337/62477665-5a0e1200-b7a1-11e9-87d0-00dea3bcd369.png)
added

**Comment by dleszcz** [comment]
Hi @carmenfan, some questions about the sorting here :)

What actually should be sorted by sorting menu? Only federations & models? or everything (federations, models, projects, teamspaces)?
And which option should be selected initially in this menu?

![Screenshot 2019-08-22 at 14 12 44](https://user-images.githubusercontent.com/17221890/63513583-f3019480-c4e6-11e9-8c9c-f8a5e007f317.png)

**Comment by simplypixi** [comment]
@carmenfan another tricky question :D
Are you sure about centering project names? I think it'll be inconvenient from a user perspective. It's easier to go through the list inline than jumping between two parts of the screen (especially, when a resolution is really big)

**Comment by simplypixi** [comment]
@carmenfan and next one :)
Can we move the sorting option to burger menu in panel header? It'll be consistent with other panels (eg. issues, risks)

![image](https://user-images.githubusercontent.com/5683490/63515871-1975fe80-c4ec-11e9-8dbe-39dc8df864b6.png)
