### ISSUE TITLE
Fix Security alerts

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1654]
See https://github.com/3drepo/3drepo.io/network/alerts

Axios and Lodash require upgrades.

@simplypixi @dleszcz can you do the front end?
@Charence @sanmont3drepo  can you do the back end?

**Comment by simplypixi** [comment]
Ok! ;)

**Comment by carmenfan** [comment]
> Ok! ;)
> 
> btw, we are not able to see this page :/

Hm...... Screenshots here:
![image](https://user-images.githubusercontent.com/11945337/63342764-37086400-c344-11e9-97b3-bc81e22d3a4e.png)

![image](https://user-images.githubusercontent.com/11945337/63342774-438cbc80-c344-11e9-8eff-66d409604bf7.png)

![image](https://user-images.githubusercontent.com/11945337/63342782-48517080-c344-11e9-8162-9f346024c9c2.png)
