### ISSUE TITLE
Another Yarn build script

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1665]
Currently we have:
Yarn build
Yarn build:dev
Yarn watch

The problem we have currently is that yarn build takes forever due to the type checking. This is used by the production environment so it takes a more time than necessary to spin up new machines.

Realistically, we only ever need to do type checking on travis, so we know if it passess travis, the type check is done.

If we can add a new `yarn build:test`, which is essentially the current `yarn build`, and remove type checking from yarn build, that would be ideal.

**Comment by keifgwinn** [comment]
it's now much faster to build, but I'm also still getting the occasional build failure

**Comment by carmenfan** [comment]
yea this doesn't solve the failure, it just takes the type checking out of it.
