### ISSUE TITLE
Session expired message keeps popping up

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1666]
### Description
Regardless of how you invalidate your session, the session expired message keeps popping up.

It is also missing the content of the message
![image](https://user-images.githubusercontent.com/11945337/63873763-11203680-c9b8-11e9-834b-840218ee8d7c.png)

### Steps to replicate
- Log in
- Log out
- Refresh

Do we really need a session expired dialog? I definitely shouldn't be seeing the dialogue if I logged out on purpose. I think the user just needs to be re routed to login.

**Comment by carmenfan** [comment]
@simplypixi @dleszcz This problem seems to stem from [this part](https://github.com/3drepo/3drepo.io/blame/staging/frontend/modules/auth/auth.sagas.ts#L105) of the code 

Judging from the comments this probably got changed in some other migration branch? (probably model/viewer?)


I think We can maybe just remove the dialog part of the code...

**Comment by simplypixi** [comment]
> this part

Sure, we can get rid it of. ;)
