### ISSUE TITLE
Add scroll support to clipping plane slider

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#170]
When hovering or clicking on the slider in the clipping plane card, it should be possible to move the slider simply by scrolling a mouse wheel.

**Comment by camden-kid** [comment]
I'm not sure this is really necessary and we should aim to make the UI as mobile friendly as possible.

**Comment by jozefdobos** [comment]
Supporting scroll wheel should have no effect on touch functionality, it is just an additional aid. So I'd say it is necessary (should be an easy add-on I would imagine)
