### ISSUE TITLE
Experiment with launching Unity Viewer in the background

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1719]
### Description
Currently the user incurs a long wait time between the selecting a model to load to the model actually loading, this is due to the web UI having to fetch the unity game and also wait for the game to launch.

In the first version of 3drepo with unity renderer, we actually launch the viewer in the background, starting from the login page. One of the issue with this implementation is that when the game has been fetched and it's launching the game, there is ~2s lag that causes UI to no be unresponsive.

### Tasks
Experiment on bringing this back.
- what is the UI impact on launching the game as soon as the user enters 3drepo.io?
- If the above is undesirable, can we prefetch the game, and when the user enters the viewer component, all we do is launch the game?

**Comment by keifgwinn** [comment]
my clean-old-branches script keeps picking this up. Is this still valid?

**Comment by carmenfan** [comment]
nah doubt anyone cares. it's been almost 2 years and no one wanted to revive it

personally i don't think it's a good idea to begin with

**Comment by keifgwinn** [comment]
the idea got tried out with 3dsend didn't it and decided to keep it on launch on demand basis

**Comment by carmenfan** [comment]
@keifgwinn nah it was always designed to only launch the viewer if the user wanted it

The consideration is the user might not want to view the 3D model and in which we wasted a lot of processing time. (also accessibility is limited if for some reason the viewer crashes, and all the user wants to do is download a file.

Same considerations in 3D repo, they might want to just look at the kanban.

**Comment by mosment3DRepo** [comment]
I believe this was more of a problem pre Unity 2020 (although I may be wrong). Regardless, not worth the risk of an unresponsive app or unnecessary resource hogging
