### ISSUE TITLE
The federation on the toy models is not created

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#1724]
### Description
Creating a new account after 3.14.0 imports the toy models but does not import the federation. An error email is raised 

Model failed to import. Please help this user out.
account: xxx
model: undefined
user: xxx
Error: Project not found
Bouncer Error Code : undefined
correlationId: undefined
appId: undefined
domain: www.3drepo.io

### Steps to replicate
- complete a new sign up
- The federation on the toy models is not created

**Comment by carmenfan** [comment]
fixed in #1746
