### ISSUE TITLE
Add static page navigation dropdown inside static pages

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1736]
### Description
The dropdown with the links to other static pages is not there within a static page.This means that there is no way to navigate to other static pages within static pages.

This is the dropdown that should appear:

![staticpages](https://user-images.githubusercontent.com/42032433/66762098-9ba7f100-eea5-11e9-88a3-0c2106b9a162.gif)

In static pages:
![image](https://user-images.githubusercontent.com/42032433/66762350-1f61dd80-eea6-11e9-9585-630b78db8569.png)

**Comment by keifgwinn** [comment]
does this work under branded subdomains? I just tried it on one and it didn't seem to
