### ISSUE TITLE
Issues/Risks management board 

### ISSUE THREAD

**Issue by dleszcz** [3drepo/3drepo.io#1738]
Choosen library: https://rcdexta.com/react-trello

[Issue Management Proposal.pdf](https://github.com/3drepo/3drepo.io/files/3717476/Issue.Management.Proposal.pdf)

- [x] Install & configure library
- [x] Create redux store
- [x] Create new route for board
- [x] Drag and drop issue to other line 
- [x] Add link to Trello board on model item card
- [x] Create new menu item on dashboard
- [x] Prepare data to use in trello library
- [x] Create Trello board 
    - [x] Switch between issues & risks
    - [x] Switch between another teamspace/project/model
    - [x] Search by phrase
    - [x] Filter buttons by: Status, Priority, Type, Assigned to, Created By
    - [x]  Filter menu (like on viewer)
    - [x] Create "new issue" button
    - [x] New issue form 
    - [x] Issue details popup 
    - [x] Add other issue options 
    - [x] Implement empty and default states
    - [x] Create single issue item

**Comment by dleszcz** [comment]
Hello @BDavydov !

Two things:
1. I cant see Status & Priority fields in Risks. There are only in issues now. Should this be added in the app? Or You want to filter by another properties in Risks?
2. I think there is no reason to edit the "Created By" property. What is the use case?

**Comment by BDavydov** [comment]
Hello @dleszcz 
Thank you for your question.

1. Can we filter risks by the following properties: 
- Level of Risk
-Level of Mitigated Risk
-Category 
-Mitigation Status
-Risk Owner

2."Created By" should automatically be filled out with the account name of a person creating an issue. Ideally, it mustn't be changed in order to trail the source of an issue/risk.

**Comment by carmenfan** [comment]
> 2."Created By" should automatically be filled out with the account name of a person creating an issue. Ideally, it mustn't be changed in order to trail the source of an issue/risk.

To clarify @BDavydov 's response. We want to see it sorted in created by, but the user should not be able to move the cards around.

**Comment by dleszcz** [comment]
Hello @carmenfan @Charence ,
In the form levels aren't updated directly. They are calculated on _likelihood_, or _consequence_ change.

What about updating _level_of_risk_, or _residual_level_of_risk_ on Board?
Now, we get this response:

![Screenshot 2019-10-28 at 14 08 06](https://user-images.githubusercontent.com/17221890/67680839-6793fc00-f98c-11e9-934a-fff60fb280de.png)

![Screenshot 2019-10-28 at 14 08 12](https://user-images.githubusercontent.com/17221890/67680850-6b278300-f98c-11e9-8550-e497a99d3244.png)

**Comment by carmenfan** [comment]
> Hello @carmenfan @Charence ,
> In the form levels aren't updated directly. They are calculated on _likelihood_, or _consequence_ change.
> 
> What about updating _level_of_risk_, or _residual_level_of_risk_ on Board?
> Now, we get this response:
> 
> ![Screenshot 2019-10-28 at 14 08 06](https://user-images.githubusercontent.com/17221890/67680839-6793fc00-f98c-11e9-934a-fff60fb280de.png)
> 
> ![Screenshot 2019-10-28 at 14 08 12](https://user-images.githubusercontent.com/17221890/67680850-6b278300-f98c-11e9-8550-e497a99d3244.png)

I think it's another one of those headers that you can't move the cards around. Though if the user goes in and edit the associated likelihood/consequence then it would move
