### ISSUE TITLE
First comment should be marked differently

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#174]
When creating an issue, you fill in the title and the comment. However, once saved, the comment is visualised as any other comment, which is a bit confusing:

![image](https://cloud.githubusercontent.com/assets/3008807/12553408/21bfb7c0-c36f-11e5-912e-98f73807dd4f.png)

We need to visually distinguish the first comment I think

**Comment by camden-kid** [comment]
Closing this now as the first comment has become "Description" for the MVP release 1.5.
