### ISSUE TITLE
Pivot Point Sphere explodes when zoomed in

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1765]
### Description
Pivot point sphere size jumps (Explodes) around when zooming in and out of a model. Ideally should change the size consistently & without visual explosions. 

### Steps to replicate
- open any model and start rotating around the object
- zoom in closer and rotate around the object again

### Pictures/ Gifs of the error
![Sphere](https://user-images.githubusercontent.com/19904513/67945960-22640a00-fbd8-11e9-969f-dc5d864a4b79.gif)

**Comment by carmenfan** [comment]
this is fixed in 3.15.1 via https://github.com/3drepo/3drepo.io/issues/1746

reopen with details if you still see it
