### ISSUE TITLE
Compare card breaks page if a loaded model has no revisions

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1775]
### Description
Clash card breaks page if a loaded model has no revisions.

### Steps to replicate
- Create a model (keep it empty)
- Create a federation containing model
- Go to federation and open compare card
- White screen

### Pictures/ Gifs of the error
![Nov-04-2019 15-37-47](https://user-images.githubusercontent.com/1438332/68134520-2797c080-ff1a-11e9-9b14-37c842e94455.gif)

**Comment by m1chalkubiak** [comment]
Hi @carmenfan @Charence 
I tried to reproduce described issue:
So, I created an empty model, created new federation, added empty model to this federation and opened this federation, this caused errors from backend side.
Requests are for "revisions" but all returns "Bad Request".
Therefore, our first question is whether these queries, like the one below, are correct?
![2019-11-6](https://user-images.githubusercontent.com/24941866/68281703-86734c00-0078-11ea-8e0a-0bacdab31647.png)

**Comment by carmenfan** [comment]
> Hi @carmenfan @Charence
> I tried to reproduce described issue:
> So, I created an empty model, created new federation, added empty model to this federation and opened this federation, this caused errors from backend side.
> Requests are for "revisions" but all returns "Bad Request".
> Therefore, our first question is whether these queries, like the one below, are correct?
> ![2019-11-6](https://user-images.githubusercontent.com/24941866/68281703-86734c00-0078-11ea-8e0a-0bacdab31647.png)

This is because you can't create/modify a federation without launching a 3drepobouncer service.
Let me setup an example on your database and get back to you

**Comment by carmenfan** [comment]
@m1chalkubiak 
if you log in as Sergi (reset pw for access)
and go to viewer/Sergi/60b493f2-6521-48a5-a1c8-adf469a7770b

You should be able to trigger it

**Comment by m1chalkubiak** [comment]
@carmenfan  Thank you for creating this example for me. I was able to reproduce the issue and found the solution. I see that in general, we are rendering a message for user if we don't have any data to show in modals. What should be the message for the user if there are no models that can be compared?

**Comment by carmenfan** [comment]
If there's no revision, can we show something like this (better formatted, this is a quick paint job)
![image](https://user-images.githubusercontent.com/11945337/68385116-fd7c1380-0150-11ea-9ad7-946ddf8e73c9.png)

**Comment by m1chalkubiak** [comment]
@carmenfan 
Sure, I think we can do it. I need to change my previous solution, as I was just filtering models with testing do they have revisions just before rendering them.
