### ISSUE TITLE
Avatar gets fetched a lot

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1776]
### Description
Avatar is getting fetched every time the user clicks on something within the grid view. Can do we something about this?

![markup](https://user-images.githubusercontent.com/11945337/68143881-4e5df300-ff2a-11e9-98ea-099b358b2220.gif)

**Comment by carmenfan** [comment]
@simplypixi  any thoughts on this?

**Comment by m1chalkubiak** [comment]
@carmenfan Unchecking "Disable cache" in Chrome devtools should fix it ;)

**Comment by carmenfan** [comment]
👍 😆
