### ISSUE TITLE
Minor UI Issues

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1779]
- [x] **Helicopter Bug**
We discovered in 4.0.0 release that the API call to change helicopter speed was sending teamspace and model ID as `undefined`. It looks like the props did not contain the right information regarding teamspace and model ID. This is worked around with dac6bc08cc0acd547ca6ee3f2b1708886a6746ae but we need to make it work the way it should.

- [x] **[Object Object] API calls when you go try to view a federation model**
It only seems to happen with federations, but when you enter the viewer, you will see an API call with an incorrect URL: 
![image](https://user-images.githubusercontent.com/11945337/68215408-1cef3100-ffd7-11e9-88da-07bc0cf5dbe9.png)

- [x] **Model code not updated in gridview**
If you go into model settings and update the model code, it doesn't appear until you refresh the page
![markup](https://user-images.githubusercontent.com/11945337/68215760-b0c0fd00-ffd7-11e9-9942-1f83a424be9c.gif)

- [x] **Make a footer on model settings**
Can we have the save button on a footer so it's always shown without the need to scroll?
![image](https://user-images.githubusercontent.com/11945337/68216116-4bb9d700-ffd8-11e9-9556-9c1c7b3d00c9.png)

- [x] **On sign up, the frontend allows hyphens on the username but backend doesn't**
Backend uses this Regex:  `/^[a-zA-Z][\w]{1,63}$/`, which is alphanumeric and underscore. But frontend currently says hypens are allowed
![markup](https://user-images.githubusercontent.com/11945337/68216646-1c579a00-ffd9-11e9-9106-30c324a63296.gif)

- [x] **Change this to a user friendly error**
I think majority of our userbase would not know what this means... Can we change it to a more friendly message?
![image](https://user-images.githubusercontent.com/11945337/68216810-6b9dca80-ffd9-11e9-8286-64d9aec0eabb.png)

- [x] **Remove default group description when the user focuses**
Just like the group name, the default description should also disappear when the user focuses on the text box
![markup](https://user-images.githubusercontent.com/11945337/68217068-e36bf500-ffd9-11e9-8835-fe2839c3e7c0.gif)

- [x] Can do we do the same on views (see line above)?
![image](https://user-images.githubusercontent.com/11945337/68217102-eff04d80-ffd9-11e9-8f2e-a2181f5ed771.png)

**Comment by simplypixi** [comment]
@carmenfan Done! ;)
