### ISSUE TITLE
Can not copy paste text into the Teamspaces Search Field

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1789]
### Description
Trying to copy text from another website/application and paste it into the search field. Unfortunately, it doesn't work and only allows me to write the text.

### Steps to replicate
- Copy text from any source ie. Website/Notepad/PDF Document
- Log in to your 3D Repo account
- Activate search bar in your teamspace
- Try copy-paste the text CTRL + V

### Pictures/ Gifs of the error
![Search Teamspaces](https://user-images.githubusercontent.com/19904513/68466424-4e047700-020c-11ea-9b9d-f3ff2d0bffdd.gif)

**Comment by simplypixi** [comment]
@BDavydov, @carmenfan  ^ Done ;)
