### ISSUE TITLE
Incorrect revision count update

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1797]
### Description
At the moment, 2 + 1 = 5. May be caused by too many upload success notifications?

### Steps to replicate
- Upload model revision
- Watch the revision count

### Pictures/ Gifs of the error
![Nov-15-2019 10-45-10](https://user-images.githubusercontent.com/1438332/68938218-cda6be80-0795-11ea-831d-990d598eb169.gif)

**Comment by carmenfan** [comment]
I think this is related to #1770, which are both related to the confusing logic around what is a model settings update & unreliability of the socket io hook
