### ISSUE TITLE
Change backend to use ids for projects instead of project name

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1801]
### Description
Using projects names instead of ids for updating objects is less stable (e.g. if another person changes the project during the course of the session,  all api calls for that particular project from the user will fail). 
For now we are keeping the old api using project names, but the send invitation by email will use ids.
Also there will be a script for migrating Object(id) to LUUID(id)

### Tasks
- [ ] send invitation by email API using project ids
- [ ] migration script Object(id) to LUUID(id)

**Comment by carmenfan** [comment]
in #1723
