### ISSUE TITLE
Tree Bugs

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1812]
- [x] [Trying to isolate a empty submodel results in error](https://github.com/3drepo/3drepo.io/issues/1812#issuecomment-559512909)
- [x] [Transformation with no name is being hidden](https://github.com/3drepo/3drepo.io/issues/1812#issuecomment-559516643)

**Comment by carmenfan** [comment]
### Description
If the federation contains empty models, pressing 'isolate' or 'show/hide' on the empty sub-model breaks the tree card.

Issue on master.

### Steps to replicate
- open fed with empty sub-models
- try to 'isolate' empty sub-model

### Pictures/ Gifs of the error
![Screenshot 2019-11-28 14 07 36](https://user-images.githubusercontent.com/1438332/69812939-18d6bd80-11e9-11ea-9a11-4cd7cff9d7e0.png)

**Comment by carmenfan** [comment]
- Transformation with no name is being hidden

![markup](https://user-images.githubusercontent.com/11945337/69814498-348f9300-11ec-11ea-8567-7ac767832ba9.gif)
