### ISSUE TITLE
SafetiBase v3

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1847]
### Description
Ability to suggest risk mitigations and additional fields

### Goals
Wireframe: https://marvelapp.com/4b107ge

##### front end
- [x] New Tab layout to replace the single page layout (it should still be collapsible to view comment as per now)
- [x] Change scrollable part to be the tab section only, title should always be visible (like a header)
- [x] Mitigation renamed to treatment on user interface
- [x] Add new fields to risk/treatment tab as per the wireframe
- [x] Level of risk/level of residual risk change from a disabled drop down to an icon

##### backend
- [x] Existing risk endpoint to accept the new fields

##### frontend
- [x] Add a new teamspace setting page (only viewable by teamspace admins)
- [x] Move issue topic types to teamspace settings
- [x] remove issue topic types from model settings
- [x] add risk categories 
- [x] ability to upload a file to add suggestions for risk treatments
- [x] ability to download a template for the risk treatments
- [x] ability to download last uploaded risk treatments

##### backend
- [x] post/put/get teamspace settings
- [ ] new endpoint for risk treatment file/teamplate download
- [x] remove issue topic types from model settings endpoints
- [x] db migration to move issue topic types to teamspace settings

##### frontend
- [x] New field types require autocomplete facility
- [x] Risk categories needs to be pulled from teamspace settings instead of hard coded
- [x] Add a treatment suggestion button
- [x] treatment suggestion pop up - ability to filter treatment by stage/types
- [x] selected treatment will populate the treatment/type/stage on the risk card

##### backend
- [x] get request for autocomplete suggestions on new fields
- [x] post request to ask for treatment suggestions

**Comment by Charence** [comment]
The new fields on the UI map to the following data fields:

- Element Type = `element`
- Risk Factor = `risk_factor`
- Construction Scope = `scope`
- Location = `location_desc`

Treatment will consist of 2 text fields, as follows:
- `mitigation_desc` (existing field, restricted to 220 chars)
- `mitigation_detail` (new field, unrestricted)
- Stage = `mitigation_stage`
- Type = `mitigation_type`

@m1chalkubiak

**Comment by m1chalkubiak** [comment]
Hi @Charence 
Thanks for describing new fields and adding comments in wireframes, they were really helpful.
Most of the things from Milestone 1 are done. But I came back with a couple of things, that need your decisions.

I found one issue regarding the attachments tab.
Until we create/ save risk we are unable to add any attachments.  From what I understand we need to know the id of risk (which we get after creating the risk) to be able to add attachments. 
The best solution that I can see is disabling attachments tab for new risk (during creating) we can add tooltip saying that user needs to create (save) risk before trying to add an attachment.

  From previous risk form there is one field that completely disappeared - `safetibase_id`. Should we remove it completely from the application?

  I have also doubts regarding displaying risk levels by  Icons. In the new layout, we have 3 places where icons are rendered 
1) On risk tab the color and text part goes from `level_of_risk` field 
2) On treatment tab color and text part are going from `residual_level_of_risk` field 
3) The third icon is below the risk title and it acts exactly like the one on the treatment tab.
 In all places, the type of icon is rendered depending on `mitigation_status` field value.
Please, let me know if this is exactly the way how those icons should be rendered or there is different logic/depending witch was unclear for me.

  If I understand You wireframes correctly You would also like to redesign the header part of the form. By moving the user name with icon and the date to common container wit title of risk and role indicator.  This part of code is used in both risk and issue forms, so if You don’t anything against that it would be easier to change this in both forms.

Also, I will need to ask for help regarding `mitigation_detail` field. I really don't understand what is it on the wireframes. 
Is it about splitting this treatment description into two separate text areas?

**Comment by Charence** [comment]
Hi @m1chalkubiak, please see my responses below:

> I found one issue regarding the attachments tab.
> Until we create/ save risk we are unable to add any attachments.  From what I understand we need to know the id of risk (which we get after creating the risk) to be able to add attachments. 
> The best solution that I can see is disabling attachments tab for new risk (during creating) we can add tooltip saying that user needs to create (save) risk before trying to add an attachment.

Yes, let's do that!

>   From previous risk form there is one field that completely disappeared - `safetibase_id`. Should we remove it completely from the application?

For now, we would like to just have the `safetibase_id` hidden in the UI. It does not need to be completely removed from the application.

>   I have also doubts regarding displaying risk levels by  Icons. In the new layout, we have 3 places where icons are rendered
> 
> 1. On risk tab the color and text part goes from `level_of_risk` field
> 2. On treatment tab color and text part are going from `residual_level_of_risk` field
> 3. The third icon is below the risk title and it acts exactly like the one on the treatment tab.
> 
>  In all places, the type of icon is rendered depending on `mitigation_status` field value.
> Please, let me know if this is exactly the way how those icons should be rendered or there is different logic/depending witch was unclear for me.

Sorry this was not clearer. You are right for 1 and 2.

1. On risk tab, color/text/icon is from `level_of_risk`
2. On treatment tab, color/text/icon is from `residual_level_of_risk`
3. On third small icon on header, color/text/icon is from `overall_level_of_risk`

I have added annotations to the wireframe here: https://marvelapp.com/4b107ge/screen/65518406 

>   If I understand You wireframes correctly You would also like to redesign the header part of the form. By moving the user name with icon and the date to common container wit title of risk and role indicator.  This part of code is used in both risk and issue forms, so if You don’t anything against that it would be easier to change this in both forms.

Yes, please change this part for both forms. We would like the Risk or Issue header to remain visible if the user scrolls.

> Also, I will need to ask for help regarding `mitigation_detail` field. I really don't understand what is it on the wireframes.
> Is it about splitting this treatment description into two separate text areas?

Yes, the user wants to have a short treatment title/description (which will be the existing `mitigation_desc`) and also a longer field for treatment details (which is the new field `mitigation_detail`). Both of these fields describe the treatment.

Instead of having a label for both of them (e.g. Treatment Title and Treatment Details), I think it would be nicer if they are grouped together under Treatment. Perhaps this can be achieved by not displaying the label for the Treatment Details when the field contains text?

**Comment by m1chalkubiak** [comment]
@Charence 

> Instead of having a label for both of them (e.g. Treatment Title and Treatment Details), I think it would be nicer if they are grouped together under Treatment. Perhaps this can be achieved by not displaying the label for the Treatment Details when the field contains text?

Not sure if I get You correctly, we can have second field without label for sure but is this will be clear for the user what is the purpose of this additional field?

> On risk tab, color/text/icon is from level_of_risk
> On treatment tab, color/text/icon is from residual_level_of_risk
> On third small icon on header, color/icon is from overall_level_of_risk

So, now is even less clear.
Currently, for types of icons we are using this mapping: 

```
export const RISK_LEVELS = {
	UNMITIGATED: '',
	PROPOSED: 'proposed',
	AGREED_PARTIAL: 'agreed_partial',
	AGREED_FULLY: 'agreed_fully',
	REJECTED: 'rejected'
};

export const RISK_LEVELS_ICONS = {
	[RISK_LEVELS.UNMITIGATED]: NewReleases,
	[RISK_LEVELS.PROPOSED]: ErrorOutline,
	[RISK_LEVELS.AGREED_PARTIAL]: ErrorSolid,
	[RISK_LEVELS.AGREED_FULLY]: CheckCircle,
	[RISK_LEVELS.REJECTED]: SyncProblem
};
```
So, we have only 5 options directly related to `mitigation_status` field values, I believe we need new mapping for this. Sure, nothing hard to do (one additional icon needed), but I just want to be clear about that.

It is in the `frontend/constants/risks.ts` path if You would like to check it.

**Comment by Charence** [comment]
> > Instead of having a label for both of them (e.g. Treatment Title and Treatment Details)...
> 
> Not sure if I get You correctly, we can have second field without label for sure but is this will be clear for the user what is the purpose of this additional field?

@carmenfan says that we should have labels for both fields as it will be clearer for the user.

![Screenshot 2020-01-24 15 42 46](https://user-images.githubusercontent.com/1438332/73081918-5f325b00-3ec0-11ea-9f19-a6324280702f.png)

Wireframe: https://marvelapp.com/4b107ge/screen/65758806

> > On risk tab, color/text/icon is from level_of_risk
> > On treatment tab, color/text/icon is from residual_level_of_risk
> > On third small icon on header, color/icon is from overall_level_of_risk
> 
> So, now is even less clear.
> Currently, for types of icons we are using this mapping:
> 
> ```
> export const RISK_LEVELS = {
> 	UNMITIGATED: '',
> 	PROPOSED: 'proposed',
> 	AGREED_PARTIAL: 'agreed_partial',
> 	AGREED_FULLY: 'agreed_fully',
> 	REJECTED: 'rejected'
> };
> 
> export const RISK_LEVELS_ICONS = {
> 	[RISK_LEVELS.UNMITIGATED]: NewReleases,
> 	[RISK_LEVELS.PROPOSED]: ErrorOutline,
> 	[RISK_LEVELS.AGREED_PARTIAL]: ErrorSolid,
> 	[RISK_LEVELS.AGREED_FULLY]: CheckCircle,
> 	[RISK_LEVELS.REJECTED]: SyncProblem
> };
> ```
> 
> So, we have only 5 options directly related to `mitigation_status` field values, I believe we need new mapping for this. Sure, nothing hard to do (one additional icon needed), but I just want to be clear about that.
> 
> It is in the `frontend/constants/risks.ts` path if You would like to check it.

I believe I have added to the confusing by mentioning icon.

1. On risk tab, color and text is from `level_of_risk`. We would like the icon to always be the `warning` icon (same as the one used for SafetiBase card). Updated wireframe: https://marvelapp.com/4b107ge/screen/65758885

![Screenshot 2020-01-24 15 58 40](https://user-images.githubusercontent.com/1438332/73083124-81c57380-3ec2-11ea-8cd8-5f9e0a9e8037.png)

2. On treatment tab, color and text is from `residual_level_of_risk`. The icon should be from `mitigation_status`, so it should have the same icon as the small icon in the header.

3. The third small icon on header should remain unchanged. Its color is from `overall_level_of_risk` and icon is from `mitigation_status`.

**Comment by m1chalkubiak** [comment]
Hey @Charence , I am at the end of finishing the first milestone, still fighting with `mitigation detail` field and making it collapsible.
Describing the logic behind rendering risk icons was very helpful, thank You so much for this.

But I have an organization question, as this feature is divided into milestones, would You like me to create separate PR's with them directed to the main ISSUE_1847 branch? Or should I just push all commits into `ISSUE_1847` branch? I'm not sure how this was done in the past.

**Comment by Charence** [comment]
> But I have an organization question, as this feature is divided into milestones, would You like me to create separate PR's with them directed to the main ISSUE_1847 branch? Or should I just push all commits into `ISSUE_1847` branch? I'm not sure how this was done in the past.

Hi @m1chalkubiak , just push all commits into the current `ISSUE_1847` branch. I believe it will be more straightforward this way.

**Comment by Charence** [comment]
@m1chalkubiak For Teamspace Settings, we have the following new endpoints:

- `GET /:teamspace/settings` for retrieving all teamspace settings

Example Response:
```
HTTP/1.1 200 OK
{
	"topicTypes":[
		{
			"value":"constructibility",
			"label":"Constructibility"
		},
		{
			"value":"gis",
			"label":"GIS"
		}
	],
	"riskCategories":[
		{
			"value":"other",
			"label":"Other Issue"
		},
		{
			"value":"unknown",
			"label":"UNKNOWN"
		}
	],
	"teamspace":"acme"
}
```

- `PUT /:teamspace/settings` for updating all teamspace settings

Example Request:
```
PUT /acme/settings HTTP/1.1
{
	"topicTypes":[
		"New Topic 1",
		"New Topic 2"
	],
	"riskCategories":[
		"New Category 1",
		"NEW CATEGORY 2"
	]
}
```

Response will be the updated teamspace settings in the same format as the GET request.

- `GET /:teamspace/topicTypes` for retrieving all teamspace topic types (you probably don't need to use this)

Example Response:
```
HTTP/1.1 200 OK
[
	{
		"value":"for_information",
		"label":"For information"
	},
	{
		"value":"vr",
		"label":"VR"
	}
]
```

- `GET /:teamspace/riskCategories` for retrieving all teamspace risk categories (you probably don't need to use this)

Example Response:
```
HTTP/1.1 200 OK
[
	{
		"value":"commercial",
		"label":"Commercial Issue"
	},
	{
		"value":"environmental",
		"label":"Environmental Issue"
	}
]
```

- `GET /:teamspace/treatments.csv` for downloading a treatments CSV file/CSV template with headers

At the moment, this will always return a 1 row CSV file with the headers. The backend code for storing and retrieving the file is not done yet.

- `POST /:teamspace/treatments.csv` for uploading a treatments CSV file

Example Response:
```
{ "status": "ok" }
```

At the moment, this will always return `status: ok` as the backend code for processing the given file is not done yet.

Please note that the endpoint `PUT /:teamspace/:model/settings` for update model settings will no longer process topicTypes.

**Comment by m1chalkubiak** [comment]
@Charence,
I'm unable to force new endpoints to work. Until now, I've always used the `./run/run_app` command to run the backend, nothing else was needed. Do I need to do any additional actions this time to launch new endpoints?

I keep getting 404 with additional information that "Teamspace settings not found"

![Zrzut ekranu 2020-01-31 o 11 08 58](https://user-images.githubusercontent.com/24941866/73531148-217e8680-441a-11ea-9af7-c3771417c3d7.png)
![Zrzut ekranu 2020-01-31 o 11 09 49](https://user-images.githubusercontent.com/24941866/73531213-3e1abe80-441a-11ea-9b3d-6df11bdc2e0a.png)

**Comment by Charence** [comment]
> I'm unable to force new endpoints to work. Until now, I've always used the `./run/run_app` command to run the backend, nothing else was needed. Do I need to do any additional actions this time to launch new endpoints?
> 
> I keep getting 404 with additional information that "Teamspace settings not found"

@m1chalkubiak I've run a migration script on the database you are using. Teamspace settings should exist now.

**Comment by m1chalkubiak** [comment]
@Charence 
You are right,  I see it works, thanks for the help.

**Comment by m1chalkubiak** [comment]
@Charence 
One thing regarding `GET /:teamspace/settings` endpoint 
Instead of 
```
HTTP/1.1 200 OK
{
	"topicTypes":[
		{
			"value":"constructibility",
			"label":"Constructibility"
		},
		{
			"value":"gis",
			"label":"GIS"
		}
	],
	"riskCategories":[
		{
			"value":"other",
			"label":"Other Issue"
		},
		{
			"value":"unknown",
			"label":"UNKNOWN"
		}
	],
	"teamspace":"acme"
}
```
I'm getting labels at 'name' property for `riskCategories`
![Zrzut ekranu 2020-01-31 o 13 41 02](https://user-images.githubusercontent.com/24941866/73540203-960ff000-442f-11ea-95f8-40cfc724b5ed.png)
Can You take a look on this ?

**Comment by m1chalkubiak** [comment]
@Charence 
Additional question:
From what I understand from wireframes, at the bottom of form on teamspace settings page we should show the info regarding  uploaded treatments:
<img width="462" alt="Zrzut ekranu 2020-01-31 o 13 56 36" src="https://user-images.githubusercontent.com/24941866/73540972-85f91000-4431-11ea-96a2-3919d58b97eb.png">

Is calling the `GET /:teamspace/treatments.csv` endpoint is the only way, to check if we have an uploaded treatments? maybe we could add this metadata to `GET /:teamspace/settings ` endpoint, then additional call on this page wouldn't be necessary.

**Comment by Charence** [comment]
> One thing regarding `GET /:teamspace/settings` endpoint
> 
> I'm getting labels at 'name' property for `riskCategories`

There was an error in the migration script. I have corrected and re-run it.

Regarding the uploaded treatments, I agree that this information can be added to the settings endpoint. Let me think about how to change this.

Also, I'm going to be removing the following as they seem to be redundant:

- `GET /:teamspace/topicTypes`
- `GET /:teamspace/riskCategories`

**Comment by m1chalkubiak** [comment]
@Charence 
> There was an error in the migration script. I have corrected and re-run it.

Thanks, I see changes, now it looks fine.  

> Also, I'm going to be removing the following as they seem to be redundant:
> 
> * `GET /:teamspace/topicTypes`
> * `GET /:teamspace/riskCategories`

Totally agree on that.

I re-read the description of `GET /:teamspace/treatments.csv` endpoint 

> GET /:teamspace/treatments.csv for downloading a treatments CSV file/CSV template with headers
At the moment, this will always return a 1 row CSV file with the headers. The backend code for storing and retrieving the file is not done yet.

And now I'm confused, Is the place I ment in https://github.com/3drepo/3drepo.io/issues/1847#issuecomment-580723841 is about downloading the template for treatments, or the already uploaded treatments? If it's about templates then message on wireframes 'No suggestions uploaded' doesn't feel to make sense.

**Comment by Charence** [comment]
> > GET /:teamspace/treatments.csv for downloading a treatments CSV file/CSV template with headers
> > At the moment, this will always return a 1 row CSV file with the headers. The backend code for storing and retrieving the file is not done yet.
> 
> And now I'm confused, Is the place I ment in [#1847 (comment)](https://github.com/3drepo/3drepo.io/issues/1847#issuecomment-580723841) is about downloading the template for treatments, or the already uploaded treatments? If it's about templates then message on wireframes 'No suggestions uploaded' doesn't feel to make sense.

The initial idea was the button would download both, depending on if treatments is already uploaded. However, I can see that this can be confusing.

I think there are 2 options:

1. Have 2 buttons (Download, Get Template)
 a. Download - retrieve the uploaded file; button disabled if none exists
 b. Get Template - always available to download a blank template file
2. Change the button text depending on treatments upload state (Download/Get Template)
 a. Button text is `Download` if there is an uploaded file
 b. Button text is `Get Template` if there is no uploaded file and the same endpoint will return the template

I think perhaps option 1 is clearer. Would you agree? This will require an additional endpoint to retrieve a template file.

**PLEASE NOTE:** after discussing with Carmen, the following 2 endpoints have changed path:

1. `GET /:teamspace/treatments.csv` --> `GET /:teamspace/settings/treatments.csv`
2. `PUT /:teamspace/treatments.csv` --> `PUT /:teamspace/settings/treatments.csv`

> Is calling the `GET /:teamspace/treatments.csv` endpoint is the only way, to check if we have an uploaded treatments? maybe we could add this metadata to `GET /:teamspace/settings ` endpoint, then additional call on this page wouldn't be necessary.

These endpoints will also include a timestamp in the field `treatmentsUpdatedAt` if an uploaded treatments file exists.

Example response:
```
{
    "riskCategories": [ ... ],
    "topicTypes": [ ... ],
    "treatmentsUpdatedAt": 1567156228976,
    "teamspace": "acme"
}
```

**Comment by m1chalkubiak** [comment]
Hi @Charence 
Now I get this idea and agree with option 1. But maybe the business perspective is different. 
Altho, I did go with this option and added additional button, the problem with this approach is that we only have one endpoint returning the template / current file, we would have to separate them.

**Comment by Charence** [comment]
Hi @m1chalkubiak 

Instead of having an endpoint for the template, the CSV template file has been placed at `templates/treatments-template.csv`. This is similar to how the `ie6.html` and other images are accessed.

**Comment by Charence** [comment]
@m1chalkubiak 

I have pulled the latest changes from this branch and I'm experiencing some problems loading the frontend.

![Screenshot 2020-02-03 14 39 42](https://user-images.githubusercontent.com/1438332/73662333-8690e100-4693-11ea-9631-2901037b0eca.png)
![Screenshot 2020-02-03 14 39 57](https://user-images.githubusercontent.com/1438332/73662343-8abcfe80-4693-11ea-8867-18740882ff70.png)

**Comment by m1chalkubiak** [comment]
@Charence 
But after pulling latest commit 973de28? I did have this similar-looking problem this today but restarting the backend server helped me.

**Comment by Charence** [comment]
@m1chalkubiak 

No. I've just seen and pulled 973de28 and it works fine now! Thanks!

**Comment by m1chalkubiak** [comment]
Good to hear that. If I can ask what are the estimations for the next backend tasks?
I had started working on Milestone 3, but most of the features depend on backend endpoints, which I believe hasn't been done. 

On the other hand, I didn't get any kind of feedback regarding current state of this feature, maybe there is something to fix from frontend side. Did You had time to check it?

**Comment by carmenfan** [comment]
@m1chalkubiak  Just had a look. Can we rework the look and feel of the teamspace settings please (sorry, our fault on the design, but it kind of looks horrendous and takes much way too much space. 

Please see here: https://marvelapp.com/4b107ge/screen/66017347

Diff Notes:
- [ ] The font sizes are massive. It should be similarly formatted as model settings.
- [ ] Teamspace name should be greyed out with a dash line underneath like model ID in model settings
- [ ] Let's use a smaller size chips and have the enter new chip line the same line as the line of chips. If it overflows to a new line, that's fine
- [ ] Let's ditch the sections and the section dividing lines.
- [ ] Treatment: pencil for upload, download icon (same as model download icon) to download. If no existing treatment -> download goes to template, otherwise download existing csv.
- [ ] Save button needs inverting. See model setting's save button.

**Comment by carmenfan** [comment]
**Risk Panel**

@m1chalkubiak somethings I noticed:

- [ ] These settings are wrong:
![image](https://user-images.githubusercontent.com/11945337/73676380-2ce8e080-46ac-11ea-85e8-b4705941c3f3.png)
Staging is showing:
![image](https://user-images.githubusercontent.com/11945337/73676412-3a9e6600-46ac-11ea-86d4-ffd25f53378b.png)
The data is there, so it should be set..
![image](https://user-images.githubusercontent.com/11945337/73676445-49851880-46ac-11ea-82cc-e79f7c6f8c11.png)
- [ ] Error when I'm trying to change risk likelihood/consequence. 
![markup](https://user-images.githubusercontent.com/11945337/73676735-cdd79b80-46ac-11ea-9fde-bb63a04b277d.gif)
it is also sending a lot of junk along with it even though I've only changed 1 field:
![image](https://user-images.githubusercontent.com/11945337/73676820-f19ae180-46ac-11ea-9bb4-8392e1854356.png)
Same action, staging version only sends this:
![image](https://user-images.githubusercontent.com/11945337/73676840-fd86a380-46ac-11ea-8108-48ab21bff189.png)
- [ ] Now that it's in it's own tab, can we change the layout of the resources a bit please:
![image](https://user-images.githubusercontent.com/11945337/73677049-640bc180-46ad-11ea-94ec-88a8bcc25d7d.png)
- [ ] When you create a new risk the default focus goes to construction scope. Can we change it to the title please:
![image](https://user-images.githubusercontent.com/11945337/73677169-987f7d80-46ad-11ea-9100-4a6083a2c48e.png)
- [ ] The footer is massive on create new risk:
![image](https://user-images.githubusercontent.com/11945337/73677237-b8af3c80-46ad-11ea-94f8-5b7e69972b22.png)
- [ ] Can we add a line on description, treatment and treatment description so it looks less like a header and more like a input box when it's empty?
![image](https://user-images.githubusercontent.com/11945337/73677332-e4cabd80-46ad-11ea-8399-a6b29099abc7.png)
![image](https://user-images.githubusercontent.com/11945337/73677360-fb711480-46ad-11ea-9e66-06697808c8d9.png)

- [ ] Footer is also massive on the treatment/attachment tabs:
![image](https://user-images.githubusercontent.com/11945337/73677400-117ed500-46ae-11ea-9015-9cff3b44a030.png)
![image](https://user-images.githubusercontent.com/11945337/73677420-1cd20080-46ae-11ea-9cc5-346e8b71ccc5.png)

**Comment by m1chalkubiak** [comment]
> **Risk Panel**
> * [x]  These settings are wrong:
>   ![image](https://user-images.githubusercontent.com/11945337/73676380-2ce8e080-46ac-11ea-85e8-b4705941c3f3.png)
> * [x]  Error when I'm trying to change risk likelihood/consequence.
>   it is also sending a lot of junk along with it even though I've only changed 1 field:
> * [x]  Now that it's in it's own tab, can we change the layout of the resources a bit please:
> * [x]  When you create a new risk the default focus goes to construction scope. Can we change it to the title please:

All above should be done.

About the remaining task, those two about footer "size". 
I forced the layout to push footer to the end of the container. But please check if this was the intention you wanted to achieve in this form.

> * [ ]  The footer is massive on create new risk:
> * [ ]  Footer is also massive on the treatment/attachment tabs:

Regarding the one below, I would like to be 100% sure what We would like to achieve.
Most of the forms witch having a text area fields are using the same component, I believe that in some of them the display wasn't so problematic, as they did have some default "placeholder"  (No Description).
So, should we add the underline to all of them, or are we missing the placeholder in some of them?

> * [ ]  Can we add a line on description, treatment and treatment description so it looks less like a header and more like a input box when it's empty?
>   ![image](https://user-images.githubusercontent.com/11945337/73677332-e4cabd80-46ad-11ea-8399-a6b29099abc7.png)
>   ![image](https://user-images.githubusercontent.com/11945337/73677360-fb711480-46ad-11ea-9e66-06697808c8d9.png)

**Comment by carmenfan** [comment]
@m1chalkubiak  

> I forced the layout to push footer to the end of the container. But please check if this was the intention you wanted to achieve in this form.
will check and let you know!

[So, should we add the underline to all of them, or are we missing the placeholder in some of them?](url)
Please add a line for all of them. My worry is that it looks more like a label than a "disabled input field"(I know it technically isn't), so the user doesn't know it's a field that is editable.


not sure if you saw [the post above](https://github.com/3drepo/3drepo.io/issues/1847#issuecomment-581528774), as I double posted, there's also some change requests for the teamspace settings :)

**Comment by m1chalkubiak** [comment]
> not sure if you saw [the post above](https://github.com/3drepo/3drepo.io/issues/1847#issuecomment-581528774), as I double posted, there's also some change requests for the teamspace settings :)

Don't worry I saw it, I just didn't start to work on it at all, for now. I would like to do the whole risk panel feedback and then move to Teamspace settings.

**Comment by Charence** [comment]
Hi @m1chalkubiak 

Please note that in commit 3b2cca0 I renamed the `treatments` endpoints to `mitigations`. I realised that the fields in risk are currently named `mitigations_*` and I think it will be clearer if the naming on the backend is kept consistent. References to `treatment` will only be on the frontend UI (similar to how `Risks` are called `SafetiBase` on the UI).

The following endpoints have changed:

- `GET /:teamspace/settings/treatments.csv` --> `GET /:teamspace/settings/mitigations.csv`
- `POST /:teamspace/settings/treatments.csv` --> `POST /:teamspace/settings/mitigations.csv`

Please also note that the field `treatmentsUpdatedAt` has been changed to `mitigationsUpdatedAt ` for Teamspace Settings.

The following endpoints are now available (currently with sample responses)

- `POST /:teamspace/mitigations` Find mitigation suggestions

An example request:
```
POST /acme/mitigations HTTP/1.1
{
	"associated_activity":"Activity 1",
	"category":"safety_fall",
	"element":"Doors",
	"location_desc":"Tower 3 - Level 2",
	"risk_factor":"Factor 9",
	"scope":"Tower 3"
}
```

The request body includes the defined fields from the risk (e.g. `associated_activity`, `category`, etc.) to filter the results returned for the mitigation (treatment) suggestions. All of these fields are optional, so for example, if only `element` is defined in the risk, the request body will be:
```
{
	"element":"Doors",
}
```
and the response will only filter by `element`.

The response will be a list of objects with fields `mitigation_desc`, `mitigation_details`, `mitigation_stage` and `mitigation_type`, which correspond to the same fields for risk. A sample response:
```
[
	{
		"mitigation_desc":"Replace all openings required in floor slabs with precast service openings.",
		"mitigation_details":"Replace openings larger than a standard anvil required in floor slabs with precast service openings from A/W 2020 catalogue.",
		"mitigation_stage":"Preliminary Design",
		"mitigation_type":"Eliminate"
	},
	{
		"mitigation_desc":"Provide safe walking surface joint covers. Any covering should be: strong enough to support any loads likely to be placed on it ; and fixed in position to prevent accidental dislodgement.",
		"mitigation_details":"Safe walking surface joint covers for all joins and gaps. Covers should be strong enough to support any loads likely to be placed on it and fixed in position with bolts to prevent accidental dislodgement.",
		"mitigation_stage":"Detail Design",
		"mitigation_type":"Reduce"
	},
	{
		"mitigation_desc":"Provide warning markings and/or colour change.",
		"mitigation_details":"Provide warning markings from approved list of markings and/or colour change using chart from Document XYZ.",
		"mitigation_stage":"Preconstruction",
		"mitigation_type":"Control"
	}
]
```

- `GET /:teamspace/mitigations/criteria` Get mitigation criteria (autocomplete for risk fields)

This will return lists of strings for the autocomplete. A sample response:

```
{
	"associated_activity":[
		"All construction",
		"Site tests",
		"Logistics"
	],
	"category":[
		"safety_electricity"
	],
	"element":[
		"Doors",
		"Floors",
		"Pipes",
		"Vents",
		"Walls"
	],
	"location_desc":[
		"Tower 1 - Level 0",
		"Tower 1 - Level 1",
		"Tower 1 - Level 2",
		"Tower 2 - Level 0",
		"Tower 2 - Level 1",
		"Tower 3 - Level 0",
		"Tower 3 - Level 1",
		"Tower 3 - Level 2"
	],
	"mitigation_stage":[
		"Preliminary Design",
		"Detail Design",
		"Preconstruction",
		"Site work and Change Control"
	],
	"mitigation_type":[
		"Eliminate",
		"Reduce",
		"Control",
		"Inform"
	],
	"risk_factor":[
		"Factor 2",
		"Factor 5",
		"Factor 8"
	],
	"scope":[
		"General concrete",
		"In situ concrete"
	]
}
```

Where autocomplete values are available for a field, a list with a matching field name will be returned. e.g. `scope` in the response corresponds to `scope` in risks and it has `General concrete` and `In situ concrete` as 2 autocomplete candidates.

Similar to the text input in Smart Groups and User Management filters, the user can input text that does not match the list of autocomplete values.

If autocomplete values are not available, the field will not be returned in the response or it will be an empty list.

`category` is a drop-down list and its values are defined in Teamspace Settings at the moment. I'm not sure if the values for it should be included in this endpoint. **What is your opinion on this?** Also, if it is included, should it be a list of Strings, or should it be in the format:
```
[
	{
		"label":"Category 1",
		"value":"category_1"
	},
	{
		"label":"Category 2",
		"value":"category_2"
	}
]
```

**Comment by Charence** [comment]
> What is your opinion on this?

`category` will be returned as a list of Strings when using the `GET /:teamspace/mitigations/criteria` endpoint.

e.g.: `[ "Category 1", "Category 2" ]

**Comment by m1chalkubiak** [comment]
@Charence 
No problem, list of strings will be enough for showing drop-down list.
I think for now everything seems clear to me.

@carmenfan Teamspace settings feedbacks are done.
Changing display of chips took me longer then I expected. I end on using the external library, which covers most of the edge cases but has some additional features. I didn't try for now to customize them, just did a basic styling. However, I believe You could have some additional requests regarding its current behavior. Please check it and let me know.

**Comment by m1chalkubiak** [comment]
@Charence 
I think I've done all the features for the milestone 3.
Since yesterday I've been doing the tests trying to find all edge cases that I could miss, so now I believe everything works fine.
Regarding the backend part, I spotted two things.
In ```POST /:teamspace/mitigations``` respons have ```mitigation_details``` property while in others its called ```mitigation_detail``` so its probably a typo. 
Regarding ```category``` field, I have doubt that it should stay a select field.
Maybe input with autosuggestion like in other new fields in this form would be a better idea in reference to backward compatibility.
Now, UI is unable to render old values of categories, but maybe You have some different plans assuming data migration.

**Comment by Charence** [comment]
> In `POST /:teamspace/mitigations` respons have `mitigation_details` property while in others its called `mitigation_detail` so its probably a typo.

Yes, you are right. I made a typo. It should be `mitigation_detail`.

> Regarding `category` field, I have doubt that it should stay a select field.
> Maybe input with autosuggestion like in other new fields in this form would be a better idea in reference to backward compatibility.
> Now, UI is unable to render old values of categories, but maybe You have some different plans assuming data migration.

For the category field, we would like to keep it as a drop down menu as the user shouldn't be able to add additional categories through the risk UI. For the old categories, I will write a db migration script.

**Comment by Charence** [comment]
@m1chalkubiak 

I've noticed there's a slight problem when the `mitigation_detail` is collapsed. It is fine when expanded.

![Screenshot 2020-02-18 at 14 59 54](https://user-images.githubusercontent.com/1438332/74747852-8120c280-525f-11ea-98ff-7dd572061e7a.png)

**Comment by m1chalkubiak** [comment]
@Charence 
Thanks for noticing this. I just pushed a fix.

**Comment by m1chalkubiak** [comment]
Hey @Charence 
Is this branch ready for the final corrections on my side? I saw your last commit, but I don't know if your work is done.

**Comment by Charence** [comment]
> Is this branch ready for the final corrections on my side? I saw your last commit, but I don't know if your work is done.
> Also, I see some lint issues in backend code.

Sorry @m1chalkubiak it is not ready for final corrections yet. Backend changes are still incomplete. I will let you know when done and give you a list of corrections.

**Comment by Charence** [comment]
Hi @m1chalkubiak it is now possible to upload/download csv files, which was the last part missing.

There are some small things we would like to change on Teamspace Settings:
- [ ] Save button stays active even after it is pressed and teamspace settings updated. It should be disabled when there are no changes.
![Screenshot 2020-03-02 14 00 06-save](https://user-images.githubusercontent.com/1438332/75695174-935c2100-5ca1-11ea-8663-208a7ab927e9.png)

- [ ] The styling of the text should be more consistent with other pages such as `Model Settings`.
![Screenshot 2020-03-02 14 00 06-style](https://user-images.githubusercontent.com/1438332/75695261-b4bd0d00-5ca1-11ea-99e1-522fbfd6ebeb.png)

There are also some conflicts on the frontend with staging. I will let you know if we have more comments. Thanks!

**Comment by m1chalkubiak** [comment]
@Charence 

> There are some small things we would like to change on Teamspace Settings:

Both of them are done, unfortunately, I see some errors from backend during fetching of mitigations/criteria.

<img width="1064" alt="2020-03-3 o 11 28 40" src="https://user-images.githubusercontent.com/24941866/75767133-9529f100-5d42-11ea-9eac-1073e4463641.png">

**Comment by Charence** [comment]
Thanks @m1chalkubiak, backend error has been fixed.

I have found the following problems:

- [ ] The scrolling goes too far down (I think Issue has the same problem because it is the same component)
![Mar-03-2020 15-33-22](https://user-images.githubusercontent.com/1438332/75796233-447abe00-5d6b-11ea-84cd-43789a48e717.gif)

- [ ] Two scrollbars appear - only the outer scrollbar should be needed to scroll everything in the card 
![Screenshot 2020-03-03 16 03 48](https://user-images.githubusercontent.com/1438332/75796792-1053cd00-5d6c-11ea-9373-10c467bf2291.png)

- [ ] When saving a new risk the whole page goes blank
![Mar-03-2020 16-01-28](https://user-images.githubusercontent.com/1438332/75797038-73456400-5d6c-11ea-9c07-a7d3fee431b0.gif)

- [ ] Selecting a treatment suggestion also populates fields on the Risk tab, which should not happen. Fields on the risk tab should be used in the request for Suggestions, but the suggestion should not be able to populate category, associated activity, element type, risk factor, construction scope or location. It should only populate the fields in the treatment tab (`mitigation_desc`, `mitigation_detail`, `mitigation_stage`, mitigation_type`)
![Mar-03-2020 16-19-24](https://user-images.githubusercontent.com/1438332/75797112-8f490580-5d6c-11ea-86e0-3a5932aac662.gif)

**Comment by m1chalkubiak** [comment]
Hi @Charence 
I think I had fixed all the issues you mentioned. However, I would be grateful if you could provide me a working example CSV file with suggestions treatments. Just to be able to make a final test regarding the last point.
