### ISSUE TITLE
Toolbar buttons

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1870]
- [ ] [Show Coordinates does not work](https://github.com/3drepo/3drepo.io/issues/1870#issuecomment-579164998)
- [ ] [Measurement feature brings up BIM Card](https://github.com/3drepo/3drepo.io/issues/1870#issuecomment-579166597)

**Comment by BDavydov** [comment]
### Description
Show coordinates does not work
 
### Steps to replicate
- Open a model in dev.3drepo.io
- Activate 'Show Coordinates' in the toolbar
- Click anywhere on a model

### Pictures/ Gifs of the error
![Tool Bar Coordinates](https://user-images.githubusercontent.com/19904513/73253207-f85cbc80-41b3-11ea-8b9e-5bd8d16cff5b.gif)

**Comment by BDavydov** [comment]
### Description
Clicking on measurement option brings up the BIM Card.
 
### Steps to replicate
- Open a model in dev.3drepo.io
- Activate 'Measurement' feature from a toolbar
- Click again to deactivate it
- Click again to hide BIM Card and activate the measurement feature alone

### Pictures/ Gifs of the error
![Tool Bar Measurement](https://user-images.githubusercontent.com/19904513/73253500-905aa600-41b4-11ea-98f8-efa98717492a.gif)

**Comment by carmenfan** [comment]
@BDavydov you're doing a dev release testing, so just put it in a single issue.

closing this in favour of #1869
