### ISSUE TITLE
Measuring tool v2

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1873]
requires https://github.com/3drepo/3drepounity/issues/244

**UnityUtils**
The following methods needs to be exposed from Unity:
- [x] dropping a new type of pin
- [x] A callback that shows the measurement that has just been created
- [x] A callback to show if a measurement has been deleted
- [x] Turn on/off measuring mode
- [x] hide/show measuring toolbar
- [x] Setting measuring mode to 
      - point to point
      - Raycast
      - Min. distance
      - Surface on click
      - Polygonal surface
- [x] Toggle metres/mm display
- [x] Toggle snap to edges
- [x] Clear all measurements
- [x] Change the colour of a specific measurement
- [x] delete a specific measurement

**Frontend**
- [x] Remove measuring icon from toolbar
- [x] add measuring panel/button on the right hand side
- [x] If the panel is closed, it should disable the measuring tool, but measurements should stay on the screen
- [x] If there are no measurements it should display a message (see wireframe)
- [x] Section headers should only appear if there is at least 1 measurement under it.
- [x] Add measuring type icons (They should be toggle buttons - only one can be active at a time)
- [x] The pin is a bit of a special case, it's technically outside of the measuring tool feature so there isn't a "Drop pin mode" call in unity util. Refer to the way we drop issue/risk pins, it should be handled the same way with a different pin type.
- [x] Unity utils will have a callback to tell you when a new measurement is created, whenever this happens it should be added to the card
- [x] All meausrements should come with a colour, but the user should be able to change it with the colour picker (which will update unity with the new colour
- [x] Measurements are deleted via the X button or Delete all in the menu.
- [x] Selected total should display the sum of all the measurements selected
- [x] Newly added measurements should be checked by default and contributes to the selected total entry
- [x] Hamburger button menu:
     - [x] Edge Snapping - a toggle that calls a unity function
     - [x] Show X Y Z - a toggle that calls a unity function
     - [x] Units displayed in mm/m - it should say mm if it's displaying m and vice versa, also change the measurement units accordingly on the panel. If the units is ft, hide the option
     - [x] Reset colours should reset the colours do the default (should be a different default colour per type of measurement
     - [x] Delete all - A toggle that calls unity function, also remove all measurements from the card

**Backend**
- [x] End point to fetch the information from a mesh by ID

**Comment by m1chalkubiak** [comment]
Hi @carmenfan, 
I have done part of the work related to the implementation of the new tool, but I have a few questions and doubts.
 
> * [ ]  Add measuring type icons (They should be toggle buttons - only one can be active at a time)
> * [ ]  The pin is a bit of a special case, it's technically outside of the measuring tool feature so there isn't a "Drop pin mode" call in unity util. Refer to the way we drop issue/risk pins, it should be handled the same way with a different pin type.

If I understand it correctly we are talking here about very first tool available from the bottom of measure panel. I would like to ask for a more detailed description of this point, I admit that I am not sure how it should be implemented.

> * [ ]  Hamburger button menu:
>   * [ ]  Edge Snapping - a toggle that calls a unity function
>   * [ ]  Show X Y Z - a toggle that calls a unity function

I am not sure which function from Unity I should call 

>   * [x]  Units displayed in mm/m - it should say mm if it's displaying m and vice versa, also change the measurement units accordingly on the panel. If the units is ft, hide the option
>   * [ ]  Reset colours should reset the colours do the default (should be a different default colour per type of measurement

Would it be possible to implement such functionality in the Unity? Currently, I would have to iterate after all measurements and make a request with a color change for each of them.

**Comment by carmenfan** [comment]
> Hi @carmenfan,
> I have done part of the work related to the implementation of the new tool, but I have a few questions and doubts.
> 
> > * [ ]   Add measuring type icons (They should be toggle buttons - only one can be active at a time)
> > * [ ]   The pin is a bit of a special case, it's technically outside of the measuring tool feature so there isn't a "Drop pin mode" call in unity util. Refer to the way we drop issue/risk pins, it should be handled the same way with a different pin type.
> 
> If I understand it correctly we are talking here about very first tool available from the bottom of measure panel. I would like to ask for a more detailed description of this point, I admit that I am not sure how it should be implemented.
> 
> > * [ ]   Hamburger button menu:
> >   
> >   * [ ]   Edge Snapping - a toggle that calls a unity function
> >   * [ ]   Show X Y Z - a toggle that calls a unity function
> 
> I am not sure which function from Unity I should call
> 
> > * [x]   Units displayed in mm/m - it should say mm if it's displaying m and vice versa, also change the measurement units accordingly on the panel. If the units is ft, hide the option
> > * [ ]   Reset colours should reset the colours do the default (should be a different default colour per type of measurement
> 
> Would it be possible to implement such functionality in the Unity? Currently, I would have to iterate after all measurements and make a request with a color change for each of them.

@sanmont3drepo  can you answer?

**Comment by sanmont3drepo** [comment]
Here is a wireframe of the feature:
https://marvelapp.com/213a03c6/screen/66581724

> Hi @carmenfan,
> I have done part of the work related to the implementation of the new tool, but I have a few questions and doubts.
> 
> > * [ ]   Add measuring type icons (They should be toggle buttons - only one can be active at a time)
> > * [ ]   The pin is a bit of a special case, it's technically outside of the measuring tool feature so there isn't a "Drop pin mode" call in unity util. Refer to the way we drop issue/risk pins, it should be handled the same way with a different pin type.
> 
> If I understand it correctly we are talking here about very first tool available from the bottom of measure panel. I would like to ask for a more detailed description of this point, I admit that I am not sure how it should be implemented.

It should be the button on the last panel in the viewer GUI.
It should be added an entry in  **\3drepo.io\frontend\constants\viewerGui.ts** in **VIEW_PANELS** and **VIEWER_LEFT_PANELS**. And also modify the PANELS_MAP in **\3drepo.io\frontend\routes\viewerGui\viewerGui.component.tsx**.
You can check the wireframe for a more visual guide.


> 
> > * [ ]   Hamburger button menu:
> >   
> >   * [ ]   Edge Snapping - a toggle that calls a unity function
> >   * [ ]   Show X Y Z - a toggle that calls a unity function
> 
> I am not sure which function from Unity I should call
I've missed to exposed that one, ill add it today and let you know when Im finished

> 
> > * [x]   Units displayed in mm/m - it should say mm if it's displaying m and vice versa, also change the measurement units accordingly on the panel. If the units is ft, hide the option
> > * [ ]   Reset colours should reset the colours do the default (should be a different default colour per type of measurement
> 
> Would it be possible to implement such functionality in the Unity? Currently, I would have to iterate after all measurements and make a request with a color change for each of them.

The idea is that unity should have the minimal possible logic, this kind of things should be manage from the web app.

**Comment by m1chalkubiak** [comment]
Hi @sanmont3drepo, thank you for the answers. 

> > > * [ ]    The pin is a bit of a special case, it's technically outside of the measuring tool feature so there isn't a "Drop pin mode" call in unity util. Refer to the way we drop issue/risk pins, it should be handled the same way with a different pin type.
> > 
> > 
> > If I understand it correctly we are talking here about very first tool available from the bottom of measure panel. I would like to ask for a more detailed description of this point, I admit that I am not sure how it should be implemented.
>
> It should be the button on the last panel in the viewer GUI.
> It should be added an entry in **\3drepo.io\frontend\constants\viewerGui.ts** in **VIEW_PANELS** and **VIEWER_LEFT_PANELS**. And also modify the PANELS_MAP in **\3drepo.io\frontend\routes\viewerGui\viewerGui.component.tsx**.
> You can check the wireframe for a more visual guide.

I was asking about the first measuring tool available in the panel, which, as I understand it, should coincide with the Pins mechanism.

> > > * [x]    Units displayed in mm/m - it should say mm if it's displaying m and vice versa, also change the measurement units accordingly on the panel. If the units is ft, hide the option
> > > * [ ]    Reset colours should reset the colours do the default (should be a different default colour per type of measurement
> > 
> > 
> > Would it be possible to implement such functionality in the Unity? Currently, I would have to iterate after all measurements and make a request with a color change for each of them.
> 
> The idea is that unity should have the minimal possible logic, this kind of things should be manage from the web app.

Of course, I understand, but in this case, I would need additional metadata to be able to recognize measurements made with different tools. Currently, type property that I get tells me only about the type of measurement: length or area.

**Comment by sanmont3drepo** [comment]
> Of course, I understand, but in this case, I would need additional metadata to be able to recognize measurements made with different tools. Currently, type property that I get tells me only about the type of measurement: length or area.

I dont understand if you refer to how pins works or how to enter pindrop mode or in general,  so to cover bases a general overview I hope this helps:

### For adding a pin
- basically as you can see here : https://github.com/3drepo/3drepo.io/blob/540684bf76a26a5ac20a61f2dafc22318fd88a9b/frontend/routes/viewerGui/components/pinButton/pinButton.component.tsx#L51
the viewer is set to dropmode 
- in the handplepickpoint and handleClickBackground is handled the position on which the pin will drop.
- this in returns calls https://github.com/3drepo/3drepo.io/blob/540684bf76a26a5ac20a61f2dafc22318fd88a9b/frontend/modules/issues/issues.redux.ts#L141 and the pin data is now in the state
- When the user decides that the position is ok  then  she deactivate the mode and this gets call with false as an argument 
https://github.com/3drepo/3drepo.io/blob/540684bf76a26a5ac20a61f2dafc22318fd88a9b/frontend/routes/viewerGui/components/pinButton/pinButton.component.tsx#L51

### For showing the  pin in
- in the issues selector the issues that has pins generate the actual pin data here:
https://github.com/3drepo/3drepo.io/blob/540684bf76a26a5ac20a61f2dafc22318fd88a9b/frontend/modules/issues/issues.selectors.ts#L128
- in the viewercanvas component this selector is set a a prop and in component update the pins get set to render here
https://github.com/3drepo/3drepo.io/blob/540684bf76a26a5ac20a61f2dafc22318fd88a9b/frontend/routes/viewerCanvas/viewerCanvas.component.tsx#L110
and here
https://github.com/3drepo/3drepo.io/blob/540684bf76a26a5ac20a61f2dafc22318fd88a9b/frontend/routes/viewerCanvas/viewerCanvas.component.tsx#L67

This is the general gist of it if you have any more questions  or if im answering the wrong one dont 


> Hi @sanmont3drepo, thank you for the answers.
> 
> > > > * [ ]     The pin is a bit of a special case, it's technically outside of the measuring tool feature so there isn't a "Drop pin mode" call in unity util. Refer to the way we drop issue/risk pins, it should be handled the same way with a different pin type.
> > > 
> > > 
> > > If I understand it correctly we are talking here about very first tool available from the bottom of measure panel. I would like to ask for a more detailed description of this point, I admit that I am not sure how it should be implemented.
> > 
> > 
> > It should be the button on the last panel in the viewer GUI.
> > It should be added an entry in **\3drepo.io\frontend\constants\viewerGui.ts** in **VIEW_PANELS** and **VIEWER_LEFT_PANELS**. And also modify the PANELS_MAP in **\3drepo.io\frontend\routes\viewerGui\viewerGui.component.tsx**.
> > You can check the wireframe for a more visual guide.
> 
> I was asking about the first measuring tool available in the panel, which, as I understand it, should coincide with the Pins mechanism.
> 
> > > > * [x]     Units displayed in mm/m - it should say mm if it's displaying m and vice versa, also change the measurement units accordingly on the panel. If the units is ft, hide the option
> > > > * [ ]     Reset colours should reset the colours do the default (should be a different default colour per type of measurement
> > > 
> > > 
> > > Would it be possible to implement such functionality in the Unity? Currently, I would have to iterate after all measurements and make a request with a color change for each of them.
> > 
> > 
> > The idea is that unity should have the minimal possible logic, this kind of things should be manage from the web app.
> 
> Of course, I understand, but in this case, I would need additional metadata to be able to recognize measurements made with different tools. Currently, type property that I get tells me only about the type of measurement: length or area.

I think you should just use the colour that came originally with the recently created measurement.

**Comment by sanmont3drepo** [comment]
@m1chalkubiak also de enable/disable Show X Y Z function has been added to unity util here:
https://github.com/3drepo/3drepo.io/blob/540684bf76a26a5ac20a61f2dafc22318fd88a9b/frontend/globals/unity-util.ts#L776
https://github.com/3drepo/3drepo.io/blob/540684bf76a26a5ac20a61f2dafc22318fd88a9b/frontend/globals/unity-util.ts#L784

**Comment by m1chalkubiak** [comment]
First of all, thank you very much @sanmont3drepo , descriptions and comments were clear and have helped me a lot.
With the current implementation, it seems to me that the ALL_MEASUREMENTS_REMOVED event is not needed. When I call clearMeasureToolMeasurements Unity method, I clean up state from measurements myself. So additional listening seems unnecessary unless I should wait until give me info that all measurements have been removed, Is that the case here?

I have an additional question regarding "remove measuring icon from toolbar" point. Of course, I know how to remove it, but it seems that there is additional logic inside toolbar regarding enabling measurements. If I understand it correctly BIM panel and measurement tool can not be active at the same time, is it right?
If this still correct I need to add this additional logic to the current implementation.

@carmenfan , I have my doubts when comparing wireframes to implementation, I realized this recently but forgot to ask earlier. 
Where exactly the measurement names should come from, on the mockups they have individual names, but this would mean that the user would enter them himself. The mockups do not indicate when it should be possible.

I just realized that I didn't add the ability to collapse the measurement section. I apologize for that. Of course, there are also a few issues about styling that can be improved, but I would like to know if except that, the main functionally of the new panel works in line with your expectations.

**Comment by carmenfan** [comment]
> If I understand it correctly BIM panel and measurement tool can not be active at the same time, is it right?

Yes that's correct. I guess in translation, if any of the measuring tool button is toggled on, BIM card should be toggled off and vice versa

> Where exactly the measurement names should come from, on the mockups they have individual names, but this would mean that the user would enter them himself. The mockups do not indicate when it should be possible.

Sorry that's not clear. We should've addressed it in the mockup!

If you make it so that it's like editing description in issues/risks, where there is a edit button and a save button that'll be great. like this:
![sample](https://user-images.githubusercontent.com/11945337/77181861-d270db80-6ac3-11ea-82a7-606f35a1acc8.gif)

Upon save we need to send the measuring name to unity so it displays on the label too. But I doin't think this is done. @sanmont3drepo you think you can have a look at facilitating that?

**Comment by m1chalkubiak** [comment]
Hi @carmenfan 
> > If I understand it correctly BIM panel and measurement tool can not be active at the same time, is it right?
> 
> Yes that's correct. If any of the measuring tool button is toggled on, BIM card should be toggled off and vice versa

I added this additional logic as well as the option of collapsing the measuring section.

I'm right now working on adding the option of changing the measurement name on the list, of course, I will do it so that it can be quickly connected with Unity when needed. However, out of that, all seems to work fine, I would be grateful if you let me know if you have any comments on the current implementation. Note that elements such as checkbox, color picker take up more space than on mockups, but I wanted to be consistent with the rest of the application. I've also added icons to the panel menu, so if there is any feedback here, I'm waiting for them.

**Comment by carmenfan** [comment]
@m1chalkubiak 

I just had a look and it's looking good. Some things I found:
- [ ] Can we set the sections to be expanded by default?
- [ ] It should be down arrow when expanded, right arrow when collapsed: 
![image](https://user-images.githubusercontent.com/11945337/77443166-cbf3a400-6de2-11ea-958f-b7fdf34d9fb1.png)
![image](https://user-images.githubusercontent.com/11945337/77443281-e0d03780-6de2-11ea-85a0-b0baa2351fb0.png)
- [ ] Measuring pins is using issue pin as the type, which is incorrect. it should be dropping bookmark pins: 
![image](https://user-images.githubusercontent.com/11945337/77444580-f134e200-6de3-11ea-8f26-6282199bf0e3.png)
- [ ] Units should display right next to the numbers:
![image](https://user-images.githubusercontent.com/11945337/77444136-7075e600-6de3-11ea-8c93-20899d930a54.png)
- [ ] Can we make all the measurements align? so the x y z measurements should move towards the right and be inline with the length measurements:
![image](https://user-images.githubusercontent.com/11945337/77444806-36591400-6de4-11ea-94b5-b8b65492ebb3.png)
- [ ] Can we add a bit more padding on the edge of the card, something like this : 
![image](https://user-images.githubusercontent.com/11945337/77444984-6c969380-6de4-11ea-9416-46afd63a4f29.png)
- [ ] Can we have uniform spacing between the components, it looks like there is a bigger gap between the check box and the arrow vs arrow and the name:
![image](https://user-images.githubusercontent.com/11945337/77445233-ba130080-6de4-11ea-81d6-59e04639890f.png)
- [ ] Deleting a measurement shouldn't cause the measurements below it to rename. (i.e. point 2 is deleted, point 3 should stay as point 3, not point 2.)
![1](https://user-images.githubusercontent.com/11945337/77445535-20981e80-6de5-11ea-9366-c3c8546d27f0.gif)
- [ ] Measurements on the card doesn't match on viewer, looks like we're pretending the values from unity to be mm when it's in m?: 
![image](https://user-images.githubusercontent.com/11945337/77445754-62c16000-6de5-11ea-89a3-6e8819624f6a.png)
Looks like this is a problem for all types of measurements:
![image](https://user-images.githubusercontent.com/11945337/77446060-ca77ab00-6de5-11ea-905a-c4356508a1e6.png)
- [ ] The check all check box should be on a half ticked state if some of the measurements are selected instead of empty 
![image](https://user-images.githubusercontent.com/11945337/77446678-99e44100-6de6-11ea-94b1-ccc03723fd10.png)
Like in user management:
![image](https://user-images.githubusercontent.com/11945337/77446738-af596b00-6de6-11ea-97e1-47cc349a8535.png)
- [ ] Can we make the check box grey instead of green?

**Comment by carmenfan** [comment]
@m1chalkubiak #1916 has been merged in , that will probably affect this branch quite a bit so if you can do the merge when convenient that'd be great! :)

**Comment by m1chalkubiak** [comment]
Hi @carmenfan 
> * [x]  Can we set the sections to be expanded by default?
> * [x]  It should be down arrow when expanded, right arrow when collapsed:
> * [ ]  Measuring pins is using issue pin as the type, which is incorrect. it should be dropping bookmark pins:

I did it as instructed by Santiago, but I guess probably this wasn't clear for me from the beginning. Tomorrow I will start to work on change it, but in case of any questions, I will let You know.
 
> * [x]  Units should display right next to the numbers:
> * [x]  Can we make all the measurements align? so the x y z measurements should move towards the right and be inline with the length measurements:
> * [x]  Can we add a bit more padding on the edge of the card, something like this :

I added 8px on both sides. Please let me know if it ok or the spacing should be bigger.

> * [x]  Can we have uniform spacing between the components, it looks like there is a bigger gap between the check box and the arrow vs arrow and the name:
> * [x]  Deleting a measurement shouldn't cause the measurements below it to rename. (i.e. point 2 is deleted, point 3 should stay as point 3, not point 2.)

> * [ ]  Measurements on the card doesn't match on viewer, looks like we're pretending the values from unity to be mm when it's in m?:
>   Looks like this is a problem for all types of measurements:

I've been working on models from the demo sample project and they seem to work properly.
However, I suspect that the issue can come from the initial unit value set at the beginning of the measurements. Based on what, Unity determines what unit is it? Settings in the model or something else?

> * [ ]  The check all check box should be on a half ticked state if some of the measurements are selected instead of empty
>   Like in user management:

I missed it, I will add it tomorrow.

> * [ ]  Can we make the check box grey instead of green?

Should they be gray or navy blue, like in the comparison panel?

> * [x]  State of the panel should reset when the user exit and re-enter the viewer (even if they go into the same model). There should be no measurements and all tools should be disabled by default:

I Completely forgot about the resetting the panel as I was constantly hard-refreshing the page. It's resetting properly now.

**Comment by carmenfan** [comment]
@m1chalkubiak 

> Based on what, Unity determines what unit is it? Settings in the model or something else?

Unity knows the units of the model as the React code tells unity. The data that unity sends back is what unity currently displays, so if you toggled the measurements to mm, it'll send you mm and if it sends you m, it send back m.

So basically you shouldn't have to fiddle with the numbers apart from when the users change the units toggle, in which case you'd have to update the numbers on the existing measurements, but new measurements should already be in the right units.

**Comment by m1chalkubiak** [comment]
@carmenfan 
> > Based on what, Unity determines what unit is it? Settings in the model or something else?
> 
> Unity knows the units of the model as the React code tells unity. The data that unity sends back is what unity currently displays, so if you toggled the measurements to mm, it'll send you mm and if it sends you m, it send back m.
> 
> So basically you shouldn't have to fiddle with the numbers apart from when the users change the units toggle, in which case you'd have to update the numbers on the existing measurements, but new measurements should already be in the right units.

Of course, you are right, I was not aware that the values ​​come depending on the settings of the model. I mistakenly assumed that they are always in mm, because on models with such a unit I was developing this functionality.
Now the values ​​should display correctly for all models.

**Comment by m1chalkubiak** [comment]
@carmenfan @sanmont3drepo 
Hi all, 
Can You please check if everything is fine on this branch, as after the last commit by Santiago I see that there is some CORS issue with `https://config.uca.cloud.unity3d.com/` resource. 
Also, it seems to me that `show coordinates` option is turned on by default in Unity now.
I made a small amendment related to the change of color format that began to come from Unity.

Adding and editing measurement names work fine.
However, please remember that this has never been displayed for pins, so I wonder if something should change in their case on the Unity side.

**Comment by carmenfan** [comment]
> Can You please check if everything is fine on this branch, as after the last commit by Santiago I see that there is some CORS issue with https://config.uca.cloud.unity3d.com/ resource.

This is fine, @sanmont3drepo  doesn't have unity pro and Unity forces us to send stats to their site on the bottom tier! I will rebuild the unity when everything is done.

> However, please remember that this has never been displayed for pins, so I wonder if something should change in their case on the Unity side.
@sanmont3drepo  will provide you with a function to call to change name inside Unity

**Comment by m1chalkubiak** [comment]
@carmenfan 
I was thinking, as we can add measurement names right now, should we have some kind general method for resetting those names, similar to the case of the colors?

**Comment by sanmont3drepo** [comment]
> @carmenfan
> I was thinking, as we can add measurement names right now, should we have some kind general method for resetting those names, similar to the case of the colors?

For resetting the name just call the unityUtil function without the name parameter

**Comment by m1chalkubiak** [comment]
@sanmont3drepo Yes, I think it could work, however, my question is whether we should have such an option added to the panel menu, currently, we only have color reset.

**Comment by carmenfan** [comment]
> @sanmont3drepo Yes, I think it could work, however, my question is whether we should have such an option added to the panel menu, currently, we only have color reset.

I don't think this is necessary as the default naming bears no meaning to the user.

**Comment by carmenfan** [comment]
@m1chalkubiak  just to confirm all the changes are done on this branch?

If so, @sanmont3drepo  can you make a PR once you're done with the error checking thing?

**Comment by m1chalkubiak** [comment]
@carmenfan 
I believe I still waiting for this additional functionality, which would allow me sent names to Unity pins, or I just not aware that it's already implemented.

> > However, please remember that this has never been displayed for pins, so I wonder if something should change in their case on the Unity side.
> 
> @sanmont3drepo will provide you with a function to call to change name inside Unity

**Comment by carmenfan** [comment]
> @carmenfan
> I believe I still waiting for this additional functionality, which would allow me sent names to Unity pins, or I just not aware that it's already implemented.
> 
> > > However, please remember that this has never been displayed for pins, so I wonder if something should change in their case on the Unity side.
> > 
> > 
> > @sanmont3drepo will provide you with a function to call to change name inside Unity

The pin names should stay on the react side only, as the pins don't get a label in unity there's not much point passing the name down.

**Comment by carmenfan** [comment]
@m1chalkubiak 
Can you add a 30 character limit on the label names?
Also can we fix this? 
![image](https://user-images.githubusercontent.com/11945337/78123794-a54af400-7406-11ea-9eeb-bcf930d042a4.png)

**Comment by m1chalkubiak** [comment]
@carmenfan 
> @m1chalkubiak
> Can you add a 30 character limit on the label names?
> Also can we fix this?

Done & fixed.

> The pin names should stay on the react side only, as the pins don't get a label in unity there's not much point passing the name down.

Last time I probably misunderstood you on this one.

In addition, I made a small refactor resulting from the fact that for the needs of the new panel I was modifying the old measure module, and at some point a realize that it should be renamed to measurements as is responsible for measurements panel.

Now, I believe everything is ready on the front-end side.
