### ISSUE TITLE
Searching in dashboard doesnt seem to do anything

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#1876]
### Description
Searching for anything in the models/federations part of the dashboard doesnt seems to work.

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/42032433/73677180-9d443180-46ad-11ea-9e66-80f4daa26c0b.png)

**Comment by carmenfan** [comment]
Need to hit enter to start the search. 😆
