### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#1882]
### Description

Exposing sensible Prometheus friendly metrics of running instances on /metrics

for example; https://www.npmjs.com/package/express-prometheus-middleware

The desire is to expose operational metrics to keep an eye on the running system. 

### Goals

- [ ] decide on sensible metrics that are worth exposing
- [ ] /metrics route

**Comment by carmenfan** [comment]
This sounds like it's N/A nowadays? @keifgwinn

**Comment by keifgwinn** [comment]
This is still a useful feature to add to the software for monitoring purposes. I've worked around it for now monitoring outside the software.

**Comment by carmenfan** [comment]
closing - we don't use prometheus anymore
