### ISSUE TITLE
Model not accessible...

### ISSUE THREAD

**Issue by theoryshaw** [3drepo/3drepo.io#189]
Thanks @paloknapo for setting up our model. 

Unfortunately after login... this is the only thing i see... 

![2016-02-24_11-29-51](https://cloud.githubusercontent.com/assets/507113/13294533/03f9263a-daea-11e5-951c-cb427feb7b3e.gif)

**Comment by jozefdobos** [comment]
Hi Ryan,

You need to have www, as in https://www.3drepo.io

![image](https://cloud.githubusercontent.com/assets/3008807/13294704/28326394-db1d-11e5-9ebf-00a6aa698684.png)

**Comment by theoryshaw** [comment]
Thanks Josef.
