### ISSUE TITLE
Remove legacy fields from tickets

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1896]
There's scale, norm in issue that no longer makes sense

I think they were for 3D pins in the old days

Also the front end is sending pickedNorm and pickedPos
Also defaultHidden and objectId are sent, I don't know what they are or what they do

![image](https://user-images.githubusercontent.com/11945337/74540816-5ae5e480-4f38-11ea-943a-8c282ab64e94.png)

Which the backend doesn't use and i think it stem from weird variables back in v1 days...

**Comment by m1chalkubiak** [comment]
@carmenfan 
It mostly coincides with this task #1674 
I believe I can fix it right away.

**Comment by carmenfan** [comment]
@m1chalkubiak sure
