### ISSUE TITLE
Add a message if favourites is empty

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1898]
At the moment it just looks like something's wrong:

![image](https://user-images.githubusercontent.com/11945337/74352696-c7ce7280-4db0-11ea-8f87-84e2f007fd3c.png)

**Comment by m1chalkubiak** [comment]
@carmenfan 
I added a simple message saying:
```
No favorites models have been added yet
```
I also did a small refactor on this branch, as I realized that we are displaying such info in plenty of places around the app, but we had a couple of declarations of those message styling which in the end were exactly the same.
So I moved the styling for the empty state information to one place.

However, I wonder if in this particular case, it wouldn't be better not to display an additional tab under which there is nothing until some favorite models are added.

**Comment by carmenfan** [comment]
> However, I wonder if in this particular case, it wouldn't be better not to display an additional tab under which there is nothing until some favorite models are added.

@m1chalkubiak  It's better to have the message, so the users are aware this feature exists :)
