### ISSUE TITLE
Navigation buttons disappear when penultimate issue closed

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1906]
### Description
Navigation buttons disappear when penultimate issue closed

### Steps to replicate
1. Have a list of issues
2. Open one of the issues
3. Set status to `closed` and advance to next issue
4. Repeat 3 until navigation buttons on top row of card disappear
5. Go back to issues list and there will still be one open issue remaining

### Pictures/ Gifs of the error
![Feb-18-2020 14-37-48](https://user-images.githubusercontent.com/1438332/74745868-6f89eb80-525c-11ea-8c91-86309d33ed01.gif)

**Comment by m1chalkubiak** [comment]
@Charence 
So, on frontend we have simple condition checking if the size of a list has at least 2 elements, if no we are no displaying navigation.  I think, in this case, we should check if the item we are currently on is the last item on the list. Please check, if updated conditions work fine for You.
