### ISSUE TITLE
Profile cannot be scrolled

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#1910]
### Description
No option to scroll when Profile page is too long for the screen

### Steps to replicate
- Open Profile page on a low resolution screen (e.g. 2880*1620 @ 200% scale)
- Try to go to bottom of Profile page

### Pictures/ Gifs of the error
![Screenshot 2020-02-24 14 35 00](https://user-images.githubusercontent.com/1438332/75161295-765ca680-5713-11ea-9bc7-8ada47299f67.png)

**Comment by sanmont3drepo** [comment]
This will also fix #1924
