### ISSUE TITLE
SafetiBase Risks Report Is not working

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1919]
### Description
SafetiBase Risks report does not work and gives an error code

### Steps to replicate
- Open any model on www.3drepo.io
- Create some SafetiBase issues
- Create a Report

### Pictures/ Gifs of the error
![SafetiBase Report](https://user-images.githubusercontent.com/19904513/75900403-c71b8000-5e34-11ea-9611-6a6a34e0be9a.jpg)
![SafetiBase Report Error](https://user-images.githubusercontent.com/19904513/75900408-c8e54380-5e34-11ea-80f6-1a75b6178a60.jpg)

**Comment by keifgwinn** [comment]
error: 2020-03-04T16:35:53.576Z system  undefined (4000) [11255439 ms] place=GET /api/localtest3/4ced5200-5e1f-11ea-84ab-653a62c5d8ca/risks.html?ids=9f8cf8f0-ee84-11e8-b6a8-098757cec2ac, httpCode=500, contentLength=173
error: 2020-03-04T16:36:28.067Z system  TypeError: res.render is not a function
    at Promise.all.then (/home/node/3drepo.io/backend/models/report.js:229:8)
    at process._tickCallback (internal/process/next_tick.js:68:7) [11289930 ms]

**Comment by carmenfan** [comment]
Fixed in #1915
