### ISSUE TITLE
Dev 4.3.4 Bugs List

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1921]
### Bugs
- <del> Issue throws and error when can't select model elements </del> 
- [x] Risk pins not appearing when switching models

**Comment by BDavydov** [comment]
### Description
I import a BCF File from a different federation of the same models. When I click on the issue an error message comes up if the issue contains a selection of model elements
### Steps to replicate
- Open any model in 3D Repo
- Create Issues and export them as a BCF File
- Upload the same model under a different
- Upload BCF File to the new model
- Click on any issues that have elements selection

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/76080006-e124a200-5f9d-11ea-9eb2-fabec62d9748.png)
![image](https://user-images.githubusercontent.com/19904513/76080061-00bbca80-5f9e-11ea-8d83-f3e97482e6db.png)

**Comment by carmenfan** [comment]
**Risk pins not appearing when switching models**

- go into a model, hide pins in risk
- leave the model, go into the same/another model
- showPins is checked, but pins are not visible.


NB: this is probably also happening on issue pins...
