### ISSUE TITLE
Attach resource gives white screen

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1935]
### Description
I first create an issue and then attach a resource without quitting the issue. When I hit the save button it gives me a white screen.

### Steps to replicate
- Open any model/federation
- Create a new issue and save it (don't close or quit it)
- In the same issue click 'attach resource'
- Select your file and click the Save button
- A white screen will appear

### Pictures/ Gifs of the error
![Attach Resource White Screen](https://user-images.githubusercontent.com/19904513/76758755-46d51300-6782-11ea-9da8-373f97111b0e.gif)

**Comment by sanmont3drepo** [comment]
Do you know if that particular account has enough quota?

**Comment by BDavydov** [comment]
Yeah, It's my account and the model has some issues with resources attached. Anything new comes up with a white screen
