### ISSUE TITLE
Navisworks Plugin - Log in issues

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1943]
- [ ] [Log in using your email address]
- [ ] [Forgot Password button takes you to the wrong webpage]

**Comment by carmenfan** [comment]
@BDavydov this needs to go to https://github.com/3drepo/3drepoPlugin/issues

**Comment by BDavydov** [comment]
@carmenfan Okay. Even though it is a Navisworks plugin related issue?

**Comment by carmenfan** [comment]
@BDavydov specifically because it's a navis plugin issue... :stuck_out_tongue: 

The code base for the plugin is in the aforementioned repository, can't fix the problems in here

**Comment by BDavydov** [comment]
@carmenfan I see. My bad. Thank you

**Comment by carmenfan** [comment]
@BDavydov what i mean of course is open a new issue, don't add it in the excel issues branch!
