### ISSUE TITLE
removeOrphanFiles.py needs to respect ignoreDirs when comparing existing refs

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#1949]
### Description

When running removeOrphanFiles.py on a populated system, it inaccurately reports that it wants to export the toy models to the filesystem as they are missing, as it ignored the toy model directory when creating its index of filenames. If you then set the ignoreDirs to blank, it correctly identifies the missing files, but also assumes the toy folders are additional and need removing on a wet run.

### Goals

- [ ] Add logic to line 61 to ignore ref's that have part of the ignoreDirs path

**Comment by keifgwinn** [comment]
additionally, doing path validation on the incoming localFolder variable would be handy, to ensure trailing slash for correct path creation

**Comment by carmenfan** [comment]
@keifgwinn  do you want to look into this one? since it's all python it shouldn't be too bad XD
