### ISSUE TITLE
Instant Clash loads additional (unselected model)

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#1958]
### Description
I select MEP as my Base Model and Structure as my Target. When Instant Clash is active, the furniture model remains visible even though it is not active in the list of models selected to perform clash detection.

### Steps to replicate
- Open 3drepo.io
- Open the [Federation](www.3drepo.io/viewer/Bogdan_D/4c512810-74d3-11ea-b2b0-37b8e53df327)
- Open the Compare Card
- Select the MEP Model as your Base model
- Select the Structural Model as your target
- Activate Instant Clash

### Pictures/ Gifs of the error
![Instant Clash](https://user-images.githubusercontent.com/19904513/78250554-e9fa8c00-74e7-11ea-8075-521402cd8c6f.gif)

**Comment by carmenfan** [comment]
according to @sanmont3drepo  this is not reproducible in latest of staging. Closing. Reopen with a new model if problem persist! 👍
