### ISSUE TITLE
Browser version check

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#1970]
We've been getting some users trying to access 3D Repo with very old safari versions which ends up with errors due to the lack of ES6 support. We should test the version of browser they are using and throw an error telling them to upgrade.

We don't know for sure which version we can't support, but we know we need webGL2 and ES6 support for the browser to have a chance to work.

ES 6 support:
![image](https://user-images.githubusercontent.com/11945337/78893753-c3969c80-7a63-11ea-8d84-40e6ad9fbcce.png)

WebGL2 support:
https://caniuse.com/#feat=webgl2

NOTE: If the browser does not support ES6, they're doomed, just tell them to upgrade (add to the IE check?). If the browser doesn't support Webgl2, they can access everything but the viewer, so maybe a warning should suffice.

**Comment by m1chalkubiak** [comment]
@carmenfan 
Current status of checking supported browser is that in case we detect unsupported browser version we showing user this screen:
<img width="1307" alt="Zrzut ekranu 2020-08-25 o 15 27 16" src="https://user-images.githubusercontent.com/24941866/91181712-8e74a900-e6e9-11ea-9e83-757c9a9fe9e4.png">

It can be skipped, but it will show on every refresh of the page.

If the browser doesn't support WebGL2 user that came to viewer should see additional info:
<img width="1254" alt="Zrzut ekranu 2020-08-25 o 15 39 05" src="https://user-images.githubusercontent.com/24941866/91181795-a77d5a00-e6e9-11ea-8514-35e99d203e4c.png">
And after clicking ok
<img width="1250" alt="Zrzut ekranu 2020-08-25 o 15 43 58" src="https://user-images.githubusercontent.com/24941866/91182028-ef9c7c80-e6e9-11ea-884b-a40df4ff244b.png">
At least this is what happens on Safari which doesn't support WebGL2.0 at all.

What I could do at this moment was adjusting browsers versions in detecting script to align it with ES6 support.

The supported version of Safari was set to 8 and due to the ES6 support requirement, I raised it to 10.1. I think this may have been the cause of the problem

**Comment by carmenfan** [comment]
@m1chalkubiak 

>It can be skipped, but it will show on every refresh of the page.

Can we make it unskippable? (removing the ok button?) I'm guessing this is what we show people who has a browser with no ES6 support. In which case we're pretty certain the UI will be broken for them, no point letting them do anything.


><img width="1254" alt="Zrzut ekranu 2020-08-25 o 15 39 05" src="https://user-images.githubusercontent.com/24941866/91181795-a77d5a00-e6e9-11ea-8514-35e99d203e4c.png">
>And after clicking ok
><img width="1250" alt="Zrzut ekranu 2020-08-25 o 15 43 58" src="https://user-images.githubusercontent.com/24941866/91182028-ef9c7c80-e6e9-11ea-884b-a40df4ff244b.png">
>At least this is what happens on Safari which doesn't support WebGL2.0 at all.

Is this what is happening when you launching without any code changes (i.e. this is what unity game build has coded in?) I think we want our own message as soon as the user lands on our site (e..g where we check the ES6 support), to tell people that other features would still work fine without problems, but you won't be able to see the viewer.

**Comment by m1chalkubiak** [comment]
@carmenfan 

> Can we make it unskippable? (removing the ok button?) I'm guessing this is what we show people who has a browser with no ES6 support. In which case we're pretty certain the UI will be broken for them, no point letting them do anything.

Sure, button removed.

> Is this what is happening when you launching without any code changes (i.e. this is what unity game build has coded in?) I think we want our own message as soon as the user lands on our site (e..g where we check the ES6 support), to tell people that other features would still work fine without problems, but you won't be able to see the viewer.

Yes, those messages are places inside `frontend/unity/Build/UnityLoader.js` and probably they are part of some default support check from Unity.
For sure, we can check for this support on our own, but I'm not sure how we would like to display it.

For all no ES6 browsers we would display the "blue screen" without a button.
For all browser that supports ES6 but doesn't support WebGL2.0, we would like to display very similar screen but with a button and with a different message: 
```
Your browser doesn't support WebGL 2.0. 
If You want to use it anyway, You will be able to use all the features of 3DRepo except displaying of 3D models.
```
Do I get it correctly?

**Comment by carmenfan** [comment]
> Do I get it correctly?
@m1chalkubiak 

Yes

For the webGL warning, can we just use a standard pop up (the ones we use for error messages etc) so it's not as scary. 

And can we alter the message a bit:
```
Your browser does not support WebGL 2.0 therefore the 3D Viewer will be unavailable. However, you can still other functionalities we offer.

To get the full experience, please update to the latest Chrome, Firefox or Edge.
```

In general we're supporting the new edge, so can we add edge in both messages?

**Comment by m1chalkubiak** [comment]
@carmenfan 
> For the webGL warning, can we just use a standard pop up (the ones we use for error messages etc) so it's not as scary.

Of course, we can use our standard pop up, but then when exactly we would like to show it. My assumption would be:
At the first-time user login to the app (or maybe even before login, it's Your decision) we checking if browser support WebGL 2.0 if not we show popup, after confirming we saving confirmation in cookie, just to be sure that for that browser we had show info popup, user saw it, and we don't need to show it on every page refresh, Is this seems ok for You?

> In general we're supporting the new edge, so can we add edge in both messages?

Sure, no problem

**Comment by carmenfan** [comment]
>Of course, we can use our standard pop up, but then when exactly we would like to show it. My assumption would be:
At the first-time user login to the app (or maybe even before login, it's Your decision) we checking if browser support WebGL 2.0 if not we show popup, after confirming we saving confirmation in cookie, just to be sure that for that browser we had show info popup, user saw it, and we don't need to show it on every page refresh, Is this seems ok for You?

Yes, sounds good!
