### ISSUE TITLE
Add sufficient support to test Alluxio performance

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2017]
### Description
@keifgwinn  is looking into replacing the use of fileShare/S3 with Alluxio, which will have us the flexibility of using one interface but plugging in different type of file storage solutions, with the added benefit of hot cache (as far as I understand it.

Keif has already setup an Alluxio server with the existing fileshare as the storage solution. The aim at this stage is do the minimal amount of work to connect to it to read existing model files, so we can test the reliability and the performance of this setup, also to see if there are any undiscovered caveats to this approach.

### Goals
To be able to successfully load an existing model through Alluxio API. 

### Tasks
- Add configurations needed to connect to alluxio
- Add alluxio as a new storage solution via external services 
- Add read support via alluxio (don't worry about the writes yet unless it gets in your way of making this work)

**Comment by sanmont3drepo** [comment]
The configuration options for config.js in the backend are:
alluxio: {
	hostname: string,
	port: number,
	levels: number
}

where levels serves at the same as with the fs config

**Comment by carmenfan** [comment]
This was done and merged in
