### ISSUE TITLE
Excel Issues Macro - Issues with no pin receive one when the issues is synced

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2018]
### Description
Excel Issues Macro - Issues with no pin receive one at 0,0,0 when the issues is synced
### Steps to replicate
- In 3D_Repo_Issues_Template2.xlsm
- Define Project parameters on 'User' Sheet for a project which contains issues without pins
- On 'Issues' sheet click 'PULL FROM 3D REPO'
- 'x','y' and 'z' columns are empty
- Click 'PUSH TO 3D REPO'
- Issue in 3D Repo now has a pin at 0,0,0

### Pictures/ Gifs of the error
![](https://raw.githubusercontent.com/mosment3DRepo/images/master/IssueExcel.gif)

**Comment by carmenfan** [comment]
moved to https://github.com/3drepo/3drepoPlugin/issues/30 as it's not a bug in io
