### ISSUE TITLE
Comments UI improvement

### ISSUE THREAD

**Issue by m1chalkubiak** [3drepo/3drepo.io#2026]
### Description
Improvement of comments UI in 3D Repo, allowing the user to filter comments, add references to a user or issue, quote comments, and have base support of markdown syntax.

Mockup: https://marvelapp.com/ad2hjh3/screen/68029558  

### Goals
- [x] A fresh layout for comments
- [x] Owner comments should be in a different colour to other comments.
- [x] Comment should be listed by date/time ascending, with scroll automatically scrolled to bottom by default
- [x] Add filter comments/system message/all to filter the comments
- [x] Avatar image of each user with outline colour matching its job colour
- [x] Show user card on hover
- [x] User reference should be in a emphasis colour and it should show user card on hover
- [x] Issue reference  should look like a hyperlink and show issue info on hover, go to issue if clicked (the back button on the issue card should then go back to issues list as normal, not back like a browser!)
- [x] Resource reference should look like a hyperlink, no need for tooltip and just act as if the user clicked on the resource on the resource list.
- [x] Add quote button to reference: when clicked, add reference link to comment (markdown - #res.<resourceID>)
- [x] Add quote button to comment: when clicked, add quote to comment (markdown)
- [x] Add reply button: when clicked, add reference to user (@username)
- [x] render markdown appropriately for comments
- [x] if user enters @xx... list of filtered users (users within teamspace) that matches the username should come up
- [x] if user enters #<num>... list of possible issues should come up
- [x] viewer quote/reply should be disabled if the user has no write access
- [x] comments should be sent as markdown and only be rendered visually on the fly
- [x] if the quoted text has an image, add domain name placeholder that is replaced on the fly depending on configuration
- [x] do not render references within quotes, it should be plain text + images only.

**Comment by m1chalkubiak** [comment]
Hi @carmenfan 
I'm at the end of finishing this feature and soon I will be able to send you a ready-to-test version (I think it needs about 1 more day's work). However, I have a few last points left, which causes some problems and I would like to ask you for help.

Creating hovers for user references, I found that the main endpoint that we've used to get detailed user information so far was:
`/api/{teamspace}/members/{user}`

The problem, however, is that it returns relatively little data.
<img width="528" alt="Zrzut ekranu 2020-05-7 o 11 49 48" src="https://user-images.githubusercontent.com/24941866/81280549-ef07a980-9058-11ea-9742-eaeee316d88c.png">

I discovered, however, that there is another endpoint:
`/api/{teamspace}/members`

Which, in turn, returns a list of all users in a given teamspace, with much more information about them.
<img width="491" alt="Zrzut ekranu 2020-05-7 o 11 51 23" src="https://user-images.githubusercontent.com/24941866/81280677-1eb6b180-9059-11ea-9bd9-d1064a9f8f4e.png">

But, because for endpoint 
`/api/{teamspace}/members/{user}`
there is already written logic including storing these queries, I would like to be able to use it because it would simplify implementation.

So I would like to ask if you would be able to modify this endpoint to returns the data that are needed to display new hovers?
It would be ideal if it also returns the job color of a specific user as well, but I am currently taking it from redux state and it isn't a big problem for me.

**Comment by carmenfan** [comment]
> So I would like to ask if you would be able to modify this endpoint to returns the data that are needed to display new hovers?

Yep, I'll look into it. So is that just the job and job colour needed?

**Comment by m1chalkubiak** [comment]
> Yep, I'll look into it. So is that just the job and job colour needed?

Yes @carmenfan , just those two fields are additionally needed to be able to use only this one endpoint for the user reference hover feature.

**Comment by carmenfan** [comment]
@m1chalkubiak  I can't find this branch, can you push your changes?

**Comment by m1chalkubiak** [comment]
> @m1chalkubiak I can't find this branch, can you push your changes?

@carmenfan Oh, Yes I had working on this on a temporary branch, as I did not have issue number. I will create proper branch and start cherry-pick my commits.

**Comment by carmenfan** [comment]
@m1chalkubiak done:
![image](https://user-images.githubusercontent.com/11945337/81290846-a81db200-9060-11ea-9e07-b19eef73ad57.png)

**Comment by m1chalkubiak** [comment]
Hi @carmenfan
I'm sorry but I still fighting with autosuggestions, I underestimated this part of the feature. We did have a very similar feature in a User management page in process of adding / inviting new users And it seemed to me that we would be able to use the same solution, but it does not work properly with textarea elements, this library also does not allow to personalize these hints to look like the ones on the mockups (I think we are taking pattern on those suggestion from github). Currently, I'm trying to implement and customize another library for this form. It seems promising but it still requires some work. 

It seems to me that tomorrow by noon I should have a finalized scope of work that we have established on this feature and I should be able to provide you a version ready for testing.

One more time I apologize for the delay.

**Comment by m1chalkubiak** [comment]
@carmenfan 
>  - [x] do not render references within quotes, it should be plain text + images only.

This point has not been completed 100% as described, so I prefer to write about it honestly. For proper handling of markdown syntax in the comments, I used an external library, which we have already used in our company before in several other projects. This reduced a large part of the work related to the implementation of the entire text parsing mechanism but also imposed some restrictions. 

By default in markdown, all links in the quoted fragments remain links, so in order to change this behavior I would have to start changing library implementations, or at least I think so because I haven't found a good way to do that. What I managed to do in a reasonable time was to style the links inside the quotes in such a way that they look like normal text and are not clickable.

Hope this solution is fine for You.

**Comment by carmenfan** [comment]
> @carmenfan
> 
> > * [x]  do not render references within quotes, it should be plain text + images only.
> 
> This point has not been completed 100% as described, so I prefer to write about it honestly. For proper handling of markdown syntax in the comments, I used an external library, which we have already used in our company before in several other projects. This reduced a large part of the work related to the implementation of the entire text parsing mechanism but also imposed some restrictions.
> 
> By default in markdown, all links in the quoted fragments remain links, so in order to change this behavior I would have to start changing library implementations, or at least I think so because I haven't found a good way to do that. What I managed to do in a reasonable time was to style the links inside the quotes in such a way that they look like normal text and are not clickable.
> 
> Hope this solution is fine for You.

Hard to visualise from the description... but makes sense.

I'll have a look when you created a PR and see :)
