### ISSUE TITLE
'Create a Model' API call not working with API key

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2041]
### Description
Creating a model container appears to be incompatible with API Key

### Steps to replicate
Make a POST request to api/{teamspace}?key={API key}

With an example Payload:

> {
   project: "classic project",
   modelName: "awesomeModel",
   unit: "ft",
   desc: "This is an awesome model!",
   code: "awe12",
   type: "Mechanical"
}

The response is:

> {
    "message": "Password is missing",
    "status": 400,
    "code": "SIGN_UP_PASSWORD_MISSING",
    "value": 62,
    "place": "POST /api/mosment3d?key={API key}"
}

### Pictures/ Gifs of the error
![](https://raw.githubusercontent.com/mosment3DRepo/images/master/API%20call.png)

**Comment by sanmont3drepo** [comment]
The url is incorrect. The documentation was incorrect also because it noted that /:model instead of /model as part of the url.
