### ISSUE TITLE
Implement/Refactor sign up, forgot password and verification APIs

### ISSUE THREAD

**Issue by thenrikie** [3drepo/3drepo.io#208]

**Comment by thenrikie** [comment]
New actions needed by nodeUserRole for sign up API


**createUser**
**grantRole**
for admin db


**update** for collection admin.system.users 
in order to make the most of mongoose library and to allow $set operator on customData field. Since giving **createUser** and **grantRole** actions are now necessary for sign up API and using them can create a user with different roles and therefore giving **update** action for nodeUserRole would not make it less secure.

**Comment by jozefdobos** [comment]
Before proceeding, this needs to be properly triaged as there are significant security implications. The plan was to offload all such funtionality to bouncer as far as i remember.

**Comment by timscully1983** [comment]
- [ ] Create BouncerJS service

**Comment by thenrikie** [comment]
## User.authenticate
Description: To Login

Request JSON body to send to BouncerJS
```
{
	"username": <username>,
	"password": <password>
}
```

Expected return 
```
{
	"status": "success|error"
	"errorCode": "2" (if status is error), <- as in response_code.js
	"message": "extra info"
}
```



## User.createUser
Description: Sign up

Request JSON body to send to BouncerJS
```
{
	"username": <username>,
	"password": <password>,
	"email": <email>
}
```


Expected return 

```
{
	"status": "success|error"
	"errorCode": "55"(if status is error),
	"message": "extra info",
	"data": {
		"token": <token> <- token to be used in a verification URL in a welcome email
	}
}
```



## User.getForgotPasswordToken
Description: get a forgot password token to be sent to an email

Request JSON body to send to BouncerJS
```
{
	"username": <username>,
	"email": <email>
}

```
Expected return 

```
{
	"status": "success|error"
	"errorCode": "57" (if status is error),
	"message": "extra info",
	"data": {
		"token": <token> <- token to be used in a reset password URL in a reset password email
	}
}
```


## User.updatePassword
Description: reset password, either given old password or reset password token

Request JSON body to send to BouncerJS
```
{
	"oldPassword": <oldPassword>,     < either one
	"token": <token>,                 < either one
	"newPassword": <newPassword>
}
```

Expected return 

```
{
	"status": "success|error"
	"errorCode": "18|58|59" (if status is error),
	"message": "extra info",
}
```


## User.verify
Description: verify an email address is valid by giving token returned from sign up

Request JSON body to send to BouncerJS
```
{
	"token": <token>
}
```

Expected return 

```
{
	"status": "success|error"
	"errorCode": "58" (if status is error),
	"message": "extra info",
}
```

new error code
```
{
		57: "Username or email address doesn't match/ exist",
		58: "Token is invalid or expired",
		59: "old password is incorrect"
}
```

**Comment by thenrikie** [comment]
communication between api server and BouncerJS

API Server
```
socket.emit('User.authenticate', <request json body>);
socket.on('User.authenticate', function (<return json body>) {
    // message return from BouncerJS
});
```

**Comment by carmenfan** [comment]
Adding new error codes that will be returned by bouncer. (for future reference error codes can be found [here](https://github.com/3drepo/3drepobouncer/blob/master/client/src/error_codes.h))

AFAIK the API server doesn't really do anything with the error right now, so all I've done is add it to the switch case statement(and also created more response codes). @thenrikie  please clean up my mess if necessary :)
