### ISSUE TITLE
Ref (and occasionally comments) are being exposed in the list all issues endpoint

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2102]
### Description

The issue Template used to pull in a comma separated list of resources against each issue. This fields no longer exists in the JSON object at 
`/:teamspace/:model/revision/:rid/issues`

Code from Excel Template:

            If Not IsEmpty(issue("resources")) Then
                For Each resourceData In issue("resources")
                    If Not IsEmpty(resourceData("link")) Then
                        ActiveWorkbook.Sheets("Issues").Cells(issueRow, 13).Value = _
                            ActiveWorkbook.Sheets("Issues").Cells(issueRow, 13).Value & _
                            "," & resourceData("link")
                    End If
                Next resourceData
            End If

**Comment by carmenfan** [comment]
It's currently being sent out in raw form as a form of `ref`
![image](https://user-images.githubusercontent.com/11945337/87050347-0ba99480-c1f6-11ea-9402-9f138d475c8a.png)

Also interestingly, it seems like we're not completely committing the comments for some reason

Imo resources should be like comments and only be exposed in issueDetails, list all is suppose to only give brief info about the issue.

So we should leave ref out on the `projection` in the query

Tagging this as maintenance.

**Comment by carmenfan** [comment]
this is addressed in #2093
