### ISSUE TITLE
Issues/Risks opened from Kanban Board do not apply Section Cut (camera position only)

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2122]
### Description
You can open a model viewer directly from the Kanban board or simply by clicking on the URL link shared with you. Camera view changes, however, Section Plane/Box is not applied.

### Steps to replicate
- Log in to 3drepo.io
- Open any model
- Create an Issue/Risk with a section plane
- Go back to your teamspace
- In Kanban board, open the Issue/Risk you have just created
- Click on the _View on Model_ icon

### Pictures/ Gifs of the error
![Section Cut](https://user-images.githubusercontent.com/19904513/88924635-72f1bc00-d26b-11ea-9eb1-9f05df957d9b.gif)

**Comment by carmenfan** [comment]
This is fixed in #2093
