### ISSUE TITLE
Some federations do not load fully

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2157]
### Description
Some federations do not load fully

### Steps to replicate
- Load any of the following:
 - https://dev.3drepo.io/viewer/Bogdan_D/03c4a630-a4d5-11ea-90bd-db80072a6c88
 - https://dev.3drepo.io/viewer/Bogdan_D/7582583e-52d5-4d76-a693-f4b8bb9da0e9
 - https://dev.3drepo.io/viewer/charence/3bd6c11a-41b6-4606-a271-5beeaa5c7235

### Pictures/ Gifs of the error
<img width="1674" alt="Screenshot 2020-08-24 at 10 01 35" src="https://user-images.githubusercontent.com/1438332/91039138-e3d68a80-e603-11ea-9ef4-1f22e519ed57.png">

### Notes
- Bug first appears in 51148bad1a79d96b399c9b8030099f97159fe919

**Comment by carmenfan** [comment]
closing this in favour of #2159
