### ISSUE TITLE
Invalid Email Address Warning does not work

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#2165]
### Description
Invalid Email Address Warning does not work. 

### Steps to replicate
- Entered a wrong gmail address: miadibeh@g**g**mail.com
- Invalid email warning should pop up, instead, Message 'Thank you for signing up with 3D Repo. An email has been sent to verify your request. You must click on the link to complete the sign up process. If you have not received this, please check your spam folder or ask your email administrator for assistance.'

### Pictures/ Gifs of the error
![invalidemail](https://user-images.githubusercontent.com/56918163/91440537-a9205c80-e866-11ea-850f-f0606d43f41e.JPG)

**Comment by carmenfan** [comment]
@3drepo/product-team 

We can only really check if the mail address is of a valid format, we can't really detect typo.

This is why we ask the user to type it twice.

We can potentailly check if someone typed the popular email domains right (gmail, microsoft, hotmail etc) but that would be a feature request.
