### ISSUE TITLE
Version number is incorrect

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#2166]
### Description
Version number is incorrect even after Refreshing the page. Shows 4.8.3 instead of 4.9.2

### Pictures/ Gifs of the error
![version](https://user-images.githubusercontent.com/56918163/91441239-c275d880-e867-11ea-93dd-cbd430f33726.JPG)

**Comment by carmenfan** [comment]
@miadibe  I'm struggling to reproduce this. Can you produce steps to reproduce?

**Comment by miadibe** [comment]
@carmenfan I am reviewing the Release QA chart. In the Sign Up (form) category.
1- Go to [](https://www.3drepo.io/sign-up) and [](https://www.3drepo.io/login)
2- In both pages, the windows shows Version: 4.8.3 instead of 4.9.2. Thus, the incorrect version number. I Refreshed the page but did not get a pop up window to Reload 3D Repo to the latest version. I am guessing the Version number should be corrected?

**Comment by carmenfan** [comment]
are you sure you're on the right website? the production server should be 4.8.3 and that's correct. dev never hosted 4.8.3 so it's virtually impossible for it to show you this number.

**Comment by miadibe** [comment]
https://www.3drepo.io/login and https://www.3drepo.io/sign-up
Okay my bad, I thought it should be 4.9.2, then you can click on it and it takes you to the Release Notes page.

**Comment by carmenfan** [comment]
If you're doing QA testing it should be https://dev.3drepo.io 😄 

Not a lot of point to QA test production as it's already out! 😆
