### ISSUE TITLE
Add a link to login on forgot password page

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2167]
see https://github.com/3drepo/3drepo.io/issues/2159#issuecomment-681975366

It would be nice if `login` is clickable to lead the user back to the login page.

**Comment by MajaZubko** [comment]
@carmenfan The text shown after password reset is a response from backend, thus creating a clickable `login` would be problematic. We suggest adding a Back to login button under the text. Is it acceptable?

**Comment by carmenfan** [comment]
@MajaZubko  yes that's fine
