### ISSUE TITLE
Mouse cursor should show the multi select curor on tree/group UI when in multi-select mode

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2173]
### Description
When the user is in multi-select mode, the mouse cursor should change when hovering on tree/groups as they are effected by the multi select behaviour.

This will reduce the chance of user getting a sticky ctrl press without realising, as described here: https://github.com/3drepo/3drepo.io/issues/2159#issuecomment-685505530

### Steps to replicate
- hold on to `ctrl` when you're on the viewer, it shows the cursor with a + icon.
- move over to the tree/groups tab, it shows the standard select icon.

Just like when hovering on the viewer, it should show the + cursor icon when we're on multi select (addictive) mode, and - cursor on multi select (reduction) mode.

**Comment by MajaZubko** [comment]
@carmenfan Can you please give more detail about this bug? 
Do you mean that the cursor is not changing from pointer to an arrow with + when holding the ctrl key?
Or is the problem in the cursor not changing from arrow with + to an arrow with - after selecting an item?

On branch staging selecting or multi selecting items when user is in model view is not working properly, so we are not able to recreate this bug.

**Comment by carmenfan** [comment]
@MajaZubko  sorry yes we're aware of that, In the process of sorting this out.

Will let you know when it's working again

**Comment by carmenfan** [comment]
@MajaZubko staging should now be fixed. Selection should be working again.

>@carmenfan Can you please give more detail about this bug?
Do you mean that the cursor is not changing from pointer to an arrow with + when holding the ctrl key?
Or is the problem in the cursor not changing from arrow with + to an arrow with - after selecting an item?

The cursor should change to arrow with + when hover on top of the tree and group UI. It looks like it's already doing it on groups UI but not tree UI.
