### ISSUE TITLE
Quoting a comment with an image prevents me from being able to write my comment

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2185]
### Description
I am looking at Issue comments in 3D Repo. When I see a comment that I want to quote and add my notes to it, but I hit the comment character limit, because it includes the Image's URL link.

#### Tasks: _(Edit by CF)_
- [x] Add a character count on comments so the users are aware of the limit and how far they are from it.
- [x] Abbreviate references to screenshots of another comment (regex to detect the url and abbreviate it to something like `screenshot-<commentID>` )?

### Steps to replicate
- Create any issue in 3D Repo
- Add a comment with a model screenshot
- Quote the comment with a model screenshot
- Try and your message to the comment

### Pictures/ Gifs of the error
![Comment Quote](https://user-images.githubusercontent.com/19904513/93093278-6a790780-f698-11ea-9e63-5b72463ae115.gif)

**Comment by BDavydov** [comment]
The quote text should also be a light grey colour, it's not very intuitive. At first I couldn't figure out what and where I am writing

**Comment by carmenfan** [comment]
> When I see a comment that I want to quote and add my notes to it, but I hit the comment character limit, because it includes the Image's URL link.

I think the user will also have a chance of hitting the character limit by quoting some other user's text. We probably shouldn't just ignore the quoted text in word count as that can lead to abuse or unexpectedly large message sizes.

The question is what do we want to do? increase the character limit? @3drepo/product-team

**Comment by mosment3DRepo** [comment]
@carmenfan do you know what the original reasoning behind the character limit was?

**Comment by carmenfan** [comment]
> @carmenfan do you know what the original reasoning behind the character limit was?

The exact limit is probably just a finger in the air number. But we do store the entire issue (barring resources and screenshots) within a single document, which has a maximum size of 16MB. So unlimited message size will get us closer to hitting that faster

**Comment by mosment3DRepo** [comment]
What happens if we exceed 16MB per document? It seems the solution would be to add a counter to the message limit (similar to the 3D Send mockup) that people can understand the limitation

**Comment by carmenfan** [comment]
> What happens if we exceed 16MB per document? It seems the solution would be to add a counter to the message limit (similar to the 3D Send mockup) that people can understand the limitation

@mosment3DRepo  It'll probably throw an unexpected error.

16MB can store about 16Million characters so with a sensible size limit on comments it would need to be a very very long issue to hit that limit.

We can add a character count on the UI, we could also look into reducing the reference string for images that are screenshots from previous replies. Do we want to keep the size limit as is?

**Comment by mosment3DRepo** [comment]
I think we can keep the character count as is. If we make it visible we'll be able to get feedback from anyone that doesn't think it's long enough. It might also encourage brevity. (which we could sell as a feature)

Having the limit there might also encourage people to remove some of the quote characters and add a "..."

**Comment by MajaZubko** [comment]
@carmenfan Is the reduced reference string meant to be functional and still lead to displaying the screenshot?
If not, is this form okay? It is using the name of the author and publish date of the comment.

<img width="412" alt="Screenshot 2020-09-30 at 11 27 51" src="https://user-images.githubusercontent.com/66833364/94670348-bd96bf80-0312-11eb-8c09-2d67a46403e2.png">

**Comment by carmenfan** [comment]
@MajaZubko 
>  Is the reduced reference string meant to be functional and still lead to displaying the screenshot?

That's part of the issue to code it in. Similar to resource linkage, we just have to code it in to be recognised.

> If not, is this form okay? It is using the name of the author and publish date of the comment.

No, we'd like to see the quoted picture. Essentially the screenshot url is too long, if we can reduce with using keywords that would be good. for e..g `#SS-<viewpoint-id>` ? @m1chalkubiak  you did the resource link, is this something we can achieve?
