### ISSUE TITLE
Screenshot Update is registered in the PDF Report

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2188]
### Description
PDFs contain the JSON info about the screenshot update . See https://github.com/3drepo/3drepo.io/issues/2188#issuecomment-879873619 for concluded tasks

### Steps to replicate
- Create an Issue
- Update the viewpoint
- Create a PDF report of the Issue

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/93209845-965ac280-f756-11ea-81f4-593b95e0a2db.png)

**Comment by carmenfan** [comment]
@3drepo/product-team do you want this to be shortened like the issues?

The PDF report is suppose to give you more details. so it depends to what extent.

**Comment by mosment3DRepo** [comment]
If there is a screenshot attached ideally it should just load that

**Comment by carmenfan** [comment]
@mosment3DRepo  I think @BDavydov meant the log and mostly to do with how viewpoint json is showing you the change from and to so it's massive

**Comment by BDavydov** [comment]
@carmenfan Have we been able to rectify this issue? I am still getting it in my PDF Reports
Resources ie. attachments that are URL links seem to come through like that also.
I happened to notice that long descriptions go outside the border as well
![image](https://user-images.githubusercontent.com/19904513/105055418-f3e77e80-5a6a-11eb-8288-117f378cf448.png)

**Comment by carmenfan** [comment]
@BDavydov 

We haven't looked at this. As with many layout problems, they tend to be put at the bottom of the barrel unless you guys tells us it's urgent to fix.

**Comment by BDavydov** [comment]
@carmenfan Okay, thank you for the update. I'll double-check how urgent this as there is a number of updates required for the PDF export feature.

**Comment by BDavydov** [comment]
@mosment3DRepo Any update on this? We were just providing some support and it came up for our customer's project report.

**Comment by carmenfan** [comment]
@3drepo/product-team  Unless you guys want it any other way, this is what we're going to do:

- Like the front end, viewpoint change will simply say "Viewpoint changed by x" (or however we display it on the front end, same with screenshots.
- We'll tweak the css to make overflow text wrapped where possible


If there's anything else needs doing or it needs to be done any other way, reply here.

**Comment by carmenfan** [comment]
@ChristosTsiotsias Whilst this looks like front end, this is actually done in the backend. When the user wants to see a report, they make a http request , which returns a HTML, generated with a [PUG template ](https://pugjs.org/api/getting-started.html) 

The file you're interested in is this `backend/models/report.js`. This class gathers all the necessary data then this [line ](https://github.com/3drepo/3drepo.io/blob/master/backend/models/report.js#L234) renders the report
