### ISSUE TITLE
Cannot read property 'meshesToUpdate' of undefined

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2192]
### Description
Loading model occassionally errors at the "Loading Tree" stage with the following error:

`Cannot read property 'meshesToUpdate' of undefined`

Seems to happen inconsistently when opening particular models, Skanska report it happening more regularly to certain individuals

It may be due to a poor internet connection as I only experienced it after I was having ISP issues (may be a coincidence)

### Steps to replicate
- Open model [AEC Control Model works](https://www.3drepo.io/viewer/AEC_Control/c4ea7ac0-f7f9-11ea-bc0e-bde6b59d19c0)
- Occasionally issue will appear before Tree has loaded
- Sometimes triggered when loading directly into an issue 

### Pictures/ Gifs of the error
![](https://github.com/mosment3DRepo/images/blob/master/meshesToUpdate.png?raw=true)

**Comment by BDavydov** [comment]
Got the same error message in [this issue](https://www.3drepo.io/viewer/Demo_3D_Repo/19ce3220-6e89-11ea-9f08-1387f50c0299?issueId=e6a287b0-6ea2-11ea-9043-f5b42de4172c)
![image](https://user-images.githubusercontent.com/19904513/93319590-f5c4db00-f807-11ea-9b51-385b6b1f7662.png)

**Comment by carmenfan** [comment]
This typically happens if you enter a model with highlighted/hidden objects, correct?

i.e. your default view has it, or your entering the model with issues/risks in your url?

**Comment by mosment3DRepo** [comment]
@carmenfan anecdotally yes, but I can't seem to force it by loading into an issue with highlighted objects

**Comment by mosment3DRepo** [comment]
note based of discussion with @keifgwinn I have also replicated the error in dev.3drepo.io

![https://github.com/mosment3DRepo/images/blob/master/meshesToUpdateDev.png?raw=true](url)

**Comment by BDavydov** [comment]
@carmenfan I also get this message when I open issues with no model element selection, but a clip plane instead!
![image](https://user-images.githubusercontent.com/19904513/93326437-b18a0880-f810-11ea-85b1-57911cd4154b.png)

**Comment by mosment3DRepo** [comment]
@3drepo/dev  did we find the cause of this error? Would be good to see if we can mitigate it for Skanska if it's a configuration issue
