### ISSUE TITLE
When I open an Issue URL Link, it does not load a clip plane

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2193]
### Description
Using Kanban board, I click on 'view on model' which opens a new tab and starts loading the issue. Unfortunately, it does not apply the clip plane. When you navigate to this issue from a list of issue & viewer open, it works.

### Steps to replicate
- Open [This Issue's URL Link](https://www.3drepo.io/viewer/Demo_3D_Repo/19ce3220-6e89-11ea-9f08-1387f50c0299?issueId=eb0a4470-6eeb-11ea-be7a-cf2ec7a6205f)
- Notice how the clip plane is not there
- Go back to the issues list in the card and open the same issue again

### Pictures/ Gifs of the error
![Issue URL Link Section Cut](https://user-images.githubusercontent.com/19904513/93325427-3d9b3080-f80f-11ea-81b0-3c0c031dedfa.gif)

**Comment by carmenfan** [comment]
@sanmont3drepo  I thought this was supposed to be fixed with the viewpoint refactoring?

**Comment by sanmont3drepo** [comment]
> @sanmont3drepo I thought this was supposed to be fixed with the viewpoint refactoring?

Yes actually. Can we have this uploaded to dev so I can debug it?
