### ISSUE TITLE
Display formatting and mark down support in descriptions

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2196]
### Description
Formatting seems to be preserved but not displayed in issues description

![1](https://user-images.githubusercontent.com/11945337/93488234-06f01380-f8fe-11ea-8597-91724dfbf607.gif)

I can see my new lines when I edit but it becomes a wall of text when i'm out of edit mode.

It would also be good if it's rendered with markdown like the comments, so things like bullet points would render nicely

I only tested this on issues, but it should apply for both risks and groups

### Goals
- [ ] Display intended formatting even when the user is out of edit mode
- [ ] Support markdown

**Comment by MajaZubko** [comment]
@carmenfan Do you wish only for adding markdown support or is adding the ability to tag @ someone or # an issue also desired in this enhancement?

**Comment by carmenfan** [comment]
@MajaZubko that would be ideal yes.

**Comment by MajaZubko** [comment]
@carmenfan After digging into the subject we found that implementing tagging people and issues in the description is a complicated problem and would be very time consuming. 
If that is something that you would like to have implemented, we suggest opening a new issue for it.

I created a pull request that achieves the main goals of this issue.
