### ISSUE TITLE
Issue or SafetiBase Screenshot disappears if you update the viewpoint without updating the screenshot

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2237]
### Description
When I open an existing Issue or SafetiBase risk, I can update its current viewpoint. If I do so, I have an option to update the screenshot. If I press no, then I only update the viewpoint. Next time open the same Issue or Risk, it shows the new viewpoint camera position, however, the screenshot is gone! ☹

### Steps to replicate
- Open the model viewer
- Create an Issue/Risk
- Come out of the new Issue/Risk
- Open the new Issue/Risk and see the screenshot in the card
- Update the viewpoint (without updating the screenshot)
- Go back to the Teamspace
- Open the same model again
- Open the Issue/Risk you have created and update the viewpoint 
- Notice how the screenshot is missing in the card now
- Bye Bye my beautiful markup it's been a pleasure ( ಥ_ʖಥ )
### Pictures/ Gifs of the error
**Update the Viewpoint**

![Update Risk Viewpoint](https://user-images.githubusercontent.com/19904513/95100446-ff67a180-0728-11eb-8786-b1e6e6a442ab.gif)

**Open the Risk/Issue again**
![Updated Risk](https://user-images.githubusercontent.com/19904513/95100786-5a999400-0729-11eb-9e4d-54a612e1a20d.gif)

**Comment by sanmont3drepo** [comment]
### Description
When I open an existing Issue or SafetiBase risk, if I update the screenshot it goes blank

### Steps to replicate
- Open the model viewer
- Open an issue.
- Edit image
- Create screenshot -> save
- Save viewpoint -> no or yes is the same
- The screenshot is broken

![brokenscreenshot](https://user-images.githubusercontent.com/42032433/99557267-67610700-29ba-11eb-813d-3a11f7d71dee.gif)
