### ISSUE TITLE
Bug: Clicking a screenshot in Issue Comments fails

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2248]
### Description
Clicking a screen shot from an issues comment does not successfully navigate to the view

### Steps to replicate
- Create Screenshot comment in issues
- Move viewpoint to different position
- Click on issue screenshot in comments
- Image pop-up show, but model underneath jitters a little and pins appear to move slightly
- Once the image pop up is closed and the 3D View interacted with the model view updates, and it appears to have crept slightly, but has not moved to the correct position

### Pictures/ Gifs of the error
![](https://github.com/mosment3DRepo/images/blob/master/IssueMove.gif?raw=true)

**Comment by carmenfan** [comment]
@mosment3DRepo you have to click on the comment, not the screenshot for the to go the view (i.e. try clicking on the grey bubble) This is probably something we should consider on revamp, the other annoying thing is there's also no button to go back to the original viewpoint, you have to go back out to reset it...

The pins moving is definitely some weird bug though..
