### ISSUE TITLE
SSL issue on 3drepo.io

### ISSUE THREAD

**Issue by crydalch** [3drepo/3drepo.io#225]
Was going to check out 3drepo.io, but I think the ssl certificate is expired? Or something along those lines...

Cheers!

![screenshot-area-2016-06-11-195449](https://cloud.githubusercontent.com/assets/458856/15988018/8375a46e-300e-11e6-9b7d-eb52e7a44f1d.png)

**Comment by jozefdobos** [comment]
Try https://www.3drepo.io
