### ISSUE TITLE
SafetiBase pins not correct colour

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2255]
### Description
SafetiBase pin colour doesn't align with parameters

### Steps to replicate
1. Create new SafetiBase risk
2. Add pin
3. Save
4. Change Likelihood to Low
5. Change it back to Very Low
6. Pin colour goes red when it should be green

### Pictures/ Gifs of the error
![](https://github.com/mosment3DRepo/images/blob/master/SafetiBase%20Pin.gif?raw=true)

**Comment by carmenfan** [comment]
c;losing this in favour of #2291
