### ISSUE TITLE
Allow editing of Units in Model Settings

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2270]
### Description

Allow users to edit the Units in the Model Settings page in order to correct error during upload.

<img width="590" alt="UOM" src="https://user-images.githubusercontent.com/62879582/98020889-8167ea80-1dfb-11eb-88ca-88e581ff4f93.png">

**Comment by keifgwinn** [comment]
whilst we're doing this, it would be wonderful to default the units to metric rather than imperial on the model upload

**Comment by mosment3DRepo** [comment]
API already allows the PATCH request, so just a case of unlocking the field in the front-end

**Comment by klesnyatapptension** [comment]
> whilst we're doing this, it would be wonderful to default the units to metric rather than imperial on the model upload

@keifgwinn can you specify a scenario for this please? 
When adding a new Model there is no default unit of measurement selected. When it comes to existing models, they should have the unit chosen during their creation and in the event that is not the case the default value is "Millimetres"

**Comment by keifgwinn** [comment]
We already did it in https://github.com/3drepo/3drepo.io/issues/2526
