### ISSUE TITLE
Place feedback for when a view/issue/risk/comment/group is being loaded

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2285]
### Description
When a view/issue/risk/comment/group is being loaded there is no feedback so it can be mistaken for the system not applying the view selected changes.

**Comment by AsiteZane** [comment]
This is similar to the loading ticket that was also mentioned.
Considering merging @AsiteZane

**Comment by AsiteZane** [comment]
Referenced, close.
