### ISSUE TITLE
Treatment Suggestions CSV with some empty cells can't be uploaded. Breaks the current CSV Template

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2306]
### Description
When I create a list of Risk Treatment suggestions I need to compile it as a CSV file (template provided on 3drepo.io). After uploading it works fine in 3drepo.io only if every column cell contains information. If for any reason some of the cells don't contain information, it throws an error upon updating the Treatment Suggestions in 3D Repo.

### Steps to replicate
- Download a Risk Treatment Suggestions Template
- Fill in all of the cells for every column
- Upload to 3drepo.io & see it work
- Download the recently uploaded CSV file
- Add more information, but this time leave some of the cells blank
- Reupload the CSV file as a new revision
- Notice the Error message pop-up
- Now even the previous CSV's fields aren't available for use in SafetiBase

### Pictures/ Gifs of the error

[Example CSVs.zip](https://github.com/3drepo/3drepo.io/files/5584894/Example.CSVs.zip)

![Risks CSV](https://user-images.githubusercontent.com/19904513/99998622-e1c4c900-2db6-11eb-9bfe-8b42d12517f6.gif)

**Comment by Charence** [comment]
@BDavydov @3drepo/product-team @carmenfan The error appears for the rows where the first field `Treatment Title` is not completed, which is what it's supposed to do as it is a required field. We could look into changing the template slightly to state that the first field is required or changing the error message.

I agree that the previously uploaded data shouldn't be removed though if the new file fails, so I'll look into that.

- [ ] Don't modify suggestions if new file fails

**Comment by BDavydov** [comment]
@Charence I think it makes perfect sense. If you have no suggestion, then why even have identifiable fields. If we leave it as it is, I'll just create some support content should anyone come across this issue. As long as the only reason it throws an error is the missing Treatment Title, then I think it's no longer an issue/bug? @3drepo/product-team @mosment3DRepo
