### ISSUE TITLE
Some issues/risks don't open on Kanban board

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2313]
### Description
Some issues/risks don't open on Kanban board

### Steps to replicate
- Go here: http://127.0.0.1/dashboard/board/issues/willsmith/Brick%20Cube/57f64790-0e07-11eb-a083-2b878a4dc41e
- Try to expand details on any issue/risk in this model

**Comment by BDavydov** [comment]
@Charence 
Is this a similar experience to yours? I was going to raise as a bug discovered on staging.dev.3drepo.io but since you're here I thought I'd check.
Issue cards don't open in the Kanban Board.
![Kanban Board Issues Don't open](https://user-images.githubusercontent.com/19904513/100325595-c75e3b80-2fc0-11eb-8040-f5e76095d49b.gif)

**Comment by Charence** [comment]
> @Charence
> Is this a similar experience to yours? I was going to raise as a bug discovered on staging.dev.3drepo.io but since you're here I thought I'd check.
> Issue cards don't open in the Kanban Board.
> ![Kanban Board Issues Don't open](https://user-images.githubusercontent.com/19904513/100325595-c75e3b80-2fc0-11eb-8040-f5e76095d49b.gif)

@BDavydov Yes, this is the issue.

So far, Keif and I have found that it seems to affect certain projects in teamspaces (or maybe whole teamspaces in some cases?).

It also happens here:

- https://dev.3drepo.io/dashboard/board/issues/asdf/unityAssets%20copy/aacca5df-c4bc-4704-91b6-460fe8f29446
- https://staging.dev.3drepo.io/dashboard/board/issues/Bogdan_D/Revit%20Plugin%20QA/3ff20db0-2fc6-11eb-8692-d394773a8834
- https://staging.dev.3drepo.io/dashboard/board/issues/Bogdan_D/Not%20A%20Plugin/00c7d400-2fc9-11eb-9e77-29c3ba5c5398

but not here:

- https://staging.dev.3drepo.io/dashboard/board/issues/asdf/Test/9146e1bb-52ea-42e5-8ae0-f9d3d2d0e746

**Comment by Charence** [comment]
UPDATE: Kanban problem seems to be occur only on projects with spaces in their name.

This works:

- https://staging.dev.3drepo.io/dashboard/board/issues/Bogdan_D/No_spaces_project/6113e620-2fcc-11eb-9e77-29c3ba5c5398
