### ISSUE TITLE
Add support for pre-compressed Unity files

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#2316]
Unity 2020 [removed default support](https://forum.unity.com/threads/solved-unity-2020-webgl-doesnt-work-uncaught-syntaxerror-invalid-or-unexpected-token.872581/) for the software gzip decompressor. 

As a workaround has been re-enabled temporarily in the Unity project for #2315 (321 in [3drepoforunity](https://github.com/3drepo/3drepounity/issues/321))

For best performance we should ensure the compressed flag is set in the http response header for those unity files, so they can be decompressed by the browser.

**Comment by carmenfan** [comment]
This is all N/A as unity bundles are now replaced with repo bundles, but I believe we've also implemented this in 5.8 I believe 

@sebjf let me know if i'm talking rubbish!
