### ISSUE TITLE
4.11.4 bug list

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2322]
- [x] [When the next frame of a sequence isn't preloaded the view jumps to the default configuration whilst it's loading](https://github.com/3drepo/3drepo.io/issues/2322#issuecomment-734995683)
- [x] [Issue isn't transforming meshes until you go into the issue](https://github.com/3drepo/3drepo.io/issues/2322#issuecomment-734996147)

**Comment by carmenfan** [comment]
### Description
When the next frame of a sequence isn't preloaded the view jumps to the default configuration whilst it's loading, causing some jarring playback

### Steps to replicate

### Pictures/ Gifs of the error
![Sequence Skip](https://user-images.githubusercontent.com/62879582/100474355-4eea9e00-30d8-11eb-995d-8e04956abc88.gif)

**Comment by carmenfan** [comment]
Issue isn't transforming meshes until you go into the issue

**Steps to replicate**
- Open a sequence to a frame where the object is moved
- save the state as an issue
- reset the state somehow (refresh, fast forward to the next key frame in the sequence etc)
- click on the issue, it changes the viewpoint/visibility etc, but it does not apply the transform.
