### ISSUE TITLE
Can't find a user in the database on ca.3drepo.io When I try to send the invite it says User already exists

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2323]
### Description
I have a user's e-mail address. When I copy-paste into a search field, it doesn't find any entry in the database, so I get a message '**_Send Invitation?_**' When I try to send the invitation it says **_User Already Exists_**.
I have realised that if I start typing in the email address instead of copy-pasting it works. However, there are other users in the database that this method doesn't work on, so I can't find them nor invite them 😲 

### Steps to replicate
- Login to ca.3drepo.io
- Head over to the User management Section
- Click on the Green Plus button
- Copy & Paste this email address _hani.karam@wsp.com_
- User not found message will appear
- Try sending the invite (it won't work as the user exists, apparently 🙃) 

### Pictures/ Gifs of the error
Can't find a user
![image](https://user-images.githubusercontent.com/19904513/100553753-92cfd580-3287-11eb-877d-9154041143f4.png)
Apparently, there's already a user with this email
![image](https://user-images.githubusercontent.com/19904513/100553775-b09d3a80-3287-11eb-853d-218e90cba3c1.png)

**Comment by carmenfan** [comment]
@BDavydov This email belongs to an account that was created in 2019 but never verified.

We have a script that we run on prod to remove these cases but it seems like we currently don't run them on CA.

I've ran this just now, so this user should no longer exist and you can go ahead and invite them.

Ticket on devops to make sure we run this regularly https://github.com/3drepo/DevOps/issues/93
