### ISSUE TITLE
SafetiBase Pin colour doesn't update via chat service

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2328]
Originally reported in https://github.com/3drepo/3drepoPlugin/issues/170

### Description
When I change Risk likelihood or severity it doesn't update pin colour in 3D Repo. This happens for both Risk information & Treatment Levels. Only when I refresh a page in 3drepo.io my pin colour is correct.

It's worth looking at the following issue for your information:
https://github.com/3drepo/3drepo.io/issues/2255#issue-725469326

### Steps to replicate
- open a model in staging.dev.3drepo.io
- Load the same model in Revit & open any risk using the SafetiBase Plugin
- Change the Level of Risk and the pin colour will set to red in 3drepo.io
- Change the treated level of risk and the pin colour will set to red as well
- Refresh your model in 3drepo.io and it displays the right colour now

### Pictures/ Gifs of the error
**Behaviour in 3drepo.io when I update the Level of Risk in Revit**
![Change Risk Level](https://user-images.githubusercontent.com/19904513/100742746-311c8200-33d3-11eb-8b5f-d92cd95443b7.gif)

**Behaviour in 3drepo.io when I update the mitigated level of Risk in Revit**
![Change Treatment Level](https://user-images.githubusercontent.com/19904513/100742795-442f5200-33d3-11eb-9bb7-c83d79161ce6.gif)

**Risk Icon in 3drepo.io changes colour when I refresh the model and shows it correctly**
![Model Refresh Risk Pin Colour](https://user-images.githubusercontent.com/19904513/100742835-527d6e00-33d3-11eb-8340-971e2166273a.gif)

**Comment by BDavydov** [comment]
@carmenfan @mosment3DRepo 
Hi, I had a quick run through this and discovered the following:

**1)** Issue Pin colour changes when I update the priority level.
SafetiBase Risks icons do not update in 3D Repo when I make changes in Revit
![Icons Change 1](https://user-images.githubusercontent.com/19904513/101674953-0bd1e880-3a51-11eb-9a54-ade2d1c00edd.gif)

**2)** When I refresh the web page, SafetiBase risk icon remains the same colour, even though I have updated it to Very Low in Revit.
![Icons Change 2](https://user-images.githubusercontent.com/19904513/101674958-0e344280-3a51-11eb-834e-e848f55b5dd5.gif)
