### ISSUE TITLE
A more user friendly experience of failing to access a model with insufficient permissions.

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2342]
### Description
If you've been given a link to a model you don't have permissions on, the experience is quite ugly with many pop up boxes about not being able to access the model settings, or permissions in general, ultimately resulting in an empty loaded screen.

On the first permission denied perhaps catch that and offer a neater message about needing access to that model and return to the teamspaces page. 

### Goals
- [ ] More user friendly experience of failing to access a model with insufficient permissions.

**Comment by keifgwinn** [comment]
I also found this here #2548

**Comment by carmenfan** [comment]
ah. closing this as the other one is referenced in coda
