### ISSUE TITLE
SafetiBase Void Risk filter brings up 3D Pins but not risk cards

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2344]
### Description
When I filter the list of risks based on their treatment status I get no results for Risks set to Void. It activates the 3D Pins, but nothing shows up in the SafetiBase Card.

### Steps to replicate
- Log in to 3drepo.io
- Open the [following model](https://www.3drepo.io/viewer/Demo_3D_Repo/19ce3220-6e89-11ea-9f08-1387f50c0299)
- Click on the Search/Filter Icon
- Select Treatment Status Void
- Notice how icons appear, but nothing in the card

### Pictures/ Gifs of the error
![SafetiBase Treatment Void](https://user-images.githubusercontent.com/19904513/101466409-05e8e400-3939-11eb-9f5e-48c152ea978c.gif)

**Comment by m1chalkubiak** [comment]
Hi @BDavydov 
Can I ask, what is the expected interface behavior here? 
From what I understand, status Void, just like Agreed (Fully), is equivalent to closing a Ticket, such items are by default hidden from the list of this panel, but they are available on the Kanban Board.

@carmenfan From what I can see in the code for issues and risks there is a method `showDefaultHiddenItems` but I don't see any place of using it, it was probably once available from the interface, but currently it is not possible to display tickets with hidden statuses in these panels.

I added a pin hiding fix and a small refactor to improve code DRY.

But my main question should be probably, does it make sense to allow user to pick an option in the filters that are hidden by default? And should they be visible in this particular case?

Also, I can see that risks with Rejected status aren't hidden at all, is this an oversight?

**Comment by carmenfan** [comment]
> Hi @BDavydov
> Can I ask, what is the expected interface behavior here?
> From what I understand, status Void, just like Agreed (Fully), is equivalent to closing a Ticket, such items are by default hidden from the list of this panel, but they are available on the Kanban Board.
> 

They should be shown if the chip filter explicity says it should be shown, a bit like searching for closed issues in issues: 
![image](https://user-images.githubusercontent.com/11945337/104738244-2cbae700-573d-11eb-83e4-a49d8ba4b00c.png)

This also applies to `Agreed (Fully)`

> @carmenfan From what I can see in the code for issues and risks there is a method `showDefaultHiddenItems` but I don't see any place of using it, it was probably once available from the interface, but currently it is not possible to display tickets with hidden statuses in these panels.
> 
> I added a pin hiding fix and a small refactor to improve code DRY.

Probably obvious from the previous answer, but just to be clear, pin should be shown along with the issues in the card.

> But my main question should be probably, does it make sense to allow user to pick an option in the filters that are hidden by default? And should they be visible in this particular case?

Yes, we used to have a "Show closed issues/risk" option to do this, but was deprecated due to chip filters
 
> Also, I can see that risks with Rejected status aren't hidden at all, is this an oversight?

No it doesn't mean the risk is rejected, it means the treatment suggestion is rejected and the owner needs to come up with a better treatment plan.
