### ISSUE TITLE
Consider renaming fronted text for .BIM file format

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2395]
### Description

Consider renaming fronted text for .BIM file format as it currently displays NAVIS. The format is also now supported by the REVIT plug-in so it can be confusing for these users.

### Related Resources
![Screenshot from 2021-01-13 12-38-25](https://user-images.githubusercontent.com/1438332/104454247-7d93d980-559d-11eb-8e56-73dde6e4a78a.png)

**Comment by carmenfan** [comment]
this is a duplicate of #2374
