### ISSUE TITLE
Documentation for the clipping plane object

### ISSUE THREAD

**Issue by har00n-haider** [3drepo/3drepo.io#2405]
Minor point but would be good to state how the properties of the clippingPlane object map to the equation of a plane:
```
// ax + by + cz + d = 0
const planeEq = {
  a : plane[0],
  b : plane[1],
  c : plane[2],
  d : plane.distance
};
```
Also documentation states:

>The distance for the clipping plane to the origin

Would be good to clarify this as

>The distance from the clipping plane to the origin in the direction of the plane normal

Also we should mention that the plane normal is always normalised (which is what allows us to interpret d from the equation as distance, otherwise it would some multiple of d)

**Comment by carmenfan** [comment]
User orientated docs are being done in Swagger by @3drepo/product-team 

It is probably also (if not more!) important to note the explanation there, @mosment3DRepo ?

**Comment by carmenfan** [comment]
N/A
