### ISSUE TITLE
View URL Links don't work (don't update 3D Views)

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2414]
### Description

Opening a saved view does not load from Teamspaces or as a URL link.

- This is happening in: prod/
- This requires a hotfix to production: no 

### Steps to replicate
- Open this view: `https://www.3drepo.io/viewer/Bogdan_D/6dba85c6-58d5-4407-9c48-0a7ed744a1eb?viewId=9b7c77f0-02f9-11eb-b2d0-77003e769734`
- Now open the Views Card
- Click on the **Position is wrong view**.

### Current Behaviour
- Opens a model with default camera position

### Expected Behaviour
- Expected to change camera position & element colour overrides to suit the view's settings
- Expect this behaviour from both, URL link and opening a view in Teamspaces

### Pictures/ Gifs of the error
![Views](https://user-images.githubusercontent.com/19904513/105382334-dc91c800-5c07-11eb-91a7-d88cdad7359c.gif)

**Comment by mosment3DRepo** [comment]
fixed with 4.14.0
