### ISSUE TITLE
Changing model revisions in the viewer, doesn't update Base Model in 3D Diff

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2416]
### Description

Switching between model revisions in the viewer does not update the Base model for 3D Diff.

- This is happening in: prod/this bug on the respective PR -->
- This requires a hotfix to production: no 

### Steps to replicate
- Open this model: `www.3drepo.io/viewer/Demo_3D_Repo/a8ca7ab0-c15e-11ea-b904-51d95a540cbc`
- Open Compare Card
- Select Rev05
- Click on the Revision icon and select Rev03 or any other revision

### Current Behaviour
- If you open another model revision the base model remains as rev05

### Expected Behaviour
- When I open rev03 Base Model should say rev03

### Pictures/ Gifs of the error
![Compare Card](https://user-images.githubusercontent.com/19904513/105385317-20d29780-5c0b-11eb-913d-6c0ae0f7c5f1.gif)

**Comment by sanmont3drepo** [comment]
There is still a problem when you navigate back and forth after switching revisions. You can see that the revision changes in the switch button and the loading of the model but the compare card is not getting update.

![versioncompareproblems](https://user-images.githubusercontent.com/42032433/118847734-f7c6c880-b8c5-11eb-8fda-2e8c39af6297.gif)
