### ISSUE TITLE
4D Sequence elements missing intermittently

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2432]
### Description

Elements in the 4D sequence seem to disappear and won't return until after the page is refreshed

- This is happening in: prod
- This requires a hotfix to production: yes

### Steps to replicate
- Open this model using the 3D Repo support account: [https://www.3drepo.io/viewer/Multiplex/bba7f2f0-51a2-11eb-895f-adff9a52627d](https://www.3drepo.io/viewer/Multiplex/bba7f2f0-51a2-11eb-895f-adff9a52627d)
- Click on the only risk in the Safetibase card
- Click the icon next to the sequence start date to move the sequence to the 13 Jan 2021
- See that the crane appears
- Move the sequence slider around
- Go back to the Risk and click the icon to move the sequence date back to 13 Jan 2021
- Notice that the crane no longer appears and doesn't seem to appear in any area of the sequence
- Refresh page and repeat, crane is back

### Expected Behaviour
- Crane element should behave consistently

### Pictures/ Gifs of the error
![4D Crane](https://user-images.githubusercontent.com/62879582/106139191-09dcf980-6165-11eb-9960-cc09fb45f155.gif)

**Comment by carmenfan** [comment]
Merging this with #2433 so we have one branch for hotfix
