### ISSUE TITLE
Treatment suggestions get white screen for empty risks

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2443]
### Description

When you create a risk and leave the input fields blank, your treatment suggestion window will give you a white screen (only if you start filtering for suggestions)

- This is happening in: prod
- This requires a hotfix to production: no 

### Steps to replicate
- Open any model in the viewer
- Start creating a risk
- DO NOT fill in any of the information
- Click on the Treatments tab
- Click on the Suggest button
- In the suggested Treatments window click on the Stage drop-down menu

### Current Behaviour
- Only one of the models was highlighted.

### Expected Behaviour
- Should work fine as it would with any risk that has some information input

### Pictures/ Gifs of the error
![Treatment Suggestions](https://user-images.githubusercontent.com/19904513/106896530-964d6600-66e9-11eb-9706-8bed729b7291.gif)

**Comment by Charence** [comment]
@BDavydov Can you give me access to this model?

**Comment by Charence** [comment]
Resolved in bug branch #2455
