### ISSUE TITLE
Pentest M2 - Turn off Cross-Site Requests

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2449]
### Description

Cross site requests expose 3D Repo to malicious attacks and is often rendered incompatible by  changes to Chrome (edge/Firefox etc.)

In order to solve both problems we should turn off Cross-Site Requests and restrict all usage of the embedded viewer and APIs to API Key only

If possible this change should be reversible in case we find a client using cross site for a critical tool, in which case we will turn it back on as we assist the client in transitioning to an API key

We have clients attaching via iframe, we want to make sure they are unaffected from this change

**Comment by Charence** [comment]
Note: "Strict" and "Lax" don't work with iframe; user is unable to proceed from login page.
