### ISSUE TITLE
Pentest M3- Account Lockout policy

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2451]
### Description

Currently there's is no password lockout policy and this means passwords can be brute forced. ALthough we can monitor this there is no failsafe if someone brute forces in the middle of the night

The following goals were set based off Microsoft guidelines [Available Here](https://docs.microsoft.com/en-gb/archive/blogs/secguide/configuring-account-lockout)

### Goals

- [x] After 10 bad attempts at password entry a users account is locked (this should be a variable in case we want to change it later)
- [x] The account is locked for 15 minutes (as above, may need to be changed later)
- [x] If no incorrect password is entered for a period of 15 mins the counter is reset (eg. if I enter it wrong 8 times, then do nothing for 15 mins, the counter is set back to 0)
- [x] Account locking triggers a flag which can be monitored on either Elastic or Intercom (or perhaps both)
- [x] Password reset only works when account is unlocked
- [x] If the number of attempts remaining is <=5 the Login screen will explain "You have x attempts remaining"
  - [x] backend
  - [x] frontend

**Comment by carmenfan** [comment]
> Password reset remains working regardless of account locking

@mosment3DRepo so if I got locked out, reset the password, do you expect the lockout to reset or there's still a 15min timeout?

**Comment by mosment3DRepo** [comment]
@carmenfan updated to 

> Password reset only works when account is locked
