### ISSUE TITLE
Clicking white space in the cards to deselect Issues/Risks/Groups

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2463]
### Description

At the moment is is tricky to deselect an Issue/Risk/Group which means the pins stay visible even when all pins are turned off, or it is not the correct time in the sequence.

When the user clicks the whitespace it should deselect the current selection

### Goals

- [ ] Allow users to deselect the currently selected Issue/Risk/View

### Related Resources
<img width="305" alt="issues area crop" src="https://user-images.githubusercontent.com/62879582/107524460-b380a980-6bad-11eb-85c2-e50d365d8bae.png">

**Comment by abyszewski** [comment]
Hello @mosment3DRepo! I got into this issue and I was thinking about solutions. For me clicking outside the issues list to deselect is not user-friendly especially when the list takes the full height of the container. What do you think about deactivating on click an active issue/group? The second question is what should happen when we don't have an active issue, the model should zoom out?

**Comment by mosment3DRepo** [comment]
hi @abyszewski I think we need to keep the concept of clicking the whitespace as it includes the area at the bottom which contains the count of results and is always visible, but I do agree clicking on a selected issue or group to deselect is also a good idea.

### Issues & Risks
When we deselect the issue/risk, we should do the following:
- Remove the arrow box on the right hand side of the issue in the UI
- Remove highlighted element overrides
- Remove emphasis on pin (it should go back to translucent or hidden if the issue/risk is out of sequence)
- Keep camera position
- Keep sections
- Keep element colour overrides
- Keep hidden elements hidden

### Groups
When we deselect a group:
- Remove the arrow box on the right hand side of the group in the UI
- Remove object selection on group elements
