### ISSUE TITLE
BIM Card - don't stack "Select Similar Elements" action

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2470]
### Description

When you click the "select similar elements" button in the BIM Card it should override any previous selection rather than adding to it.

If you select the same parameter again it should remove the selection override and just go back to the single element selection

### Current Behaviour
- Select Element
- Click the "select similar" button next to Level = "Level 00 - GF Level"
- All items with Level = "Level 00 - GF Level" are selected
- Click the "select similar" button next to IFC Type = "IfcSlab"
- All items with IFC Type = "IfcSlab" are added to the existing selection

### Expected Behaviour
- Select Element
- Click the "select similar" button next to Level = "Level 00 - GF Level"
- All items with Level = "Level 00 - GF Level" are selected
- Click the "select similar" button next to IFC Type = "IfcSlab"
- All items with Level = "Level 00 - GF Level" (excluding the original component) are deselected
- All items with IFC Type = "IfcSlab" are selected
- Click the "select similar" button next to IFC Type = "IfcSlab" for a second time
- All items with IFC Type = "IfcSlab" (excluding the original component) are deselected

### Pictures/ Gifs of the error
Current behavour:
![overidestacking](https://user-images.githubusercontent.com/62879582/107764383-07af9900-6d28-11eb-94cb-537bb6006e10.gif)

**Comment by carmenfan** [comment]
adding this to #2462

**Comment by mosment3DRepo** [comment]
> * Click the "select similar" button next to IFC Type = "IfcSlab" for a second time
> * All items with IFC Type = "IfcSlab" (excluding the original component) are deselected

@carmenfan current functionality looks much better, but think we missed the last two actions off
