### ISSUE TITLE
Show All not working correctly on some models

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2487]
### Description

Certain models seem to not work properly with the "Show All" command, seems to be related to the tree as the same models have a selection issue

- This is happening in: prod & staging

### Steps to replicate
- Open this model [NHS model (staging)](https://staging.dev.3drepo.io/viewer/andrew/d8b89f20-9afb-4dd9-be47-8a9f77658a46)
- Drag the selection box over a series of elements (notice if doing the top right to bottom left selection it always selects every element)
- Hide the selection using the toolbar
- Hit the "Show All" button, not everything returns

### Expected Behaviour
- When hitting "Show All" all elements in the model should return

### Pictures/ Gifs of the error
![errorVisibility](https://user-images.githubusercontent.com/62879582/108853332-80dba580-75de-11eb-8ce6-d3abad94feaf.gif)

**Comment by mosment3DRepo** [comment]
Not sure if this was a result of 4.14.0 because prod was updated before I had a chance to check

**Comment by carmenfan** [comment]
@mosment3DRepo  most likely, I had to tweak the the visibility logic to fix the crane problem in sequencing.

do you want a hotfix for this?

**Comment by mosment3DRepo** [comment]
Any idea what might be causing it? Just tried it with other IFC models and can't duplicate
