### ISSUE TITLE
New Federations asks you to upload a model revision

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2490]
### Description

When you create a new Federation, you can't open it. It prompts you to upload a new revision. Only after the hard refresh Ctrl + R, it opens.

- This is happening in: prod/
- This requires a hotfix to production: yes/no

### Steps to replicate
- Log in to 3drepo.io
- Create a new Federation
- Open the new federation

### Current Behaviour
- Asks you to upload a new revision (thinking that it's a model)

### Expected Behaviour
- Open and start loading models

### Pictures/ Gifs of the error
![Federation](https://user-images.githubusercontent.com/19904513/108975565-88528b80-767e-11eb-98ab-95569d225379.gif)

**Comment by keifgwinn** [comment]
looks like the same thing as #2429

**Comment by carmenfan** [comment]
@keifgwinn  this theoretically shouldn't happen because we always have a box that deals with the jobq right?

**Comment by keifgwinn** [comment]
we do and it does deal with it but it's a UI update thing

**Comment by carmenfan** [comment]
temp fixed in #2487. This needs a proper rework as federation on the UI assumes success as soon as it dispatch the request.

The work actually starts in the bouncer https://github.com/3drepo/3drepobouncer/issues/347
