### ISSUE TITLE
Update the list of jobs for Issues/Risks based on Model/Federation permissions

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2494]
### Description

It's to do with the Issue assignment for models/federations. Your teamspace may have 10 Jobs and whilst only 2 jobs have permissions for a model, you still get a full list of jobs to choose from. 
The list should only contain the jobs that have access to a model/federation
 
### Goals

- [ ] Users can only see jobs that have access to a model/federation

### Related Resources

Only MEP Engineer & Structural Engineer have access to this model, but a full list of jobs is visible.
![image](https://user-images.githubusercontent.com/19904513/109152977-22403400-7764-11eb-9f2a-0b037bd868f9.png)

**Comment by carmenfan** [comment]
Jobs aren't pegged against revisions, it's users. So it doesn't make a lot of sense to do this. I've always been in the opinion that permission should be pegged against jobs, but I wasn't a decision maker when that was designed.

Perhaps this is something to be considered on reworking permissions @mosment3DRepo

**Comment by carmenfan** [comment]
Closing this as this should live somewhere in the product planning side and be delivered as part of permissions revamp
