### ISSUE TITLE
Synchro Animations missing

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2501]
### Description

The SPM file "MO_SPM from Synchro Link.spm" ([Dropbox Link](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Clients/Customers/Gammon/Support/210223/Models/SPM )) contains transformations using the "Transform" tool in Synchro, this leads to the model animating as per the GIF [HERE](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Clients/Customers/Gammon/Support/210223/Models/SPM?preview=Synchro+Video.gif)

This has been done using the "Transform Assigned Resources" function in Synchro, which we have not seen before:
![image](https://user-images.githubusercontent.com/62879582/109296604-80cee600-7828-11eb-81e4-740c513861a6.png)

It seems 3D Repo does not process this correctly as no animations are created in the 3D Repo sequence, and the components do not move for the whole sequence ([3D Repo Link](https://www.3drepo.io/viewer/support_3DRepo/84d94550-7815-11eb-8ff9-5dcd7743e810)) 

[3D Repo GIF HERE](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Clients/Customers/Gammon/Support/210223/Models/SPM?preview=3D+Repo+Video.gif)

The source SP file is available [Here](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Clients/Customers/Gammon/Support/210223/Models)

- This is happening in: prod 
- This requires a hotfix to production: yes

### Current Behaviour
- Transformation logic not interpreted by 3D Repo

### Expected Behaviour
- Transformations in 3D Repo should reflect the Synchro transformations

### Pictures/ Gifs of the error
[Synchro Playback](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Clients/Customers/Gammon/Support/210223/Models/SPM?preview=Synchro+Video.gif)
[3D Repo Playback](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Clients/Customers/Gammon/Support/210223/Models/SPM?preview=3D+Repo+Video.gif)

**Comment by carmenfan** [comment]
Closing this as it's something we can't fix.

I've probed the file and it seems like Synchro library is not giving us any information regarding this animation. If they don't give it to us, we can't do anything about it 😢
