### ISSUE TITLE
Add URL base path to API docs

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2503]
### Description

Now we have witched to using https://www.3drepo.io/api/ we should include the base path in the api docs to avoid confusion.

We can it as either part of every request example:

![image](https://user-images.githubusercontent.com/62879582/109470399-430bd080-7a67-11eb-8892-b5582bdbef01.png)

Or as part of the opening paragraph:

![image](https://user-images.githubusercontent.com/62879582/109470533-764e5f80-7a67-11eb-99ac-bec38592f3aa.png)

### Goals

- [ ] Make it easy for users to understand how to access the APIs
- [ ] Avoid unnecessary support requests

#

**Comment by mosment3DRepo** [comment]
added as high priority as users are starting to look in the Network tools and include api1/ai2/api3 in their requests

**Comment by carmenfan** [comment]
@mosment3DRepo how much do we still care about this if we're moving onto v5 and will support swagger?

servers will be listed up top https://issue-2722.dev.3drepo.io/docs/

**Comment by mosment3DRepo** [comment]
it's not necessary if we're switching to swagger, was mostly just to compensate for the lack of space for it in apidocs
