### ISSUE TITLE
T&Cs prompt hotfix

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2505]
### Description

Apply T&Cs prompt fix as hotfix

- This is happening in: ~~prod/staging/~~ both 
- This requires a hotfix to production: yes ~~/no~~ 

### Steps to replicate
- Sign up for new account and login

### Current Behaviour
- No prompt

### Expected Behaviour
- Prompt

**Comment by carmenfan** [comment]
@Charence  just to clarify, we don't expect new accounts to have a prompt. it should only get a prompt if lastLoginAt < the timestamp declared in the config.

The new users used to get the prompts, but we don't want that 😆

**Comment by Charence** [comment]
> @Charence just to clarify, we don't expect new accounts to have a prompt. it should only get a prompt if lastLoginAt < the timestamp declared in the config.
> 
> The new users used to get the prompts, but we don't want that 😆

I see. Ok!
