### ISSUE TITLE
Allow activity data to be uploaded in an array

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2506]
### Description

When the initial sequence is uploaded (detailed in #2440) it is common to then need to upload a series of tasks. Using the individual task upload (detaile in #2441) will be complicated due to the number or requests and parent/child relationships.

In order to resolve this we should allow the users to perform a POST request with the activity data in an array similar to the below. This is a similar schema to [getSequenceActivities](https://3drepo.github.io/3drepo.io/#api-Sequences-getSequenceActivities) with the addition of the "data" object to attach the additional meta data

```
{
  "tasks": [
    {
      "name": "Clinc Construction",
      "startDate": 1603184400000,
      "endDate": 1613062800000,
      "data": [
        {
          "key": "string",
          "value": "string"
        }
      ],
      "subTasks": [
        {
          "name": "Site Work & Logistics",
          "startDate": 1603184400000,
          "endDate": 1613062800000,
          "data": [
            {
              "key": "string",
              "value": "string"
            }
          ],
          "subTasks": [
            {
              "name": "Site Office Installation",
              "startDate": 1603184400000,
              "endDate": 1603213200000,
              "data": [
                {
                  "key": "string",
                  "value": "string"
                }
              ]
            },
            {
              "name": "Excavation",
              "startDate": 1603270800000,
              "endDate": 1603299600000
            }
          ]
        }
      ]
    }
  ]
}
```

### Goals

- [ ] Enable all activities for a 4D sequence to be uploaded in a single request
- [ ] Allow uploading of child tasks at the same time as parents, resolving the need to know the parent id

**Comment by carmenfan** [comment]
closing this as it's been done as part of #2539
