### ISSUE TITLE
Issues should contain a list of Jobs & Types that are relevant to the project. Large Teamspaces overload the drop-down menu & expose irrelevant information

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2508]
### Description

When your teamspace contains 25 projects and a user starts working on a new project number 26 Issues card will contain all of the possible Issue types and jobs inherited from the previous 25 projects. It should only contain jobs that have access to the project or projects models & Issue types that are relevant to this project rather than 50+ other issue types from 25 previous projects.

I only have Architect & Engineer that have access to this Project:
![image](https://user-images.githubusercontent.com/19904513/109522004-cea45200-7aa5-11eb-8e95-16e4d69846e0.png)

You get a long list of Issue Types that have nothing to do with this project:
![image](https://user-images.githubusercontent.com/19904513/109522353-1b882880-7aa6-11eb-8b5a-7923249c9994.png)

### Goals

- [ ] List Jobs that have access to this model/project only
- [ ] Have a limited number of issue types ie. block 50+ other issues types in the Teamspace that are irrelevant

**Comment by carmenfan** [comment]
this is very similar to #2494 and the comment I made there also stands here.

Closing this as this should live somewhere in the product planning side and be delivered as part of permissions revamp
