### ISSUE TITLE
Objects explode into multiple layers for direct Revit model imports

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2513]
### Description

Currently, a Revit file imported on 3drepo.io generates model elements with multiple layers instead of a single solid object. For instance, a single model element such as Wall is counted as 3 Objects in 3D Repo and you can hide, independently of each other exterior, interior and core faces of the wall (rather odd). 

### Goals

- [ ] Maintain a consistent object structure as per Revit

### Related Resources

**Walls in Revit**
161 Wall Instances
![image](https://user-images.githubusercontent.com/19904513/109703706-aee85900-7b8d-11eb-9dfd-41af78ce29bd.png)
![image](https://user-images.githubusercontent.com/19904513/109703815-d17a7200-7b8d-11eb-867a-c6dbfd389ae9.png)

**Walls in 3D Repo**
483 objects 🤯
![image](https://user-images.githubusercontent.com/19904513/109703996-05559780-7b8e-11eb-916b-6585fbdbbb3c.png)
![Triple Layerd Wall](https://user-images.githubusercontent.com/19904513/109704400-78f7a480-7b8e-11eb-85e7-9cc3fd45de78.gif)

Walls in 3D Repo

**Comment by carmenfan** [comment]
direct upload, plugin or both?

import issues can't be fixed in 3drepo.io. if it only happens in plugins, create an issue there.

If it happens through native upload, create an issue in 3drepobouncer.

Closing this one

**Comment by carmenfan** [comment]
@BDavydov would also be good if you provide a model as a test case
