### ISSUE TITLE
Model Isolate/Show does not update icon in the Tree card

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2514]
### Description

I isolate a model in the model tree, then to save time I click Show All in the toolbar. All of the models are visible, but in the tree card the icon is still showing up as hidden.

- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Open this model: [`Demo Federation`](https://www.3drepo.io/viewer/Demo_3D_Repo/19ce3220-6e89-11ea-9f08-1387f50c0299)
- Open the Tree Card
- Click Isolate on one of the models
- Now Click Show all in the toolbar 
- Go back to the Tree card, Icons haven't changed

### Current Behaviour
- Show/Hide icons in the tree card don't respond to changes made in the toolbar

### Expected Behaviour
- Icons to update accordingly

### Pictures/ Gifs of the error
![Model Isolate](https://user-images.githubusercontent.com/19904513/109783369-d37e1880-7c01-11eb-845b-77faf384e67d.gif)

**Comment by carmenfan** [comment]
it does update but you need to trigger it by clicking on the card.

This is most likely to do with us not creating a new copy of the state every time we update it, which was done because of performance issues.

Not sure what's the best way to go about this @sanmont3drepo

**Comment by BDavydov** [comment]
@carmenfan Okay, it's not mission-critical, as the actual functionality works. It's just confusing with the icons, given that model elements are showing.
