### ISSUE TITLE
Clip box planes behave differently when camera angle changes

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2517]
### Description

When you use the clip box, you can drag an individual clip plane. Well, the behaviour changes depending on whether you're looking at the clip plane from inside or outside the clip box. This becomes confusing and hard to use on large scale projects.

- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Open a 3D Model
- Activate Clip box
- Select a Clip Plane and drag it
- Rotate 180 degrees around that clipping plane
- Now drag it again

### Current Behaviour
- It behaves differently. Moving it towards and away from you works from one angle, whilst from another angle that logic changes. 

### Expected Behaviour
- To work consistently from any angle where you drag away and it moves away, drag towards you and it moves towards you

### Pictures/ Gifs of the error
![Clip Box Plane Dragging](https://user-images.githubusercontent.com/19904513/109810646-b2c5bb00-7c21-11eb-904e-01a89dbbd861.gif)

**Comment by carmenfan** [comment]
@BDavydov the one you created previous has been moved to unity repo: https://github.com/3drepo/3drepounity/issues/352

no need to create it again 😆 

closing this

**Comment by BDavydov** [comment]
@carmenfan it would be good if GitHub told me that. My internet dropped, so I thought I didn't save it, apologies.
