### ISSUE TITLE
weird UI on screenshot canvas

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2522]
### Description
**UI oddity in 3D Repo when creating Comment screenshot in Civil 3D:** Odd white element appearing in comment screenshot when opening it in 3D Repo.

### Steps to replicate
- In SafetiBase or Issues viewer, open a model which has a list of already-created risks/issues
- Click on any risk/issue to open the card
- Add a comment with a screenshot/markup and save the comment
- Go to 3D Repo and open the same risk/issue card 
- Click on the comment screenshot and notice the white element in the image
- Open the comment screenshot in Civil 3D and notice that the white element doesn't exist in the image

### Pictures / GIFs of the error
![oddity](https://user-images.githubusercontent.com/56918163/109513494-14a8e800-7a9d-11eb-84bb-e41697a54939.gif)

**Comment by m1chalkubiak** [comment]
@carmenfan In case I had to deal with it, I do not have access to the linked comment.

**Comment by carmenfan** [comment]
@m1chalkubiak  description updated with the actual comment. The comment itself is a bit misleading, but the general gist is that there's a hidden button that appears if your window is at a weird resolution


![image](https://user-images.githubusercontent.com/23369849/109809655-7b0a4380-7c20-11eb-9ba0-2c8529fc1681.png)

**Comment by m1chalkubiak** [comment]
<img width="1082" alt="Zrzut ekranu 2021-05-26 o 12 17 46" src="https://user-images.githubusercontent.com/24941866/119643812-84204080-be1c-11eb-9b66-99beeda1157f.png">
If we are thinking about this little element that appears at the bottom of the modal with the screenshot open, it looks like it was a not fully hidden toolbox that is normally available during creating the screenshot.

And it seems to me that it was visible even on desktop resolutions, at least I had no major problem recreating it.

I just wanted to confirm, is that was the described issue?

**Comment by carmenfan** [comment]
@m1chalkubiak  yes
