### ISSUE TITLE
Automated Emails contain incorrect date. Remove it completely

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2529]
### Description

Currently, our automated emails report an incorrect date. Remove it completely to avoid any issues.

### Goals

- [ ] Update Email HTML to contain no date highlighted in red

### Related Resources

![image](https://user-images.githubusercontent.com/19904513/111287553-3e384680-863b-11eb-8890-c247369b58ac.png)

**Comment by carmenfan** [comment]
Date on copyright declaration implies the date of first publication, so it shouldn't be updated as the years go by anyway.

![image](https://user-images.githubusercontent.com/11945337/111293360-18ae3b80-8641-11eb-8479-0fe123474ac0.png)

**Comment by carmenfan** [comment]
I'm going to close this as it's not really a bug.

@mosment3DRepo reopen this if you really want to remove the copy right notice.
