### ISSUE TITLE
Deleting API key does not stop it from working

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2547]
### Description

When deleting an API key (in either the UI or the API) the API key continues to work until a new one is generated.

- This is happening in: both
- This requires a hotfix to production: no 

### Steps to replicate
- Generate API key
- Use it to make a request
- Delete API key
- Notice that request using the original api key still works
- Generate a new API key
- Notice that the old one no longer works

### Current Behaviour
- API key is only invalidated once a new one has been generated to replace it

### Expected Behaviour
- When an API key is deleted it should stop working immediately

**Comment by sanmont3drepo** [comment]
Hi! It actually stops working immediately.  If you were already logged in it will use your logged in user information. So if you take a look at the results of the requests they are from the already logged in user.
Maybe we should prioritize the key over the logged in user?

**Comment by carmenfan** [comment]
@sanmont3drepo @mosment3DRepo tbh i think this is a user error... 😆

**Comment by mosment3DRepo** [comment]
Are you guys sure? Because I'm doing this in Postman

**Comment by carmenfan** [comment]
> Are you guys sure? Because I'm doing this in Postman

@mosment3DRepo  have you logged in on postman? it does auto-saves the cookie.

**Comment by sanmont3drepo** [comment]
Yup/

![apikey](https://user-images.githubusercontent.com/42032433/112971156-d9a2de80-9146-11eb-8ad5-acd9ceff70bd.gif)

Although there is no test testing this. I can add it.

**Comment by carmenfan** [comment]
@mosment3DRepo have you tried on dev? I think this is actually a bug regarding removing fields in user document

**Comment by mosment3DRepo** [comment]
Guessing this can be closed now since it's a problem on prod but resolved on dev

**Comment by carmenfan** [comment]
Yup. closing this
