### ISSUE TITLE
Look into unhandled promise rejection warning

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2556]
There's a bunch of unhandled promise rejection warning triggered in travis:

![image](https://user-images.githubusercontent.com/11945337/114065173-467a4f00-9892-11eb-8e76-3695bc9d6b6e.png)

We should investigate where it's coming from

**Comment by sanmont3drepo** [comment]
I think most of those are the mail service when you run it locally.

**Comment by carmenfan** [comment]
closing as these are v4 tests
