### ISSUE TITLE
Can't delete a long list of groups. Throws a Network Error message

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2557]
### Description

I have a long list of groups in my model. I have decided to clean it up and utilise the Delete all functionality. When I press on the Delete all button, I get a Network error message every single time.

- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Open this model: [structure](https://www.3drepo.io/viewer/Bogdan_D/6dba85c6-58d5-4407-9c48-0a7ed744a1eb)
- Open the Groups card
- Click on the Delete all button

### Current Behaviour
- Fails. Network Error 

### Expected Behaviour
- Delete all of the Groups

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/114142458-e07dde00-990a-11eb-9c9b-9f4ba669329e.png)

**Comment by carmenfan** [comment]
the query string is too long. 

Only way we can fix this is to make the front end send multiple requests

**Comment by m1chalkubiak** [comment]
@carmenfan Would You be so kind to let me know what is the specific query string length limit value allowed for these queries?

**Comment by carmenfan** [comment]
@m1chalkubiak  it's imposed by the browsers: https://stackoverflow.com/questions/15090220/maximum-length-for-url-in-chrome-browser
