### ISSUE TITLE
4D Sequence Playback not loading elements correctly

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2560]
### Description

Playback of a 4D sequence doesn't appear to show/hide the correct elements

- This is happening in: prod
- This requires a hotfix to production: no (needs to be fixed for next release) 

### Steps to replicate
- Open this model: [4D Example](https://www.3drepo.io/viewer/anorrie/b4ef43b0-566f-11eb-bc6a-2f1fcc287e6a)
- Open the sequence
- First frame looks like [this image](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Images?preview=Sisk+4D+Issue+1.png)
- Open up the first frame JSON object using the API [here](https://api1.www.3drepo.io/api/anorrie/b4ef43b0-566f-11eb-bc6a-2f1fcc287e6a/revision/lat_jss_00_zz_vs_w_0007/sequences/27816138-0923-4004-a0d5-e1794e07b79b/state/a4c646e7-5c06-404e-870d-01eaa30d9cef)
- I have set up Groups in the model to represent the equivalent sections of the sequence frame
- See Group "Hidden Elements" [screenshot here](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Images?preview=Sisk+4D+Issue+2.png)
- Notice that the elements in this group are different from the ones in the sequence.
- It also seems as though not all elements are selected in the groups either
- Same model has correct frames on staging [model link](https://staging.dev.3drepo.io/viewer/andrew/e11a4930-9c38-11eb-86ad-4bacbc759634)

### Current Behaviour
- Sequence frame does not match JSON object
- Element selection seems to be inconsistent for the groups (perhaps due to the number of elements)

### Expected Behaviour
- Sequence frames should be correct according to the JSON object
- All elements should select in the group

**Comment by carmenfan** [comment]
@mosment3DRepo  have you tried this on staging? This could be related to #2509, which we have a fix for in staging

**Comment by carmenfan** [comment]
confirmed this is the same issue as #2509
