### ISSUE TITLE
4D Sequence playback based on frames can crash

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2562]
### Description

When playing back a 4D sequence based on frames it can suddenly stop displaying the model. Also loading times between frames is slow (no prefetching?)

- This is happening in: staging
- This requires a hotfix to production: no (fix for next release) 

### Steps to replicate
- Open [this model](https://staging.dev.3drepo.io/viewer/andrew/e11a4930-9c38-11eb-86ad-4bacbc759634) (you may need to clear your cache if you've already opened the model before)
- Open the sequence
- Select playback via frames
- Play through the sequence
- Notice the first few frames don't load (this may be a separate issue)
- Around 27/9/2021 the model disappears (see video below)
- Going to the same date in day playback does not produce the error

Sometimes the following icon appears in the top left after the model disappears
![sad face](https://user-images.githubusercontent.com/62879582/114697303-a7cc7300-9d15-11eb-8b80-5570e72ab1d4.png)

### Current Behaviour
- The sequence playback seems to fail at some point

### Expected Behaviour
- Playback should play smoothly

### Pictures/ Gifs of the error
[video on dropbox](https://www.dropbox.com/home/3D%20Repo%20Team%20Folder/Support%20Team/GitHub%20Issues/Images?preview=2021-04-14+11-23-40.mp4)

**Comment by carmenfan** [comment]
Currently I cannot reproduce the problem, but some stuff I found and needs fixing

**To do list:**
- [ ] Prefetch is not fetching the correct  3 frames
- [ ] freshly uploaded models seems to be stuck on "loading frames" if model caching is turned on

**Comment by Charence** [comment]
@carmenfan Frames playback for Sequence 3 on this model doesn't get very far: http://127.0.0.1/viewer/mosment3ddev/10ff30c0-9874-11eb-8e5c-c9ff1aec95c5

Not sure if it is related to the problems you already listed. I don't have model caching enabled.

**Comment by carmenfan** [comment]
@Charence  problem is I can't run that model outside of the Sequence API branch as it's new schema...

I'll see if I can reproduce it over there and if yes then I'll try to fix it on that branch.

Assuming this is the same bug @mosment3DRepo

**Comment by mosment3DRepo** [comment]
Managed to recreate the issue in Edge:

3D Repo Error:

```
Your browser has failed to load 3D Repo's model viewer. The following occured:

TypeError: Cannot read property '0' of null at _emscripten_set_canvas_element_size_calling_thread (blob:https://staging.dev.3drepo.io/e85a5d04-389a-427e-8e4f-8902e807f11a:2:189737) at _emscripten_set_canvas_element_size (blob:https://staging.dev.3drepo.io/e85a5d04-389a-427e-8e4f-8902e807f11a:2:190260) at :wasm-function[10360]:0x3d0910 at :wasm-function[10358]:0x3d02de at dynCall_v (:wasm-function[52254]:0x10f9b81) at Object.dynCall_v (blob:https://staging.dev.3drepo.io/e85a5d04-389a-427e-8e4f-8902e807f11a:2:470280) at browserIterationFunc (blob:https://staging.dev.3drepo.io/e85a5d04-389a-427e-8e4f-8902e807f11a:2:169987) at Object.runIter (blob:https://staging.dev.3drepo.io/e85a5d04-389a-427e-8e4f-8902e807f11a:2:173048) at Browser_mainLoop_runner (blob:https://staging.dev.3drepo.io/e85a5d04-389a-427e-8e4f-8902e807f11a:2:171510)

This may due to insufficient memory. Please ensure you are using a modern 64bit web browser (such as Chrome or Firefox), reduce your memory usage and try again. If you are unable to resolve this problem, please contact support@3drepo.org referencing the above error.
```
