### ISSUE TITLE
Autocomplete attributes help password managers on password fields

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2563]
### Description

[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) 

### Goals

- [ ] Better password support in chromium browsers to auto-suggest hard passwords

### Tasks

- [ ] TBD
-

### Related Resources

Background: https://goo.gl/9p2vKq

**Comment by m1chalkubiak** [comment]
Hi @carmenfan  @keifgwinn
I would like just to confirm what we want to do in this task.
I understand that the suggestion concerns the login form and the password field.

Currently, this input has an autocomplete attribute with a value of "password", and we would like to change this to "current-password", that's all?
<img width="847" alt="Zrzut ekranu 2021-06-8 o 13 33 44" src="https://user-images.githubusercontent.com/24941866/121178020-585e7b00-c85e-11eb-84b1-9035b483f756.png">

**Comment by carmenfan** [comment]
i think also new-password for the sign-up & password change form?

@keifgwinn  you read up on these stuff, can you elaborate?
