### ISSUE TITLE
Google Tag Manager for .io

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2584]
### Description

We are now moving to Google Tag Manager, which allows us to embed a single tag reference and use it for a number of different products, including Google Analytics, without having to change backend code in the future

### Tasks

- [ ] Add the Google Tag Variable 'GTM-5H6W9JP'
- [ ] Add the code to .io
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5H6W9JP');</script>


<!-- End Google Tag Manager -->

```
Additionally, paste this code immediately after the opening <body> tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src=https://www.googletagmanager.com/ns.html?id=GTM-5H6W9JP
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

```

**Comment by m1chalkubiak** [comment]
@mosment3DRepo What about current Google Analytic code? I know it's something else, but do we give it up in favor of GTM, because GTM can track the same data + gives more flexibility, because it does not require changes directly in the code?
Or should we just leave the GA code and additionally add GTM?

**Comment by mosment3DRepo** [comment]
@m1chalkubiak we can replace the code with the new one and then link to old Google Analytics back in to the Tag on Google
