### ISSUE TITLE
Change email regex to support TLD > 5 chars

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2586]
### Description

A user's email address xxxxxxxx@yyyy.london was rejected at the login screen, further investigation show that the regex is currently limited to 5 character TLDs

### Current Behaviour
- TLD of .london is rejected using the regex: `define("EMAIL_REGEXP", /^([a-zA-Z0-9_\-.]+)@([a-zA-Z0-9_\-.]+)\.([a-zA-Z]{2,5})$/);`

### Expected Behaviour
- Extended TLDs should be supported as they are becoming more common
- https://emailregex.com/ offers a solution which seems to resolve this issue

**Comment by Charence** [comment]
In line with the e-mail validation on the frontend, we will adopt Yup for e-mail validation on the backend as well. A function that returns a promise will be added to `backend/utils`.
