### ISSUE TITLE
Can not create an issue in 3D Repo

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2588]
### Description

Shows me an error message **Missing or invalid arguments**

- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Open this model: [`a link to the model`](https://www.3drepo.io/viewer/Bogdan_D/9b92e06f-add6-42ca-91f7-f617f5837011)
- Create an issue as show in the screenshot below

### Current Behaviour
- Error message

### Expected Behaviour
- Work

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/19904513/116576125-30970180-a907-11eb-8c78-d3aa2720de51.png)

**Comment by BDavydov** [comment]
@Charence Permission granted!

**Comment by mosment3DRepo** [comment]
can no longer replicate
