### ISSUE TITLE
Record user logins

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2611]
### Description
We want to start logging more information regarding the user logging in. The main aim is as follows:

- In the future, we may want to show the user a log of their session activity; identifying where they logged in from and with what kind of device.
- We want to start gathering statistics about which plugin version with which CAD software the user is using, so we can make better decisions on deprecating support. (this will require https://github.com/3drepo/3drepoPlugin/issues/181)

### Goals
- [ ] Every time a successful login request has been processed, we should gather data about the user origin and record an entry in the database.
- [ ] Send a copy of the record to elastic

### Specification
Upon successful login, we should extrapolate the user origin, type of device etc  from the request and store it as an entry. 

We should store it like notifications, where we have a database called `loginRecords`, where each user has its own collection. (NOTE: we need to blacklist the database to prevent users from creating a user account with the same name)

The schema should (probably) look like this:
````js
{
   _id: <string> //session ID so we can refer to it if necessary (to check if the session is still active?)
   loginTime: <MongoDB date>, //date time when the user logged in
   referrer: <string>, //the domain the request came from (e.g. https://www.3drepo.io or somewhere else which embedded our viewer),
   ipAddr: <string>, //ip address of the request
   location: {
        country: <string>, //country code
        city: <string>
    },
   application: {
       name: <string>, //If this came from a plugin, this should be Revit/Civils/Autocad/Navis, if it's browser it should be "chrome", "firefox" etc.
       version: <string>,
       type: <string> //"browser" or "plugin" or "unknown" (unknown used if there's no user agent information)
   },
   engine: {
       name: <string>, //If this came from a plugin, this should say "3drepoplugin"
       version: <string> //If this came from a plugin, this should be the version of the plugin
   },
   os: {
      name: <string>,
      version: <string>
   },
   device: <string> //type of device, e.g. mobile, computer etc
         
}
````

#### Considerations
- express seems to store the [ip ](http://expressjs.com/en/api.html#req.ip) as part of the request object. so we should be able to get the ip from just doing `req.ip`
- We utilise a nginx box in front of the web io boxes for traffic forwarding... so to get the original ip in these situatiosn, we need to check [req.ips](http://expressjs.com/en/api.html#req.ips) - make sure we cater for both cases.
- location info we should be able to extract from the IP address by utilising a nodejs library
- the other info should be extractable from the user agent (again, with a 3rd party nodejs library)
- We will need to come up with a format for plugin user agent and parse it for the info accordingly.

### Tasks
to be filled out by the developer

**Comment by carmenfan** [comment]
@keif this is related to this https://github.com/3drepo/3drepoPlugin/issues/181 which you asked where we're going to store it and initially I thoguht we'd just like a statistics of this so elastic.

But after some thought, we'd probably want to store this in the database so we can make an endpoint to retrieve it eventually (bit like how netflix/twitter etc has a page to see where and when you signed in). But we can still send analytics to elastic if it's worthwhile. any thoughts?

**Comment by carmenfan** [comment]
@keifgwinn  i think we want it in the main database so it can be exposed as a form of api for the user to see their login history (as a future work). If we start getting info from elastic for endpoints instead of just stats gathering then we may as well replace mongo with elastic... 😆 

It's more of a question of whether we want any of this data to go into elastic for stats gathering purposes (any or all, and at what kind of format etc) - for e.g. i dont' think we want user data specifically like how it's proposed for the main db schema (because we don't need/want to extract login history like this via elastic?), but there might be value in generalised data to show how many users uses which autodesk plugin and what version etc.

**Comment by keifgwinn** [comment]
The best form of the records for elastic look exactly the same as the main record keeping as it's all processable. Having log in records like this is useful and easier than working out a way of extracting this information from the text log files. Generally any of these metrics that we can export to elastic is easier than scraping the log files. 

For some purposes it'll just be aggregated up for reporting, and for other purposes it can form part of the tracing of requests for debugging.

**Comment by keifgwinn** [comment]
yes, this would be a general improvement for all the elastic monitoring to be able to trace every request all the way through with the session
