### ISSUE TITLE
SafetiBase pins don't load after save

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2621]
### Description

When adding a pin to a Safetibase risk, it is not immediately visible until the model is reloaded

- This is happening in: prod/staging/both 
- This requires a hotfix to production: fix before next release

### Steps to replicate
- Open any model
- Create a new risk
- Add a pin to the risk
- Save the risk
- Notice the pin disappears
- Reload the page
- Pin is back

### Current Behaviour
- Pin isn't shown after risk is saved

### Expected Behaviour
- Pin should remain visible after risk is saved

### Pictures/ Gifs of the error
![Pin Load](https://user-images.githubusercontent.com/62879582/119375394-ab5afe80-bcb2-11eb-9738-7ce15a307c94.gif)

**Comment by mosment3DRepo** [comment]
@carmenfan can we fix before 4.18?

**Comment by carmenfan** [comment]
@mosment3DRepo  yep
