### ISSUE TITLE
User exists in the database, but can't be added using the email address confuses our users

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2626]
### Description

Currently, if you search for a user using their email address, after a couple of seconds a drop-down will appear prompting you to select an existing user. However, if you rush and don't wait for 2-3 seconds and click ADD user, it will prompt you to invite them, suggesting that they don't exist in 3D Repo. This confuses our users as they're unable to add new users using their email address & when they proceed to invite them, it says the user already exists!

- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Open the user management tab in 3drepo.io
- Search for this user test-kurt@3drepo.io
- Don't select anything in the drop-down
- Select a job
- Add a user
- 
### Current Behaviour
- Can't add a user if you skip the drop-down menu selection (sometimes doesn't pop up for 2-3 secs)

### Expected Behaviour
- Be able to add a user using their email address if it already exists and is tied to their account

### Pictures/ Gifs of the error
**What users sometimes don't see or don't understand because of the UI:**
![image](https://user-images.githubusercontent.com/19904513/119793031-22b8aa00-bece-11eb-89c3-cd000b839491.png)

**What happens when you don't select anything in the drop-down menu:**
![image](https://user-images.githubusercontent.com/19904513/119792870-f866ec80-becd-11eb-9982-c629d10ff6ab.png)
![image](https://user-images.githubusercontent.com/19904513/119792914-01f05480-bece-11eb-950d-a8cc9a7e44b6.png)

**Comment by carmenfan** [comment]
this seems like the API stopped accepting email address to add member for some reason.

marking it as a backend bug.
