### ISSUE TITLE
Allow editing of Issue & Risks titles in the UI and API

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2647]
### Description

Editing of Issue & Risk titles should be possible in the web interface and the API

### Goals

- [x] Allow users to amend the title of an issue
- [x] Allow users to amend the title of a risk
- [x] Restrict the permission to those that can already edit the descriptions in the issue/risk (Admins, and assigned Commenters & Collaborators)
- [x] Use the same UI interaction as editing the description (seen in the GIF below)
- [x] Editing Title shows the "Issue Updated" toast (same as editing the description) or "Risk Updated" for risks
- [x] Updating an Issue title will be communicated to other users and updated live using the chat server
- [x] Sending a PATCH request to /api/{teamspace}/{model}/issues/{issuedId} (or risks/{riskId}) with the following body will update the issue title
`{"name": "Updated Issue or Risk title"}`
- [x] Make the edit option available in the Kanban screen too

### Related Resources
![Description Edit](https://user-images.githubusercontent.com/62879582/121885645-4b350680-cd0c-11eb-9704-b3165c2f0f30.gif)

**Comment by carmenfan** [comment]
@mosment3DRepo 

>assigned Commenters & Collaborators

Do you mean commenters+ that is of the assigned role? or just anyone with commenters+ access?

**Comment by carmenfan** [comment]
> Sending a POST request to /api/{teamspace}/{model}/issues/{issuedId} (or risks/{riskId}) with the following body will update the issue title

@mosment3DRepo also editing this to PATCH. POST doesn't make sense in http verb terms (see [here ](https://stackoverflow.com/questions/31089221/what-is-the-difference-between-put-post-and-patch)for explanation)

**Comment by mosment3DRepo** [comment]
> @mosment3DRepo
> 
> > assigned Commenters & Collaborators
> 
> Do you mean commenters+ that is of the assigned role? or just anyone with commenters+ access?

The former, any Commenter+ with the correct assigned role
