### ISSUE TITLE
IPAD support issues

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2652]
### Bugs
- [ ] [Going to 3drepo.io with chrome is showing me the browser unsupported message](https://github.com/3drepo/3drepo.io/issues/2652#issuecomment-865111766)
- [ ] [We should drop the webgl2 warning message](https://github.com/3drepo/3drepo.io/issues/2652#issuecomment-865113604)
- [ ] [Navigation is completely unresponsive on ipad]()

**Comment by carmenfan** [comment]
**Going to 3drepo.io with chrome is showing me the browser unsupported message**

Even when I have updated chrome to the latest version available on the appstore, I'm still getting the browser unsupported page.

Firefox works fine however.

**Comment by carmenfan** [comment]
**We should drop the webgl2 warning message**

Going in with firefox, upon login I am seeing a warning message about webgl2. Since we now support WebGL 1, we should remove this check and should only display the message if the browser doesn't support webgl at all.

**Comment by carmenfan** [comment]
**Navigation is completely unresponsive on ipad**

Tested on firefox. Navigation via touch is not doing anything at all. Interaction with model via UIs (tree, views, issues etc) works fine though.

**Comment by mosment3DRepo** [comment]
@carmenfan did you try safari? My understanding is that they all have to use the Safari Webkit stuff on iOS so it's strange tha firefox works and chrome doesn't.

Was there a limit to the size of the models in Firefox [This one tends to push the upper bounds of the memory limit](https://www.3drepo.io/viewer/Bogdan_D/65f55ba0-7b54-11eb-90e4-594342e39ba0)

**Comment by carmenfan** [comment]
@mosment3DRepo it could just be some weirdness with our white list agent logic. If we're rewriting it into a black list instead then it will probably automatically resolve itself.

**Comment by carmenfan** [comment]
> @carmenfan did you try safari? My understanding is that they all have to use the Safari Webkit stuff on iOS so it's strange tha firefox works and chrome doesn't.
> 

Safari can log in fine. I think 3drepo.io has the same white list policy as 3D Send, which (until the last hotfix) did not include chrome as a supported browser for ios devices.

> Was there a limit to the size of the models in Firefox [This one tends to push the upper bounds of the memory limit](https://www.3drepo.io/viewer/Bogdan_D/65f55ba0-7b54-11eb-90e4-594342e39ba0)

Tried it on both safari and firefox, they both had the pop up message where it ran out of memory. However, I think this is more restricted by the ipad's memory than it being a problem with browser support.

**Comment by carmenfan** [comment]
This is older than #2972  so closing this in favour of the other one
