### ISSUE TITLE
Small fixes for node 14 upgrade

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2678]
### Description
- backend logger is no longer formatted:
![image](https://user-images.githubusercontent.com/11945337/124775654-b56d4f80-df36-11eb-95c9-d79c852ad4a2.png)

- there's a lot of warnings if you do a fresh yarn install:
![image](https://user-images.githubusercontent.com/11945337/124776014-02e9bc80-df37-11eb-8759-bc59fcd5d5ec.png)

### Tests
- [ ] model upload should still work as usual
- [ ] check login records are still logging IP correctly

### config update
`config.logfile.noColors = true` to get plain logs.

**Comment by keifgwinn** [comment]
ooh, can we use this as an opportunity to fix the logging =D been meaning to raise that for ages
