### ISSUE TITLE
Groups Post API to accept array of Groups and UI to allow upload

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2711]
### Description

Currently our Groups card lets you download a JSON of groups (as per the screenshot below), but once you have the file there isn't a simple way to reuse it in 3D Repo. Since the POST groups API endpoint only supports a single object our customers need to understand how to loop through request and it becomes much more complicated,

In order to help our customers with some of their model validation workflows it would be very useful to allow the groups API to accept an array of groups.

### Goals

- [ ] Add an option to download smart groups only (exclude regular groups) as JSON and exclude the "objects" element from the response, as it is unnecessary bloat in this use case
- [ ] Allow an array of groups to be uploaded via the API
- [ ] Where a group exists with the same ID, perform a PUT action to replace the old record with the new one. Where one doesn't exist, add a new group and create a new ID
- [ ] Add support on the UI to "Upload JSON" of an array of groups into a model/federation

#### Front end
- [x] Add 2 filter options (toggle inside hamburger button, default on)
  - show smart groups
  - show normal groups
- [x] 2 extra options (inside hamburger button)
  - Export groups
  - Import groups

#### Backend
- [x] `HTTP POST` endpoint (POST instead of GET to avoid the problem with query string being too long) to export groups
  - payload should contain an array of groups that the user wants to export
  - The group listing will contain the standard information about groups (title, name, createdAt etc), and also
    - if the group is a normal group if will return the `ifc_guids` if possible, otherwise `shared_ids` - never both
    - if the group is a smart group, it will return the rules (not objects)
- [x] `HTTP POST` endpoint to import a group 
  - This will take in the schema exported from the previous endpoint
  - If group id already exists in the fed/model, overwrite the content, otherwise create a new group
  - Ensure chat server is wired up to fire up the notifications
- [x] Adapt the endpoints to v4
- [x] Hook up with notifications
  - [x] Establish the pub/sub service for notifications
  - [x] hook v4 notifications onto it

### Related Resources

![image](https://user-images.githubusercontent.com/62879582/126627832-7625a8b7-289c-4be6-9530-a0dabebc24fd.png)

**Comment by carmenfan** [comment]
@mosment3DRepo 
What if we find a matching ID within the json that matches an existing group? Is this more of a PUT request (update or insert depending if theres already a matching ID) or a POST request (ignore all the IDs, create brand new groups)?

**Comment by mosment3DRepo** [comment]
Is that sort of Upsert logic relatively straightforward?

Am i right in thinking that if I downloaded some groups from a different federation, then uploaded them to a new one that mongo would give them new IDs and ignore the ones I gave it?

**Comment by carmenfan** [comment]
> Is that sort of Upsert logic relatively straightforward?

It's less straight forward than just blind insert with new IDs but it's nothing out of the ordinary.

> Am i right in thinking that if I downloaded some groups from a different federation, then uploaded them to a new one that mongo would give them new IDs and ignore the ones I gave it?

IDs are determined by the backend, so we can do it as we see fit.

**Comment by mosment3DRepo** [comment]
👍 added another goal to the issue relating to the upsert details

**Comment by BDavydov** [comment]
> @mosment3DRepo
> What if we find a matching ID within the json that matches an existing group? Is this more of a PUT request (update or insert depending if theres already a matching ID) or a POST request (ignore all the IDs, create brand new groups)?

@carmenfan I would prefer if we had the option to update the existing groups, so PUT. Users may well download JSON to update multiple groups at once & then post it back to 3D Repo.

**Comment by BDavydov** [comment]
@mosment3DRepo There might need to be 2 options for Downloading JSON. Currently, when you Download JSON, it contains additional fields of information that may not be necessary for users to see such as: 
- createdAt
- updatedAt
- updatedBy
- author
- objects ( account, model, shared_ids)

**Comment by carmenfan** [comment]
After some conversations with @BDavydov  we believe this is the approach we should do:

#### Front end
- [ ] Add 2 filter options (toggle inside hamburger button, default on)
  - show smart groups
  - show normal groups
- [ ] 2 extra options (inside hamburger button
  - Export groups
  - Import groups

#### Backend
- [ ] `HTTP POST` endpoint (POST instead of GET to avoid the problem with query string being too long) to export groups
  - payload should contain an array of groups that the user wants to export
  - The group listing will contain the standard information about groups (title, name, createdAt etc), and also
    - if the group is a normal group if will return the `ifc_guids` if possible, otherwise `shared_ids` - never both
    - if the group is a smart group, it will return the rules (not objects)
- [ ] `HTTP POST` endpoint to import a group 
  - This will take in the schema exported from the previous endpoint
  - If group id already exists in the fed/model, overwrite the content, otherwise create a new group
