### ISSUE TITLE
Invitation Model Assignment Bug

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2712]
### Description

When I am creating a new user invitation I can decide which models/federations to share. If I select all of the models at once and then decide to remove one or more of them I get a warning message. It seems as though it registers the original selection and if I unassign the model it throws an error.

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Log in to staging
- Head over to the User Management page
- Create a new user invitation
- Select a project and batch select all models as a viewer
- Now make one of the models as unassigned
- Click Send invitation

### Pictures/ Gifs of the error

![User Invtire permissions](https://user-images.githubusercontent.com/19904513/126299644-b6cbdca2-4ee7-4d64-adce-873a4d625c19.gif)

**Comment by Amantini1997** [comment]
Can't reproduce
