### ISSUE TITLE
Research warnings with packages

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2734]
### Description
When installing modules a bunch of "unmet peer dependency" and "deprecate" warnings shows up. We need to investigate what it means, if they can be a problem and in that case 

### Steps to replicate
- remove node_modules
- npm install or yarn install

**Comment by keifgwinn** [comment]
we're also getting this currently after the application starts on staging

node:12) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTo
pology: true } to the MongoClient constructor.

**Comment by carmenfan** [comment]
@keifgwinn  I'm pretty sure it's fixed in #2722 as I added `useUnifiedTopology` in https://github.com/3drepo/3drepo.io/pull/2731/files#diff-33ce0a26586671fe63d1b750b83ed18c49fc886c3472e3f8654e65f7a17f58aaR74
