### ISSUE TITLE
Dates are out of frame in kanban board

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2740]
### Description
Issues in kanban board are being chopped, date is being cut.

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- Create issues 
- Navigate to kanban board

### Current Behaviour
- Dates are cut out of frame

### Expected Behaviour
- Dates should be fully visibles

### Pictures/ Gifs of the error
With scrollbar:
![](https://user-images.githubusercontent.com/42032433/129720650-7e7c7ca3-f3f2-4aaa-baa3-1f290233fca4.png?v=4&s=100)

Without scrollbar:
![](https://user-images.githubusercontent.com/42032433/129720640-34843356-feb3-4b63-861d-d98b9dae207c.png?v=4&s=100)

**Comment by carmenfan** [comment]
probably obsolete

![image](https://user-images.githubusercontent.com/11945337/222494445-d6107ba7-a8d0-4b69-ac39-6f658a00a5d4.png)
