### ISSUE TITLE
server fail to launch without any error message if the user has alluxio configured

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2767]
### Description
If the user has alluxio configured (but not a working connection) , node fails quietly instead of showing the proposed error message:

![image](https://user-images.githubusercontent.com/11945337/131890552-5e4a229c-daa9-4379-940f-7ca815d2c0ee.png)

### Steps to replicate
- launch the server with an erroneous alluxio configuration

### Current Behaviour
- server dies without any messaging

### Expected Behaviour
- it should show an error message indicating it has failed to connect to the alluxio service

**Comment by Charence** [comment]
@ChristosTsiotsias @sanmont3drepo What did your config for alluxio look like?

**Comment by Charence** [comment]
I get something like this:

```
charence@charence-ThinkPad-X1-Extreme-Gen-3:~/Workspace/3drepo.io$ run/run_app remote
WARNING: If running locally then you may require sudo due to port issues 

yarn run v1.22.11
$ cross-env NODE_CONFIG_DIR=../config node ./src/v4/3drepo.js
2021-09-03T09:21:47.130Z [info] [APP] 	Loading api on 127.0.0.1:8080 
2021-09-03T09:21:47.706Z [info] [APP] 	Loading frontend on 127.0.0.1:8080 
2021-09-03T09:21:47.919Z [info] [APP] 	Loading chat on 127.0.0.1:3000 
2021-09-03T09:21:47.938Z [info] [APP] 	Starting server on 0.0.0.0 port 3000 
2021-09-03T09:21:47.938Z [info] [APP] 	Starting server on 0.0.0.0 port 8080 
2021-09-03T09:21:47.951Z [error] [APP] 	Health check failed on alluxio connection, please check settings. 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

From the screenshot, it looks like the other other messages such as `Loading api` are also not coming through.

**Comment by carmenfan** [comment]
As it turns out @ChristosTsiotsias has his log silenced... 
![image](https://user-images.githubusercontent.com/11945337/131993300-5130d368-af4f-4527-a20c-a3e77c8c92a1.png)


@sanmont3drepo since he copied it from you you probably have the same thing? 


Closing this as it's a non issue
