### ISSUE TITLE
Replace farmhash dependency due to deployment issue

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2773]
### Description

Farmhash, which we are using to generate random filenames, is crashing on a private deployment. This affects files saved through IO such as screenshots and other file attachments to a model. We are only using this library to generate a random filename, alternatives can be used.

- This is happening in: private prod deployment 
- This requires a hotfix to production: yes

### Steps to replicate
- Use 3drepo on private deployment
- Open a model
- Save a view

Note: This does not happen if you create a issue/risk through the Kanban board without a screenshot

### Current Behaviour
- IO crashes when attaching file

### Expected Behaviour
- IO to accept the file

**Comment by keifgwinn** [comment]
hacking fs.js to return a fixed string in place of the farmhash function results in the files being able to be saved, but only to that one folder.
