### ISSUE TITLE
SafetiBase Screenshot disappears from the list when you make any change

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2778]
### Description

When I open any of the SafetiBase risks and make some changes to them, I can go back to the original list of risks. Unfortunately, the screenshot disappears from the list.

- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Open the SafetiBase Card
- Open any SafetiBase Risk
- Make any change
- Go back to the list of Risks

### Current Behaviour
- Screenshot disappears

### Expected Behaviour
- Show the list in its original state

### Pictures/ Gifs of the error
![SafetiBase](https://user-images.githubusercontent.com/19904513/132500883-13cdd828-c0c8-4e2b-94e5-9d52a6d90000.gif)

**Comment by carmenfan** [comment]
cannot reproduce
