### ISSUE TITLE
Satisfy frontend linter on Travis

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#2780]
### Description

Linter is complaining on Travis

- This is happening in: staging 
- This requires a hotfix to production: no 

### Steps to replicate
- Make travis run linter

### Current Behaviour
- Problem only exists on Travis, not locally

### Expected Behaviour
- Linter should pass

**Comment by carmenfan** [comment]
@Charence  Any issue that has been tagged in a milestone should be closed.
