### ISSUE TITLE
Extract is not working with i18n._('...')

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#2783]
### Description
We have lingui working without macros because of a incompatibility between the config needed for lingui for macros and needed for v4 .  I believe if you are using the i18n._('...')  method ( https://lingui.js.org/ref/core.html#I18n._  ) the extract command should extract the id defined in there when right now it doesnt. It only works with `<trans id='...'/>` tag.

### Steps to replicate
- Add a  i18n._('...')  sentence in v5 source code 
- run yarn extract

**Comment by carmenfan** [comment]
This is N/A too i think because we moved away from Lingui? @sanmont3drepo 

Closing as well, reopen if I'm wrong here too! 😆
