### ISSUE TITLE
Change LONG_TEXT_CHAR_LIM to 1200

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2836]
### Description

We have a number of instances where the 660 character limit on Description in Issues and Risks is causing issues.

Unless there is a reason why we limited it to 660, we should increase it to 1200 to accommodate customer use cases

### Goals

- [ ] Enter up to 1200 characters for Issues & Risks descriptions in the UI
- [ ] Enter up to 1200 characters for Issues & Risks descriptions via the API

**Comment by carmenfan** [comment]
added to #2824
