### ISSUE TITLE
3D Repo v 4.19.2 (QA Test)

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2848]

**Comment by BDavydov** [comment]
When I import the Groups JSON file, nothing happens in the Groups Card.
There is no loading screen or icon. If that's the case, do groups not appear in the list without you needing to CTRL + R the page?
![Smart Groups Import](https://user-images.githubusercontent.com/19904513/140492512-a049897b-2c38-4344-92d4-e335aefe0644.gif)

**Comment by BDavydov** [comment]
Compare card slider behaviour is inconsistent. Sometimes it leaves the slider bar behind. At times, the slider is there, but no text.
![Compare Card Slider](https://user-images.githubusercontent.com/19904513/140524814-4c557085-d570-4b0c-b4f8-f64baa3d2b74.gif)

**Comment by BDavydov** [comment]
Groups count is still inconsistent. If a user opens another model/federation objects count = 0. In reality, there are objects and they
![Groups Count](https://user-images.githubusercontent.com/19904513/140530337-fc9a7193-7319-4132-925b-44c5f527ff94.gif)
 show you the number.

**Comment by mosment3DRepo** [comment]
> When I import the Groups JSON file, nothing happens in the Groups Card. There is no loading screen or icon. If that's the case, do groups not appear in the list without you needing to CTRL + R the page? ![Smart Groups Import](https://user-images.githubusercontent.com/19904513/140492512-a049897b-2c38-4344-92d4-e335aefe0644.gif)

Can't seem to reproduce, spoke to @BDavydov and he can't either now, so have to assume is was a cache problem

**Comment by mosment3DRepo** [comment]
> Groups count is still inconsistent. If a user opens another model/federation objects count = 0. In reality, there are objects and they ![Groups Count](https://user-images.githubusercontent.com/19904513/140530337-fc9a7193-7319-4132-925b-44c5f527ff94.gif) show you the number.

https://github.com/3drepo/3drepo.io/issues/2835

**Comment by carmenfan** [comment]
closing as we released 4.20 and i think anything unresolved are now in separate issues
