### ISSUE TITLE
Update DevOps build to include release tags

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2855]
### Description
Previously I removed automatic build on all the tagging builds but that doesn't help me on the release pipeline. I need to work out the syntax for semver based tagging

### Goals
- [x] Build release tags but do not auto-deploy them.

### Tasks
- [x] Probably add a new pipeline without release component set on tags.

### Related Resources

**Comment by carmenfan** [comment]
@keifgwinn  added this to your triage project as it's more suited there
