### ISSUE TITLE
Can't import Smart Groups JSON (exported from another federation)

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2862]
### Description

I'm trying to export a select few smart groups from Residential Federation in 3D Repo. When I upload the JSON export to another federation, it doesn't work

- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Open this model in 3drepo.io [Residential Federation](www.3drepo.io/viewer/Demo_3D_Repo/19ce3220-6e89-11ea-9f08-1387f50c0299)
- Open the Groups card
- Filter for Smart Groups ONLY
- In the search bar type in CS and hit enter
- Export the groups
- Open this model in 3drepo.io [MEP vs STR](www.3drepo.io/viewer/Demo_3D_Repo/2e30c430-4308-11ec-80ea-2de55b1b3ca1)
- Open Smart Groups Card
- Import groups (recently exported JSON)

### Current Behaviour
- Fails to import "Request failed with status code 400"

### Expected Behaviour
-  Import Groups

### Pictures/ Gifs of the error

[Smart Groups JSON Export](https://github.com/3drepo/3drepo.io/files/7521789/Federation_11_11_2021_15_57_50_groups.zip)

**Groups to Export**
![Smart Groups Bug](https://user-images.githubusercontent.com/19904513/141332867-51272300-156f-4381-9c23-bee1962f12b6.jpg)

**Import Error**
![Smart Groups Bug 2](https://user-images.githubusercontent.com/19904513/141332883-80cda3c8-8922-4dfb-a6c0-6265a3eec382.jpg)

**3D Repo Error Message**
![Import Smart Groups](https://user-images.githubusercontent.com/19904513/141331840-4fe7b8fc-f803-4fd9-abf5-bc9b85a8eb6d.gif)

**Comment by carmenfan** [comment]
I'm 99.9% sure this is to do with legacy groups data having the wrong type. 

As a super quick fix if you need this working, if you look through the list of groups, you'll probably see a group  (or groups) that has a createdAt or updatedAt value that is a string isntead of a number. either do a API update to fix it, or just alter it by hand on the epxorted json  - it should work after.
