### ISSUE TITLE
[MONGODB DRIVER] Warning: Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2889]
### Description

Since the recent DB upgrades, I've seen this warning

`[MONGODB DRIVER] Warning: Top-level use of w, wtimeout, j, and fsync is deprecated. Use writeConcern instead.
`
### Goals
- [x] Warning shouldn't throw

### Tasks

- [x] Identify all use of  use of w, wtimeout, j, and fsync and update to current standards

**Comment by keifgwinn** [comment]
actually this is showing up as a problem when using a non-replicaset local database

"MongoError: cannot use non-majority 'w' mode 1 when a host is not a member of a replica set". I think answering the question of why invitations are creating index and if this writeConcern needs to exist at all?

**Comment by keifgwinn** [comment]
@carmenfan @sanmont3drepo

**Comment by carmenfan** [comment]
not sure if it's relevant, creating indices is quite a normal process that we do (probably more on bouncer than io), I just don't get why we are doing it everytime we do `getCollection`.

And why we'd need to specify write concern for this - as we don't specify write concern on any of our write actions to the database

**Comment by keifgwinn** [comment]
It seemed to be the only place in the codebase doing it

**Comment by carmenfan** [comment]
Ok, it exists in the[ metadata schema migration scripts](https://github.com/3drepo/3drepo.io/pull/2876/files#diff-61482841343a16b4fbf22175bad0beb4e3eaa962bc61156ecc05094bff5b5769R29) that's still in PR

And like I said, in [3drepobouncer](https://github.com/3drepo/3drepobouncer/blob/master/bouncer/src/repo/core/model/collection/repo_scene.cpp#L723)

But, my point, isn't whether we need to createIndex or not:

1. it's weird to create index on getCollection
2. We shouldn't need to specify special write concerns for index

**Comment by carmenfan** [comment]
> I think answering the question of why invitations are creating index and if this writeConcern needs to exist at all?

It makes sense to need indexing, though I question the place we're doing it. But since it's v4, I'm not too concerned as we'd rewrite it for v5 anyway.

I don't think we need the writeConcern - hence i tagged @sanmont3drepo originally - who didn't answer but since it wasn't that big of a deal I merged it anyway. If it's a problem then you could just try removing the write concern part and see if it affects the invitation feature - we do want to keep indexing it for effective queries.

**Comment by carmenfan** [comment]
@keifgwinn 

@sanmont3drepo said he doesn't remember why it's there. He said most likely it's due to a warning or error.

If it's causing problems then I suggest just outright remove it and see if it solves your problem - as logically I don't think it needs to exist.
