### ISSUE TITLE
SPM upload timezone selection

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2892]
### Description

Currently Synchro records all activity in UTC time, this means that when they are uploaded to 3D Repo the epoch times display incorrectly if a user is working outside of UTC or in a timezone which uses daylight savings.

This can be fixed by overriding the browser timezone sensor to UTC, but this is not a sustainable workflow

### Goals

- [x] Allow users to set the Timezone when uploading an SPM file
  - [x] Support 2 dropdowns in the user interface to first allow selection of the country, followed by the timezone (to avoid a long list of timezones) using this list or similar as a basis https://en.wikipedia.org/wiki/List_of_time_zones_by_country
    - We should be able to utilise something like this for the information https://www.npmjs.com/package/countries-and-timezones
  - [x] Set the default timezone when uploading via the 3D Repo UI to the users timezone as presented by the browser

- [x] add extra parameters on the model upload request to pass in timezone information
  - [x]  Use Timezone naming standards from tz database https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

### Related Resources
![image](https://user-images.githubusercontent.com/62879582/144903658-2767e555-3822-400b-8d16-39656aa537bd.png)

**Comment by keifgwinn** [comment]
deployed on staging
