### ISSUE TITLE
Review and cleanup

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepo.io#290]

**Comment by timscully1983** [comment]
Backend

- [ ] ./encoders/img_transcoder.js
- [ ] ./encoders/helper/googleMap.js
- [ ] ./encoders/helper/search.js
- [ ] ./encoders/src_encoder.js
- [ ] ./encoders/bin_encoder.js
- [ ] ./encoders/json_encoder.js
- [ ] ./encoders/img_encoder.js
- [ ] ./encoders/cache/pbf_cache.js
- [ ] ./encoders/html_encoder.js
- [ ] ./encoders/pbf_encoder.js
- [ ] ./encoders/x3dom_encoder.js
- [ ] ./encoders/gltf_encoder.js
- [ ] ./constants.js
- [ ] ./services/session.js
- [ ] ./services/chat.js
- [ ] ./services/queue.js
- [ ] ./services/frontend.js
- [ ] ./services/maintenance.js
- [ ] ./services/api.js
- [ ] ./db/db_interface.js
- [ ] ./db/db_schema.js
- [ ] ./db/db.js
- [ ] ./repo/repoNodeTransformation.js
- [ ] ./repo/repoGraphHistory.js
- [ ] ./repo/repoNodeMeta.js
- [ ] ./repo/repoGraphScene.js
- [ ] ./repo/repoNodeMesh.js
- [ ] ./repo/repoNodeMaterial.js
- [ ] ./repo/repoNodeCamera.js
- [ ] ./test/unit/mock/repoGraphScene.js
- [ ] ./test/unit/mock/utils.js
- [ ] ./test/unit/mock/db.js
- [ ] ./test/unit/models/vat.js
- [ ] ./test/unit/models/user.js
- [ ] ./test/unit/models/payment.js
- [ ] ./test/unit/models/projectSetting.js
- [ ] ./test/unit/models/texture.js
- [ ] ./test/unit/models/mesh.js
- [ ] ./test/cleanup/queue.js
- [ ] ./test/cleanup/db.js
- [ ] ./test/integrated/revision.js
- [ ] ./test/integrated/federation.js
- [ ] ./test/integrated/logout.js
- [ ] ./test/integrated/collaboration.js
- [ ] ./test/integrated/upload.js
- [ ] ./test/integrated/helpers.js
- [ ] ./test/integrated/model.js
- [ ] ./test/integrated/payment.js
- [ ] ./test/integrated/login.js
- [ ] ./test/integrated/project.js
- [ ] ./test/integrated/download.js
- [ ] ./test/integrated/contact.js
- [ ] ./test/integrated/issue.js
- [ ] ./test/integrated/price.js
- [ ] ./test/integrated/verification.js
- [ ] ./test/integrated/infrastructure.js
- [ ] ./test/integrated/updateInfo.js
- [ ] ./test/integrated/signup.js
- [ ] ./test/integrated/notification.js
- [ ] ./mailer/mailer.js
- [ ] ./mailer/templates/paymentSuspended.js
- [ ] ./mailer/templates/paymentFailed.js
- [ ] ./mailer/templates/projectImported.js
- [ ] ./mailer/templates/paymentReceived.js
- [ ] ./mailer/templates/invitedToProject.js
- [ ] ./mailer/templates/contact.js
- [ ] ./mailer/templates/forgotPassword.js
- [ ] ./mailer/templates/paymentRefunded.js
- [ ] ./mailer/templates/verifyUser.js
- [ ] ./mailer/templates/paymentError.js
- [ ] ./routes/history.js
- [ ] ./routes/routes.js
- [ ] ./routes/payment.js
- [ ] ./routes/project.js
- [ ] ./routes/routes_put.js
- [ ] ./routes/plan.js
- [ ] ./routes/bid.js
- [ ] ./routes/issue.js
- [ ] ./routes/routes_get.js
- [ ] ./routes/texture.js
- [ ] ./routes/middlewares.js
- [ ] ./routes/mesh.js
- [ ] ./routes/routes_post.js
- [ ] ./routes/projectPackage.js
- [ ] ./routes/testHelper.js
- [ ] ./routes/group.js
- [ ] ./routes/auth.js
- [ ] ./routes/osBuilding.js
- [ ] ./config.js
- [ ] ./response_codes.js
- [ ] ./utils.js
- [ ] ./libs/generateObj.js
- [ ] ./libs/generateMeshes.js
- [ ] ./libs/httpsReq.js
- [ ] ./libs/buildQueryString.js
- [ ] ./libs/generateglTF.js
- [ ] ./libs/OSGet.js
- [ ] ./libs/normalVec.js
- [ ] ./models/vat.js
- [ ] ./models/history.js
- [ ] ./models/addressMeta.js
- [ ] ./models/user.js
- [ ] ./models/helper/project.js
- [ ] ./models/helper/stash.js
- [ ] ./models/payment.js
- [ ] ./models/repo.js
- [ ] ./models/role.js
- [ ] ./models/stash3DRepo.js
- [ ] ./models/projectSetting.js
- [ ] ./models/templates/html/termsAndConds.js
- [ ] ./models/chatEvent.js
- [ ] ./models/unit.js
- [ ] ./models/bid.js
- [ ] ./models/issue.js
- [ ] ./models/texture.js
- [ ] ./models/subscription.js
- [ ] ./models/billing.js
- [ ] ./models/mesh.js
- [ ] ./models/factory/modelFactory.js
- [ ] ./models/sharedSchemas/termsAndConds.js
- [ ] ./models/projectPackage.js
- [ ] ./models/group.js
- [ ] ./models/counter.js
- [ ] ./models/ref.js
- [ ] ./models/base/repo.js
- [ ] ./models/scene.js
- [ ] ./logger.js

Frontend

- [ ] ./billing/js/billingDirective.js
- [ ] ./login/js/loginDirective.js
- [ ] ./tree/js/treeDirective.js
- [ ] ./tree/js/treeService.js
- [ ] ./revisions/js/revisionsService.js
- [ ] ./revisions/js/revisionsDirective.js
- [ ] ./cookies/js/cookiesDirective.js
- [ ] ./signUp/js/signUpDirective.js
- [ ] ./signUp/js/signUpFormDirective.js
- [ ] ./utils/js/utilsService.js
- [ ] ./utils/js/utilsDirectives.js
- [ ] ./utils/js/colourPickerDirective.js
- [ ] ./utils/js/utilsFilters.js
- [ ] ./utils/js/progressDirective.js
- [ ] ./bid4freeWorkspace/js/bid4freeWorkspaceDirective.js
- [ ] ./panel/js/panelCardOptionPrintDirective.js
- [ ] ./panel/js/panelDirective.js
- [ ] ./panel/js/panelCardOptionVisibleDirective.js
- [ ] ./panel/js/panelCardFilterDirective.js
- [ ] ./panel/js/panelCardDirective.js
- [ ] ./panel/js/panelCardOptionCloseDirective.js
- [ ] ./panel/js/panelCardOptionEraseDirective.js
- [ ] ./panel/js/panelCardAddDirective.js
- [ ] ./panel/js/panelCardOptionPinDirective.js
- [ ] ./panel/js/panelCardOptionAddDirective.js
- [ ] ./panel/js/panelCardOptionScribbleDirective.js
- [ ] ./panel/js/panelCardOptionMenuDirective.js
- [ ] ./panel/js/panelCardOptionFilterDirective.js
- [ ] ./issues/js/issueDirective.js
- [ ] ./issues/js/issueAreaDirective.js
- [ ] ./issues/js/issuesDirective.js
- [ ] ./issues/js/issueScreenShotComponent.js
- [ ] ./issues/js/issuePinComponent.js
- [ ] ./issues/js/issuesListComponent.js
- [ ] ./issues/js/issuesService.js
- [ ] ./issues/js/issueComponent.js
- [ ] ./terms/js/termsDirective.js
- [ ] ./measure/js/measureDirective.js
- [ ] ./clip/js/clipDirective.js
- [ ] ./account/js/accountLicensesDirective.js
- [ ] ./account/js/accountDirective.js
- [ ] ./account/js/accountProjectDirective.js
- [ ] ./account/js/accountService.js
- [ ] ./account/js/accountMenuDirective.js
- [ ] ./account/js/accountProfileDirective.js
- [ ] ./account/js/accountBillingDirective.js
- [ ] ./account/js/accountInfoDirective.js
- [ ] ./account/js/accountProjectsettingDirective.js
- [ ] ./account/js/accountTeamDirective.js
- [ ] ./account/js/accountReposDirective.js
- [ ] ./account/js/accountFederationsDirective.js
- [ ] ./account/js/accountProjectsDirective.js
- [ ] ./rightPanel/js/rightPanelDirective.js
- [ ] ./oculus/js/oculus.js
- [ ] ./registerRequest/js/registerRequestDirective.js
- [ ] ./registerVerify/js/registerVerifyDirective.js
- [ ] ./contact/js/contactDirective.js
- [ ] ./privacy/js/privacyDirective.js
- [ ] ./payment/js/paymentDirective.js
- [ ] ./bid4free/js/bidProjectSummaryDirective.js
- [ ] ./bid4free/js/bidSummaryDirective.js
- [ ] ./bid4free/js/bidService.js
- [ ] ./bid4free/js/bidDocsDirective.js
- [ ] ./bid4free/js/bidWorkspaceDirective.js
- [ ] ./bid4free/js/bid4freeDirective.js
- [ ] ./bid4free/js/bidStatusDirective.js
- [ ] ./bid4free/js/bidListDirective.js
- [ ] ./bid4free/js/bidImageDirective.js
- [ ] ./passwordChange/js/passwordChangeDirective.js
- [ ] ./pricing/js/pricingDirective.js
- [ ] ./walkthroughVr/VRDemoCtrl.js
- [ ] ./home/js/controlinterface.js
- [ ] ./home/js/StateManager.js
- [ ] ./home/js/notificationService.js
- [ ] ./home/js/autoLoginDirective.js
- [ ] ./home/js/Auth.js
- [ ] ./home/js/homeDirective.js
- [ ] ./home/js/serverConfig.js
- [ ] ./home/js/httpService.js
- [ ] ./home/js/httpProvider.js
- [ ] ./bottomButtons/js/compassDirective.js
- [ ] ./bottomButtons/js/bottomButtonsDirective.js
- [ ] ./groups/js/groupsDirective.js
- [ ] ./groups/js/groupsService.js
- [ ] ./passwordForgot/js/passwordForgotDirective.js
- [ ] ./docs/js/docsDirective.js
- [ ] ./docs/js/docsService.js
- [ ] ./walkthrough/walkthroughDirective.js
- [ ] ./walkthrough/WalkthroughService.js
- [ ] ./project/js/threed/logo.js
- [ ] ./project/js/threed/pin.js
- [ ] ./project/js/threed/measureTool.js
- [ ] ./project/js/threed/gamepad.js
- [ ] ./project/js/threed/viewer.js
- [ ] ./project/js/threed/pinShader.js
- [ ] ./project/js/threed/mapTile.js
- [ ] ./project/js/threed/viewermanager.js
- [ ] ./project/js/threed/clipplane.js
- [ ] ./project/js/threed/collision.js
- [ ] ./project/js/threed/viewerutil.js
- [ ] ./project/js/eventService.js
- [ ] ./project/js/viewerDirective.js
- [ ] ./project/js/projectDirective.js
- [ ] ./project/js/projectService.js
- [ ] ./project/js/viewerManagerDirective.js
- [ ] ./project/js/globalDirective.js
- [ ] ./project/js/multiSelectComponent.js
- [ ] ./building/js/buildingDirective.js

Other 

- [ ] 3drepo.js
- [ ] postinstall.js

**Comment by timscully1983** [comment]
- [ ] Remove old code
- [ ] Remove all of B4F stuff
- [ ] Cleanup duplicates in mesh.js

**Comment by thenrikie** [comment]
estimated at least two more days is need for complete re-factoring of payments.
Will continue to work on that next week. 
DB migration scripts will be in here  https://github.com/3drepo/3drepo.io/tree/ISSUE_290/scripts/db_migrations/v1.7
