### ISSUE TITLE
Schema change to model settings 

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#2900]
### Description
There has been a slight change to the model settings schema in V5. We no longer want `type` in Federations, thus we need to make the necessary changes in the backend code to adjust.

### Goals
- Containers should remain the same as before
- Federations:
  - should not take in a `type` on new federation/update federation endpoints
  - federation stats should not return `category` or `type`, but return `desc` instead (Can we also make sure Containers is also returning `desc`

### Tasks
to be filled in by the developer

**Comment by mosment3DRepo** [comment]
@carmenfan just checked the V5 swagger and I think this is done, can we close?
