### ISSUE TITLE
Teamspace Settings not found Error message

### ISSUE THREAD

**Issue by BDavydov** [3drepo/3drepo.io#2921]
### Description

I am trying to access another user's Teamspace settings. However, an error message pops up, leaving me unable to make any changes. The account with this error message has signed up 5 years ago.

- This is happening in: prod
- This requires a hotfix to production: no 

### Steps to replicate
- Login to support account
- Access the teamspace settings for username: **cgarrick**
- An error message will appear

### Current Behaviour
- Error message appears and I can't do anything

### Expected Behaviour
- Open the teamspace settings menu for Issues/Risks types list and Safetibase CSV

### Pictures/ Gifs of the error
![Teamspace Settings Menu](https://user-images.githubusercontent.com/19904513/146937403-ee213733-8e3b-4c20-8c19-f937faee0d3a.gif)

**Comment by BDavydov** [comment]
https://github.com/3drepo/3drepo.io/issues/2589

**Comment by carmenfan** [comment]
closing this as it's a duplicate.
