### ISSUE TITLE
Logging out doesn't always work

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#2922]
### Description

Sometimes when logging out you can get back to the teamspace view without logging back in

It also prevents you from logging in to a new account, telling you that you are already logged in

- This is happening in: prod
- This requires a hotfix to production: depends

### Steps to replicate
- Login to 3DRepo
- Logout
- Go back to https://www.3drepo.io/dashboard/teamspaces
- Notice you are still logged in

### Current Behaviour
- Logout doesn't seem permanent

### Expected Behaviour
- Logging out should not allow you to gain access again

### Pictures/ Gifs

https://user-images.githubusercontent.com/62879582/147132906-08cc0199-4076-4509-b536-dd69a6187f17.mp4

 of the error

**Comment by carmenfan** [comment]
@mosment3DRepo i can't reproduce this. I'm guessing this might be a caching/race condition behaviour

There's also probably not that high of security risk as the session is terminated on the backend, so if the user tries to do anything it should fail. If we are moving towards v5 login page soon ish then maybe it's not worth fixing

**Comment by mosment3DRepo** [comment]
@carmenfan I think this has something to do with having more than one tab open and the logout from one not propagating to the others.

It also seems as though logging to an account doesn't kick other instances of that account out, eg. Mia and I were both able to have the support account open at the same time.

Could it be a socket.io problem?

**Comment by carmenfan** [comment]
closing this as it is not reproducible, and possible that #3006 or #3045 might've fixed the issue

reopen with reproducible steps if needed
