### ISSUE TITLE
Fix all OpenAPI warnings

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#2986]
### Description

There's a large number of warnings on the current definition

- This is happening in: staging 
- This requires a hotfix to production: no 

### Steps to replicate
- Open this link: https://staging.dev.3drepo.io/docs/openapi.json
- Import the JSON to https://editor.swagger.io/
- review errors

### Current Behaviour
- Show's a number of errors
 
### Expected Behaviour
- no warnings should be thrown.

### Tasks
- [x] Clean up all errors
- [x] Add error check on end point test

**Comment by keifgwinn** [comment]
Current error list

Structural error at 
should NOT have additional properties
additionalProperty: basePath
Jump to line 0
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers.post.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 18
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers.post.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 25
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers.get.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 119
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers.get.parameters.1
should NOT have additional properties
additionalProperty: project, type
Jump to line 126
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers.get.parameters.1.schema
should be object
Jump to line 131
Semantic error at paths./teamspaces/{teamspace}/projects/{project}/containers.get.responses.200.content.application/json.schema.properties.containers.items.properties.role.$ref
$refs must reference a valid location in the document
Jump to line 155
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/stats.get.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 170
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/stats.get.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 177
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/stats.get.parameters.2
should NOT have additional properties
additionalProperty: container
Jump to line 184
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/favourites.patch.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 251
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/favourites.patch.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 258
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/favourites.delete.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 289
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/favourites.delete.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 296
Semantic error at paths./teamspaces/{teamspace}/projects/{project}/containers/favourites.delete.requestBody
DELETE operations cannot have a requestBody.
Jump to line 303
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.delete.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 328
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.delete.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 335
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.delete.parameters.2
should NOT have additional properties
additionalProperty: container
Jump to line 342
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.patch.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 362
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.patch.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 369
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.patch.parameters.2
should NOT have additional properties
additionalProperty: container
Jump to line 376
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.patch.requestBody.content.application/json.schema.properties.name.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 390
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.patch.requestBody.content.application/json.schema.properties.desc.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 393
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.patch.requestBody.content.application/json.schema.properties.type.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 396
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.get.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 440
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.get.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 447
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}.get.parameters.2
should NOT have additional properties
additionalProperty: container
Jump to line 454
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/export.post
should NOT have additional properties
additionalProperty: links
Jump to line 473
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/export.post.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 479
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/export.post.parameters.1
should NOT have additional properties
additionalProperty: project, type
Jump to line 486
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/export.post.parameters.1.schema
should be object
Jump to line 491
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/export.post.parameters.2
should NOT have additional properties
additionalProperty: container, type
Jump to line 493
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/export.post.parameters.2.schema
should be object
Jump to line 498
Semantic error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/export.post.responses.404.$ref
$refs must reference a valid location in the document
Jump to line 524
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/import.post.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 537
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/import.post.parameters.1
should NOT have additional properties
additionalProperty: project, type
Jump to line 544
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/import.post.parameters.1.schema
should be object
Jump to line 549
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/import.post.parameters.2
should NOT have additional properties
additionalProperty: container, type
Jump to line 551
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/groups/import.post.parameters.2.schema
should be object
Jump to line 556
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.get.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 585
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.get.parameters.1
should NOT have additional properties
additionalProperty: project, type
Jump to line 592
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.get.parameters.1.schema
should be object
Jump to line 597
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.get.parameters.2
should NOT have additional properties
additionalProperty: container, type
Jump to line 599
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.get.parameters.2.schema
should be object
Jump to line 604
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.get.parameters.3
should NOT have additional properties
additionalProperty: showVoid, type
Jump to line 606
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.get.parameters.3.schema
should be object
Jump to line 611
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.post.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 648
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.post.parameters.1
should NOT have additional properties
additionalProperty: project, type
Jump to line 655
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.post.parameters.1.schema
should be object
Jump to line 660
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.post.parameters.2
should NOT have additional properties
additionalProperty: container, type
Jump to line 662
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.post.parameters.2.schema
should be object
Jump to line 667
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions.post.requestBody.content.multipart/form-data.schema.properties.importAnimations.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 684
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions/{revision}.patch.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 706
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions/{revision}.patch.parameters.1
should NOT have additional properties
additionalProperty: project, type
Jump to line 713
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions/{revision}.patch.parameters.1.schema
should be object
Jump to line 718
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions/{revision}.patch.parameters.2
should NOT have additional properties
additionalProperty: container, type
Jump to line 720
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions/{revision}.patch.parameters.2.schema
should be object
Jump to line 725
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions/{revision}.patch.parameters.3
should NOT have additional properties
additionalProperty: revision, type
Jump to line 727
Structural error at paths./teamspaces/{teamspace}/projects/{project}/containers/{container}/revisions/{revision}.patch.parameters.3.schema
should be object
Jump to line 732
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations.post.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 758
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations.post.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 765
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations.get.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 859
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations.get.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 866
Semantic error at paths./teamspaces/{teamspace}/projects/{project}/federations.get.responses.200.content.application/json.schema.properties.federations.items.properties.role.$ref
$refs must reference a valid location in the document
Jump to line 895
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/favourites.patch.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 910
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/favourites.patch.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 917
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/favourites.delete.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 948
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/favourites.delete.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 955
Semantic error at paths./teamspaces/{teamspace}/projects/{project}/federations/favourites.delete.requestBody
DELETE operations cannot have a requestBody.
Jump to line 962
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/stats.get.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 987
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/stats.get.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 994
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/stats.get.parameters.2
should NOT have additional properties
additionalProperty: federation
Jump to line 1001
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.delete.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 1058
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.delete.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 1065
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.delete.parameters.2
should NOT have additional properties
additionalProperty: federation
Jump to line 1072
Semantic error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.patch.operationId
Operations must have unique operationIds.
Jump to line 1090
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.patch.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 1092
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.patch.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 1099
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.patch.parameters.2
should NOT have additional properties
additionalProperty: federation
Jump to line 1106
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.patch.requestBody.content.application/json.schema.properties.name.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 1120
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.patch.requestBody.content.application/json.schema.properties.desc.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 1123
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.patch.requestBody.content.application/json.schema.properties.type.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 1126
Semantic error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.get.operationId
Operations must have unique operationIds.
Jump to line 1174
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.get.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 1176
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.get.parameters.1
should NOT have additional properties
additionalProperty: project
Jump to line 1183
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}.get.parameters.2
should NOT have additional properties
additionalProperty: federation
Jump to line 1190
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/export.post
should NOT have additional properties
additionalProperty: links
Jump to line 1209
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/export.post.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 1215
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/export.post.parameters.1
should NOT have additional properties
additionalProperty: project, type
Jump to line 1222
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/export.post.parameters.1.schema
should be object
Jump to line 1227
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/export.post.parameters.2
should NOT have additional properties
additionalProperty: federation, type
Jump to line 1229
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/export.post.parameters.2.schema
should be object
Jump to line 1234
Semantic error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/export.post.responses.404.$ref
$refs must reference a valid location in the document
Jump to line 1260
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/import.post.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 1273
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/import.post.parameters.1
should NOT have additional properties
additionalProperty: project, type
Jump to line 1280
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/import.post.parameters.1.schema
should be object
Jump to line 1285
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/import.post.parameters.2
should NOT have additional properties
additionalProperty: federation, type
Jump to line 1287
Structural error at paths./teamspaces/{teamspace}/projects/{project}/federations/{federation}/groups/import.post.parameters.2.schema
should be object
Jump to line 1292
Structural error at paths./teamspaces/{teamspace}/projects.get.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 1321
Structural error at paths./teamspaces/{teamspace}/members.get.parameters.0
should NOT have additional properties
additionalProperty: teamspace
Jump to line 1389
Structural error at components.schemas.group.properties.createdAt.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 2159
Structural error at components.schemas.group.properties.updatedAt.type
should be equal to one of the allowed values
allowedValues: array, boolean, integer, number, object, string
Jump to line 2163

**Comment by carmenfan** [comment]
probably worth adding a test on v5 to just validate the json,  with something like this: https://www.npmjs.com/package/openapi-schema-validator

So we avoid introducing any errors/warnings in the future
