### ISSUE TITLE
Group/Smart group message pops up when clicking twice on Save button 

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#3006]
### Description
Group/Smart group message pops up when clicking twice on Save button 
- This is happening in: prod
- This requires a hotfix to production: no

### Steps to replicate
- Open any model in 3D Repo
- Open the groups card
- Create a group or edit an existing group (or smart group) 
- Click on save button twice in a row (some users accidentally click more than once) 

### Current Behaviour
- Message 'This group has been updated by someone else' appears. Some users find it annoying. 

### Expected Behaviour
Group isn't updated by someone else. This message is misleading and affects overall UX of groups creation and should not appear in the UI. 

### Pictures/ Gifs of the error
![image002](https://user-images.githubusercontent.com/56918163/152797704-8c8d9642-7318-4053-8cea-95da6d409cdc.png)
![groups message](https://user-images.githubusercontent.com/56918163/152797899-995665d6-90ef-4011-b311-2ba6f800a19f.JPG)

**Comment by carmenfan** [comment]
I think the issue is - the user shouldn't be able to click on the save button twice. On the 2nd time, nothing has changed.
