### ISSUE TITLE
Add download icon to V5 containers list

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3012]
### Description

Once we have an endpoint for downloading container revisions - https://github.com/3drepo/3drepo.io/issues/2997 (V4 only lets you download the latest revision), we will need to add a download icon to all of the revisions in the container

### Goals

- [ ] Clearly show the user that they can download models per revision

### Related Resources
https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=2242%3A25187

**Comment by mosment3DRepo** [comment]
@sanmont3drepo is this closed with https://github.com/3drepo/3drepo.io/pull/3148 ?

**Comment by carmenfan** [comment]
yup, looks like a duplication of #3075
