### ISSUE TITLE
Improve the logic behind circleButton and apply it across v5

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3044]
### Description
- The circleButton control is currently coded quite messily
    - There's lots of weird CSS specificity
    - It uses [MUI Fab](https://mui.com/api/fab/) when it should probably just use a [MUI Button](https://mui.com/api/button/)
- There are a few places in the app that have circular buttons but do not use the circleButton control. The logic behind these buttons is confusing and split between multiple components

### Goals
- Have a more versatile circleButton control

### Tasks
- Make a circle button that uses MUI Button
- Create the different variants for its multiple uses [1]
- Apply the new circleButton to places where circular buttons are used but do not currently use the circleButton control (e.g. the favourite and elipses icons in dashboard list items)

[1] Perhaps...
**Main**:    white button like that used for favourites button in dashboard lists
**Contrast**:    Dark blue button like that used by the favourites button when the list item is selected
**ContrastBordered/Navbar**:    Dark blue with white outline like that used for the "?" and "Bell" icons in the nav bar

**Comment by Amantini1997** [comment]
These changes are being addressed as part of #3778 (PR https://github.com/3drepo/3drepo.io/pull/3783)
