### ISSUE TITLE
4.22.0 QA Bugs List

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#3059]
This list is related to Issue 3034 [https://github.com/3drepo/3drepo.io/issues/3034](url)

### Bugs
- [ ] [1. Model Container fails to be deleted](https://github.com/3drepo/3drepo.io/issues/3059#issuecomment-1047099374)
- [ ] [2. Map tiles are not running](https://github.com/3drepo/3drepo.io/issues/3059#issuecomment-1047109036)

**Comment by miadibe** [comment]
### Description
Cannot delete model container. Delete model warning message shows up but after clicking on YES, throws Error message: _System error. Please try again later. (Status Code: 500)_
This is not the case with federation containers which we can delete

### Steps to replicate
- Create a new model container and delete it
- Or hover over an existing model container to click on the delete icon
- Click yes when the warning message appears and check the error 

### Current Behaviour
- 'Something went wrong trying to remove the model'

### Expected Behaviour
- User should be able to delete any model container, new, existing, and with/without revisions. 

### Pictures/ Gifs of the error
![error delete model](https://user-images.githubusercontent.com/56918163/155002667-e18d0c4d-ee18-4259-aaee-e53593e63c6c.JPG)

**Comment by miadibe** [comment]
### 2. Map tiles are not running
Map tiles do not show when clicking on the show button 

### Steps to replicate
- Open a model with GIS coordinates
- Pick any map provider and click on the eye button to show tiles
- Click yes when the warning message appears and check the error 

### Current Behaviour
- Map tiles do not show. Consequently 

### Expected Behaviour
- Map tiles visibility show/hide should work as expected and user should be able to close GIS card and keep the map tiles running

**Comment by keifgwinn** [comment]
> ### 2. Map tiles are not running
> Map tiles do not show when clicking on the show button
> 
> ### Steps to replicate
> * Open a model with GIS coordinates
> * Pick any map provider and click on the eye button to show tiles
> * Click yes when the warning message appears and check the error
> 
> ### Current Behaviour
> * Map tiles do not show. Consequently
> 
> ### Expected Behaviour
> * Map tiles visibility show/hide should work as expected and user should be able to close GIS card and keep the map tiles running

I can see the backend is getting the images correctly, but there's an issue with the drawing of the tiles
<img width="1762" alt="image" src="https://user-images.githubusercontent.com/23369849/155130545-75eb4233-c19e-4e34-b864-e5c970ab9c70.png">
<img width="1864" alt="image" src="https://user-images.githubusercontent.com/23369849/155130681-1fb24464-e25f-4828-b6e8-c2b1783a72f7.png">

**Comment by carmenfan** [comment]
@miadibe  can you post any bugs you found here: 
https://github.com/3drepo/3drepo.io/pull/3035

We've changed the process a bit so it's now a Pull request - so any bugs should be posted there and will be addressed in that branch.

I've added the links to the existing bugs on the top of the PR, closing this.
