### ISSUE TITLE
User Permissions sending empty value

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3092]
### Description

When inviting a user to a project and assigning permissions, adding permissions to a user and then removing them before saving adds the following value to the API request:

`permission: ""`

This is then rejected by the API as it is not a valid value

- This is happening in: prod 
- This requires a hotfix to production: yes

### Steps to replicate
- Invite a new user to a project with specific model settings
- Change a model permission to Viewer before changing it back to unassigned
- Notice you get an error message

### Video

https://user-images.githubusercontent.com/62879582/156802963-de72a1a4-163b-4b34-a094-a5ad296e2254.mp4

**Comment by carmenfan** [comment]
fixing in #3104
