### ISSUE TITLE
Resolve dependabot alerts

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3095]
### Description

There are a number of high severity security alerts come through on dependabot, that could use package upgrades to resolve.

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Review dependabot alerts

### Expected Behaviour
- All alerts to be resolved through upgrades or confirming code not in use.

### Pictures/ Gifs of the error
<img width="202" alt="image" src="https://user-images.githubusercontent.com/23369849/157227844-f41c661f-7861-483e-b0b6-2ee258023ed1.png">

**Comment by carmenfan** [comment]
in favour of #3133
