### ISSUE TITLE
Get array of metadata fields not getting all fields (Smart Groups)

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3103]
### Description

Smart Groups is not getting all of the available meta data keys when setting a new rule. This means it is not possible to capture certain properties with Smart Groups. 

- This is happening in: both 
- This requires a hotfix to production: tbd 

### Steps to replicate
- Open this model using the support account: https://www.3drepo.io/viewer/mid_group/362fc9b0-f5fb-11eb-bb31-991b95af3ce5
- Open the BIM Card and select any element
- Look for a nested property eg. **General::AssetType**
- Create a new smart group
- Notice **General::AsssetType** is not available for selection
- Query the meta keys API: https://www.3drepo.io/api/mid_group/362fc9b0-f5fb-11eb-bb31-991b95af3ce5/meta/keys
- Notice there are no nested properties in the list, many of the keys for this model are missing

### Current Behaviour
- Not all meta data keys are being displayed in the groups card

### Expected Behaviour
- I should be able to select any of the metadata keys used in the BIM Card from the Smart Groups feature

### Pictures/ Gifs of the error
Parameter in the BIM Card
![image](https://user-images.githubusercontent.com/62879582/158183911-195f04dc-c9a7-4f76-a8c9-7e40d9ba8fdf.png)

Not available in groups
![image](https://user-images.githubusercontent.com/62879582/158183927-f4f6fa16-d619-4faf-ab0e-5b7c0056c361.png)

**Comment by carmenfan** [comment]
@mosment3DRepo has retested on staging (as of 4.23.1), seems like the metadata schema revamp has fixed it as the query was rewritten.

Closing. Reopen if we found another case where it's broken.
