### ISSUE TITLE
1.7 bug fix (iteration 2)

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#311]
**Henry:**
(Let me know if you want me to look into some of these -- Carmen)
- [x] User should not be able to assign issue to read only roles
- [x] Comment with screen shot -> change status of issue is making the screenshot disappear
- [x] Read only user should have the save button greyed out, with a message saying you do not have permissions to comment
- [x] Create issue button should be greyed out for read only users
- [x] Chat server: issue list of a fed project is not listening changes for issue from a sub project
- [x] Turn issue save button into a spinning icon to avoid users double click it
- [x] potential web socket problem. sessions of two tab with same id, one of the tab will fire message back to itself causing double issue/comments

**Carmen:**
- [x] If there is a screenshot with the comment, the viewpoint should be saved at the point of screen shot, not at the point of saved button
- [x] The model is highlighted at the point of load (for some models)
- [x] Revit house model - clicking on the grass turf highlights the transformation instead of the geometry (note: Won't fix - this is caused by the geometry being tagged on IFCSite, hence the entire site is being selected)
- [x] Uploading to an existing project - No indication that the file is accepted and ready when the the selected file is accepted. (new project with file is fine however)
- [x] create new project -> upload a valid file -> upload an invalid file -> "Selected File" should disappear but it still stayed there
- [x] create a new project -> upload a valid file -> upload an invalid file  : should yield an error message about the invalid file, but it should still let the user save the project without any uploads
- [x] File extension in caps are flagged as format not supported even though it's the right format
- [x] Bouncer crashing is causing an undefined value being returned , which is interpreted as success (see https://github.com/3drepo/3drepobouncer/issues/179)
- [x] Missing Nodes is being interpreted as Unknown Error
- [x] Collada imports are crashing the bouncerClient (see bouncer issue: https://github.com/3drepo/3drepobouncer/issues/180)
- [x] move select file message of upload to the bottom

**Comment by timscully1983** [comment]
- [ ] Fix for scrolling on tree
