### ISSUE TITLE
UI Oddities in staging

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3143]
### Description

A few UI oddities have sprung up on staging recently (last week or so)

- [ ] [Contents of view card wider than card](https://github.com/3drepo/3drepo.io/issues/3143#issuecomment-1090332675)
- [ ] [Sequence Date is very small](https://github.com/3drepo/3drepo.io/issues/3143#issuecomment-1090334880)

- This is happening in: staging 
- This requires a hotfix to production: fix before release

**Comment by mosment3DRepo** [comment]
**Sequence Date is very small**

### Steps to replicate
- Open a model with a sequence in  (https://staging.dev.3drepo.io/viewer/mosment3ddev/977422b0-94a8-11ec-8f3b-1fbc8a49d7ad)
- Open the Sequence
- Notice the date is too small compared to prod

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62879582/161997600-a6081b23-a9ca-4e31-b7f8-572545d32901.png)

**Comment by sanmont3drepo** [comment]
@mosment3DRepo  my guess is that it probably has to do with the material ui upgrade.
