### ISSUE TITLE
Viewer facelift - Dialog modals

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3166]
### Description
The styles of the dialog modals in v4  is very different to the one in v5. We need to style the ones in the viewer to fit the style in v5.

### Goals
- [ ]  To have a dialog modal that fit in v5

### Tasks
- [ ] Style the dialog

### Related Resources
![image](https://user-images.githubusercontent.com/42032433/163483204-ec7b89f0-4103-4261-9383-dc2973d72dfc.png)

**Comment by george-hadfield** [comment]
@Amantini1997 could this not use the standard error modal design?

<img width="859" alt="image" src="https://user-images.githubusercontent.com/78047794/165315848-c910e5f4-f00e-4363-8b9d-587e17c5353a.png">

**Comment by Amantini1997** [comment]
> @Amantini1997 could this not use the standard error modal design?
> 
> <img alt="image" width="859" src="https://user-images.githubusercontent.com/78047794/165315848-c910e5f4-f00e-4363-8b9d-587e17c5353a.png">

I will try

**Comment by carmenfan** [comment]
Merged into #3168
