### ISSUE TITLE
drop pin, measure tool not working after using new version x3dom

### ISSUE THREAD

**Issue by thenrikie** [3drepo/3drepo.io#320]
Every feature depending on the value of VIEWER_PICK_POINT event will not work because after switching to lateset version of X3DOM, the values of position and normal are always null.

**Comment by carmenfan** [comment]
I've reverted back to using https://github.com/3drepo/x3dom/commit/a8944e33499b6fb7d7d20b48e1a353c7111b448c on dev/staging as anything above that was unstable. (there was a conflict on one of the merges hence i pushed it to use head)

**Comment by thenrikie** [comment]
both 3drepo/x3dom@a8944e3  or master are not working for pick_point as well

**Comment by thenrikie** [comment]
just checked actually pick_point stop working in the previous version 1.9.3, 1.9.2 still works
