### ISSUE TITLE
You can upload files to containers that are being processed

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3216]
### Description
When a container is being processed or queued, the ui allows to upload a new 

- This is happening in: prod/staging/both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- Navigate to a containers route
- Upload a new revision
- Refresh

### Current Behaviour
- It allows the user to upload a new revision straight away

### Expected Behaviour
- The interface should forbid the user to upload a new revision while is processing or queued

Like in v4:
![image](https://user-images.githubusercontent.com/42032433/167469289-2d4b56e6-9c14-4af1-ac79-af91872b7d60.png)

**Comment by george-hadfield** [comment]
Is this v4 or v5 related?
