### ISSUE TITLE
Viewer Facelift - V4 viewer crashes when viewing issues

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3218]
### Description
- This bug is a result of ISSUE #3171 and exists on the base branch #3168
- There is one line of code which doesn't check whether it is/isn't V5

### Steps to replicate
- Open the v4 viewer and click the 'Issues' button

### Current Behaviour
- Crash

### Expected Behaviour
- The Issues window opens without a crash

**Comment by carmenfan** [comment]
Merged into #3168
