### ISSUE TITLE
Viewer facelift - Bim Card

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3225]
### Description
We need to revamp the BIM card to match v5 styles

### Goals
- [ ] To have the BIM card styled like v5 

### Tasks
- [ ] Just follow the styles in the mockup

### Related Resources
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136292%3A177725)

**Comment by carmenfan** [comment]
Merged into #3168
