### ISSUE TITLE
Viewer facelift - Views Card

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3235]
### Description
We need to revamp the Views card to match v5 styles

### Goals
- [ ] To have the Views card styled like v5 

### Tasks
- [ ] Just follow the styles in the mockup

### Related Resources
[MockUp](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=136292%3A177725)

**Comment by carmenfan** [comment]
merged into #3168
