### ISSUE TITLE
1.9 bug fixes

### ISSUE THREAD

**Issue by thenrikie** [3drepo/3drepo.io#324]
- [x] toy project report more error message
- [x] if operation to rename the stash fails then don't mark the toy project imported successfully
- [x] frontend show no error message if creating fed project with invalid project name 
- [x] issue page filter doesn't work for fed project

**Comment by thenrikie** [comment]
not sure why on dev mongoimport command stuck at 100% and never finishes, it is why toy project failed to import but without any error message generated

**Comment by timscully1983** [comment]
- [ ] Release tool throws a warning when compiling the webfont
