### ISSUE TITLE
### Text size and spacing in select menus is too big

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3drepo.io#3243]
### Text size and spacing in select menus is too big
This should match the style and sizing used in the ellipsis menus in Teamspace. The text also looks grey.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/78047794/168095777-ead1f99b-34ce-4aaf-bdbc-9a60bbc36a8f.png">

_Originally posted by @george-hadfield in https://github.com/3drepo/3drepo.io/issues/3238#issuecomment-1125049563_

**Comment by Amantini1997** [comment]
Merge into #3168
