### ISSUE TITLE
### Add 5px margin or padding above first date field

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3drepo.io#3244]
### Add 5px margin or padding above first date field
Just a tad too tight to the tabs

<img width="293" alt="image" src="https://user-images.githubusercontent.com/78047794/168094976-58c63428-d3bc-4af5-b8da-4c1f1837e06a.png">

_Originally posted by @george-hadfield in https://github.com/3drepo/3drepo.io/issues/3203#issuecomment-1125044303_

**Comment by Amantini1997** [comment]
Merge into #3168
