### ISSUE TITLE
### Change font weight in tab items to 500 from 400

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3drepo.io#3245]
### Change font weight in tab items to 500 from 400

<img width="333" alt="image" src="https://user-images.githubusercontent.com/78047794/168096286-0b05544d-fe2a-4716-af8f-53352457b517.png">

_Originally posted by @george-hadfield in https://github.com/3drepo/3drepo.io/issues/3238#issuecomment-1125052063_

**Comment by Amantini1997** [comment]
Merge into #3168
