### ISSUE TITLE
Groups: Disable download JSON/import/export for viewers

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#3250]
### Description
Disable the download JSON, Import/Export of Groups and smart groups for users with the viewer permission.
@mosment3DRepo for triage

### Goals
- [ ] Only collaborators/admins can create groups and manage groups (import/export)
- [ ] Viewers cannot download JSON

**Comment by carmenfan** [comment]
> Only collaborators/admins can create groups and manage groups (import/export)

Commenter should be able to do this as well (As it stands.) you will need to clarify if the intention is to remove them from group write privilege.

they shouldn't be able to import already (the UI might exist but it should fail with 401 error)

this doesn't make too much sense considering the read based API is valid for viewers, there's nothing stopping them from just calling the API

**Comment by AsiteZane** [comment]
Permissions are changing, to be within https://github.com/3drepo/3D-Repo-Product-Team/issues/355

This is therefore no longer needed and to be addressed in there.
