### ISSUE TITLE
Categorise groups and smart groups with a parent type group 

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#3251]
### Description
“Categorise” the smart groups with a parent type group that could be interrogated by PowerBI.
This helps producing a detailed set of model compliance check with a hierarchical way to organise the groups.
This ability to separate categories of smart groups by each use case is a customer's feature request. 

### Goals
@mosment3DRepo to define the scope. This is probably linked to an existing issue which I can't find so you can close this one out if you have the user stories stored already.

**Comment by mosment3DRepo** [comment]
https://github.com/3drepo/3drepo.io/issues/3021
