### ISSUE TITLE
Incorrect modal when creating screenshot

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3drepo.io#3261]
A confirmation modal is needed here rather than an error modal. I can provide design for this, but thought it was worth flagging.

v5 issue
<img width="816" alt="image" src="https://user-images.githubusercontent.com/78047794/168796548-141412a3-7c73-46be-bb72-5fbdc2ded3e1.png">

v4
<img width="447" alt="image" src="https://user-images.githubusercontent.com/78047794/168796892-5fc6f223-e29a-4fc9-b532-0634f048719f.png">

**Comment by sanmont3drepo** [comment]
This one was already been addressed
