### ISSUE TITLE
Viewer Facelift - Panels fixes

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3264]
### Description
Just a bunch of small tweaks to enhance the look and feel of the viewer.

### Tasks

- [x] right panel (BIM) has the wrong border-radius. It should match left panel one.
![image](https://user-images.githubusercontent.com/43547703/168856753-1d5b698d-372e-49e2-a5c6-d36c15e476c7.png)

- [x] search textfield has the wrong height.
![image](https://user-images.githubusercontent.com/43547703/168856879-aef16d80-e49a-4601-be60-6f2fba2c4885.png)

**Comment by carmenfan** [comment]
Merged into #3168
