### ISSUE TITLE
Entering a risk in v5 crashes the app

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3268]
### Description
Entering a risk in v5 crashes the app

- This is happening in: #3168 
- This requires a hotfix to production: no
- 
### Steps to replicate
- Enter a container/federation in v5 
- Click on a risk 

### Current Behaviour
- apps goes white

### Expected Behaviour
- Should show the  container/federation

**Comment by carmenfan** [comment]
Merged into #3168
