### ISSUE TITLE
Revamping - Scrollbars in Facelift

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3310]
### Description

Facelifted components in V5 are still using the default scrollbars rather than the updated versions from V5

### Goals

- [ ] Scrollbar parity across all 4.26 release

### Related Resources

![image](https://user-images.githubusercontent.com/62879582/170511891-9689170e-148a-45d4-8bac-4097ca0f7a5f.png)

**Comment by sanmont3drepo** [comment]
Do we want these type of scrollbars in v4?
