### ISSUE TITLE
TypeError: require(...).createApp is not a function

### ISSUE THREAD

**Issue by ojengwa** [3drepo/3drepo.io#332]
I am trying to run this with a docker container.

On inspecting the forever log, this is what I get...

`3drepo.js:128
						let app = require("./backend/services/" + serverConfig.service + ".js").createApp(serverConfig);
						                                                                        ^

TypeError: require(...).createApp is not a function
    at /path/to/3drepo.js:128:79
    at Object.<anonymous> (/~/~/app/3drepo.js:166:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
`

Any reasons why this is happening?

**Comment by thenrikie** [comment]
You may be using an old version. Try to use an version >= 1.10
Also make sure you have setup your configuration file correctly and start the app with correct config name.
Instructions can be found here 
https://github.com/3drepo/3drepo.io#configuration

**Comment by ojengwa** [comment]
Checked out the latest version (v1.1.0)

<img width="573" alt="screen shot 2017-03-02 at 10 10 18 pm" src="https://cloud.githubusercontent.com/assets/3935007/23527331/cd825d20-ff95-11e6-87e5-f9a741346680.png">

**Comment by thenrikie** [comment]
Should be 1.10.0 not v1.1.0

**Comment by ojengwa** [comment]
Will check and revert to you... :)

**Comment by ojengwa** [comment]
The version tag you gave does not exist...

<img width="1336" alt="screen shot 2017-03-03 at 12 26 32 pm" src="https://cloud.githubusercontent.com/assets/3935007/23549582/3676234e-000d-11e7-9ac0-164a84eab9c1.png">

**Comment by ojengwa** [comment]
Just found the 1.10.0 tag...

Going forward, can we be more consistent with naming conventions for release tags?

**Comment by thenrikie** [comment]
Sorry for the confusion. For all new releases we dropped the 'v'. If you go to this page https://github.com/3drepo/3drepo.io/releases you can see all the releases sorted by date

**Comment by ojengwa** [comment]
Thanks, @thenrikie. I will be checking the build and reverting to you if I have further challenges on this...

Veering off topic, I have been trying to build 3drepobouncer but I keep getting an ASSIMP_ROOT error. Would like to share screenshots but I don't have access to the project right now...

**Comment by carmenfan** [comment]
Hi @ojengwa , ASSIMP_ROOT is a environment variable telling the cmake where to find your assimp install. If it is complaining about it then it means cmake failed to find your assimp header/libraries.

Compilation instructions can be found here https://github.com/3drepo/3drepobouncer#compilation-windows , though it is slightly out of date as we now use IFCOpenShell as well, which means you will need to tell cmake where to find your IFCOpenshell and OCCT install.

**Comment by ojengwa** [comment]
@carmenfan: Thanks for the help.

I am trying to create a custom build for learning purposes...

Below are screenshots of my configurations...

<img width="856" alt="screen shot 2017-03-03 at 1 54 54 pm" src="https://cloud.githubusercontent.com/assets/3935007/23551978/cac4b4dc-0019-11e7-8124-0c522e28b3a4.png">
<img width="568" alt="screen shot 2017-03-03 at 1 55 57 pm" src="https://cloud.githubusercontent.com/assets/3935007/23551979/cac8660e-0019-11e7-9964-67da5e057a24.png">

Running on Docker.
I created an intermediary container and confirmed that assign was installed to the path specified above...

I will check the links you sent...

Regards

**Comment by carmenfan** [comment]
What does the cmake log say exactly? If it is successful it should dump out something on the lines of :

````
$ASSIMP_ROOT defined: C:\local\assimp_issue1
ASSIMP installation found.
ASSIMP_INCLUDE_DIR: C:/local/assimp_issue1/include
ASSIMP_LIBRARIES: debug;C:/local/assimp_issue1/lib/assimp-vc120-mtd.lib;optimized;C:/local/assimp_issue1/lib/assimp-vc120-mt.lib

````

**Comment by ojengwa** [comment]
Have been experiencing this error while running this in a dcker container...

<img width="560" alt="screen shot 2017-03-03 at 7 55 39 pm" src="https://cloud.githubusercontent.com/assets/3935007/23564737/71e21e7c-004b-11e7-935d-4a699ec4bd52.png">

**Comment by ojengwa** [comment]
@carmenfan Any ideas?

**Comment by carmenfan** [comment]
sounds to me it's failing to find the files stated (if you try to access those files separately does it work?). Most likely the post install script wasn't run or didn't run properly. This is quite commonly triggered by failing on the bower install step needing a human input, you may have to tweak the bower.json file.

**Comment by thenrikie** [comment]
looks like you forgot to run one of these commands

- Update submodules: git submodule update --init
- Install the required dependencies: npm install
- Install the client dependencies: bower install
- Compile the frontend: grunt

**Comment by ojengwa** [comment]
I already have these steps in my dockerfile...

<img width="862" alt="screen shot 2017-03-07 at 12 45 40 pm" src="https://cloud.githubusercontent.com/assets/3935007/23655126/1287f55a-0334-11e7-9b7c-d61f1f07c34e.png">

**Comment by carmenfan** [comment]
try running the post install script after bower install. 

As I suggested it's likely that you're missing those files in your public\js\external, which are symlinked within the post install stage.

As this isn't a bug or feature request I'm closing this thread. If you are interested in exploring 3D Repo's features please feel free to sign up for a free account. if you would like us to help you deploy 3D Repo for commercial purposes please contact us for an enterprise solution. http://3drepo.org/pricing/
