### ISSUE TITLE
Wrong due date in Risks PDF report

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#3336]
### Description
Creating a PDF risks report returns the wrong due date for all risks created in using the plugins. 
_Note that this is not the case when the risk is initially created in 3D Repo, where the PDF report shows the accurate due date._ 

- This is happening in: staging

### Steps to replicate
- Install plugins version found here: [ISSUE_356](https://www.dropbox.com/sh/itj4d6fjk8zo1ca/AACYKFlD6s7G_Rz7JAn7oyoMa?dl=0)
- Open any of the applications and the plugin Safetibase viewer. Create a risk and pick a due date
- Go to staging.dev.3drepo.io and create a pdf report in SafetiBase

### Current Behaviour
- Even though risk date is accurately shown in 3D Repo and the plugins, PDF report still shows wrong date (-1 day).

### Expected Behaviour
- PDF report should show the same due date as on 3D Repo and plugins

### Pictures/ Gifs of the error
![date2](https://user-images.githubusercontent.com/56918163/172405834-be04e557-6582-4336-9c1f-00bb224e0aaf.JPG)
![date1](https://user-images.githubusercontent.com/56918163/172405840-c7835f33-1354-4d79-b89a-fd3a30bd3fec.JPG)

**Comment by miadibe** [comment]
@carmenfan added here

**Comment by AsiteZane** [comment]
@carmenfan - is this still relevant given we're moving to custom tickets?

**Comment by carmenfan** [comment]
> @carmenfan - is this still relevant given we're moving to custom tickets?

depends on how we implement the custom tickets version. This is one of the reasons why I mentioned the report logic should live in the front end, so we can probe the user's localisation settings.

We could work around it by making the front end tell us what timezone the user is in, but front end would have more power such as displaying the date format in the way that is preferred by the user e.g.

**Comment by AsiteZane** [comment]
Consider this in https://github.com/3drepo/3D-Repo-Product-Team/issues/360

We will not be editing this as risks are going to be deprecated but we will need to consider when creating the alternative in custom tickets.
