### ISSUE TITLE
Description is not being fetched as a basic data for the federation

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3347]
### Description
When showing the federations list in v5 there is no description showing in spite the federation having a description. This is because the stats endpoint is not returning the federation's description.

- This is happening in: staging
- This requires a hotfix to production: no

### Steps to replicate
- Create a federation with a description
- Navigate to the federations page

### Current Behaviour
- The descrpition is not showing up
<img width="700" src="https://user-images.githubusercontent.com/42032433/176395481-4346963e-9840-42ab-b272-d13ca5e443c8.png" />

### Expected Behaviour
- The description should be visible (you can trigger this by editing the federation settings because it fetches the rest of the data)
<img width="700" src="https://user-images.githubusercontent.com/42032433/176395853-84af6476-0cf0-444f-86af-236fbc817af7.png" />

**Comment by carmenfan** [comment]
@sanmont3drepo  can you add a link to the model?

I can't replicate this from the lego house

![image](https://user-images.githubusercontent.com/11945337/176188779-5edf9055-646a-424a-bacf-7e4f85b1aa5a.png)

**Comment by sanmont3drepo** [comment]
> @sanmont3drepo can you add a link to the model?
> 
> I can't replicate this from the lego house
> 
> ![image](https://user-images.githubusercontent.com/11945337/176188779-5edf9055-646a-424a-bacf-7e4f85b1aa5a.png)

Oh sorry , my bad, I created this issue without filling in the details, the actual content of this issue is from the default template for bugs.

**Comment by sanmont3drepo** [comment]
Is not happening , maybe I was in an outdated branch
