### ISSUE TITLE
Hide elements which are not operational in 4.26

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3351]
### Description

Matt to create a list of elements which need to be hidden

### Goals
**Hide the following elements so they cannot be seen in 4.26:**

> **Navi Bar**
> 
> - [ ] Notification button
> - [ ] Help button
> ![image](https://user-images.githubusercontent.com/62879582/174646979-0e6819e4-f22a-4e92-ab6c-12f0ca01c2d7.png)
> 
> **Project View**
> - [ ] Tasks tab
> - [ ] Project Setting
> ![image](https://user-images.githubusercontent.com/62879582/174647128-98545bae-597c-4975-9d68-254e9556e779.png)
> 
> **Federation Sub-menu**
> - [ ] View issues
> - [ ] View risks
> ![image](https://user-images.githubusercontent.com/62879582/174647363-eed91d92-446e-4bf6-a8ba-b55798fe68ca.png)
> 
> **Container Sub-menu**
> - [ ] View issues
> - [ ] View risks
> - [ ] Upload Container
> ![image](https://user-images.githubusercontent.com/62879582/174647569-0278a941-5fae-45e3-8da5-62a1c9f99a0e.png)

**Disable the following elements so they cannot be clicked in 4.26 (George to advise on disabled state):**

> **Viewer**
> - [ ] Compare Card button
> - [ ] GIS Card button
> - [ ] 4D Sequence button
> ![image](https://user-images.githubusercontent.com/62879582/174648567-96b01567-911a-4611-a3fc-0f05b7960657.png)
> 
> **Federation List**
> - [ ] {x} issues
> - [ ] {x} risks
> ![image](https://user-images.githubusercontent.com/62879582/174648723-9900e476-000f-4d9f-b374-397640fbe38e.png)

**Comment by sanmont3drepo** [comment]
@mosment3DRepo should we pay attention to this?

**Comment by carmenfan** [comment]
close as it's pretty N/A at this point
