### ISSUE TITLE
V5 Quota display

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3354]
### Description
This issue depends on #3307. 
Adding quota display in projects selection in v5.

### Goals
- [ ] As a User I want to see the Teamspace quota

### Tasks
- [ ] Add the quota display as shown in the mockup

### Related Resources
[MockUp](https://www.figma.com/file/djgxvRKOaMMyutswn5yywU/Teamspace-(live)?node-id=5323%3A35803)

**Comment by george-hadfield** [comment]
@mosment3DRepo test notification
