### ISSUE TITLE
'Save Changes' button in Fed/Cont settings modal is enabled/disabled when it shouldn't be

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3360]
### Description
- It is possible to edit a field in the Federation/Container settings modal and the Save Changes button is still disabled.
- This appears to be if there are empty fields (e.g. description)
- Alternatively if the Federation/Container already has a description when you open the modal the button will be enabled despite the fact you have made no changes.

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- Open the modal on a Fed/Cont that has a description
- Open the modal on a Fed/Cont that doesn't have a description and try to edit a different field (e.g. name)

### Current Behaviour
- The button doesn't enable when editing fields on a 'no description' Fed/Cont
- The button is instantly enabled when opening a 'described' Fed/Cont

### Expected Behaviour
- The button should be disabled until a field has been edited (unless the newly edited field is invalid)

**Comment by Amantini1997** [comment]
Fixed in #3393
