### ISSUE TITLE
Custom scrollbar not disappearing when content collapses

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3365]
### Description
The custom scrollbar should only be rendered when the content does not fit in the container.
However, the custom scrollbar does not detect when a collapsible content get collapsed

### Steps to replicate
- Open v5 viewer
- Open Measurements card
- Create enough Points to have the scrollbar showing up
![image](https://user-images.githubusercontent.com/43547703/174998324-b67dc87f-fda2-4e3e-b21c-6094713d50d0.png)
- Collapse the content
![image](https://user-images.githubusercontent.com/43547703/174998399-7f46a4f7-0a83-4777-9378-14740848818c.png)

### Current Behaviour
- After collapsing the Points, the scrollbar is still there 
![image](https://user-images.githubusercontent.com/43547703/174998498-743ca57a-ade7-4d53-9e2e-ad59f182bfa2.png)

### Expected Behaviour
- After collapsing the Points, the scrollbar should disappear
![image](https://user-images.githubusercontent.com/43547703/174998598-e99e48bf-9e2d-4227-aae3-fcc9ee8b3c57.png)

**Comment by mosment3DRepo** [comment]
no longer an issue in staging
