### ISSUE TITLE
run-migration should have friendly help message

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3382]
### Description

yarn run-migration without a value gives an unhandled exception as well as the message with a missing version.

- This is happening in: both 
- This requires a hotfix to production: /no 

### Steps to replicate
- yarn run-migration 

### Current Behaviour
- unhandled exception

### Expected Behaviour
- help message displayed

### Pictures/ Gifs of the error
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/23369849/176659836-bd68dec8-1d9e-4c32-b7e9-acc7b80f5256.png">

**Comment by keifgwinn** [comment]
should probably be updated to the yargs system

**Comment by carmenfan** [comment]
done in #3647
