### ISSUE TITLE
Edit Federation Modal uses default horizontal scrollbar, which is only visible at bottom of vertical scroll

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3392]
### Description

If you open the Edit Federation modal and then reduce the screen size a horizontal scrollbar will appear, however it is only visible when the user scrolls to the bottom.

This is happening on Firefox, Edge, and Chrome. On Edge and Chrome the horizontal scrollbar is the default browser scrollbar, and not the custom react one.

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- Open the Edit Federation modal in a project with lots of containers
- Reduce the screensize until the search bar starts to overflow its container
- Scroll down and you will see a horizontal scrollbar

### Current Behaviour
- The search fields overflow causing a horizontal scroll bar to appear
- This scrollbar is only visible when the user is scrolled to the bottom of the modal

### Expected Behaviour
- Either the horizontal scrollbar doesn't need to appear, or it is visible at any vertical scroll level.

### Pictures/ Gifs of the error

![image](https://user-images.githubusercontent.com/62481250/177318450-95a31815-b3f0-48de-8596-19418aa4c0a1.png)
Note the lack of horizontal scroll bar. In this picture I have scrolled right and then up which obscures part of the list.

**Comment by Amantini1997** [comment]
@george-hadfield This probably needs a new design:
- This problem arises when the viewport shrinks too much, that is the equivalent of supporting smaller device factors, but we don't;
- In the `Expected Behaviour` two solutions are suggested, but the overall design still looks messed up because of the search bar overflowing, so the new design should probably address that, rather than the scrollbar itself

**Comment by george-hadfield** [comment]
Can you push the accordion title onto two lines? Which should allow the search bar not to overflow. We can also decrease the width of the search box as the modal decreases in width to 200px min width.

With regards to the scrollbar, can we make it visible from any height in the modal.

**Comment by sanmont3drepo** [comment]
@carmenfan
