### ISSUE TITLE
Analytics Dashboard

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepo.io#340]
# Analytics functions ( backend ):

- [x] Group and count issues by:
 - Status
 - Type
 - Creator
 - Assignee
 - Priority
 - Or combination ( multiple groupings, subcounts )

-  [x] Sort issues by:
 - \# of changes ( busiest )
 - Most viewed 
 - Oldest

- [x] Export CSV

**Comment by timscully1983** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stats](https://trello.com/c/xMMYkO4P/3-stats)

**Comment by timscully1983** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stats](https://trello.com/c/xMMYkO4P/3-stats)

**Comment by carmenfan** [comment]
There is now a mock up of analytics in Node Red. What we need to do on the front end (if any) would be pretty much driven by based on what's on node red.
