### ISSUE TITLE
Unable to remove Federations and Containers from favourites

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3400]
### Description

Trying to remove a favourite Federation/Container brings up an error window. The Federation/Container is not removed from the favourites.
The error message is "ids must be provided as part fo the query string" 
Note there is a typo in the error dialog.
Adding favourites works fine.
This is only happening in V5.

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- Try to remove a Federation/Container

### Current Behaviour
- The item is not unfavourited.
- An error modal appears

### Expected Behaviour
- The item is unfavourited

### Pictures/ Gifs of the error

![image](https://user-images.githubusercontent.com/62481250/177775848-f2b16a5f-9b06-4293-a46a-8ff320296cf4.png)

**Comment by carmenfan** [comment]
oh yes this end point was changed in #2986 by @ChristosTsiotsias  but he didn't change the frontend to match 😆

**Comment by ChristosTsiotsias** [comment]
oops
