### ISSUE TITLE
Log user out when session closes

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepo.io#341]

**Comment by carmenfan** [comment]
Is this done? It's moved to done but there's no reference commit (nor tagged against anything

**Comment by JamesMilnerUK** [comment]
this is a duplicate of #383 essentially. We need to work out the session timer and then send a interval request for that time to check the login API and logout if necessary.

**Comment by JamesMilnerUK** [comment]
Closing in favour of #383
