### ISSUE TITLE
Limit email length

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3437]
### Description
Backend does not support emails longer than 320 characters.
Despite having an email so long is an edge case, it can lead to errors.

- This is happening in: staging
- This requires a hotfix to production: no

Validators should then limit the max length to 320. It would also be nice to trim the value of the email in order to prevent further errors related to the email length.

### Steps to replicate
- Try to register with an email longer than 320 chars
> `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@gmail.com` for instance

### Current Behaviour
- An unexpected error is received from the backend with code 500

### Expected Behaviour
- User should not be able to use emails which, after being trimmed, are longer than 320 chars

**Comment by carmenfan** [comment]
we should also fix the backend so it doesn't return code 500 as part of this issue

We use Yup.string().email(), i guess they don't check for the max length either and it's falling through and erroring out when we try to send an email

https://github.com/3drepo/3drepo.io/blob/master/backend/src/v5/utils/helper/yup.js#L93

**Comment by keifgwinn** [comment]
recommend the limit is set to [254](https://7php.com/the-maximum-length-limit-of-an-email-address-is-254-not-320/)
