### ISSUE TITLE
User account (admin) not found; skipping log message

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3439]
### Description

Logging in to any account created after https://github.com/3drepo/3drepo.io/issues/566 was merged results in this log line

`{"level":"error","message":"User account (admin) not found; skipping... ","timestamp":"2022-07-22T10:13:39.807Z"}`

- This is happening in: staging  
- This requires a hotfix to production: no 

### Steps to replicate
- Log in with any account after the new empty user role is added.

### Current Behaviour
- Spurious log message

### Expected Behaviour
- No reason to check this user role so no log should be produced

### Pictures/ Gifs of the error

- [line in question](https://github.com/3drepo/3drepo.io/blob/f03f81c84e3f161c3ce46167972db95970e85e64/backend/models/user.js#L660)

**Comment by carmenfan** [comment]
addressing in #3453
