### ISSUE TITLE
new permission structure 

### ISSUE THREAD

**Issue by thenrikie** [3drepo/3drepo.io#345]

**Comment by timscully1983** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Role (Basic)](https://trello.com/c/l6Ch3FdW/8-role-basic)

**Comment by timscully1983** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Role (Basic)](https://trello.com/c/l6Ch3FdW/8-role-basic)

**Comment by thenrikie** [comment]
@carmenfan @JamesMilnerUK @timscully1983 
db migration script: 
https://github.com/3drepo/3drepo.io/blob/ISSUE_345/scripts/db_migrations/v2/permisson.js

copy and paste to robomongo and run or do
```mongo permission.js```
