### ISSUE TITLE
In the V5 Viewer the memory usage stats are positioned behind the navbar

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3456]
### Description
The memory usage stats for the viewer are partially obscured in V5

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- In the **V4** viewer click your user profile and select visual settings
- In advanced settings toggle "Show Statistics"

### Current Behaviour
- The memory usage stats are partially hidden by the navbar

### Expected Behaviour
- The memory usage stats are fully visible

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62481250/181052085-045c24dd-12e6-4a5d-82b3-5261c7fa407b.png)

**Comment by carmenfan** [comment]
the stats are unity UI, with this whole idea of having the canvas behind the nav bar you're not going to be able to fix it without a change in unity.

I'm still against this idea of having canvas hiding behind like this as mentioned and ignored [here](https://github.com/3drepo/3drepo.io/pull/3266#issuecomment-1129853346)

**Comment by mosment3DRepo** [comment]
Superseded by https://github.com/3drepo/3drepo.io/pull/3501
