### ISSUE TITLE
It is not possible to exit focus mode in V5

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3457]
### Description
When using focus mode in V5 the button to close exit mode is partially obscured by the navbar. When trying to click this button a tooltip appears which prevents you from clicking the button.

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- Open the V5 Viewer
- In the bottom bar select "Focus Mode"
- Try to close Focuse Mode by clicking the top right "Close Focus Mode" button

### Current Behaviour
- The button is partially obscured

### Expected Behaviour
- The button is fully visible and clickable

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62481250/181054897-db5d43cd-e208-4590-81ad-6e619fdf777c.png)
![image](https://user-images.githubusercontent.com/62481250/181056279-20ebc8fc-e861-4fb7-83f1-170b49e381b2.png)

**Comment by mosment3DRepo** [comment]
Superseded by https://github.com/3drepo/3drepo.io/pull/3501
