### ISSUE TITLE
Node v6 Certificate bug

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepo.io#346]
- Bug fix for wildcard certificate

**Comment by JamesMilnerUK** [comment]
This fix will allow us to merge #359 :+1:

**Comment by carmenfan** [comment]
this and #359 are in Project 1.13 , should they be moved to 2.1?

**Comment by JamesMilnerUK** [comment]
would be nice to get it into 1.13 if possible. Getting onto Node 6.11 would put us on LTS, as we are currently use an older version of Node. Moving to 6.11 gives us a later and more stable version of NPM in production to, which helps fix #359

**Comment by carmenfan** [comment]
Tim replied on a message that he can't reproduce it on dev so he'd look into it when it reaches production. So this is still planned for 1.13 but need to wait till the content is ready!

**Comment by carmenfan** [comment]
Since This is not going to be in production before Tim leaves, can we have a description of what to look for and potentially what would be the problem/fix?

**Comment by timscully1983** [comment]
Can't reproduce this in development or locally. So I can't provide any more details. I would close this and reopen if it appears again.
