### ISSUE TITLE
Share Modal tooltip floats away on change tab in Edit profile

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3467]
### Description

- This is happening in: prod/staging/both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- Open edit profile modal;
- Go to integrations tab;
- Click on "Copy to Clipboard" button;
- As the blueish tooltip "copied to clipboard" is still open, go to password tab.

### Current Behaviour
- The tooltip is rendered in the top right corner

### Expected Behaviour
- The tooltip should unmount

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/43547703/181458292-9bcc4e17-9e9f-454e-b97b-4ec75f41b341.png)

**Comment by carmenfan** [comment]
fixed in #3866
