### ISSUE TITLE
Container does not show description

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3479]
### Description
Trying to update the settings of a container, reflect that change only for as long as the page is not refreshed.
After refresh, the description is no longer displayed.

The problem should in the modal itself, the redux state, in fact, has the correct data

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- Open `edit settings` for a container;
- Modify the description;
- Update the settings and re-open the modal. Note how the description was updated;
- Refresh the page;
- Re-open the settings modal. The description is gone

### Current Behaviour
- Container's description fetched from the backend is not showed in the modal.

### Expected Behaviour
- Should a container have a description, it should show it after fetching it from the backend.

**Comment by sanmont3drepo** [comment]
This is a regression bug. I already fixed this before. This is happening also in federation settings with the gis data.

**Comment by sanmont3drepo** [comment]
This issue was already addressed and ixed in a different one
