### ISSUE TITLE
Stream JSON in response

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepo.io#348]
- Large JSONs cannot be processed

**Comment by thenrikie** [comment]
don't use xmlhttprequest (or angular $http) as the response is too large and the response text reset to empty string automatically without error or warning. use fetch API
```
fetch('<LARGE JSON URL>', {
  method: 'GET',
  credentials: 'include'
})
.then(function(response) {
  return response.blob();
// or return response.arrayBuffer();
})
.then(function(data) {
	console.log(data);
});
```
The next step would be to implement a function to convert this blob/bufferarray to a Javascript object
