### ISSUE TITLE
Download Revision button does not work

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3482]
### Description

Clicking the "Download Revision" button in the container revision list should download the source file, instead it redirects to the viewer.

Oddly the URL seems to be correct if you right click it and copy, but it takes you to the viewer instead when you click it

- This is happening in: staging 4.25
- This requires a hotfix to production: no 

### Steps to replicate
- Open a Project in V5
- Go to the Containers tab
- Open a container revision list
- Click Download on one of the revisions

### Current Behaviour
- Redirects to viewer

### Expected Behaviour
- Downloads source file

### Pictures/ Gifs of the error

https://user-images.githubusercontent.com/62879582/181738681-b2e7f37a-69f0-4ff8-af2d-e421563f83c6.mp4

**Comment by The-Daniel** [comment]
I haven't been able to replicate, but I have found that if you click any of the tooltips (e.g. when hovering over download revision) it will act as if you clicked the list item and launch that revision in the viewer. Do we want to disable interactions with the tooltips?

**Comment by sanmont3drepo** [comment]
Fixed already
