### ISSUE TITLE
The 'Release Notes' link on the login page is a dead link

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3509]
### Description

Trying to access the release notes link on the login page takes you to a dead link. @mosment3DRepo I believe at the time of developing the login page there was a problem with delivering the release notes, so this got posponed and forgotten about. Do we have a way of showing the latest release notes with a URL now?

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- On the login page for V5 click the `Version 4.XX.XX` footer.

### Current Behaviour
- You are taken to a deadlink `/releaseNotes`

### Expected Behaviour
- You are taken to the release notes

**Comment by carmenfan** [comment]
@mosment3DRepo I'm guessing this is suppose to link to page in .com

**Comment by mosment3DRepo** [comment]
@carmenfan I'm not getting a dead link. It's sending me here: https://github.com/3drepo/3drepo.io/releases/tag/4.26.1

Is there any way we can add a link on the github page to the intercom article here: https://help.3drepo.io/en/articles/6471284-4-26-change-log

**Comment by carmenfan** [comment]
> @carmenfan I'm not getting a dead link. It's sending me here: https://github.com/3drepo/3drepo.io/releases/tag/4.26.1
> 

@mosment3DRepo pretty sure @The-Daniel is talking about v5

> Is there any way we can add a link on the github page to the intercom article here: https://help.3drepo.io/en/articles/6471284-4-26-change-log

It would make more sense if change the link there to direct to a URL that will redirect to the latest release notes, otherwise it'll be a manual effort every time we release

**Comment by mosment3DRepo** [comment]
Should redirect to https://help.3drepo.io/en/collections/3358238
