### ISSUE TITLE
Edit View in Viewer looks messed up

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3521]
### Description

Editing (or creating a new) View in the Viewer looks messed up. The textfield and its label are not in the right position.

- This is happening in: staging
- This requires a hotfix to production: no

### Steps to replicate
- Open any model;
- Go to `Views`;
- Edit the the title;

### Current Behaviour
- The texfield is not center-aligned and the label overlaps it.

### Expected Behaviour
- The texfield should be center-aligned and the label correctly position on top of it.

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/43547703/184620703-49c382b9-faa1-47ce-a5fd-62cbfffc5269.png)

**Comment by sanmont3drepo** [comment]
Can you verify that this is not a regression @Amantini1997 ?

**Comment by Amantini1997** [comment]
This was fixed as part of https://github.com/3drepo/3drepo.io/issues/3561
