### ISSUE TITLE
Compare Card dropdown menus look messed up

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3523]
### Description
The elements in the list of `Compare` card include a dropdown. This dropdown doesn't not seem to work correctly

- This is happening in: staging
- This requires a hotfix to production: no

### Steps to replicate
- Open a container in the viewer;
- Go to `Compare` (**1st bug**)
- Click on the dropdown menu (**2nd bug**)

### Current Behaviour
- **1st bug:**  the dropdown looks weird;
- **2nd bug:** the dropdown looks even worse, and the label on the left shift up and hides a bit

### Expected Behaviour
- the dropdown should not move and should not hide under the title;
- the label on the left of the dropdown should not move;

### Pictures/ Gifs of the error
**unselected revision**
![image](https://user-images.githubusercontent.com/43547703/184622201-97c406a4-f96c-478c-98fb-2904010d1d3a.png)

**selected revision**
![image](https://user-images.githubusercontent.com/43547703/184628447-ca496b7f-0def-4e4a-90ff-42c36025eeb2.png)

**Comment by sanmont3drepo** [comment]
I wouldnt create a lot of issues for this. I think we never tackled  compare cards offically. Let George take a look at the whole card and create ONE issue to address all the problems in this card.
