### ISSUE TITLE
ERR_STREAM_WRITE_AFTER_END - Can't set headers after they are sent.

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3546]
### Description

If you visit the billing or favicon route you get an error about the headers being modified after they're sent

[https://3drepo.local/favicon.ico](https://3drepo.local/favicon.ico)
[https://3drepo.local/dashboard/billing/subscription](https://3drepo.local/dashboard/billing/subscription)

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- start up a local copy of IO
- repeatedly visit the billing endpoint

### Current Behaviour
- sometimes it will just error with a soft warning
- after a certain amount of visits it will crash node entirely.

### Expected Behaviour

- we shouldn't crash or attempt to modifier headers after send

### Pictures/ Gifs of the error
<img width="821" alt="image" src="https://user-images.githubusercontent.com/23369849/185613292-cfe62641-dac3-4c42-88ac-bb30356fa721.png">

[https://bobbyhadz.com/blog/javascript-error-cannot-set-headers-after-they-are-sent-to-client](https://bobbyhadz.com/blog/javascript-error-cannot-set-headers-after-they-are-sent-to-client)

**Comment by carmenfan** [comment]
this is likely to be a won't fix as it's not a page our typical customer goes into and v5 revamp will make the endpoints obsolete.

**Comment by keifgwinn** [comment]
further investigation shows this is down to the 404 handler and https enabled on the local server.

**Comment by keifgwinn** [comment]
reordering some of the events and removing some 404 events cleared up the total crash, but really the whole static files handler needs a look
