### ISSUE TITLE
Groups card oddities

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3561]
### Description
The dropdown menus are incorrectly outlined, with the outline that overlaps the label.

- This is happening in: staging
- This requires a hotfix to production: no

### Steps to replicate
- In the group card, click "add new group"

### Current Behaviour
- Dropdown outline overlaps the label

### Expected Behaviour
- Outline should be limited to the dropdown Textfield

### Pictures/ Gifs of the error
 ![image](https://user-images.githubusercontent.com/43547703/186111366-b947c419-6b90-479f-8c09-aa1020d92cd2.png)

**Comment by sanmont3drepo** [comment]
We already addressed issues in the groups card and it looked good. @Amantini1997  please research what generated this regression so it doesnt happen again.

**Comment by mosment3DRepo** [comment]
The background is as designed as this will be the direction we go in for Custom tickets, so only #2 needs addressing
