### ISSUE TITLE
identifyZombieFiles.js need to get the refs from avatar.refs

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3581]
### Description
running `identifyZombieFiles.js` will currently remove all the avatar images from fileshare as it doesn't pull in the refs in `avatars.ref` within the `admin` database. 

### Steps to replicate
- ensure the database has some accounts with avatars
- run identifyZombieFiles script

### Current Behaviour
- all avatars will be removed from the fileshare

### Expected Behaviour
- avatars should not be removed

**Comment by Charence** [comment]
Links for dev/prod obtained

**Comment by keifgwinn** [comment]
Could this issue also fix the help in the file
```

root@staging-59d4d596fd-fvrvs:/home/node/3drepo.io/backend# yarn run-script identifyZombieFiles --help
yarn run v1.22.19
$ cross-env NODE_CONFIG_DIR=../config node ./src/scripts/utility/index identifyZombieFiles --help
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
Done in 0.71s.
```

**Comment by Charence** [comment]
> Could this issue also fix the help in the file
> 
> ```
> 
> root@staging-59d4d596fd-fvrvs:/home/node/3drepo.io/backend# yarn run-script identifyZombieFiles --help
> yarn run v1.22.19
> $ cross-env NODE_CONFIG_DIR=../config node ./src/scripts/utility/index identifyZombieFiles --help
> Options:
>   --help     Show help                                                 [boolean]
>   --version  Show version number                                       [boolean]
> Done in 0.71s.
> ```

Current behaviour for `run-script` seems to be it will show you the options if you don't specify any. e.g. `yarn run-script identifyZombieFiles` and then start running the script. Adding `--help` shows the default options of `--help and --version` rather than options of a specific script and it's happening for all scripts in `src/utility/`.

**Comment by carmenfan** [comment]
> > Could this issue also fix the help in the file
> > ```
> > 
> > root@staging-59d4d596fd-fvrvs:/home/node/3drepo.io/backend# yarn run-script identifyZombieFiles --help
> > yarn run v1.22.19
> > $ cross-env NODE_CONFIG_DIR=../config node ./src/scripts/utility/index identifyZombieFiles --help
> > Options:
> >   --help     Show help                                                 [boolean]
> >   --version  Show version number                                       [boolean]
> > Done in 0.71s.
> > ```
> 
> Current behaviour for `run-script` seems to be it will show you the options if you don't specify any. e.g. `yarn run-script identifyZombieFiles` and then start running the script. Adding `--help` shows the default options of `--help and --version` rather than options of a specific script and it's happening for all scripts in `src/utility/`.

didn't used to be the case, something broke the help command.
