### ISSUE TITLE
Custom tickets - Basic Search tickets

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3585]
### Description
Create a basic string search functionality for custom tickets. Only tickets which satisfies all the search term should appear in the filtered list.

- It would be good if the search term is highlighted on the ticket listing 
- Maybe make it a chip filter like the BIM card? so we can search for multiple search terms
![image](https://user-images.githubusercontent.com/11945337/227245359-aaad5f60-9487-4920-bca9-0d430569ff64.png)

- Fields to inspect:
  - Ticket name
  - ticket number

### Goals
- The user should be able to type in the search bar to filter the list of tickets base on the search term

### Tasks
-TBC

**Comment by george-hadfield** [comment]
Getting this error "Cannot GET /"

**Comment by george-hadfield** [comment]
Design still applies

**Comment by george-hadfield** [comment]
Link to design

https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3625%3A36672&t=3oZvZG8NUL6uANKy-1

**Comment by george-hadfield** [comment]
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3625%3A36672&t=dDT5ThHwuGG0NCQk-1
