### ISSUE TITLE
socket.io-client-cookie causes issues with npm install 

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#359]

**Comment by JamesMilnerUK** [comment]
@timothyscully  This branch also updates CI Node to 6.10.3 and NPM 4.6.1, so we will need to fix #346 first

**Comment by JamesMilnerUK** [comment]
@thenrikie am I right in think we fixed this by removing dependency and updating the socket library?

**Comment by carmenfan** [comment]
sounds like this is a non issue so i'm closing it

**Comment by JamesMilnerUK** [comment]
It's been fixed :tada:
