### ISSUE TITLE
Upgrade deprecated npm dependencies

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#360]
https://www.npmjs.com/package/npm-check-updates looks like it may be useful

**Comment by JamesMilnerUK** [comment]
Here's a list of the outdated dependencies:

![screenshot_20170525_172950](https://cloud.githubusercontent.com/assets/8822075/26459875/d6c4be5c-416f-11e7-9177-4d9da9aa06e6.png)

**Comment by thenrikie** [comment]
make sure it pass all API tests before merging it to staging, I am afraid there will be a lot of backward incompatibilities since a lot of the upgrades in the table includes major version changes.

**Comment by JamesMilnerUK** [comment]
There are too many breaking changes to update everything in one go. Instead I will upgrade us to using Pug and update all minor changes and if that passes then I'll merge that into staging for now.

**Comment by JamesMilnerUK** [comment]
When I attempted to bump all the dependencies to the latest version, there were about 12 failing integration tests. Once I've got the Pug and frontend build depencies to latest I think @thenrikie would be best placed to update the rest of the depencies.

**Comment by JamesMilnerUK** [comment]
![screenshot_20170706_090859](https://user-images.githubusercontent.com/8822075/27901917-bb1b6c64-622b-11e7-8ece-3dec167c4560.png)

Latest state of affairs
