### ISSUE TITLE
V5 Breadcrumbs can wrap onto two lines leaving a large gap

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3601]
### Description

If a breadcrumb section is too long (and contains a space?) it can wrap onto multiple lines leaving a weird gap. This also seems to cause the final breadcrumb to be truncated when it doesn't need to be.

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Create a federation/container with a very long name
- Access it

### Current Behaviour
- The project name wraps onto two lines leaving a large gap to its right hand side

### Expected Behaviour
- There should not be a large gap in the breadcrumbs. The text should probable stay on one line, if not the width that the breadcrumb occupies should shrink when it wraps

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62481250/188197307-7f836e4e-0672-4890-9885-2bcac50c79b5.png)

The image below shows the revision name being truncated when it has plenty of space. This same container has a 4-letter long revision tag which gets truncated down to 1 letter - so truncation seems to happen no matter how long the tag is.
![image](https://user-images.githubusercontent.com/62481250/189655556-37d2917b-b111-42c9-9682-495e736e8b35.png)

**Comment by Amantini1997** [comment]
This was fixed as part of https://github.com/3drepo/3drepo.io/issues/3827
