### ISSUE TITLE
Have more descriptive page names for easier browser history navigation

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3607]
### Description

Trying to navigate backwards or forwards is difficult as all the pages are called _3D Repo | Online BIM collaboration platform_. It is not possible to know which one is the federations list, teamspace selection, viewer, etc.

### Goals

- The user should easily be able to navigate backwards and forwards through the browser's history and know where in 3D Repo it will take them

### Tasks
[ ] - Add specific page names for all the pages in 3D Repo

### Related Resources

![image](https://user-images.githubusercontent.com/62481250/188640480-c4a986c1-7b48-42a3-a54d-3cf50108a30d.png)
All the same!

**Comment by The-Daniel** [comment]
![image](https://user-images.githubusercontent.com/62481250/189165869-1cc1c4d3-f167-47b2-80a2-8ce94604115a.png)
@mosment3DRepo Here's an example of the current page titles. Let me know your feedback.

A few things to note:
- My teamspace is called Test1, everything else has a logical name. (e.g. 'My Project' is the name of the project)
- I've made it possible to have a default should the title for a page not be set. It's currently using the old page title for that (3D  Repo | Online BIM collaboration Platform). In theory this shouldn't happen though.
- For some variables that aren't known at the start of the page load I've added 'Loading...' until they are known. The example below shows the Project name before it is found
![image](https://user-images.githubusercontent.com/62481250/189167260-6b858e6c-5454-4853-a672-40a375d2108f.png)

**Comment by mosment3DRepo** [comment]
@The-Daniel Agreed on most, the only thing I would like to change is to get consistency between the viewer and the rest of the teamspace.

With the viewer you have **{{name}} - {{screen}}**

Whereas with Containers, Federations and Teamsapces you have **{{screen}} - {{name}}**

I think we should go with the following:

```
Teamspace Name - Projects
Project Name - Federations
Project Name - Containers
Container Name (revision) - Viewer
Federation Name - Viewer
```
