### ISSUE TITLE
Custom tickets - Tickets details -  sequencing module

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3609]
### Description
Add support for Sequencing model to interact with the sequence card.

#### UI 
`Start time` and `End time` dates in the sequence card are special date fields where there should be an icon to move the sequence to that date/time:
![image](https://user-images.githubusercontent.com/11945337/227242483-b92fa692-7cff-4de4-b063-24cc0aa3567e.png)
![img](https://user-images.githubusercontent.com/11945337/227243865-3cd84287-9584-4b78-8b9a-633e52f7834a.gif)

Additional thought - perhaps it'd be good to have a button to do the reverse - update the date with the current time in the sequence

### Goals
- If the sequence card is playing a sequence and the user creates a ticket that has the `sequence` module, it should populate the `start time` with the current date time of the sequence
- If a custom ticket has a pin and sequence start/end time is recorded, if we are playing the sequence, the pin should only appear when the current time is within the start/end time.
  -  If start time is unspecified, assume it starts from the beginning of the sequence
  - If end time is not specified, assume it finishes at the end of the sequence

### Tasks
TBC

**Comment by carmenfan** [comment]
@mosment3DRepo Any chance we can take this out of 4.28?

The only "special" thing that's going on here is the interaction with the sequence card

Without it, we will still be displaying the module, just with standard dates fields that wouldn't link up with sequence card

**Comment by george-hadfield** [comment]
**Link to design**
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=3497%3A27075&t=84kGphFInLknl12U-1

The design displays the outlined version of the sequencing icon (will be used in the future). For now, please the existing Sequencing icon.

**Comment by carmenfan** [comment]
> @carmenfan I think it's ready on my end. Could let me know once you added the sequencing module as part of the basic ticket data fetched?

sorry yes it's on my to do list i'll have a look after rechecking QA
