### ISSUE TITLE
Custom tickets - Advanced Search tickets

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3621]
### Goals
- [ ] 

### Tasks
- [ ]

**Comment by AsiteZane** [comment]
What does this mean @carmenfan ?

**Comment by carmenfan** [comment]
@AsiteZane basically https://github.com/3drepo/3D-Repo-Product-Team/issues/311

This was created as part of the custom ticket stuff, but it went out of scope due to timing constraint.

i'll just close this and we can track this via https://github.com/3drepo/3D-Repo-Product-Team/issues/311
