### ISSUE TITLE
Custom tickets - Tickets details - Basic details

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3622]
### Description
As a user I want to see the contents of a ticket with the actual first design

### Goals
- [ ] As a user I want to see the Details of a ticket

### Tasks
- [ ] Show the content of the ticket in ticket details

### Related Resources
[Mockup](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=496%3A5428)

**Comment by carmenfan** [comment]
Merged into main branch
