### ISSUE TITLE
Custom tickets - Tickets details  - Safeti base module

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3623]
### Description
Readonly status of the (mitigated/ inprogress) . Accordion module

### Goals
- [ ] As a user I want to be able to use the  safetibase prefab module

### Tasks
- [ ] Should fetch safetibase categories and fill oout that select
- [ ] Fix crash

### Endpoints
To fetch the list of risk categories, call `HTTP GET  teamspaces/{teamspace}/settings/tickets/riskCategories`

### Related Resources
<img width="418" alt="image" src="https://user-images.githubusercontent.com/42032433/198564686-a8a233d7-72af-4ee2-9707-96e89e61d118.png">

**Comment by carmenfan** [comment]
Merged into main branch
