### ISSUE TITLE
Custom tickets - Tickets details - New ticket ui

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3627]
### Description
Right now we have a new ticket functionality but it lacks nice design. We need to apply the ui to make it pretty

### Goals
- [ ] As a user I want to be able to create tickets using a nice design 

### Tasks
- [ ] Apply the design  from figma

### Related Resources
[Design](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=789%3A5282)

**Comment by carmenfan** [comment]
Merged into main branch
