### ISSUE TITLE
Custom tickets - Tickets details - Shapes module

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3628]
### Goals
- [ ] 

### Tasks
- [ ]

**Comment by carmenfan** [comment]
@george-hadfield  do we have UI for this?

**Comment by AsiteZane** [comment]
Not potentially needed now that there is a new ticket. Will be positioned to “provisional to delete”.

**Comment by AsiteZane** [comment]
https://github.com/3drepo/3D-Repo-Product-Team/issues/362 covers how this will now be handled in lieu of the previous Shapes functionality. Closed.
