### ISSUE TITLE
Custom tickets - Tickets details - Attachments module

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3629]
### Goals
- [ ] 

### Tasks
- [ ] 

### Related Resources
MockUp : `link to mockup`
Coda doc: `link to coda`

**Comment by AsiteZane** [comment]
@carmenfan  - could we please fill this in properly? I am trying to edit the original message but it’s not letting me - don’t think I have the rights - could you help please?

**Comment by carmenfan** [comment]
@AsiteZane  considering we haven't started the work (barring George's design), do you want to just close this and create one in Product team repo?

**Comment by AsiteZane** [comment]
@carmenfan sure. Please could you close?
