### ISSUE TITLE
Implement Teamspace tree view

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#365]
- [x] Refactor 'project' to become 'model'
- [x] Rename repos to 'teamspaces' in the UI
- [x] Remove top bar, as we move into a folder structure approach
- [x] Create a new folder structure that follows: teamspaces -> projects -> models (includes / models + federations)
- [x] Allow folders to be shown and hidden
- [x] Add a plus button to allow users to add a new project/model/federation
- [x] Add federation, project and model buttons
- [x] Smoke test folder structure works
- [x] Smoke test all original functionality is maintained
- [x] Add dialog for adding a new project
- [x] Allow delete and update project
- [x] Check that new code works with Collaborators
- [x] Allow models on the top level object (without a project) to be assigned to a 'Unassigned' folder for backwards compatability
- [x] Refactor code to improve readability and separation of concerns

**Comment by JamesMilnerUK** [comment]
This is blocked until we can get the backend to support projects beneath teamspaces and refactor projects to models/federations in the current code

**Comment by JamesMilnerUK** [comment]
#376 needs to be done on the back of this

**Comment by JamesMilnerUK** [comment]
![treeexample](https://user-images.githubusercontent.com/8822075/26887376-c78b17a8-4b9f-11e7-9e93-9ba9a76c7969.gif)

**Comment by timscully1983** [comment]
Things that are happening now, that should be fixed:
- [ ] Missing spinning icon  - Processing/Uploaded
- [ ] Can only add projects from default project
- [ ] Need to refresh to access new fed/project.

**Comment by JamesMilnerUK** [comment]
There is still some undesired behaviour around submodels not being deleted from a federation when the model is deleted and there are no models left. This leads to some white space in the federation list. This should be fixed when @thenrikie fixes https://github.com/3drepo/3drepo.io/issues/377
