### ISSUE TITLE
V5 - Teamspace Project & model permissions

### ISSUE THREAD

**Issue by miadibe** [3drepo/3drepo.io#3661]
### Description
Currently, a user with viewer/commentor or collaborator rights on a project/model in another teamspace cannot navigate and open the model.
This is happening in: prod and staging 

### Steps to replicate
- Add a user to a project/model with permissions that aren't admin (viewer, commenter or collaborator)
- Log in to 3D Repo's V5 as the user with one of these permissions and try to navigate to the corresponding model

### Current Behaviour
- In this example, Emma is made a collaborator in a project on the mia_dibe teamspace.
- When logged in 3D Repo's V5, Emma can see the mia_dibe teamspace but gets an error as soon as she tries to open the model she's been assigned to

### Expected Behaviour
- Users should be able to navigate other users' teamspaces without getting an error to access as long as they have the right permissions to view
- Users should not have to make other users admins in order for them to access the relevant projects/models
- All permissions should be retained

### Pictures/ Gifs of the error
**Error:**
![image](https://user-images.githubusercontent.com/56918163/192315355-c7420ed3-1cb5-4a6d-be6c-b439b4cf7c82.png)
**Video below highlights model access in V4 in comparison to V5**
https://user-images.githubusercontent.com/56918163/192317191-10e3dc2f-9ec9-4d15-aafb-903a255d8731.mp4

**Comment by carmenfan** [comment]
Verified fixed as of 5.0.5
