### ISSUE TITLE
change cookie based auth to jwt based auth

### ISSUE THREAD

**Issue by thenrikie** [3drepo/3drepo.io#369]
- [x] issue signed jwt and parsing jwt from header
- [x] restrict Access-Control-Allow-Origin to list of whitelist domains

**Comment by thenrikie** [comment]
Should we generate an ID (something like a session id) and include it in jwt and also save this id on the server side? 

Pros of doing it will be 

1. Able to invalidate jwt from server side (by removing this id on server side) instead of just telling the browser/client to forget this token and waiting for it to expire.
2. Even if secret key used to sign the jwt is compromised and the hackers can generate a valid signed jwt, it will still be considered invalid from our server (because of missing / incorrect session id), which leaves us time to fix the problem.

Cons
1. The need for database/file lookup for the session ID seems defeating part of the purposes of jwt?

Another way to invalidate an jwt would be creating a blacklist of jwts and garbage collect the blacklist.

**Comment by JamesMilnerUK** [comment]
I would generally be against using session IDs in JWT and keep the JWT stateless. This will avoid unnecessary complexity on the backend / server chattiness, and in turn be more scaleable. We can invalidate sessions from the client fairly easily so I don't feel like that's such a concern.

**Comment by timscully1983** [comment]
Can we also track from how many machines a user is logged in from, with a stateless approach ?
For enterprise licensing this may be a problem.

**Comment by carmenfan** [comment]
closing as this will need redo-ing since the code base has moved on loads.
