### ISSUE TITLE
Viewer Facelift - Sequences card

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3690]
### Description
Most of the components in the viewer have been facelifted, but the sequences card doesn't look very nice yet.

### Goals
Sequences card should be facelifted, this should also include the two panels that can be opened by toggling the two toggles.

### Tasks
- [ ] Basic Sequences card;
- [ ] Legend panel;
- [ ] Activity List panel

### Related Resources
![image](https://user-images.githubusercontent.com/43547703/195818258-3092603f-fcf6-4a35-9b4d-c4ab8799f7c5.png)
![image](https://user-images.githubusercontent.com/43547703/195818208-c5b9e9e1-2947-4073-845b-4438df8c74d4.png)

**Note** the toggles are being refactored in #3632 and will eventually look like this
![image](https://user-images.githubusercontent.com/43547703/195818429-14100c44-b9bd-40ba-a4f0-575f6ec995d0.png)

Make sure to show the number value here 
![image](https://user-images.githubusercontent.com/43547703/195819016-6b103b28-70ed-4b3d-8845-5f4ecdcc8e0d.png)

**Comment by carmenfan** [comment]
@george-hadfield To provide link to design

**Comment by george-hadfield** [comment]
[Link to design](https://www.figma.com/file/J5I3hYQTrLCjEVP1iqcyZK/3D-Viewer?node-id=138651%3A182512&t=7asHKLmrkSW4hGZA-1)
