### ISSUE TITLE
Custom tickets - Modules icons

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3707]
### Description
We want the user to be able to distinguish between modules instinctively, on that matter different icons for each type of predefined module will makes things easier

### Goals
- [ ] As a user I want to distinguish fast which modules are which

### Tasks
- [ ] Set the icon for each module as shown in figma

### Related Resources
[MockUp](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=319%3A6)

**Comment by carmenfan** [comment]
@george-hadfield to update the link to mockup

**Comment by george-hadfield** [comment]
[Link to mockup](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=319%3A6&t=aIZ6uRFkJnXtuwsP-1)
