### ISSUE TITLE
fedModels is missing from project in backend docs and return values

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#371]
Unless I'm mistaken/missing something

**Comment by JamesMilnerUK** [comment]
I am assuming the federate property handles this?

**Comment by thenrikie** [comment]
Yes, sorry for the confusion. In project.models array, it is just a list of models (and fed models), with federate property. I actually want to merge the models and fedModels array into one single array but I keep them there for backward compatibility.

**Comment by carmenfan** [comment]
Is there anything actionable here or should this be closed?
