### ISSUE TITLE
V5 error template visual update

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3723]
### Description

Update the error modal which is generated from V4 errors being displayed in a V5 environment

Current model errors in V5 render like this:

![image](https://user-images.githubusercontent.com/62879582/199291830-96d58fb5-42e0-437f-97b0-73d744b4763b.png)

### Goals

- [ ] All error messages should not look out of place in V5 design

**Comment by george-hadfield** [comment]
@mosment3DRepo The issue won't let me add the link to the Description. I imagine it's a permission problem.

**Link to design** 
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1410%3A13060

**Screenshot**
<img width="618" alt="image" src="https://user-images.githubusercontent.com/78047794/199493171-708362c4-5c88-4417-ad63-3b1b7ddd1f36.png">

**Comment by sanmont3drepo** [comment]
Merged into main branch
