### ISSUE TITLE
V5 Visual Settings As is

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3725]
### Description

In order to move users over to V4 permanently we must have a Visual Settings modal in the new style

### Goals

- [ ] Try to keep all settings on a single screen divided by group
- [ ] Remove any non functioning inputs

### Related Resources
**Existing Design**

![image](https://user-images.githubusercontent.com/62879582/199473194-74852c61-4e49-4c07-a386-b1e1cb7baafa.png)

![image](https://user-images.githubusercontent.com/62879582/199473206-3e9acc07-281a-4595-9259-96a3284354f8.png)

**Comment by mosment3DRepo** [comment]
@carmenfan could you advise which settings no longer do anything. If memory servers "Memory for Unity" is no redundant

**Comment by carmenfan** [comment]
> @carmenfan could you advise which settings no longer do anything. If memory servers "Memory for Unity" is no redundant

if you're just face-lifting then i wouldn't bother here

Wait till you do a proper v5 one then we can review then.

If you're that bothered about it, I can remove anything irrelevant when I add in the streaming settings (which as discussed in the meeting you weren't around, that should be a different issue to facelift anyway)

**Comment by mosment3DRepo** [comment]
> > @carmenfan could you advise which settings no longer do anything. If memory servers "Memory for Unity" is no redundant
> 
> if you're just face-lifting then i wouldn't bother here
> 
> Wait till you do a proper v5 one then we can review then.
> 
> If you're that bothered about it, I can remove anything irrelevant when I add in the streaming settings (which as discussed in the meeting you weren't around, that should be a different issue to facelift anyway)

in that case a straight face lift is fine.

@george-hadfield just keep it as simple as possible, a like for like face lift

**Comment by mosment3DRepo** [comment]
@george-hadfield can you review the visual settings on https://github.com/3drepo/3drepo.io/pull/3767 as there is a new tab there

**Comment by carmenfan** [comment]
> @george-hadfield can you review the visual settings on #3767 as there is a new tab there

@george-hadfield just so you are aware there's now 2 extra settings on the advance tab on that branch

![image](https://user-images.githubusercontent.com/11945337/203781220-b7437d01-8c7b-477c-923d-e8d73d6f5673.png)

**Comment by george-hadfield** [comment]
@carmenfan do you have the fields for the streaming tab anywhere?

**Comment by carmenfan** [comment]
> @carmenfan do you have the fields for the streaming tab anywhere?

@george-hadfield  you could just go to the deployment for #3767 and see it

**Comment by george-hadfield** [comment]
> > @carmenfan do you have the fields for the streaming tab anywhere?
> 
> @george-hadfield you could just go to the deployment for #3767 and see it

When viewing https://issue-3759.dev.3drepo.io/v5/dashboard and clicking on visual settings nothing happens

**Comment by carmenfan** [comment]
> When viewing https://issue-3759.dev.3drepo.io/v5/dashboard and clicking on visual settings nothing happens

@george-hadfield viewer setting haven't been facelifted yet (this is the issue for it), you need to go into v4 to see it

**Comment by george-hadfield** [comment]
> > When viewing https://issue-3759.dev.3drepo.io/v5/dashboard and clicking on visual settings nothing happens
> 
> @george-hadfield viewer setting haven't been facelifted yet (this is the issue for it), you need to go into v4 to see it

thank you

**Comment by george-hadfield** [comment]
This is now updated and ready for review

**Comment by carmenfan** [comment]
Merged into #3065
