### ISSUE TITLE
V5 Kanban Board MVP - Design only

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3726]
### Description

In order to get a functional version of V5 up and running we must have a means to access the kanban board

### Goals

- [ ] Allow the kanban board to be accessed from V5
- [ ] Where possible maintain styling with V5
- [ ] If the page opens in a new tab, avoid users from accessing other elements of V4

### Related Resources
The functionality for this one is being addressed in #3757

**Comment by george-hadfield** [comment]
[Link to design](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1624%3A13620&t=HLdywiW9Zv1tClLW-1)

**Comment by carmenfan** [comment]
closed in favour of #3757
