### ISSUE TITLE
V5 Teamspace user list MVP

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3727]
### Description

In order to get a functional version of V5 up and running we must have a means to access the teamspace user list, including adding and removing users

### Goals

- [ ] Allow the user list to be accessed from V5
- [ ] Where possible maintain styling with V5
- [ ] If the page opens in a new tab, avoid users from accessing other elements of V4

**Comment by george-hadfield** [comment]
Link to design
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1416%3A15085

Screenshot

![Image](https://user-images.githubusercontent.com/78047794/199732735-fc7b87d7-ece5-40a6-ac58-ec91e54631b5.png)

![Image](https://user-images.githubusercontent.com/78047794/199732796-4e697441-23c9-4ae6-8540-5aa712103389.png)

![Image](https://user-images.githubusercontent.com/78047794/199732883-ebafc0d5-376c-4a1a-8d07-b9c50a8331b2.png)

![Image](https://user-images.githubusercontent.com/78047794/199732925-c081076b-bce9-4cc8-94c8-06938c445c29.png)

**Comment by mosment3DRepo** [comment]
Agreed to embed as per George's design above but with V5 facelift applied

**Comment by carmenfan** [comment]
@george-hadfield  please update link to mockup

**Comment by The-Daniel** [comment]
So is the design I should be following the frame titled ['V5 light touch style'](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1415%3A15003&t=LsBbe5Uwhq4XTOQd-1)?

**Comment by carmenfan** [comment]
@george-hadfield  can you make sure the light touch version is up to date and feature match with v4
