### ISSUE TITLE
V5 Project Settings (rename project)

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3728]
### Description

In order to get a functional version of V5 up and running we must have a means to access the project settings. Since the project settings only consists of renaming the project this can be built from scratch rather than porter from V4

### Goals

- [ ] As an admin I want to see the name of the project in the editable text field when I load the settings
- [ ] As an admin when I save a new project name I expect the Project name on the page and the tab header to update to the new name
- [ ] As an admin I expect other users to see the updated name when they next refresh/load the project page or teamspace project list

**Comment by carmenfan** [comment]
@george-hadfield  to provide the latest mock up
