### ISSUE TITLE
V5 Remove non-functional elements from profile menu

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3729]
### Description

When selecting the users avatar, the resulting drop down menu has several options which are not currently set up and instead fulfilled by the intercom chat bubble.

We will temporarily remove them (they will be back in future releases) to avoid having non-functional elements in the V5 release

### Related Resources
![image](https://user-images.githubusercontent.com/62879582/199475133-4ddd8771-97cd-46a9-9b7e-a48b24de38ad.png)

**Comment by keifgwinn** [comment]
could the contact us promote the use of the intercom button somehow, highlight it?

**Comment by george-hadfield** [comment]
Link to design
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1464%3A13368

Screenshots

![Image](https://user-images.githubusercontent.com/78047794/199738692-71162701-6320-4b26-9e4a-41cd58273bc9.png)

![Image](https://user-images.githubusercontent.com/78047794/199738733-2e9e3c96-9885-46e9-98c1-775edf316f90.png)
