### ISSUE TITLE
Refactor API URL structure

### ISSUE THREAD

**Issue by timscully1983** [3drepo/3drepo.io#373]
- [x] Refactor to include verbs in URL structure.
/teamspaces/:ts[/projects/:project]/models/:modelName/issues/:issueId
/teamspaces/:ts/models/:modelID/issues/:issueId
- [x] account > teamspace

**Comment by carmenfan** [comment]
@JamesMilnerUK  account name to teamspace aside (I know you want to refactor that), do you think there is much point in deploying this url change?

This is once again a drastic db migration. Apart from looking marginally cleaner i'm not really seeing the benefits.

**Comment by JamesMilnerUK** [comment]
@carmenfan think we can park this for now. Probably a good one for the new backend dev to pick up? Like you say apart from cleanliness I think it would cause more problems than it would solve in the short term.

**Comment by carmenfan** [comment]
I don't think we'll ever do this.
If we do, i'm not sure if what is suggested here is the best solution.

If we revisit, we probably need a new issue as this branch has some super old outdated version
