### ISSUE TITLE
V5 Notifications MVP

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3730]
### Description

We need to have a mechanism for accessing notifications from inside V5. At the moment we are not looking to redefine the notifications, but just allow them to be accessed

### Goals

- [ ] Allow notifications to be accessed from V5
- [ ] Where possible maintain styling with V5
- [ ] If the page opens in a new tab, avoid users from accessing other elements of V4
- [ ] Add the notification count to the V5 toolbar

**Comment by george-hadfield** [comment]
[Link to design](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1407%3A13015)

**Comment by george-hadfield** [comment]
[Link to design](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?node-id=1504%3A13969&t=7Krch54Xdqq3C40B-1)

**Comment by carmenfan** [comment]
@george-hadfield  can you update the mock up to make sure it's up to date
