### ISSUE TITLE
Custom ticket - Safetibase module is not saveable

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3749]
### Description
Attempting to create a new ticket using a template with a safetibase module fails since the save button is not clickable

### Steps to replicate
- Create a template with a safetibase module;
- Try to create a new ticket using such a template

### Current Behaviour
- Save button is disabled

### Expected Behaviour
- Save button should be clickable once all the fields required are filled in

### Resources
You may use the following template
```json
{
  "name": "___Basic Safetibase___",
  "code": "BSB",
  "config": {
    "comments": false,
    "issueProperties": true,
    "defaultView": false,
    "defaultImage": false,
    "pin": false
  },
  "deprecated": false,
  "modules": [
    {
      "type": "safetibase",
      "deprecated": false,
      "properties": [
        {
          "name": "Floor",
          "type": "oneOf",
          "deprecated": false,
          "required": true,
          "values": [
            "Level 1",
            "Level 2",
            "Basement"
          ]
        }
      ]
    }
  ]
}
```

**Comment by sanmont3drepo** [comment]
Merged in the main branch
