### ISSUE TITLE
Frontend code should consistently use 'Teamspaces' instead of 'Accounts'

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#376]

**Comment by JamesMilnerUK** [comment]
In hindsight this shouldn't be it's own issue.

**Comment by JamesMilnerUK** [comment]
On futher hindsight this should be done in conjunction with @thenrikie on the backend

**Comment by thenrikie** [comment]
It will be included in #373   as they are quite related.
