### ISSUE TITLE
Custom tickets: Attachments endpoints

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3772]
### Description
Adding endpoint to support adding and removing resources

#### Storage Schema
````js
// tickets.attachments collection
{
  _id: LUUID,
  teamspace: string,
  project: string,
  model: string,
  files: [
    { name: string, ref: string}
  ],
  links: [
    { name: string, link:  string}
  ]
}

// tickets.log 
{
  changes: {
    attachments: {
      // whichever one applicable
      added: {
        // whichever one applicable
         files: [
           { name: string, ref: string}
        ],
        links: [
          { name: string, link:  string}
        ]
      },
    removed: {
        // whichever one applicable
         files: [
           { name: string, ref: string}
        ],
        links: [
          { name: string, link:  string}
        ]
      }
    }
    }
  }
  // other fields should be same as other ticket logs
}

````
###### NOTES:
- `ref` should be a resource id that indicates where the file is stored and it should be retrievable via the get resource endpoint (just like images) - we should make sure the mime type is correct.
- links format should be checked in a very simple way, matching `<protocol>://<string>`
- names and links length should confirm to `strings.title`

##### Attach files
route: `PATCH /teamspaces/:teamspace/projects/:project/:type/:model/tickets/:ticket/attachments/files`
payload: multipart/form-data of files and their names [(just like v4)](https://3drepo.github.io/3drepo.io/#api-Issues-attachResource)
permissions: commenter and above

###### NOTES:
- The teamspace must have sufficient quota
- Each file size must be less than `config.resourceUploadSizeLimit`
- There should be a record in the tickets log when a user uploads attachments
- filename should be the provided filename + the extension of the file (unless the user already provided the extension)
- It should trigger a chat message to indicate the user the ticket has been updated (same as updating a property)
- This should append to the files array instead of overwriting it
- If filename is already used, it should throw an error
- If there is a duplicated filename in the array, it should throw an error
- should error if the ticket template does not support attachments

##### Removing files
route: `DELETE /teamspaces/:teamspace/projects/:project/:type/:model/tickets/:ticket/attachments/files?names=[x, y, z]`
permissions: commenter and above

###### NOTES:
- should not really delete the file, it should just remove the references from the ticket of any matching filenames and record an entry in the ticket log
- ignore any unrecognised filenames
- should throw an error if no filename is provided, or the filenames parameter does not conform to the expected format
- ensure the filenames are recognised even if it has non URL friendly characters
- should error if the ticket template does not support attachments

##### Attaching links
route: `PATCH /teamspaces/:teamspace/projects/:project/:type/:model/tickets/:ticket/attachments/links`
payload: 
```` js
{
  links: [
    { name: "name of link ", link: "http://link.to.something" },
    { name: "name of link2 ", link: "ftp://link.to.something2" }
  ]
}
````
permissions: commenter and above

###### NOTES:
- should append to the links array instead of overwriting it
- names must be unique in the resulting updated array
- links must be of the format `<protocol>://<string>` 
- should error if the ticket template does not support attachments

##### Removing links
route: `DELETE /teamspaces/:teamspace/projects/:project/:type/:model/tickets/:ticket/attachments/links?names=[x,y,z]`
permissions: commenter and above

###### NOTES:
- Should just remove the links from the ticket of any matching names and record an entry in the ticket log
- ignore any unrecognised names
- should throw an error if no filename is provided, or the filenames parameter does not conform to the expected format
- ensure the filenames are recognised even if it has non URL friendly characters
- should error if the ticket template does not support attachments

##### Get Attachments
route: `GET /teamspaces/:teamspace/projects/:project/:type/:model/tickets/:ticket/attachments`
permissions: viewer and above
response:
````js
{
 attachments: {
    files: [
      { name: "filename", ref: "abc", size: 1000 }
    ],
    links: [
      { name: "link name", link: "http://sdfldskj"}
    ]
  }
}
````

##### New Attachments 
- Event name: containerNewTicketAttachments / federationNewTicketAttachments
- scope: Container/Federation event
- data: 
````js
{  
  teamspace: "teamspace name", 
  project: "project id", 
  model: "model id", 
  data: { 
    ticket: "ticketId",
    //files or links, whichever applicable
    files: [
      { name: string, ref: string}
    ],
    links: [
      { name: string, link:  string}
    ]
  }
}
````

##### New Attachments 
- Event name: containerDeleteTicketAttachments / federationDeleteTicketAttachments
- scope: Container/Federation event
- data: 
````js
{  
  teamspace: "teamspace name", 
  project: "project id", 
  model: "model id", 
  data: { 
    ticket: "ticketId",
    //files or links, whichever applicable
    files: [
      { name: string}
    ],
    links: [
      { name: string}
    ]
  }
}
````
###### NOTES
- should error if the ticket template does not support attachments
- should return empty arrays if the ticket supports attachment but does not contain any

### Goals
- should be able to fetch all attachments within the issue
- should be able to fetch files through resource endpoint
- should be able to add/remove files
- should be able to add/remove links

### Tasks
to be filled in by the developer

**Comment by AsiteZane** [comment]
Is this to get current attachment capability with tickets @carmenfan

**Comment by carmenfan** [comment]
yes, but i'm closing this

This is done prior to the attachment design, when we re-start the work again we probably have to have another think on how to deal with it (the v4 approach is a bit... 💩 )
