### ISSUE TITLE
V5 Revision list appears empty when all revisions are 'Void' and the app is refreshed

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3790]
### Description

In V5 if you void all of the revisions in a container and then refresh the page the revisions list will appear as if there are no revisions.

As a side point should the user be able to open the container when all of the revisions are voided? Currently you can and you get the empty container screen which suggests uploading a new revision (there's nothing said about voided revisions)

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Open the containers list
- On a container with revisions open the revision list
- Void all of the revisions
- Refresh the page

### Current Behaviour
- The revision list says that you don't have any files 

### Expected Behaviour
- All the revisions are listed even if they are voided

### Pictures/ Gifs of the error
All revisions voided: 
![image](https://user-images.githubusercontent.com/62481250/204031660-7b9767d9-b82d-4134-b669-7474cd1d412e.png)
After refreshing the page: 
![image](https://user-images.githubusercontent.com/62481250/204031716-fbb9a83d-6b81-4cbd-b852-098f3bba6fad.png)

**Comment by carmenfan** [comment]
> As a side point should the user be able to open the container when all of the revisions are voided? 

I don't think so, it'd be the same as an empty container - there's nothing to load

@mosment3DRepo  any thoughts?

**Comment by mosment3DRepo** [comment]
> > As a side point should the user be able to open the container when all of the revisions are voided? 
> 
> I don't think so, it'd be the same as an empty container - there's nothing to load
> 
> @mosment3DRepo  any thoughts?

Unless I'm mistaken it will open to the Empty Container screen, which is fine for now.

It's very rare that this will occur so for now I think we'll leave it on the Medium priority
