### ISSUE TITLE
"Missing/invalid arguments" message when trying to upload .bcf file

### ISSUE THREAD

**Issue by Ramadyfm** [3drepo/3drepo.io#3792]
### Description

**Description**

Customer gets a "missing/invalid arguments" message when trying to upload .bcf file to 3D Repo. Customer is exporting the .bcf file from BIMCollab.

- This is happening in production and staging 
- Hotfix is up to Product director to decide 

### Steps to replicate
Download the file here [01.bcf](https://www.dropbox.com/s/szt9f2g81xzw1fc/01.bcf?dl=0)

Upload the .bcf file in issues.

### Current Behaviour
- I get a "missing/invalid arguments" message 

### Expected Behaviour
- .bcf file to successfully upload in issues 

### Pictures/ Gifs of the error

![image](https://user-images.githubusercontent.com/100203626/204326894-0b7d48df-4116-412c-b91d-64dac3045691.png)

**Comment by carmenfan** [comment]
Putting in an empty string as default in the code worked and the BCF imported successfully

**Comment by carmenfan** [comment]
Merging into #3910
