### ISSUE TITLE
Webpack config for building webworker

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3793]
### Tasks
- [ ]

**Comment by carmenfan** [comment]
this is required in https://github.com/3drepo/3drepo.io/pull/3684

**Comment by carmenfan** [comment]
@sanmont3drepo  this is now merged into #3065 

2 things to do here:
1. review the code and make sure whatever @sebjf added to the process is how you'd like it
2. fix all the type errors/lint errors introduced (sorry 😆 )

**Comment by mosment3DRepo** [comment]
merged into #3065
