### ISSUE TITLE
Streaming Milestone 2

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#3794]
### Description
Changes to support streaming milestone 2, and another .io deployment so we don't keep touching 3065, which should be only for changes in milestone 1. (This is the replacement for 3683 which has been repurposed for the indexeddb changes.)

### Goals
- [ ] Support https://github.com/3drepo/3drepounity/issues/434

### Related Resources
Project: https://github.com/orgs/3drepo/projects/26/views/1

**Comment by carmenfan** [comment]
closing. @sebjf  i'd image we'll create a new github issue for this anyway
