### ISSUE TITLE
Accessing V5 Project List screen as a non-Admin

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3798]
### Description

When accessing a teamspace in V5 which you are not an admin in you get 2 API errors which causes the below error

The two failed API requests are:

- https://issue-3583.dev.3drepo.io/api/v5/teamspaces/mosment3ddev/quota

`{"message":"You do not have sufficient access rights for this action","status":401,"code":"NOT_AUTHORIZED","value":"NOT_AUTHORIZED","place":"GET /api/v5/teamspaces/mosment3ddev/quota"}`

- This is happening in: prod/staging/both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- Login to account A
- Give Viewer access to an individual model to account B
- Login to account B
- Access account As teamspace
- See Error Message

I have added all of the developers as users to the mosment3ddev teamspace so you should be able to see the error by going to https://issue-3583.dev.3drepo.io/v5/dashboard/mosment3ddev/t/projects

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62879582/204832728-c0c58fbb-357b-4c1a-af02-3e709cfafed4.png)

**Comment by mosment3DRepo** [comment]
This also occurs when trying to access the list of containers or federations within the project, as the project request is made again

https://issue-3583.dev.3drepo.io/v5/dashboard/mosment3ddev/7d28da00-9bc3-11ec-b553-c71ee4d334d1/t/containers

![image](https://user-images.githubusercontent.com/62879582/204835686-40f436d1-835a-4ba9-9d23-65c599e2e3ea.png)

**Comment by carmenfan** [comment]
@mosment3DRepo moved the project endpoint bug to its own issue https://github.com/3drepo/3drepo.io/issues/3799
