### ISSUE TITLE
Tree selection works as selection in 3D view (and vice versa)

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#380]
- [ ] single click selects object in tree and highlights it in 3D view
- [ ] double click selects objects in tree and zooms selected in 3D view
- [ ] ctrl + click (aka. multi-select) selects multiple objects in tree and highlights them in 3D view

**Comment by carmenfan** [comment]
- single click should work already :)
- double click to centre will require calling the following function (probably should add an event service for this):
```` js
UnityUtil.prototype.centreToPoint = function(model, id)
	{
		var params = {};
		params.model = model;
		params.meshID = id
		toUnity("CentreToObject", LoadingState.MODEL_LOADING, JSON.stringify(params));
	}
````
- multi select should just be calling the highlight event:
```` js
		} else if (event.type === EventService.EVENT.VIEWER.HIGHLIGHT_OBJECTS) {
							v.viewer.highlightObjects(
								event.value.account,
								event.value.model,
								event.value.id ? [event.value.id] : event.value.ids,
								event.value.zoom,
								event.value.colour,
								event.value.multi
							);
````
Multi select should technically work already, but I think the tree is clearing the previous highlight before highlighting the new ones. so it is probably just a matter of tracking whether ctrl is pressed before deciding whether to un-highlight everything

**Comment by carmenfan** [comment]
This has been done in around 2.0 - 2.2
