### ISSUE TITLE
Custom Ticket - view mode does not update

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#3812]
### Description
There are some problems with the view mode (perspective/ortographic)

### Steps to replicate
- In perspective mode, create a new viewpoint (**VP 1**);
- Change mode to ortographic;
- Click "Go to viewpoint" for VP 1;
- **(bug)**: the mode in the bottom bar did not update
> The same is also true the other way around

### Current Behaviour
- When you click `go to viewpoint`, the view mode in the bottom bar does not update

### Expected Behaviour
- When you click `go to viewpoint`, the view mode in the bottom toolbar should reflect the view mode used in the selected viewpoint

### Pictures/ Gifs of the error
[](https://user-images.githubusercontent.com/43547703/204765411-4a8d569b-a6c7-42c1-b8b9-cda723fddc9a.mp4)

**Comment by Amantini1997** [comment]
> > Change the view mode a couple of times;
> > Second bug: the model will disappear and you need to interact with it (zoom in/out or move the view with the mouse) to have it back on the screen
> 
> I don't think this is an issue we'd be fixing. It's a known issue that the zoom level on orthorpgrahic mode can go mad if you're switching between perspective/orthographic, even revit does this.

I updated the description to not take that problem into account

**Comment by sanmont3drepo** [comment]
> > > Change the view mode a couple of times;
> > > Second bug: the model will disappear and you need to interact with it (zoom in/out or move the view with the mouse) to have it back on the screen
> > 
> > 
> > I don't think this is an issue we'd be fixing. It's a known issue that the zoom level on orthorpgrahic mode can go mad if you're switching between perspective/orthographic, even revit does this.
> 
> I updated the description to not take that problem into account

This was fixed in the view pr.
