### ISSUE TITLE
Removing a user from a teamspace where they have been assigned to a ticket can cause an error when reassigning users

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3821]
### Description

Removing a user from a teamspace only removes their assignee status to custom tickets visually. They are still stored on the custom ticket object, so when updating the assignees the PATCH request still includes them which causes a `400 - INVALID_ARGUMENTS` error. The value does not update, so you are unable to change the assignees of any ticket which includes a removed user.

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- In the custom tickets card of the viewer assign USER A to a custom ticket.
- Remove the user from the teamspace (either through V4 or the V5 facelift if/when it is merged in)
- Return to the custom tickets card and you will see that the user no longer appears as an assignee
- Add USER B as an assignee to the ticket that contained USER A.
- An error modal will appear

### Current Behaviour
- An error modal appears warning of invalid arguments
- The assignees are not updated

### Expected Behaviour
- No error modal appears
- The assignees are updated

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62481250/207077072-c8b98b81-990a-4b2f-88e4-cc5ac927de64.png)

**Comment by carmenfan** [comment]
@The-Daniel but it'd update if you remove User A as an assignee right?

I'm not sure if this is something we want to fix.

**Comment by carmenfan** [comment]
> > @The-Daniel but it'd update if you remove User A as an assignee right?
> > I'm not sure if this is something we want to fix. If you are updating the assignee list with a user that no longer exist you are effectively giving us an invalid parameter
> 
> User A can't be removed as an assignee after they've been removed from the teamspace. They don't show up in the drop down multiselect. And the problem is that you're updating the list with allowed users and you're getting an error about invalid users

so User A could be removed if you do some work on the front end to filter it/ the request is through swagger?

**Comment by The-Daniel** [comment]
Yes, I believe this a front end problem. The removed users can actually been seen in the Select input
![image](https://user-images.githubusercontent.com/62481250/207083639-717bafbf-abc3-4d89-85b8-d65e2bf0cbeb.png)
but nowhere else. So this should also be updated.
