### ISSUE TITLE
API tests for permissions on teamspace and project

### ISSUE THREAD

**Issue by thenrikie** [3drepo/3drepo.io#385]
- [x] user (non teamspace admin) with admin_project/create_model permissions have access to the model created by themselves
- [x] user (non teamspace admin) with create_project permissions have access to the project created by themselves
- [x]  limit teamspace permission assignment to users with licence only
- [x]  limit project permission assignment to users with licence only
- [x]  limit model permission assignment to users with licence only
- [x] admin of a project have access to all models underneath?
- [x] populate implied project and model permissions in GET /:account API
- [x] unable to edit/delete default admin permission template
- [x] can't unassign licences if user is assigned any permissions

**Comment by JamesMilnerUK** [comment]
Small bug; posting permissiosn project allows you to assign a set of permissions without a user i.e. 

```
{
    "permissions": [{
    	"permissions" : ["create_model"]
    }]
}
``` 

Is a valid POST body. Assume it should throw an error.

**Comment by thenrikie** [comment]
mongo https://github.com/3drepo/3drepo.io/blob/ISSUE_385/scripts/db_migrations/v2/cacheTimestamp.js
