### ISSUE TITLE
Move notifications into a single collection inside internal db

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3850]
### Description
At the moment notifications are stored inside a `notifications` db, with each user having their own collection.

As part of the effort to reduce the number of namespaces we use inside mongo, we want to merge them all into a single collection inside `internal`, similar to what we've done with login records (#3694)

Some changes to be made to the records:
- we will need to add the `user` into the record as this is currently deduced by the collection name
- Whilst we're at it, we should change the timestamp to Date type
![image](https://user-images.githubusercontent.com/11945337/211000601-8c416c36-17f6-406a-8a69-7d5d319c702a.png)

This work will need a migration script to move all existing notifications into the new collection, ensure all new notifications are stored in the same way, and ensure all `GET` requests are fetching records from the right place.

We will also need to look into indexing the query (most likely by username) as we will have a lot of data in a single collection.

### Goals
- write a migration script to migrate the data into `internal.notifications`
- ensure index is applied to this collection
- update code to write/read from the new place

**Comment by Charence** [comment]
- [x] write a migration script to migrate the data into internal.notifications
- [ ] ensure index is applied to this collection
- [ ] update code to write/read from the new place

**Comment by Charence** [comment]
@carmenfan We can remove `notifications` from the `USERNAME_BLACKLIST`, but do we want to?

**Comment by carmenfan** [comment]
> @carmenfan We can remove `notifications` from the `USERNAME_BLACKLIST`, but do we want to?

let's leave it incase we need to downgrade or something

I don't think anyone's desperate to call themselves notifications 😆
