### ISSUE TITLE
Dates on custom tickets defaults

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3858]
### Description

Currently when creating a new custom ticket with a date field, the date will default to the current date. It is also being displayed in American date formats.

It should behave more like the date field in issues

- This is happening in: prodh 
- This requires a hotfix to production: no 

### Steps to replicate
- Create a template with a date field (example below)
- Create a ticket using that template
- Notice the date is already filled with todays date

### Current Behavior
- Prefilling today date
- Displaying in US format (mm/dd/yyyy)
![image](https://user-images.githubusercontent.com/62879582/211424945-77a7dae4-3eb9-4f03-83e4-7c21ef92619e.png)

### Expected Behaviour
- No date selection should display "Choose a date"
- Date should be displayed in dd MMM yyyy format

**Comment by The-Daniel** [comment]
@mosment3DRepo I think the date format problem might be due to your browser locality settings
![image](https://user-images.githubusercontent.com/62481250/212696752-e5dcbb78-1ec3-4ee9-bdca-91e23126fa86.png)
I get the DDMMYYYY format

**Comment by mosment3DRepo** [comment]
> @mosment3DRepo I think the date format problem might be due to your browser locality settings ![image](https://user-images.githubusercontent.com/62481250/212696752-e5dcbb78-1ec3-4ee9-bdca-91e23126fa86.png) I get the DDMMYYYY format

very weird, it seems you are correct but I have no idea how my browser has ended up like that
