### ISSUE TITLE
Collapsing/expanding the folder gives UUID instead of model names

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#386]
First time I expand it looks like this:
![image](https://user-images.githubusercontent.com/11945337/27384689-b3569df0-5687-11e7-8796-6a0fdca0e1c3.png)

If I collapse and expand the folder again model name turns into model ID:
![image](https://user-images.githubusercontent.com/11945337/27384716-d1f6bf06-5687-11e7-92ef-3efed4318133.png)

**Comment by JamesMilnerUK** [comment]
I also fixed a bug with federations in this patch. 

1. Default models appearing in other federations where they shouldnt
2. Bug with federation models being renameable / going haywire
