### ISSUE TITLE
Unity loading blocks user input/interaction

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#388]
When unity is loading the user is blocked. Perhaps some way to make the load async?

**Comment by carmenfan** [comment]
Could be wrong, as I haven't investigated it yet.

I think the reason you can't type while the unity is loading is not due the loading is freezing the UI, Unity by default overtakes the input listening which i have to proactively disable within my c# scripting code. That scripting code isn't loaded until the game has started, thus the input is blocked from the point unity is loaded to my game being initialised

That time should be reduced when we remove the splash screen, so the impact should (theoretically) be minimal.

**Comment by carmenfan** [comment]
removed the splash screen on #389 (now in staging), instead of blocked input it is now a slight lag for about ~2 seconds.

**Comment by carmenfan** [comment]
Looks like this is resolved in another issue by moving it to model loading
