### ISSUE TITLE
When the user changes his name via user profile, the hover in containers doesnt reflect it

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3886]
### Description
When the user changes his name via user profile, the hover in containers doesnt reflect it

- This is happening in: staging
- This requires a hotfix to production: no

### Steps to replicate
- Rename your user in the user profile
- Navigate to containers
- expend on a container your user createad

### Current Behaviour
- The name shown is the old one

### Expected Behaviour
- Should show the new name

### Pictures/ Gifs of the error
![renamed](https://user-images.githubusercontent.com/42032433/212906306-720f04f1-73ec-4912-ad42-fe310cc51db5.gif)

**Comment by mosment3DRepo** [comment]
does this update with a page refresh?
