### ISSUE TITLE
Release Candidate 5.0.5 

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3887]
Previously this was an issue for V5: Remove menus/buttons for non-admin users, but now it will contain all hotfixes needed for 5.0.5

### Description

Currently the APIs block users without the relative permissions from performing certain actions, but the UI should reflect this too

### Goals

- [ ] Remove options for non-admins to access areas of the app/commands they are blocked from performing
- [ ] Teamspace & Project Admins should have access, anyone with Viewer, Commenter, Collaborator access to a container/fed within the teamspace should have the options removed

### Tasks
See https://docs.google.com/spreadsheets/d/1DJWz09Nwi59TtbwRE5r4FPMHWcDsNBTaZWNnx7Ax7_U/edit#gid=289465492 for live version
![image](https://user-images.githubusercontent.com/62879582/214833686-ed7f0ff1-d3fb-4f3a-88bf-b175b4888e8a.png)

**Comment by carmenfan** [comment]
> ![image](https://user-images.githubusercontent.com/11945337/212923241-0be959e8-7607-4b11-ae44-51f6f282759e.png)

@mosment3DRepo I think you might've deleted too many things here

Collaborators of a federation (whatever that means) would have `edit federation` rights, and even viewers would be able to look at the settings, they just can't edit them.


Similar with containers

**Comment by The-Daniel** [comment]
@mosment3DRepo 
1. What should happen when a non-admin user tries to access an authorised page (e.g. by putting the URL for teamspace settings into the browser). Should it redirect to the projects tab of the same teamspace? Should it trigger an error modal?

2. Should there be some restrictions on the Teamspace Users tab?

**Comment by mosment3DRepo** [comment]
> 1. What should happen when a non-admin user tries to access an authorised page (e.g. by putting the URL for teamspace settings into the browser). Should it redirect to the projects tab of the same teamspace? Should it trigger an error modal?
We should redirect them to the project page with a modal saying insufficient access (we can use the API response)


> 2. Should there be some restrictions on the Teamspace Users tab?
"Project Permissions" and "User Permissions" should be hidden from users whihc are not teamspace or project admins

**Comment by mosment3DRepo** [comment]
@The-Daniel  I have updated the issue with a table and a link to google sheets, it should make more sense now
