### ISSUE TITLE
Resetting Sequence Timeline from Default View

### ISSUE THREAD

**Issue by Ramadyfm** [3drepo/3drepo.io#3894]
### Description
Allow sequence timeline to be at the same point  as reflected in the default view when opening a 4D model in the viewer.  Currently the timeline starts at the beginning no matter the default view. 

### Goals
Commenters, collaborators & admins to be able to create default views that correspond to the  actual date and time in the timeline when opening any 4D model in the viewer.

### Tasks

Product director to clarify

**Comment by AsiteZane** [comment]
@carmenfan  - now we store transformation data, this is solved. Create a view off of a 4D sequence.
