### ISSUE TITLE
Incorrect fed ID after fed container update on v5

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#3898]
### Description

Incorrect fed ID after fed container update on v5. It is fine after a refresh.

- This is happening in: both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- Go to v5 UI
- Edit containers in a federation -> save changes (note the fed ID)
- Open that federation (note that it attempts to use a diff fed ID)
- Fails with resource not found
- It works if you refresh the page (the project listing)

### Current Behaviour
- Fails with resource not found

### Expected Behaviour
- Should load federation

### Pictures/ Gifs of the error
![Screenshot from 2023-01-20 14-32-05](https://user-images.githubusercontent.com/1438332/213724782-966992a0-91d2-4e7e-a27a-db35b1bb31e9.png)

**Comment by sanmont3drepo** [comment]
I think this one might be related to #3979

**Comment by carmenfan** [comment]
> /azp run

@Charence  this command only works on PRs i think 😆

**Comment by Charence** [comment]
Issue still exists and demonstrated to Alessandro via screenshare
