### ISSUE TITLE
Automatic signout operates on signup/login pages

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#391]

**Comment by JamesMilnerUK** [comment]
This should be fixed now @PavolKnapo

**Comment by JamesMilnerUK** [comment]
@paloknapo says he's still seeing this on dev, but @thenrikie think's hes narrowed it down to an issue with the Node sessions library not being able to write the session JSON/

**Comment by thenrikie** [comment]
Should be fixed now. After updating the library, The log said the last logout problem caused by it was Tue Jul 04 2017 16:40:47, so the logout now users experiencing could be a genuine timeout.
