### ISSUE TITLE
Request for additional measurement type in measurements card - Polylines 

### ISSUE THREAD

**Issue by Ramadyfm** [3drepo/3drepo.io#3913]
Description
Client request to be able to  create n- number of points along a single line.

Goals

This comes from the need to measure lengths around rounded objects like curbs without the need to create lots of i lines with two points only. 

- [ ] Viewers/Commenters/Collaborators/admins can create or delete polylines in the measurements card or viewer
- [ ] Total length of the polyline to be calculated in the viewer and in the measurements card.

Tasks
To be decided by product manager

**Comment by carmenfan** [comment]
> viewers cannot create polylines

This doesn't make a lot of sense. Measurements are purely on the frontend and aren't saved in the server so there's no reason to stop viewer from doing this.

We currently don't restrict viewers from creating measurements on the measurements card.

**Comment by Ramadyfm** [comment]
The feature requested  is to create a line with multiple points. We can only create lines with two points, the client requested to be able to measure length around a curb 

I have modified the feature request to mention viewers/commenters/collaborators/admins as it was a mistake in the request.

**Comment by AsiteZane** [comment]
We want to add this to the redo of markups and measurements. To be considered in 2D too.

**Comment by AsiteZane** [comment]
This has been delivered for measurements as suggested, closing
