### ISSUE TITLE
Custom Ticket Template Swagger documentation has invalid body

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3916]
### Description

The [Add Ticket](https://www.3drepo.io/docs/#/Teamspaces/addTicketTemplate) endpoint contains the following:

```
 "modules": [
    {
      "name": "BCF Reference",
      "type": "string",
      .........
```

This is invalid as the API responds with "Only provide a name or a type for a module, not both"

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Go to the swagger docs
- Use the example json to create a template

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62879582/214902200-b233ca64-3ee3-4b4c-928b-68c02883a64b.png)

**Comment by carmenfan** [comment]
We define the schema in swagger form and it generates these examples for us.

Unfortunately swagger[ doesn't seem to support `either or` properties](https://stackoverflow.com/questions/29708505/swagger-2-0-how-to-make-one-or-the-other-parameter-required). If we were to remove one of them then we lose the definition in the schema.

I think it's better to leave it as is, and the error is explanatory enough for the user to understand that they have to remove one of them.

Reopen  with suggestions if we want to revisit
