### ISSUE TITLE
Remove teamspace admin user has no confirmation modal 

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#3919]
### Description
There used to be a confirmation modal when trying to remove a teamspace admin from a teamspace, this got lost with database schema change.

The confirmation is necessary to avoid accidentally doing something, but we don't need to summarise their permissions so it can be all front end.

If a user (admin or non-admin) has been assigned permissions to a container/federation the old confirmation modal does appear

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- In either v4 or v5 go to the teamspace user settings
- Try to remove a user who has 'Teamspace admin' permissions

### Current Behaviour
- The user is instantly removed

### Expected Behaviour
- A modal opens asking if the user is sure they want to remove a teamspace admin
- On clicking 'Confirm' the user is removed
- On clicking cancel the user is not removed and the modal is closed

### Pictures/ Gifs of the error
The old v4 modal 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/62481250/215117395-2e8a4df0-2fdc-45a1-877b-13227965f491.png)

**Comment by carmenfan** [comment]
![image](https://user-images.githubusercontent.com/11945337/217269275-3ff5e536-fe7d-4549-8caa-5bbdf210818a.png)
