### ISSUE TITLE
Unity catch-all errors refreshs the page on all JS errors

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#392]

**Comment by carmenfan** [comment]
As discussed:
(from [Unity Manual](https://docs.unity3d.com/550/Documentation/Manual/webgl-interactingwithbrowserscripting.html))
> The errorhandler function will be called when the page invokes its window.onerror event handler, and uses the same parameters. Return “true” from this function to resume execution, and “false” to pass the error to Unity’s default error handler.

**Comment by JamesMilnerUK** [comment]
I've put in some changes that will catch memory allocation errors and anything with 'unity' or 'Unity' in
