### ISSUE TITLE
Make v5 the default route

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#3921]
### Description
With next release being v5, we need to make v5 the default route on the front end

### Goals
- redirect `<domain>/login` to `<domain>/v5/login`
- redirect `<domain>/sign-up` to `<domain>/v5/signup`

**Comment by mosment3DRepo** [comment]
@sanmont3drepo we also need to update the viewpoint share link that is created in v5. At the moment it creates a link to the v4 UI, we need it to generate v5 links in v5 and v4 links in v4

![image](https://user-images.githubusercontent.com/62879582/215510867-86a61c7a-533a-4865-80de-241fc7d22803.png)

**Comment by carmenfan** [comment]
merged into #3910
