### ISSUE TITLE
Share for views should be different in v4 and v5

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#3926]
### Description

we need to update the viewpoint share link that is created in v5. At the moment it creates a link to the v4 UI, we need it to generate v5 links in v5 and v4 links in v4

### Goals
- [ ] To have a shared link that matches the version of 3drepo

### Task
- [ ] Update the share link in views

### Related Resources
![image](https://user-images.githubusercontent.com/62879582/215510867-86a61c7a-533a-4865-80de-241fc7d22803.png)

_Originally posted by @mosment3DRepo in https://github.com/3drepo/3drepo.io/issues/3921#issuecomment-1408765117_

**Comment by carmenfan** [comment]
merged into #3910
