### ISSUE TITLE
Signup throws error in the logs

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3940]
### Description

Completing a signup of a new account throws an error in the logs, but not the to the client
`2023-02-03T10:57:28.965Z [error] [MongoError: Could not find role: team_member@ssotest1]        Failed to create role for  "ssotest1"`

- This is happening in: staging 
- This requires a hotfix to production: no

### Steps to replicate
- Signup and watch the logs

### Current Behaviour
- Mongo error

### Expected Behaviour
- No errors

**Comment by carmenfan** [comment]
@keifgwinn was this through v4 or v5? or both?

**Comment by keifgwinn** [comment]
v4, doesn't replicate on v5 so can probably be closed then.

**Comment by carmenfan** [comment]
closing then, with #3924 it's virtually impossible to sign up via v4 after v5.0.0

**Comment by carmenfan** [comment]
Ran into the same problem in #3923 and fixed it in be49b908bac274b1c5d093ecbe36d6db9fe314c2

Will port the fix over to #3910 just incase we have users getting v4 verify emails and end up going through to the v4 verify endpoint
