### ISSUE TITLE
v5 user verified log message

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3942]
### Description

message when the user verified via v5 is only available in debug, not info and I believe it's something useful to have in the info logs

```
2023-02-03T12:55:53.437Z [debug] [EVENT]        [USER_VERIFIED] : {"username":"ssotest2","email":"test-ssotest2@3drepo.org","fullName":"Ssotest2 Ssotest2","company":"ssotest2","mailListOptOut":false}
2023-02-03T12:55:53.441Z [info] [NET]   200     OK      28      0       unknown POST    /api/v5/user/verify 
```

### Suggested solution
Change log event from debug to info or add the username to the NET log entry.

**Comment by carmenfan** [comment]
is it really useful?  I'm in favour not creating too much spam to be honest, and I don't think we've needed it in the past.

It's in debug because it's not actually logging user verified, that's a generic event triggered debug log (we log every event in debug for... debug reasons 😆 )

**Comment by keifgwinn** [comment]
if I have to trace what's happened with an account signup it is useful to validate that the user successfully signed up, a significant event on the platform. It rarely goes wrong of course, but if it did it would be unclear to see when the specific user verified their account other than be reference to the other activity around that username after the account is activated.

**Comment by carmenfan** [comment]
> if I have to trace what's happened with an account signup it is useful to validate that the user successfully signed up, a significant event on the platform. It rarely goes wrong of course, but if it did it would be unclear to see when the specific user verified their account other than be reference to the other activity around that username after the account is activated.

not sure. The log isn't really going to tell you much. Whether a user has been verified or not is pretty apparent by the situation in the database, or what happens when the user tries to log in. It's also going to happen less and less as SSO users would not require to be verified.

At the end of the day it's just a log, if you want it, make a PR
