### ISSUE TITLE
Accounts with lots of data take a long time to load with no user feedback

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#395]
We should provide some loading spinner/feedback

**Comment by carmenfan** [comment]
In a long run, we should really look into what is being passed and break it down potentially

**Comment by thenrikie** [comment]
It is somehow fixed in ISSUE_385 and merged to staging but need to run a db migration script for it to work. pavol's account now only takes ~300ms to load instead of ~5secs

**Comment by JamesMilnerUK** [comment]
@carmenfan agree. We should probably populate account information separately from the teamspaces/projects/models etc, giving priority to things that help provide a smooth UX

**Comment by JamesMilnerUK** [comment]
Going to put a quick fix into 1.13 https://github.com/3drepo/3drepo.io/issues/394 
Address it properly another time
