### ISSUE TITLE
Session expiry doesn't redirect to login any more

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3950]
### Description

In previous versions when the session expired then you were redirected to logon, but that doesn't appear to be happening any more.

- This is happening in: both 
- This requires a hotfix to production: yes

### Steps to replicate
- log in
- allow session to expire
- click about

### Current Behaviour
- you'll get a 401 you're not logged in and another pop up, but then you are left on the screen you were on

### Expected Behaviour
- redirect session to log in

### Pictures/ Gifs of the error

this is the user experience, three pop ups and then a failing to load page.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/23369849/217911555-be60f27f-2123-446e-9880-c8190483067f.png">
<img width="835" alt="image" src="https://user-images.githubusercontent.com/23369849/217911616-258fde70-a15c-441d-9a2c-bc90c0e2a58c.png">
<img width="510" alt="image" src="https://user-images.githubusercontent.com/23369849/217911647-00309857-5d0f-4bbf-8987-e715c2b36909.png">
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/23369849/217911701-5feae6b0-9077-4046-af0a-dc536727aee3.png">

**Comment by carmenfan** [comment]
done in #3887
