### ISSUE TITLE
View Issues / View Risks on model doesn't work

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3958]
### Description
Using the three dots on the side of a federation or issue to get a menu up and chosing view issues or view risks doesn't do anything.

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Find a model/fed with issues/risks attached
- click on the three dots
- click on View Issues or View Risks

### Current Behaviour
- Nothing happens

### Expected Behaviour
- @3drepo/product-team to decide, but I think it should go to the Kanban view, and the KanBan should have an open issue on model button.

### Pictures/ Gifs of the error
<img width="319" alt="image" src="https://user-images.githubusercontent.com/23369849/218434133-bf6bbce2-f4c4-4378-b3e2-0e5cd9f32170.png">

**Comment by sanmont3drepo** [comment]
This is already fixed
