### ISSUE TITLE
Create a federation and trying to open it immediately

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#3979]
### Description

If you create a new federation and then immediately click on it, you can do so faster than the federation can be created, so you get a number of 404 and missing file warnings when you try and open the viewer on the fed. **edit initially it appeared time based, but actually it is the frontend getting out of sync somehow after the queue returns the fed is complete, it fails to update something and doesn't work unless you refresh the whole ui.

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Make a new federation on prod
- Click into the federation to open the viewer very quickly.
- It appears to clear the queued message before it's actually ready to open.

### Current Behaviour
- Many error pop ups

### Expected Behaviour
- Shouldn't let me open it until the queue returns success from the bouncer.

### Pictures/ Gifs of the error

[fedcreaterace.webm](https://user-images.githubusercontent.com/23369849/219342806-e230ca8a-04de-40b0-87cb-c1597ca49587.webm)

**Comment by sanmont3drepo** [comment]
I think this one is duplicate of this #3889

**Comment by carmenfan** [comment]
@keifgwinn, @Amantini1997  said it was not reproducible on local. Assigning this to you to figure out what is the definitive state required to reproduce this bug and maybe we can recreate it locally manually?

**Comment by keifgwinn** [comment]
this isn't reproducible on staging any more, so perhaps fixed in the 5.0.5 hotfix
