### ISSUE TITLE
Create a new queue for quick processes so slow processes doesn't block them up

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#398]
Ideally this should be instanteous

**Comment by carmenfan** [comment]
Splitting this into 2 issues:

1. Create a separate queue for federations (and potentially tree gen, sample project import) so it's not halted by the model import jobs (this issue)

2. Change Federation update to behave in a similar way as model update, using web sockets etc so it's consistent across the board.

1 will be in 1.13 and 2 will depend on priorities.

**Comment by carmenfan** [comment]
This have to be deployed together with 3drepo/3drepobouncer#206

**Comment by carmenfan** [comment]
We also need to create a project setting before ti returns from the queue as there is potential for users to create 2 federations of the same name .

**Comment by carmenfan** [comment]
- [ ] Add a new queue ("model_queue") in queue config
- [ ] Use model_queue if we're doing a model upload, use the old job_queue otherwise.

**Comment by carmenfan** [comment]
This issue requires an update on the config. An extra queue, `model_queue` needs to be defined within the `cn_queue` json and it needs to match the name on the bouncer_worker config:

````
cn_queue: {
...
model_queue: 'modelq'
}
````
