### ISSUE TITLE
Can't create view on certain models

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/3drepo.io#3981]
### Description

Certain models (potentially ones that reqire more streaming) do not allow you to create viewpoints

- This is happening in: prod/ 
- This requires a hotfix to production: yes 

### Steps to replicate
EDIT: see [this comment](https://github.com/3drepo/3drepo.io/issues/3981#issuecomment-1433293409)
<details><summary>original text</summary>
- Open the model at the link in [Dropbox](https://www.dropbox.com/scl/fo/67krxa6ba645fpdhpsqbk/h?dl=0&rlkey=4a55p7zh2irtbgry8fxl723n7)

- Login using the support credentials

- Try to create a viewpoint
</details>

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62879582/219358706-09ba48e1-ed60-4f32-9c34-49c81d2e57d5.png)

Video in [Dropbox folder](https://www.dropbox.com/scl/fo/67krxa6ba645fpdhpsqbk/h?dl=0&rlkey=4a55p7zh2irtbgry8fxl723n7)

**Comment by carmenfan** [comment]
actual error: 
![image](https://user-images.githubusercontent.com/11945337/219411721-cefb9cf7-0f59-4660-9376-dbb0d2265852.png)

@mosment3DRepo  this seems to be related to some colour override status within the default view. It seems like it contains some colour overrides on objects that no longer exists, and when we hit create viewpoint, It is going through the colour override states to create the grouping, but struggling to find a match on sharedId to Id map.

If you hit clear colour override and try to create a view - it will work. So for this model the best thing to do that will fix this is to resave the default view point without.

We should look into solving this properly in the code but will need a front end dev to look at this properly

**Comment by carmenfan** [comment]
Merged in #3887
