### ISSUE TITLE
Socket timeouts are making the server crumble

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#401]
![image](https://user-images.githubusercontent.com/11945337/27968593-8d93d06e-633f-11e7-9bb1-c948c5cacb19.png)

Dev is dying because of connection time out to the database, but the database seems to be alive and healthy

Maybe it's just a blip or a request is taking too long for some reason, @thenrikie  when you have the time, can you look into it and see whether there's any way to catch the timeout and retry? It should probably try a few times before it drags the entire system with it if anything!

**Comment by thenrikie** [comment]
Should be fixed now. Removed all old mongo API calls which didnt handle error properly.
