### ISSUE TITLE
Model status doesn't update when you upload a new revision

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4034]
### Description
If the session started as a logged out user (i.e. you have to start your journey from the login page. The queue status doesn't seem to update when you upload a new revision.

### Steps to replicate
- Make sure you sign out of 3drepo
- hit refresh
- sign in
- go to a container and upload a revision

### Current Behaviour
- revision status stays queued if you refresh
(This doesn't seem to happen if you already have a valid session (e.g. if you refresh again and try to upload a revision)

### Expected Behaviour
- revision status should update as it goes.

**Comment by carmenfan** [comment]
@sanmont3drepo  it's possible this is a backend problem, tagging as front end for now so you guys can diagnose it first

**Comment by Charence** [comment]
@sanmont3drepo 

With a change to `bouncer_worker`, the ordering of status updates seems to be resolved and the frontend updates status, but there still seems to be a difference between a session that has just logged in vs an existing one that's either already had a revision uploaded or refreshed while logged in.

The first time a revision is uploaded after login, the status received seems to be "Queued for Unity" and "Generating Bundles".

When uploading another revision, the statuses received are "queued" and "processing". It is the same for subsequent uploads and also after refreshing the window.

Logging out and in again, the "queued" and "processing" messages don't display for the first upload.

Screen capture: https://www.dropbox.com/s/t29h14buc9u677i/Recording%202023-03-13%20at%206.37.26%20PM.mp4?dl=0
