### ISSUE TITLE
Incomplete revision are being seen as available to view

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#405]
This is a change that was introduced over a year ago in https://github.com/3drepo/3drepo.io/issues/185
But seems like we've somehow reverted it:

(Only revision within the history)
![image](https://user-images.githubusercontent.com/11945337/28019286-5cf3fbc4-6578-11e7-926c-9d12b96e179f.png)

![image](https://user-images.githubusercontent.com/11945337/28019258-3b818452-6578-11e7-9ac9-6396de980815.png)

**Comment by carmenfan** [comment]
Ah I think I know why this is, are you writing timestamps onto the project settings on REPOERR_CRASH error return?

**Comment by thenrikie** [comment]
no. if the return code is not zero (OK) then the timestamp will never be save in model settings. But in general the history model doesn't know anything about the incomplete flag so it is show in the revision list.

**Comment by carmenfan** [comment]
actually this happened in prod so it's not the cache. History model should know about the incomplete flag, as the old query pre-refactoring ignores anything with incomplete flag, for e.g. if head of the revision isn't ready and someone is requesting that, then we need to load the 1 before.

Another thing is you need to create timestamp for some with error code, namely 7, 10 and 15. for e.g. 7 is for missing texture, the user should still be able to see the model
