### ISSUE TITLE
#3966 pull request broke staging

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4052]
### Description
https://github.com/3drepo/3drepo.io/actions/runs/4346736522

**Comment by keifgwinn** [comment]
very odd, the log doesn't seem to give any indication of why it took 5 hours

**Comment by carmenfan** [comment]
> very odd, the log doesn't seem to give any indication of why it took 5 hours

jest isn't exiting because there's open handles (e.g rabbit mq or db etc). in #3923 i turned off force exit and i guess i added tests in here that didn't close a connection so it started happening after a merge

**Comment by carmenfan** [comment]
![image](https://user-images.githubusercontent.com/11945337/223493718-e52b0d49-22fc-42a9-83e0-260100c957ce.png)
