### ISSUE TITLE
Top level folder tidy up and any dead code

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#406]
Could do with a tidy up and pretty certain there is dead code in there

- [ ] X3 DOM

**Comment by carmenfan** [comment]
bid4free, occulus, walkthrough, and groups (not the little bit of code in issue, but frontend/groups folder) can all be removed i believe

Also we can remove the x3dom submodule once x3dom is removed

**Comment by JamesMilnerUK** [comment]
This is in staging now. @thenrikie FYI

All the files relating to backend are now in the backend folder
jshint -> ES Lint 
Grunt -> Gulp

**Comment by thenrikie** [comment]
This breaks the unit test and the backend app can't start because the config and certs folders are not moved into the backend folder as well, attempting to fix this
