### ISSUE TITLE
Upload and open a revision crashes

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4072]
### Description
Uploading a revision and immediately opening it has the app crashing

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- In the containers tab, click on "Upload Files";
- Select a revision and upload it to a container that you create on the spot;
> The revision I used was the LegoRoundTree
- Wait for the revision to process and the open it;
A bunch of errors should be triggered

### Current Behaviour
- A bunch of errors are triggered following an api call that goes "/undefined/undefined/sequences/?rev_id=<id>"
- The app crashes

### Expected Behaviour
- The app should not crash

### Notes
The behaviour seems to be affected by time. The longer the time passed since the processing is complete, the lower the amount of errors (I know, it sounds weird)

**Comment by sanmont3drepo** [comment]
Doesn't this have to do with #4034?
