### ISSUE TITLE
Update to Angular 2 and TypeScript

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#408]
This is going to be a sizeable task. However there is a clear path we can take to upgrade our current application:

https://angular.io/guide/upgrade

To help break this down I've compiled this set of steps:

Angular 1 = AngularJS
Angular  2+ = Angular

**Preparation**

- [x] Remove any dead code from the frontend to ease the amount of work required
- [x] For none TypeScript code leverage the AngularJS styleguide - Avoid any other syntax or approaches https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md 
- [x] Rewrite all services to follow the style guide. Ideally remove all logic and state from view models (components) [#425]
- [x] Use bootstrap instead of `ng-app` i.e.:

    ```javascript 
   angular.bootstrap(document.body, ['heroApp'], { strictDi: true });
    ```
- [x] Use webpack (or other module bundler) in our build process  
- [x] Use the [component directive](https://docs.angularjs.org/api/ng/type/angular.Module#component) rather than traditional directives
- [x] Rename files to the Angular file naming convention (kebab case with . for type i.e. foo-bar.component.js', following styleguide: https://angular.io/guide/styleguide)
- [x] Implement TypeScript preprocessor into our build step (gulp)
- [x] File by file implement TypeScript, starting with the module export syntax for the component. See comment below for more ideas around that.

**Implementation**

We will want to take the approach of `Using Angular Components from AngularJS Code` as this seems less problematic in the short - medium term. 

- [ ] SystemJS for using Angular in conjunction with AngularJS
- [ ] Create an app.module.ts which leverages ngModule and bootstraps Angular 
- [ ] Component by component convert over to Angular
- [ ] Remove AngularJS and all associated code

**Comment by JamesMilnerUK** [comment]
To help break this down I've compiled this set of steps:

Angular 1 = AngularJS
Angular  2+ = Angular

**Preperation**
- [ ] Leverage the AngularJS styleguide - Avoid any other syntax or approaches https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md 
- [x] Use webpack (or other module bundler) in our build process  
- [ ] Use the [component directive](https://docs.angularjs.org/api/ng/type/angular.Module#component) rather than traditional directives
- [ ] Implement TypeScript preprocessor into our build step (gulp)
- [ ] File by file implement TypeScript, starting with the module export syntax
- [ ] Use bootstrap instead of `ng-app` i.e.:

    ```javascript 
   angular.bootstrap(document.body, ['heroApp'], { strictDi: true });
    ```

**Implementation**

We will want to take the approach of `Using Angular Components from AngularJS Code` as this seems less problematic in the short - medium term. 

- [ ] SystemJS for using Angular in conjunction with AngularJS
- [ ] Create an app.module.ts which leverages ngModule and bootstraps Angular 
- [ ] Component by component convert over to Angular
- [ ] Remove AngularJS and all associated code

**Comment by JamesMilnerUK** [comment]
One approach that might help is to use a Angular 2 styled approach to writing components as such:

**MyComponent.ts**

```javascript
import {Component} from './decorators';

@Component({
  bindings: {
    prop: '<'
  },
  template: '<p>{{$ctrl.prop}}</p>'
})
export class MyComponent {

   prop: string;

   constructor(private $q: ng.IQService) {}

   $onInit() {
     // do something with this.prop or this.$q upon initialization
   }
}

**decorators.ts**

```javascript
/// <reference path="../typings/angularjs/angular.d.ts" />

export const Component = function(options: ng.IComponentOptions): Function {
  return (controller: Function) => {
    return angular.extend(options, {controller});
  };
};
```

**module.ts**
```javascript
import {MyComponent} from './MyComponent';

angular.module('myModule', [])
  .component('myComponent', MyComponent);
```

(https://stackoverflow.com/questions/35451652/what-is-best-practice-to-create-an-angularjs-1-5-component-in-typescript)

**Comment by carmenfan** [comment]
obsolete due to react migration
