### ISSUE TITLE
Unable to import .bcf's into model containers or federations 

### ISSUE THREAD

**Issue by Ramadyfm** [3drepo/3drepo.io#4083]
Description
This bug is seen when trying to import a .bcf file to either a model container or a federation. When trying to import the .bcf to a container model, the message 'uploading BCF' appears  but no issues are uploaded. 
When trying to import the same .bcf file into a federation, 'Internal Error Status Code: 500 error message appears. 

This bug is occurring in: Production
This requires a hotfix to production: TBD

Steps to replicate

- Create an issue in [this](https://www.3drepo.io/v5/viewer/Faisal_Ramady/f4770170-c0ef-11ed-8253-5f6c87107c4e/d1fb3d50-c0f4-11ed-b39e-b9454b38bb98) model 

- Export issue as .bcf 

- import .bcf to [this](https://www.3drepo.io/v5/viewer/Faisal_Ramady/f4770170-c0ef-11ed-8253-5f6c87107c4e/079e6ae0-c0f0-11ed-b39e-b9454b38bb98) model 

- import .bcf to [this](https://www.3drepo.io/v5/viewer/Faisal_Ramady/f4770170-c0ef-11ed-8253-5f6c87107c4e/432f4d00-c0f4-11ed-b39e-b9454b38bb98) federation

**Comment by anorrie** [comment]
This is occuring in both production and staging. 

It does not require a hotflix but we should aim for inclusion in 5.2 release. 

It is throwing the following error 

![image](https://user-images.githubusercontent.com/41000373/226656989-c287c872-af51-4f2a-8bb5-831eb7e36517.png)

**Comment by Charence** [comment]
@Ramadyfm Please add permissions for me to view those models. Thanks!

**Comment by Charence** [comment]
BCF exports were empty due to an old version of `archiver` being used.
