### ISSUE TITLE
v4 viewer background flashes when loading models in v5

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3drepo.io#4091]
### Description

When a model is loading, just before it renders, the background of v4 viewer flashes before the v5 background is displayed

- This is happening in: prod/staging/both 
- This requires a hotfix to production: no 
- 
### Steps to replicate
- Open any model
- Wait for model to load

### Current Behaviour
- Background of v4 flashes before model loads

### Expected Behaviour
- Background should remain the light blue used in the v5 viewer throughout

### Pictures/ Gifs of the error
https://3drepo-my.sharepoint.com/personal/jozef_dobos_3drepo_org/_layouts/15/stream.aspx?id=%2Fpersonal%2Fjozef%5Fdobos%5F3drepo%5Forg%2FDocuments%2FMicrosoft%20Teams%20Chat%20Files%2FDiff%20%2D%20Containers%20%2D%20Google%20Chrome%202023%2D03%2D08%2011%2D20%2D45%2Emp4&referrer=Teams%2ETEAMS%2DELECTRON&referrerScenario=p2p%5Fns%2Dbim&ga=1

**Comment by sanmont3drepo** [comment]
There is no access to that video I guess?
<img width="751" alt="image" src="https://user-images.githubusercontent.com/42032433/225340174-93eb92c0-c61d-4f07-afd0-3e09bae070ba.png">

**Comment by carmenfan** [comment]
@sanmont3drepo I think all we need here is to change the default background inside the unity game so I think this is a 3drepounity issue

Unless you can think of something in the front end side that needs changing (like if we still using the v4 placeholder background?
