### ISSUE TITLE
Not showing when a container failed to import in realtime

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4096]
### Description
When there's a problem importing a model is not being shown in the frontend in realtime. After you refresh the page you can see there was an error

- This is happening in: both
- This requires a hotfix to production: no 

### Steps to replicate
- Force an error in the import (@keifgwinn is there an easy way to do this and undo it later?)
- Click on upload files in containers
- Upload a file to a new destination (a new container)
- Wait for the process to finish

### Current Behaviour
- The process failed but is not showing it in the frontend

### Expected Behaviour
- Should show the error

### Pictures/ Gifs of the error
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/42032433/225600389-5a4268fa-200e-4bc7-9826-b1637b59daf4.png">

**Comment by carmenfan** [comment]
> Force an error in the import (@keifgwinn is there an easy way to do this and undo it later?)

@sanmont3drepo  Would a corrupted file work? like create a model file with a valid extension but put jibberish in it
