### ISSUE TITLE
When creating a new ticket with Issue Properties the priority sometimes defaults to 'Low' instead of 'Unset'

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4139]
### Description

When you try to create a ticket for a template that has issueProperties the priority defaults to 'Low' (I'm pretty sure this should be 'unset')
If you try to create a successive new ticket of the same type (without closing the tickets card) the priority defaults to 'Unset'.
Closing the tickets card resets it.
This is probably due to the fetchTemplate which is called the first time you open the new ticket view for a template. Later times the template data has been stored in redux so there is no loading time

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Open a model
- Open tickets list
- Click create new ticket
- Select a template which has issueProperties = true
- You should notice that the priority is set to 'Low'
- Click the X button to return to the ticket list
- Try to create the same type of ticket again
- The priority will default to 'Unset'
- If you close the tickets card and reopen this will reset it, so the first ticket you try to create will default to 'Low' again

### Current Behaviour
- On the first attempt the priority defaults to 'Low'
- Thereafter it defaults to 'Unset'

### Expected Behaviour
- The priority always defaults to 'Unset'

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62481250/227586262-3f0151e7-305c-4d60-a989-dfda056a6da1.png)
![image](https://user-images.githubusercontent.com/62481250/227586368-1912e6c1-69fb-44a7-bef5-be9fd5690127.png)

**Comment by carmenfan** [comment]
> When you try to create a ticket for a template that has issueProperties the priority defaults to 'Low' (I'm pretty sure this should be 'unset')

This should be whatever the template endpoint tells you no?

It shouldn't be bespoke, we should always read the data from the template
