### ISSUE TITLE
For startup scripts use npm scripts (package.json) rather than bash/bat scripts

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#414]
It is cleaner, more consistent and in line with common practice

**Comment by thenrikie** [comment]
Some of them with too many logic inside and can't be converted. The only convertible one would be cleanup.sh

**Comment by JamesMilnerUK** [comment]
@thenrikie for sure. I was referring to the ones in the top folder, run_app.sh and .bat etc

**Comment by thenrikie** [comment]
oic, I actually never use that, maybe we can get rid of that. 
You can use `NODE_ENV=<env> npm run dev `instead

**Comment by carmenfan** [comment]
setting envvar on the same line like that doesn't work on windows, this is probably why we have a *.sh and *.cmd

**Comment by JamesMilnerUK** [comment]
because package.json is in frontend/backend folders now, and run scripts are in /run/ I think this isn't so necessary/possible anymore. I'll close it.
