### ISSUE TITLE
Utility script to get summary mesh information to calibrate decimation algorithm

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#4141]
### Description
This is an invalid branch to provide a utility script to extract mesh information in order to support https://github.com/3drepo/3drepobouncer/issues/599

The branch contains a utility script, `getMeshProperties`, to be run against a representative database in order to calibrate the quality settings for mesh decimation.

**Comment by keifgwinn** [comment]
crashed out on the first run 

`{"level":"info","message":"Processed 12595097 meshes across 1345 revisions... ","timestamp":"2023-03-28T17:04:48.270Z"}`

it got this far
