### ISSUE TITLE
Deleting a project with a lot of content is non-intuitive

### ISSUE THREAD

**Issue by keifgwinn** [3drepo/3drepo.io#4143]
### Description

If you delete a project with the v5 interface with a lot of content, the interface gives a poor ux by simply not appearing to respond at all. Underneath it's working through the long job of correctly cleaning up all the models from the system, but it just appears nothing is happening. If you cancel the modal then the project disappears from the view.

### Goals

- [ ] More feedback as to what's happening during a project delete

### Tasks
- [ ] tbd

### Related Resources

https://user-images.githubusercontent.com/23369849/228312198-756632e2-a93a-4a43-8087-4f67b16e4e5e.mp4

**Comment by carmenfan** [comment]
closing in favour of #4290
