### ISSUE TITLE
Change background of login/signup page

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3drepo.io#4149]
### Change background of login/signup page to use animated background
Using the JS script [here](https://www.vantajs.com/?effect=waves#(backgroundAlpha:1,color:527909,gyroControls:!f,minHeight:200,minWidth:200,mouseControls:!t,scale:1,scaleMobile:1,shininess:5,touchControls:!t,waveHeight:16.5,waveSpeed:0.45,zoom:0.9992042677475115)), can we add this to the background of the login screen?

### Related Resources
Design mockup
<img width="1581" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/78047794/229068152-2ca2f6a9-f3ab-42d6-8be2-10ff28d42b39.png">

@carmenfan I'd like to improve the login screen and want to know if we're able to push this forward?

**Comment by carmenfan** [comment]
@george-hadfield  I think it's best if we try it out and see.

Though I wouldn't say it's mission critical so we'll probably try it out when we do the other aesthetic changes

**Comment by carmenfan** [comment]
closing as won't do - we literally just changed the background image to somethign else!
