### ISSUE TITLE
Cannot destructure property 'teamspace' of 'e[0]' as it is undefined error message displayed when trying to perform 3D Diff 

### ISSUE THREAD

**Issue by Ramadyfm** [3drepo/3drepo.io#4181]
Description

This bug is encountered by certain clients for all models when trying to perform 3D Diff 

This bug is occurring in: Production
This requires a hotfix to production: TBD

Steps to replicate

The error occurs only for some clients for **all** models when trying to perform 3D Diff between different revisions

Screenshot of error message in web browser console can be found [here 
](https://www.dropbox.com/s/0q91i1jatghcofw/3D%20Diff%20error%20message.png?dl=0)
HAR file can be found [here ](https://www.dropbox.com/s/k6yt4e4blioox9s/3D%20Diff%20Error.har?dl=0)

**Comment by Charence** [comment]
Faisal says this issue happens all the time for 2 clients. Faisal says it happened 1 time randomly for him.
