### ISSUE TITLE
Models not unloading properly when switching federations / containers

### ISSUE THREAD

**Issue by anorrie** [3drepo/3drepo.io#4185]
### Description

When switching between federations the previous federation will still load in the viewer unless there is a refresh of the browser. This results in the user either seeing the old model, both models or now model. This is presumably determined by the position of each model. 

- This is happening in: both 
- This requires a hotfix to production: yes 

### Steps to replicate
- Open a model 
- return to teamspace 
- open a different model 

### Current Behaviour
- You will either see the first model, both models or now models 

### Expected Behaviour
- You should see only the new model
- 
### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/41000373/233319785-f6e75373-12d2-4710-b48f-71599cc3919d.png)

**Comment by sanmont3drepo** [comment]
<img width="1280" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/42032433/233141821-046b0a5d-1aa4-44be-85f7-dfedf7732b06.png">
There seems to be a problem with clearing the canvas of some particular models

**Comment by sebjf** [comment]
Hi, is there a model on staging or production that reproduces this?

**Comment by sebjf** [comment]
Hi, there is a hotfix here: https://github.com/3drepo/3drepounity/pull/471
