### ISSUE TITLE
Upload file sidebar form errors are not being displayed

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4188]
### Description

The sidebar inputs no longer display error text or error borders. The submit but is disabled but there is no indication as to why

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- In the upload file modal select a new container to u[pload a file to
- Set one of the fields to error (e.g. enter symbols into 'Code' or put too long a string into desc or revision name)

### Current Behaviour
- The submit button disables.
- There is no helper text or error outline

### Expected Behaviour
- The submit button disables.
- There is helper text and an error outline like other erroring text inputs

### Pictures/ Gifs of the error
![image](https://user-images.githubusercontent.com/62481250/233104003-8e53b844-4807-43aa-bfe4-71b5dbb7143c.png)

**Comment by carmenfan** [comment]
resolved in #4258
