### ISSUE TITLE
Automatically open sequence to today's date when going into a model

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4191]
### Description
We need the ability to open a sequence model to today's date

### Motivation
Customers who upload sequenced models (SPMs) or attach a sequence to their model (via API), would like to see what is the expected state of affairs for the current date. 

Initially it was suggested that the model should immediately load the sequence to today's date, but this may be troubling for any customers who do not want this behaviour, and thus we would have to introduce this as a model setting. They will also not have the capability of loading it back to the same date again easily if they have modified it.

### Suggested implementation
If we create a button for users to go to today's date in the sequence, then it would be less intrusive than automatically doing it whilst still making it easy for users to do so.

If Todays' date is:
- within the sequence time frame - go to the date as normal
- before the sequence starts - go to the beginning state of the sequence whilst showing today's date.
- after the sequence has ended - go to the end state of the sequence whilst showing today's date.

#### UI changes
we will need add to the UI somewhere to allow the date to quickly change to today's date (and current time?) on the sequence UI: 
![image](https://github.com/3drepo/3drepo.io/assets/11945337/d4de01e9-22e2-4bde-9bf8-0d00f1135fd3)

**Comment by george-hadfield** [comment]
[Link to design](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=752%3A44871&mode=design&t=mkSq7PMUQU1uvBg3-1)

**Comment by carmenfan** [comment]
close superseded by #4568
