### ISSUE TITLE
Edit Image still clickable for read-only custom tickets

### ISSUE THREAD

**Issue by ChristosTsiotsias** [3drepo/3drepo.io#4216]
### Description
When viewing a ticket in read-only state the Edit Image button is still clickable. Also the user can click on Add Image canvas and a file dialog will pop up. They are not able to upload one since the backend returned error but it misleads them to believe they can.

### Steps to replicate
View a custom ticket with an image property with a user that only has permission to view and not edit.
The Edit image button is clickable.
Also Clicking on Add image canvas will pop up a file dialog

### Expected Behaviour
The Edit image button should be disabled and clicking on Add Image should do nothing.

### Pictures/ Gifs of the error
![image](https://github.com/3drepo/3drepo.io/assets/71635617/cb5a11f6-69d5-40fd-83d0-34286bbf8a15)

**Comment by Amantini1997** [comment]
This problem is already being tackled in https://github.com/3drepo/3drepo.io/issues/4214
As that will replace the current UI, I am closing this
