### ISSUE TITLE
Look at ways to decouple frontend from backend 

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#422]
Ideally we would want it so that the Pug templates are rendered to static HTML. This is more performant and less error prone (i.e. no Pug errors on the client!). Pug could be rendered with a Gulp task. 

One of the biggest problems at the moment is we pass `PUG_VARS` to the client by echoing them to a script tag to be picked up as globals by the AngularJS code, which is somewhat ugly. We should be able to decouple this!

**Comment by carmenfan** [comment]
Sounds like it's something we've done already when you changed it to backend rendering?

**Comment by JamesMilnerUK** [comment]
It's certainly better, we're not rendering the config into the page any more, but it's still not perfect. Ideally the config would be part of the API rather than in the frontend service and we could just serve files statically from the frontend service. At the moment all unexplictly defined files we serve the home page which isn't ideal (it should 404). 

Because we build to the public directory we have to serve static files out of it, but this causes certain features to not work correctly (i.e. service worker, manifest file required to be at the top level directory). 

Ideally I would actually offload the static file server to something like nginx, but that's a lot of extra work for relatively limited reward at the moment.

**Comment by carmenfan** [comment]
@JamesMilnerUK  I feel like we've done this. If not it probably needs a fresh issue specifically stating what is the remaining task
