### ISSUE TITLE
Custom Tickets: Groups - Multiple tiers select box

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4223]
### Description
For add/edit groups we need a select box with multiple tiers for selecting the collection

### Goals
- [ ] Have a select box that can take a list of hierarchies 

### Tasks
- [ ] Create the `<GroupsCollectionSelectBox  hierarchies={viewpoint.state.colored}  onChange={...} value={...}  />` component

### Related Resources
<img width="560" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/4a629f23-e107-4c74-84e1-fc08388ba241">

[Mockup](https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?type=design&node-id=3251-29959&t=8d3eFypYxfk5kqHE-0)

**Comment by carmenfan** [comment]
merged into #3933
