### ISSUE TITLE
Add Hotjar Analytics code to prod

### ISSUE THREAD

**Issue by george-hadfield** [3drepo/3drepo.io#4228]
### Description
Adding the code snippet from _Hotjar_ so the George and the Product Team can get insights into user behaviour to help validate design decisions.

#### NOTES:
- It should be configurable whether hotjar is applied to the deployment (We don't want to do it for local/staging etc)
- Hotjar id should come from the configuration file so it can be changed without code level changes.

### Tasks
- [ ] Paste the code into the <head> of every page where you want to track user behavior or collect feedback.
- [ ] Get George to verify installation in Hotjar platform once installed.

### Related Resources
Code snippet:

```
<!-- Hotjar Tracking Code for https://www.3drepo.io -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3503717,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
```

**Comment by carmenfan** [comment]
closing in favour of 4569
