### ISSUE TITLE
Update README/Scripts to be in sync with new folder structure

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#427]
@timothyscully did you mention there was some script that needed some reworking?

**Comment by carmenfan** [comment]
Looks done to me. if not reopen and say what's missing!

**Comment by JamesMilnerUK** [comment]
Probably best to ask @Charence  :stuck_out_tongue:

**Comment by JamesMilnerUK** [comment]
also screenshot is out of date, not a massive deal though
