### ISSUE TITLE
Hide groups in hidden groups section in groups tab

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4276]
### Description
In groups there is a collection of hidden groups. we need a way to apply those hidden groups

### Goals
- [ ] Have a way to hide the hidden groups with the same granularity as with overrides

### Tasks
- [ ] Same functionality as with color overrides but with hidden groups

### Notes
Take in consideration that when group is clicked in the list it should highlight the nodes showing them
and when is dehighlighted if the group was hidden it should hide again

**Comment by carmenfan** [comment]
Merged into #3933
