### ISSUE TITLE
Issue pin does not change colour until the viewer refreshes

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4283]
### Description
When you change the priority of an issue, the pin colour does not change until you refresh the page

- This is happening in: both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- open any model
- create an issue, drop a pin
- change the priority to something different (e.g. high)

### Current Behaviour
the pin doesn't change colour until you refresh

### Expected Behaviour
the pin should change colour as soon as priority has been changed

### Pictures/ Gifs of the error
![img](https://github.com/3drepo/3drepo.io/assets/11945337/80692d59-4f7e-4bdc-a890-fb72c8fc736f)

**Comment by sanmont3drepo** [comment]
This one is fixed in #4314
