### ISSUE TITLE
Custom Ticket: Groups - Bug fixes

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4299]
### Description
- [x] Update a smart group in a viewpoint -> Update the camera -> go to view no longer works for that viewpoint; (mentioned in #3933 but cannot reproduce)
- [x] Viewpoint should be valid if it has at least one of the following: camera, clippingPlanes, state;
- [x] In a new ticket, `save current view` attempts to save the ticket;
- [x] (this may depend on the bug above) In a new ticket, with some groups selected in the groups panel, `save current view` does not save the viewpoint
- [x] selecting the no-color from the palette for a colored group triggers error modal
> This may not be a quick fix. It may need to tweak modest amount of code 
- [x] Hover state of "add to favourites" icon (in containers/fed list) has wrong background color

<i>The following bug has been fixed in #4285</i>
- [ ] Change the camera position and the checked overrides, then update/create a group. The camera gets repositioned and the overrides are wrong (if this is done in a view different from the `ticket default view`, the overrides do not even match the groups)
- [x] Select groups override in v4 and try to create a viewpoint . The app crashes. It should create the new viewpoint whith the overrides a groups.

**Comment by carmenfan** [comment]
Merged into ISSUE #4196
