### ISSUE TITLE
Not able to edit the location of a issue or safetibase pins

### ISSUE THREAD

**Issue by Ramadyfm** [3drepo/3drepo.io#4301]
### Description
No longer able to edit positions of issue or safetibase pins 

- This is happening in: production 
- This requires a hotfix to production: no

### Steps to replicate
- Open this model: [here](https://www.3drepo.io/v5/viewer/Faisal_Ramady/fbdde3f0-4df6-11ed-9d86-577ac9033907/2751e730-5161-11ed-9d86-577ac9033907) 
- Click on any created issues or risks and try to edit their pin locations

### Current Behaviour
- Not able to edit the location of saved pins

### Expected Behaviour
- Should be able to edit saved location of pins

**Comment by carmenfan** [comment]
Work around:

It seems to work if you first try to remove the pin (i.e. click on the background), then click on the desired new location.


But yes confirmed bug that also happens on staging.
