### ISSUE TITLE
Retain hidden elements in saved views across different revisions 

### ISSUE THREAD

**Issue by Ramadyfm** [3drepo/3drepo.io#4302]
### Description
It is often the case that clients work with updated model revisions which multiple project stakeholders have to engage with. We currently only save viewpoints but do not keep hidden elements in saved views across different revisions.

### Goals
Retain hidden elements:
- [ ]  In saved views across different revisions
- [ ]  In saved issues and risks across different revisions 
- [ ]  When importing .bcf's

**Comment by carmenfan** [comment]
As discussed, it's not really easy to identify revisions across objects therefore it's not something we support fully.

It should work with IFCs  (not v5 custom ticket groups) - I just verified that it does work

We could possibly make it work for any BIM file formats with consistent IDs but that would need some scoping

The quickest way is to advice the clients to use IFCs in their workflow.

**Comment by carmenfan** [comment]
As discussed, not something we can support
