### ISSUE TITLE
Do a DB migration to get rid of default models/federations

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#431]
Default models and federations cause a lot of extra complexity on the frontend. We could just create a default project in the database for models.

**Comment by thenrikie** [comment]
It's done but I found a unexpected behaviour and that is now you can add new models to 'Default' project  because default project is really a project in database now.

**Comment by carmenfan** [comment]
I think that's fine, if they really want to do it they should be able to do it

**Comment by thenrikie** [comment]
mongo scripts/db_migrations/v2/moveOrphanToDefaultProject.js
