### ISSUE TITLE
Model uploads are sending "undefined" as the description when the user doesn't provide a description

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4312]
### Description
![image](https://github.com/3drepo/3drepo.io/assets/11945337/3c632219-a4c4-409e-ad38-20c27ee0bba5)
### Steps to replicate
- upload a model without filling in the description

### Current Behaviour
- uploaded model has a description of `undefined`

### Expected Behaviour
- uploaded model should have a blank description

**Comment by sanmont3drepo** [comment]
@The-Daniel  take this in consideration when addressing https://github.com/3drepo/3drepo.io/issues/4258
