### ISSUE TITLE
Get 3drepo.io to align as a Progressive Web App (PWA)

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#432]
"Progressive Web Apps are experiences that combine the best of the web and the best of apps. They are useful to users from the very first visit in a browser tab, no install required. As the user progressively builds a relationship with the app over time, it becomes more and more powerful. It loads quickly, even on flaky networks, sends relevant push notifications, has an icon on the home screen, and loads as a top-level, full screen experience." - [Google](https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/)

Marketing spiel aside, making 3drepo.io into a progressive web app would allow us to do a few things that we want whilst also being in line with modern development practices. The key advantages:

- [x] Installable to homescreen via manifest.json like a regular app (**Easy**)
- [x] Mobile friendly responsive design for all device sizes (**Medium**)
- [x] Uses service worker for offline support (**Hard**)
- [ ] Push notifications (**Hard**)

There are other parts to the PWA pattern but we're either already doing them or they're not overly critical. The cool thing here is that it's not an all or nothing approach, we can piecemeal add in these features.

Here's a nice article explaining [what you get for free](https://getpocket.com/a/read/1831678907) with a PWA

**Comment by carmenfan** [comment]
closing as majority has been done. It will probably be a separate issue when the need arises
