### ISSUE TITLE
Use new Toolbar design

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4325]
### Description
There exists a new design for the viewer toolbar. For the new design, however, it will not be enough to just edit the styling. 
The coords function, in fact, tells Unity to render the coords at the bottom, meaning there is no control over their styling and positioning in React.

### Suggested solution
- we could move that rendering inside React by implementing a Unity endpoint or we can have Unity rendering it in a different position

### Current Design
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?type=design&node-id=1027-8244&mode=design&t=FDuaLttiFAv9rTdO-0

### New Design
https://www.figma.com/file/3FjNEOdQbcHwzquVZxUqMl/3D-Repo?type=design&node-id=1027-8244&mode=design&t=FDuaLttiFAv9rTdO-0

**Comment by carmenfan** [comment]
closed as we have a different tool bar design now
