### ISSUE TITLE
Group caches are not clearing between switching revisions

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4349]
### Description
When we save groups within a IFC container, we store ifc guids so object selections are preserved across revisions. This logic seems to be working, but on the front end, we are storing a cache of the group content, which is not being cleared when we switch revisions - resulting in an appearance that this function is not working.

### Steps to replicate
- open an IFC based container where you have 2 revisiosn (can just upload the same model twice)
- create a view with hidden/highlighted objects
- **WITHOUT** refreshing, go to a different revision
- click on the view to reinstate it

### Current Behaviour
- hidden/highlighted objects are not shown unless you refresh

### Expected Behaviour
- hidden/highlighted objects should map across revisions on ifc files

### Pictures/ Gifs of the error

![img](https://github.com/3drepo/3drepo.io/assets/11945337/b0d40fd7-f1e1-472d-930b-9e1c0884b12c)

**Comment by sanmont3drepo** [comment]
Fixed in #4354
