### ISSUE TITLE
Augment field definition in ticket groups 

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4384]
### Description
We are adding support in smart rules to search for substring or a user specified regex. This requires changes on the Add/Edit group panel within the ticket groups, and the update the logic

**This is a sub task of #4386. Please branch/merge with that branch instead of staging.**

Figma design: https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=715-17375&mode=design&t=QUnvuU28wOnbtypc-0

Backend/schema specification: https://github.com/3drepo/3drepo.io/issues/4383

#### Notes:
- By default, Field operator should set to `IS`
- There needs to be at least one value
- if operator is `REGEX`, there can only be one value thus `+` should be disabled.
- We should keep the suggested drop down and should be available regardless of operator (even regex, so the user can then trim it to their liking and add syntax to prevent typos)
- after https://github.com/3drepo/3drepo.io/issues/4383, the backend will always output the new schema, so you do not need to expect field to be a string.
- Title is a new field for the rule and is required. the name of the rule will then be displayed as a chip
- We also need to do this for V4 groups - if there is any common code for consideration.

### Goals
- [ ] The user should be able to create rules where they specify a subset/regex matching string for the field name
- [ ] The user should be able to edit those rules as they wish.

### Tasks
Developer: please fill this in as appropriate

### Related Resources
figma: https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=715-17375&mode=design&t=QUnvuU28wOnbtypc-0
scoping document: https://github.com/3drepo/3D-Repo-Product-Team/issues/308
backend issue: https://github.com/3drepo/3drepo.io/issues/4383

**Comment by The-Daniel** [comment]
> There needs to be at least one value

@carmenfan this means out of both the `field` and `value` sections, right? E.g. the field value can be left empty as long as the value field has a valid value

**Comment by carmenfan** [comment]
closing as it's been merged into https://github.com/3drepo/3drepo.io/issues/4386
