### ISSUE TITLE
Custom ticket filters not updated upon Completed filter click

### ISSUE THREAD

**Issue by ChristosTsiotsias** [3drepo/3drepo.io#4400]
### Description

Filter's label (count) should update when Completed filter is clicked to show the number of tickets that have the filter template but also satisly the Completed filter. 

However, this does not seem to happen as count stays the same regardless of the Complete filter active status.

### Steps to replicate
- Open a model with multiple tickets of multiple templates
- Click Completed filter
- The count in the label of filters does not update

### Pictures/ Gifs of the error
![image](https://github.com/3drepo/3drepo.io/assets/71635617/71e1275f-1fcd-47af-b321-308a8c3ed51a)
![image](https://github.com/3drepo/3drepo.io/assets/71635617/9da14421-aeb3-4d9b-8919-8d89b4cec04c)

**Comment by The-Daniel** [comment]
@carmenfan a question about how the counts should would with search and chip filters
I take it we want the number to change when adding a search filter, right?
![image](https://github.com/3drepo/3drepo.io/assets/62481250/b83dfe99-4c4c-4018-8b01-f1523b30e4ca) ![image](https://github.com/3drepo/3drepo.io/assets/62481250/0c513c9a-4c84-4ace-9091-b15e6e27d780)
But then we want the numbers to persist when filter chips are selected? So you know which filters chips will add items to the list.


What I currently have (below) shows the number of each template in the list, so having a chip selected sets all others to 0. Now I can't see which chips might be useful to select. (this does not apply to the completed chip which is separate and works as this issue specifies)
![image](https://github.com/3drepo/3drepo.io/assets/62481250/efb542a2-95d2-452e-844e-257f0a25cd4d)

**Comment by carmenfan** [comment]
@The-Daniel yes so conceptually speaking we break this into 2 parts:

![image](https://github.com/3drepo/3drepo.io/assets/11945337/abac8247-2024-4bc2-b382-d3d0ce368839)


The ones circled would depict the count on the ones that are not circled.

**Comment by The-Daniel** [comment]
> @The-Daniel yes so conceptually speaking we break this into 2 parts:
> 
> ![image](https://user-images.githubusercontent.com/11945337/273856693-abac8247-2024-4bc2-b382-d3d0ce368839.png)
> 
> The ones circled are filters that are applied to the list of tickets that would depict the count on the ones that are not circled.

Brilliant, thanks!
