### ISSUE TITLE
Add an option to run with unity 2023 

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4448]
### Description
We want to offer unity 2023 build of our game as an experimental feature to a selection of our clients, whilst keeping everyone else on the current viewer.

A change has been made in #4418 for the `UnityUtils.init` function to take an optional argument to determine which viewer to load.

We need to wire this to the viewer settings so the user can switch this feature on and off.

#### Changes in viewer settings
![image](https://github.com/3drepo/3drepo.io/assets/11945337/67c4e8d9-a52d-4193-8602-078b354a8259)
- Add a toggle button on here for `Use 4GB viewer (Experimental)`
- If this data has been changed, warn the user that they will need to refresh the page in order for this change to take effect
- if this is flagged, pass true to `useBetaViewer` in `UnityUtils.init`.

### Goals
- As a standard user, nothing should change and I should be able to use 3drepo as before.
- As a user looking to evaluate the latest viewer, I should be able to change to the experimental viewer and try out this feature.

### Tasks
TBC by the developer

**Comment by george-hadfield** [comment]
[Link to design](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=1233%3A17751&mode=design&t=QcGi5qykXAcnYKSg-1)

**Comment by carmenfan** [comment]
merged into 4418
