### ISSUE TITLE
Minor visual bugs when entering a long search term into viewer issues/risks search bar

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4463]
### Description

Very minor bug as it is unlikely to happen and is purely visual.
When a long filter is added to an issue/risk search there are two visual bugs when collapsing the search bar:
- The expand button overlaps with the search tag
- An unnecessary scroll bar appears

---

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- Open a risk/issue
- Click the search button
- Add a long filter (so long that it become truncated in the search tag)
- Collapse the filters

### Current Behaviour
- The expand button overlaps with the search tag
- The user can scroll revealing empty space

### Expected Behaviour
- The expand button does not overlap any element
- The scrollbar does not appear unless there are elements hidden below

### Pictures/ Gifs of the error
![image](https://github.com/3drepo/3drepo.io/assets/62481250/40cb3ecb-6da0-43f5-b5ea-e194579e2ae5)

**Comment by AsiteZane** [comment]
No longer taking risks and issues forward and this is not replicable within tickets so not an issue - thank you for raising.
