### ISSUE TITLE
Clip Tool Improvements

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#4477]
### Description
Rebuild the Clip Tool to the specification here: https://github.com/3drepo/3D-Repo-Product-Team/issues/250

The Unity changes are here: https://github.com/3drepo/3drepounity/issues/479, which include all the logic and the 3D UI. The Unity Issue will also include an updated toolbar for embedded viewers.

This issue should rebuild the toolbar in the frontend however, utilising the public API of the Clip Tool.

**Comment by carmenfan** [comment]
closing, superceded by #4623
