### ISSUE TITLE
Use HTTP/2 

### ISSUE THREAD

**Issue by JamesLMilner** [3drepo/3drepo.io#450]
https://developers.google.com/web/fundamentals/performance/http2/

**Comment by keifgwinn** [comment]
This will be addressed with the load balancing front end for client access.

**Comment by carmenfan** [comment]
Closing this as it's best left to be done at load balancers/devOps domain.

http2 isn't supported by the browser without https protocol, which will make development setup more painful. Or we'd have to make it a configuration option to use http2 and have a major refactoring to support both.
