### ISSUE TITLE
4gb viewer doesnt work in firefox

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4506]
### Description
When opening the viewer in firefox if the selected viewer is 4gb the app crashes. 
(I don't know if you can do anything @sebjf or we should just open the other viewer in case of firefox)

- This is happening in: staging
- This requires a hotfix to production: no 

### Steps to replicate
- go to visual settings and enable the 4GB viewer 
- navigate to a container or federation

### Current Behaviour
-  the viewer crashes

### Expected Behaviour
- It should load the container or viewer normally

### Pictures/ Gifs of the error
<img width="884" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/1bec50a0-7169-4f7b-bc77-e76aafef89a9">

**Comment by carmenfan** [comment]
this is related ot my comment in the unity branch here https://github.com/3drepo/3drepounity/issues/481#issuecomment-1750977756

Auto switching is not preferable as we don't want to maintain 2 viewers (the 4GB viewer is actually a later version of unity that gives us the option to expand to 4GB - the ability to have 2 viewers is just a temporary thing and we plan on dropping the old viewer going forward)

So I think we need a adaptive/configurable memory setting on the 4GB viewer going forward

**Comment by sebjf** [comment]
There is a deployment with a workaround to resolve this here ready for testing: https://issue-4506.dev.3drepo.io/v5/login
