### ISSUE TITLE
Cherry pick fixes from master

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#451]
There are a lot of fixes on masters that aren't propagated back into staging branch. Granted some are irrelevant (x3dom fixes), some are pretty important (like #361)

Using this branch to cherry pick commits from master and ensure everything still works. could be difficult with front end code..................... :(

**Comment by JamesMilnerUK** [comment]
If you pick them in just let me know and which frontend code it is likely to effect. I'll try to fix any potential bugs

**Comment by carmenfan** [comment]
I ended up deciding that the changes aren't that crazy and just merged it into the branch and tested.

Ignored every change on the front end as it was either x3dom related or it changed a lot. Only thing of concern might be the measuring tool component, but since Unity is going to be driving it instead of listening to the mouse clicks and talking to x3dom, i don't think the changes were that relevant.

This is already in staging, the only significant change was Henry's username check #361. So i don't think there will be much impact on the frontend

**Comment by carmenfan** [comment]
**Model refresh -> not reconnecting to chat service**
- Upload a medium size model so it doesn't finish straight away
- Wait till it's processing and refresh
- It no longer says processing, even though the processing hasn't finished
