### ISSUE TITLE
Custom tickets dates are converted to string

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4519]
### Description
Given a ticket with dateTime inputs (sequencing will use them, so at the moment, there is none available yet), when the user changes the value, the frontend sends the new value as a number, but then the chat event sends back a string 
![image](https://github.com/3drepo/3drepo.io/assets/43547703/8054ce2c-1c11-4b68-b8c9-e2e3d3d37c02)

For existing dates, it's not a big deal perhaps, but when the frontend tries to clear the input sending either the number 0 or null, the backend sends back a stringified date object set to 01/01/1970 
![image](https://github.com/3drepo/3drepo.io/assets/43547703/24a0a136-4b09-4c0f-9686-8035e854cfa8)
- This is happening in: both
- This requires a hotfix to production: no

### Steps to replicate
- branch off from #3609 (you have to create a ticket with sequencing module)

### Current Behaviour
- The date is sent as a string

### Expected Behaviour
- The date should be sent as a number

**Comment by sanmont3drepo** [comment]
this is a backend issue?
