### ISSUE TITLE
Some actions in the Viewer are not disabled for users with viewer permissions

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4529]
### Description

A user with viewer permissions can:
- click a safetibase/risk sequence and set a date and time. Upon doing so they get an error modal
- Click the safetibase/risk shapes options
- Add sequence legends
Doing any of these gives an 'unauthorised' error modal

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- As a user with viewer permissions open the safetibase card
- Open the 4D tab and you will see that the sequences inputs are enabled

### Current Behaviour
- The sequencing inputs are enabled

### Expected Behaviour
- The sequencing inputs are disabled (except for the 'Go to sequence' button)

### Pictures/ Gifs of the error

![image](https://github.com/3drepo/3drepo.io/assets/62481250/298d8e61-be03-4e45-ba8f-22a84d3f7087)
![image](https://github.com/3drepo/3drepo.io/assets/62481250/d4babe63-acb8-45a9-a4e4-701e38d18a5b)
![image](https://github.com/3drepo/3drepo.io/assets/62481250/ec050184-4aca-43cf-96e1-523d406536e8)
![image](https://github.com/3drepo/3drepo.io/assets/62481250/ea4ba25f-2cc5-4d1e-93e2-3e6d4fcea54d)

**Comment by AsiteZane** [comment]
Not taking risks and issues forward therefore no need to fix - thank you for raising.
