### ISSUE TITLE
Put corID onto model settings when we request work from bouncer

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#453]
Put corrID in model settings inside the database (and wipe it when the processing returns)

as it stands it's either some sort of guess work with bouncer log (i.e. latest request) or crawl through 3drepo.io log to find this either. Log crawling should be last resort.

**Comment by carmenfan** [comment]
@Charence  This is quite related to what you're doing right now, if you want to do it as well.

**Comment by Charence** [comment]
@carmenfan Since this would require read/write to DB, I assume this issue would be more appropriate in bouncer_worker?

**Comment by carmenfan** [comment]
No since the cor ID is generated on the 3drepo.io side, we need to write it in as soon as it is generated. At the moment IO will update the model settings with a processing flag - We just need to tag it in there when it does it

**Comment by carmenfan** [comment]
Dont' close it until there's a version bump (To make it easier to tag the milestone later ! XD)
