### ISSUE TITLE
V4 legal pages are empty

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4537]
### Description

If the user navigates to the legal pages in v4 the pages are blank

- This is happening in: prod/staging/**both** 
- This requires a hotfix to production: yes/**no** 

### Steps to replicate
- In V4 use the user dropdown to select one of the legal pages (privacy, cookies, terms)

### Current Behaviour
- The pages are blank except for the header

### Expected Behaviour
Either:
- The user is directed to the v5 pages
or
- The contents are readded to the v4 pages

### Pictures/ Gifs of the error

![image](https://github.com/3drepo/3drepo.io/assets/62481250/b899de81-243f-42ff-a9a7-1da0dffbbbbf)

**Comment by carmenfan** [comment]
the plan is to get rid of the v4 routes next release (5.8) so maybe this is N/A

But leaving this open until we have confirmation.

**Comment by carmenfan** [comment]
closing - this is N/A as we're removing the v4 pages next release
