### ISSUE TITLE
Visual settings clears search params

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4542]
### Description
Opening the visual settings modal clears all the search params in the URL

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Reach a URL with search params (riskId, issueId, etc) or even append them manually (e.g. "&lt;url>`?param=3`")
- Open the visual settings dialog

### Current Behaviour
- Search params get cleared

### Expected Behaviour
- I would guess search params should stay, but it's better to investigate why this behaviour was originally implemented. Maybe "issueId" and "riskId" need clearing, and if so, only those should be wiped. Otherwise, they should be kept too

**Comment by AsiteZane** [comment]
This is an issue for tickets so still needs to be resolved.
