### ISSUE TITLE
Pins in Issues and Risks should be visible when the respective card is expanded

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4555]
### Description
At the moment, when we have a sequence open to a given date, we only want to display the pins that exist for that date.
(e.g. in the 4d tab, if the start date is 10/10/2020 and the end date is 20/10/2020, only show the pins when the current date in the sequence falls within those dates).

However, we want to keep displaying the pin of an issue/risk if the respective card is expanded

### Goals
- [ ] 

### Tasks

- [ ] Keep the pins of an expanded risk/issue visible for as long as the card is exapnded

**Comment by AsiteZane** [comment]
No longer pursuing issues and risks - thank you for raising.
