### ISSUE TITLE
Ability to go to today's date in a sequence

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4568]
### Description
A lot of times users want to see the timeline assigned for today in a 4d models and there is no easy way to do so. To address this problem we want to add a goto today button in the sequence card.

### Goals
- [ ] Users can go to todays date by just clicking a button

### Tasks
- [ ] Add a button to go to todays date in the the sequence card

### Related Resources
[MockUp](https://www.figma.com/file/bRqIl0g9psqD3ISkmxwcNp/3D-Repo?type=design&node-id=752%3A44776&mode=design&t=WurfyFNzpUDK8ZG0-1)

**Comment by AsiteZane** [comment]
I know it's not on here @carmenfan as a goal but I tried this today and have something to add.
One thing that would be ideal to come up is a notification window in the event that "today's date" sits outside the sequence, when you press the go to today's date button it should notify you by saying something like:

"Note: Today's date sits outside of the sequence"

This would be true regardless of whether today's date is before the sequence, or after.

**Comment by carmenfan** [comment]
> I know it's not on here @carmenfan as a goal but I tried this today and have something to add. One thing that would be ideal to come up is a notification window in the event that "today's date" sits outside the sequence, when you press the go to today's date button it should notify you by saying something like:
> 
> "Note: Today's date sits outside of the sequence"
> 
> This requires no interaction beyond "Ok".
> 
> This would be true regardless of whether today's date is before the sequence, or after.

making a  new issue for this (and also the toggle change) as this one is already in staging!
