### ISSUE TITLE
Avatar size cap needs a better description

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#457]
We could also do with resizing and optimising images as people will forget to (including me! :stuck_out_tongue_closed_eyes: )

**Comment by JamesMilnerUK** [comment]
I've put a cap on upload on the client but need to add a dialog explaining the error

**Comment by carmenfan** [comment]
I think you already put a cap on the size already?

**Comment by jozefdobos** [comment]
The error message should be more informative, ie what are the max filesize or dimensions?

![image](https://user-images.githubusercontent.com/3008807/32187225-3bdc0a72-bd9c-11e7-929c-a2a309d4d44f.png)

**Comment by jozefdobos** [comment]
Also, the get avatar API does not seem to return anything at all when there is no avatar present. Not even error 404, like seriously nothing!

**Comment by carmenfan** [comment]
This is improved on react migration
