### ISSUE TITLE
GIS (open street map) is not working

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4598]
### Description
Backend is returning 500 when fetching the assets for GIS

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Navigate to a container in the viewer
- Open the gis card
- Fill everything with 0
- Save the coordinates
- Click on the eye to show the map

### Current Behaviour
- Nothing is shown
- 500 errors are being thrown by the backend when fetching the assets

### Expected Behaviour
- The GIS map should be shown in the viewer

### Pictures/ Gifs of the error
<img width="847" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/09a325f1-eab7-4f25-bcff-a431e34b9310">

**Comment by carmenfan** [comment]
seems to work, cannot reproduce. Reopen if you see it again
