### ISSUE TITLE
Update params for issue documentation

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#4603]
### Description
Update the API documentation for issue update (patch request) [apiDoc: 3drepo.io - 5.6.1](https://3drepo.github.io/3drepo.io/#api-Issues-updateIssue) to include the “name” parameter.

Source: Faisal

**Comment by carmenfan** [comment]
closing this due to lack of information (and 2nd hand information)

If this is needed, please create a new issue following a specific template.

@AsiteZane fyi
