### ISSUE TITLE
Remove unused components

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4607]
### Description
After #4561 there is no more access to v4 routes, which means there are a lot of v4 components that are no longer necessary so we can delete these

### Suggested solution
remove all the unnecesary files

### Goal
- remove clutter
- improve compilation/lint speed by having less code

### Tasks
- [ ] Remove unused v4 files

**Comment by AsiteZane** [comment]
@carmenfan - is this done now?

**Comment by sanmont3drepo** [comment]
Modified to address all unused files.
