### ISSUE TITLE
Review Key Auth blacklist

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#4616]
### Description
This line appears to have a typo:
https://github.com/3drepo/3drepo.io/blob/f767f62f257c0efa17e92d3d3117770b10f6c976/backend/src/v4/middlewares/keyAuthentication.js#L39

- This is happening in: ~~prod/staging/~~ both 
- This requires a hotfix to production: yes/no 

### Expected Behaviour
- Should not be able to use API Key to perform verification

**Comment by carmenfan** [comment]
@Charence  where did this come from? Did someone run into this issue?

We don't do it this way on v5 anymore. Plus this should technically impossible as you can't possibly generate an API key without verifying yourself first.

**Comment by AsiteZane** [comment]
Can we close this? @carmenfan @Charence

**Comment by carmenfan** [comment]
I think we can yes.

Having talked to Charence, he spotted the issue when he read the file whilst looking for something else. So:

1. it's a situation we don't think we'll run into
2. it's a piece of code we're looking at deprecating, as mentioned above v5 takes a completely different approach

So it's a won't fix.
