### ISSUE TITLE
Model Loading Performance Improvement

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#4628]
### Description

This issue is for the .io changes to improve loading speed.

Product Team Issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/346

Tasks and Goals to follow as investigation proceeds.

### Related Issues
Bouncer: https://github.com/3drepo/3drepobouncer/issues/654
Unity: https://github.com/3drepo/3drepounity/issues/493

**Comment by sebjf** [comment]
Hi @carmenfan,

Regarding getting the encoding in the db to responseCodes.js, do you want me to have a go at it or do you want to do it?

I was thinking we'd add a member to the ref node to store the encoding, and return the Buffer inside another object which contained it, so responseCodes could set the right header.
It seems that `_fetchFile` was originally able to do return a metadata object anyway, its just not used anymore.

Also, it looks like the Unity Editor doesn't accept gzip encodings so we could add a small snippet that pipes gzipped responses through a decompressor if the request doesn't support such encodings, which accounts for the unlikely edge case we discussed at the start anyway.

**Comment by sebjf** [comment]
> or the purpose of the asset bundles, you just need to set the header to the right mime type right (if it's already compressed)

That's right, really the ref node member is needed only so we don't have to rebuild all the Unity bundles!

> So this is for situations where you want to load the model in unity editor?

Yes - which I am aware is basically just me during development now! 😆 If it were hard I would come up with another solution but I am expecting it be trivial in Node, and supports other hypothetical non-gzip supporting users of the endpoint too as a side-effect.

**Comment by carmenfan** [comment]
> > or the purpose of the asset bundles, you just need to set the header to the right mime type right (if it's already compressed)
> 
> That's right, really the ref node member is needed only so we don't have to rebuild all the Unity bundles!
> 
> > So this is for situations where you want to load the model in unity editor?
> 
> Yes - which I am aware is basically just me during development now! 😆 If it were hard I would come up with another solution but I am expecting it be trivial in Node, and supports other hypothetical non-gzip supporting users of the endpoint too as a side-effect.

@sebjf  fair enough - if it's easy we may as well!

**Comment by carmenfan** [comment]
> Hi @carmenfan,
> 
> Here is how I have implemented it,
> 
> https://github.com/3drepo/3drepo.io/pull/4629/files https://github.com/3drepo/3drepobouncer/pull/656/files
> 
> On the bouncer side it uses the metadata node parameter, which is now stored in the web buffers type all the way from where the buffer is created. The members of this node are appended to the ref node, so in mongo it looks like...
> 
> ![image](https://private-user-images.githubusercontent.com/5058369/288495410-3cc4f60e-7c9e-4d78-bd4a-669c803179fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4ODQ4NTQsIm5iZiI6MTcwMTg4NDU1NCwicGF0aCI6Ii81MDU4MzY5LzI4ODQ5NTQxMC0zY2M0ZjYwZS03YzllLTRkNzgtYmQ0YS02NjljODAzMTc5ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMTc0MjM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDFkYTIxZjc0YzBmZGFjNGI5ZGU0OTViZmJiMGQ3ZDVhZGVhYTUyZjhmZmM1ZWVjZGU2OTE4YTBiNjVmZTlmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-mWgkhK1RlynVA1AazVAVirVLRwwI7ujgIr-k8Z3fOE)
> 
> On .io the method to return the ref node parameters like size and type picks this up as well, and the handler for the asset bundle route forwards it to the response method, where it is used to set the headers or decode the stream, depending on its existence, state and whether the client agent supports it.
> 
> I have used the V5 versions of everything, but have left `getUnityBundle` member in the unityAssets.js of v4.

@sebjf  Thanks! had a quick look, the approach looks sane to me.  2 quick comments:

[For this one](https://github.com/3drepo/3drepo.io/pull/4629/files#diff-d9d384710e62e22dcc528e1605aa93a3abec0780e138bb44e323aa3c2494ccbcR115) - if you get the version from `fs/promises` (we already include `unlink` from that up top) you won't have to manually wrap it around with promises 

[For this one](https://github.com/3drepo/3drepo.io/pull/4629/files#diff-0a8c7d17a262e46c91615a315a246fc5de52338e23ef3efa13c2fb46c0743abfR469) - if I'm reading it correctly you're now using the v5 responder thus this is N/A?
