### ISSUE TITLE
Dynamicly generated elements are an anti pattern

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#464]
Dynamically generated elements keep causing lots of problems and it would be good to remove them all when possible.

I.e. instead of

```javascript
filter = angular.element("<panel-card-filter show-filter='vm.showFilter' filter-text='vm.filterText'></panel-card-filter>");
```

just keep the element in the template markup and use directives / attributes to add data, show hide etc

**Comment by carmenfan** [comment]
I'm going to remove this issue, because chances are you're not going to be doing this as a "Feature", but rather rewriting them as you see them (which sounds like it's what you've done so far with the ones you've found?)

If you think otherwise feel free to open it again

**Comment by JamesMilnerUK** [comment]
I think that's fair enough. Good to have a point of reference if it ever becomes a more problematic / centralised issue.
