### ISSUE TITLE
Project images doesn't show until a hard refresh

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4645]
### Description
When you add a project image when you create a project, the image doesn't seem to show until you perform a hard refresh
![img-07-37-23-10-37](https://github.com/3drepo/3drepo.io/assets/11945337/8ae2c24c-68bc-41ab-b27d-2d87ac25a31d)

### Steps to replicate
- Create a new project with an image

### Current Behaviour
- The image does not show immediately
- it does not show after a refresh
- it only showed if i did a ctrl+F5

### Expected Behaviour
- Should ideally show immediately, if not, at least after a soft refresh

**Comment by Amantini1997** [comment]
I can't reproduce this on my local environment 

Uploading Registrazione 2024-01-05 141536.mp4…

I'm passing this to you @The-Daniel

**Comment by carmenfan** [comment]
> I can't reproduce this on my local environment
> 
>  Registrazione.2024-01-05.141536.mp4 
> I'm passing this to you @The-Daniel

do you see it on staging?

**Comment by The-Daniel** [comment]
@carmenfan I see the bug, yes
