### ISSUE TITLE
Account needs to become Teamspace across front and backend

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#466]
Going to be a bit of a pain but it's very inconsistent at the moment unfortunately.

**Comment by carmenfan** [comment]
this is like the 3rd issue for this. https://github.com/3drepo/3drepo.io/issues/376 and #373 
as 376 says, henry already did the work on the backend on #373. but I'm not entirely convince we really want to do #373 

Just keep with it for 1.13. I don't think we want to introduce what we had with model <-> project this late in the release

**Comment by carmenfan** [comment]
closing this due to duplication (back end is done on #373, issue for front end is #376)
