### ISSUE TITLE
Alternative examples in v4 docs don't show

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#4678]
### Description
v4 docs: https://3drepo.github.io/3drepo.io/

When you click on an alternate "Example usage", e.g. "Example usage (with e-mail)" for Forgot Password, it doesn't seem to show: https://3drepo.github.io/3drepo.io/#examples-Account-forgotPassword-0_0_0-1

Also, not sure if it's the colour scheme but everything looks like it's greyed out.

- This is happening in: ~prod/staging/~ both 
- This requires a hotfix to production: ~yes/~ no 

### Steps to replicate
- Try to use v4 docs: https://3drepo.github.io/3drepo.io/#examples-Account-forgotPassword-0_0_0-1

**Comment by AsiteZane** [comment]
To determine the importance as part of the prioritisation efforts.

**Comment by carmenfan** [comment]
Works and deployed

**Comment by AsiteZane** [comment]
@carmenfan - what was wrong exactly? Just out of curiosity.

**Comment by carmenfan** [comment]
@AsiteZane  don't know to be honest, either it was a dodgy build of the docs, or i didn't commit some of the files (css stuff perhaps) 😕
