### ISSUE TITLE
Group by custom ticket fields in ticket tabular view

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#4696]
### Description
In tabular view for tickets the `Group by` list is currently a fixed list. It would be nice to be able to group by (certain) custom ticket fields as well.

### Goals
- [ ] More group by options

**Comment by carmenfan** [comment]
Closing. This is part of https://github.com/3drepo/3D-Repo-Product-Team/issues/311

@AsiteZane  just tagging you so you know what i'm doing.
