### ISSUE TITLE
Show description in tickets list/tabular view

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#4697]
### Description
Tickets list/tabular view currently shows Ticket Title. It would be nice to show Description as well.

### Goals
- [ ] Show description alongside title in tickets list
- [ ] Show description alongside title in tabular view

**Comment by carmenfan** [comment]
Closing this, it should be handled as part of https://github.com/3drepo/3D-Repo-Product-Team/issues/360

@AsiteZane flagging this for your attention (Don't think we updated the description since the meeting). Description and also default image
