### ISSUE TITLE
signUp page elements appear blank (zero height) in Safari 10.1.2

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#470]
When attempting to view the signup page at https://dev.3drepo.io/signUp the page appears blank:

<img width="1680" alt="screenshot 2017-09-11 11 43 15" src="https://user-images.githubusercontent.com/1438332/30271467-4f70a0fa-96e8-11e7-84a3-e3bde2cd3f81.png">

Issue occurs in Safari 10.1.2.

**Comment by Charence** [comment]
Console output:

<img width="1680" alt="screenshot 2017-09-11 11 43 46" src="https://user-images.githubusercontent.com/1438332/30271578-c876a65c-96e8-11e7-9c8f-c78c4df36acb.png">

More info:

Some elements have 0px height.

<img width="1680" alt="screenshot 2017-09-11 11 44 41" src="https://user-images.githubusercontent.com/1438332/30276746-b89e823a-96fd-11e7-9909-d490d31f4a73.png">
<img width="1680" alt="screenshot 2017-09-11 11 44 49" src="https://user-images.githubusercontent.com/1438332/30276752-bec5176e-96fd-11e7-8743-d146243e7b5d.png">
<img width="1680" alt="screenshot 2017-09-11 11 45 06" src="https://user-images.githubusercontent.com/1438332/30276785-d6ce7a30-96fd-11e7-8185-fdb952d0fd44.png">
<img width="1680" alt="screenshot 2017-09-11 11 45 07" src="https://user-images.githubusercontent.com/1438332/30276797-dfce363e-96fd-11e7-890b-29029332f291.png">

**Comment by paloknapo** [comment]
See Product Backlog:
https://github.com/orgs/3drepo/projects/6#card-4706457
