### ISSUE TITLE
Trying to create a new group with already selected meshes does not detect them

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4702]
### Description

- This is happening in: both
- This requires a hotfix to production: no 

![24-01-19 12-36-11](https://github.com/3drepo/3drepo.io/assets/11945337/922c43c0-a0b9-4604-9f48-5f25908eac82)

### Steps to replicate
- In the viewer, select some meshes
- open the groups(v4) card and click the new button

### Current Behaviour
- The save button is disabled

### Expected Behaviour
- The save button should be enabled

**Comment by carmenfan** [comment]
Already happening in prod so not something we've introduced in 5.8...

Leaving this one for @AsiteZane  to triage

**Comment by AsiteZane** [comment]
Seems a similar behaviour to the BIM Card issue https://github.com/3drepo/3D-Repo-Product-Team/issues/357

What kind of time do we think it would take to address this and is it completely a front-end bug? @carmenfan

**Comment by carmenfan** [comment]
@AsiteZane 

Logically similar, but not caused by the same part of the code (the BIM card one is resolved and going into 5.8 https://github.com/3drepo/3drepo.io/issues/4649)

Don't think it's difficult, probably something that can be done in a few hours.
