### ISSUE TITLE
Cannot delete the description from a ticket group

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4719]
### Description

Although it is possible to create a ticket group with no description the user cannot edit an existing group and delete the description. An error modal appears stating that the description must be at least 1 character long

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Create a ticket group and give it a description
- Edit the group and delete all characters from the description input
- Save the updated group

### Current Behaviour
- An error modal appears stating the description must be at least 1 char long
- The group is not saved

### Expected Behaviour
- The user can update a ticket group to have no description

### Pictures/ Gifs of the error
![image](https://github.com/3drepo/3drepo.io/assets/62481250/0f17087b-81ba-458d-aa1b-a6998f1de49a)

**Comment by Amantini1997** [comment]
@carmenfan I fixed the part concerning the frontend, but I think the backend also needs fixing as it currently doesn't accept null
![image](https://github.com/3drepo/3drepo.io/assets/43547703/1507eedd-5d7d-42ff-961b-dcfa863a2724)
