### ISSUE TITLE
New comment field should be sticky at the bottom

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#473]
At the moment the new comment field scrolls with the issue comments which is not good

![image](https://user-images.githubusercontent.com/3008807/30478850-a933f2f2-9a0a-11e7-948e-5f0972fca747.png)

**Comment by jozefdobos** [comment]
Instead it should do like other chat systems, eg 
![image](https://user-images.githubusercontent.com/3008807/30478885-c453ed26-9a0a-11e7-93f6-41f4feb74c06.png)

**Comment by jozefdobos** [comment]
Also, the text "Comment requires text" should only show when someone tries to send message instead of always as it is confusing and as a I user I actually tried to type the message into that box on my fst attempt

**Comment by JamesMilnerUK** [comment]
Fixed in #458
