### ISSUE TITLE
Remove unused v5 files

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4751]
### Description
There exists file in v5 that are unused anywhere. These files should be removed.

### Suggested solution
There exists libraries to detect unimported components, an example is "unimported" as suggested [here](https://stackoverflow.com/questions/54148788/how-to-find-dead-code-in-a-large-react-project).

I ran `npx unimported` and I found these files are unused:
- src/v5/ui/components/viewer/cards/cardContext.component.tsx
- src/v5/ui/routes/dashboard/projects/tickets/ticketsTable/ticketsTable.styles.ts
- src/v5/ui/routes/viewer/tickets/ticketsForm/ticketGroups/groups/groupRulesForm/ruleValueField copy/ruleValueField.component.tsx
- src/v5/ui/v4Adapter/components/alertModal.component.tsx
- src/v5/ui/v4Adapter/components/alertModal.styles.ts (this is unused as soon as the previous file is deleted)

### Goal
- [ ] We should get rid of unused files

### Tasks
- [ ] Identify those files that are not used and delete them

**Comment by The-Daniel** [comment]
Could we add `dashboardList.component.tsx` to this list? It just restates **ListContainer** from `dashboardList.styles`, so you can just use that.

**Comment by Amantini1997** [comment]
> Could we add `dashboardList.component.tsx` to this list? It just restates **ListContainer** from `dashboardList.styles`, so you can just use that.

Yes, of course. Keep in mind that the list is not necessarily exhaustive. I just ran that library and found some files that are not imported anywhere, but other files, such as the one you just mentioned, can be included @The-Daniel

**Comment by sanmont3drepo** [comment]
Closed in favour of #4607
