### ISSUE TITLE
Default Pins for other tickets sometimes persist when opening ticket details

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4753]
### Description

By opening the tickets list and proceeding to click default pins on the viewer it is possible for default pins for other tickets to be visible when viewing a tickets details.
Strangely this only happens when clicking the pins in the viewer and not opening them with the tickets list.

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Open the ticket list.
- Select a ticket item which has a default pin so that the pin becomes selected (Note: just select the item, don't click to go in to details view)
- On the viewer click the default pin for one of the other tickets (i.e. any of the unselected ticket pins in the viewer)

### Current Behaviour
- The pin which was previously selected persists whilst the details view for the other ticket opens
- The user can now click these two default pins to quickly switch between two tickets details which opens us up to crashes as this is unexpected behaviour

### Expected Behaviour
- When opening a ticket's details all pins for other tickets are hidden.

### Pictures/ Gifs of the error

![persistingpins](https://github.com/3drepo/3drepo.io/assets/62481250/c140b111-a05f-4746-a9f9-5389f0468142)

**Comment by carmenfan** [comment]
@AsiteZane can you please prioritise
