### ISSUE TITLE
Date is overflowing 

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4755]
### Description
We need to fix the date so it doesn't overflow

- On new groups (only new, existing seems fine):
![image](https://github.com/3drepo/3drepo.io/assets/11945337/2365e3db-8fd7-4094-833f-ee1a97973714)

- For @AsiteZane - this is showing AM/PM which is overflowing. All dates shoudl be in 24hr clock format
![image](https://github.com/3drepo/3drepo.io/assets/11945337/626898d4-4965-446a-a5c4-5ed95773846e)

**Comment by AsiteZane** [comment]
@carmenfan - thank you, was coming to create the bug report just now. You're too fast!

**Comment by carmenfan** [comment]
> @carmenfan - thank you, was coming to create the bug report just now. You're too fast!

@Amantini1997  is faster, he already fixed it!

**Comment by AsiteZane** [comment]
@carmenfan @Amantini1997 you guys 🥲
