### ISSUE TITLE
Custom tickets - clean boolean props created as false

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#4807]
### Description
When Im saving a new ticket the boolean property even if I didnt change it is being save as false. I think it shouldnt be part of the properties sent if I didnt change it. This is more evident in #4752 .

- This is happening in: both
- This requires a hotfix to production: no

### Steps to replicate
- Click on new ticket in tickets card
- Select a template that has a boolean optional property  
- Fill in only the required fields
- Open the dev tools and select network
- Click on save ticket
- See what its being sent to the server as the create ticket request

### Current Behaviour
- The boolean property is set to false

### Expected Behaviour
- The boolean property shouldnt be sent as part of the request

### Pictures/ Gifs of the error
![savedboolean](https://github.com/3drepo/3drepo.io/assets/42032433/0eabb10b-e2a2-4d6e-84f5-7b21bc0f7a30)

**Comment by carmenfan** [comment]
close as it's working as intended

Until we have a UI to represent an empty boolean we can't do much
