### ISSUE TITLE
Once inside an issue, clicking on the issue card somewhere should zoom again on the right spot

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#481]
When I open an issue, the system zooms on the right spot as required. However, as I navigate around, I often found myself needing to rezoom to the same original spot which I could only do by going back to the list of issues and then again back inside the issue I needed. It would be far better user experience if we somehow (either a specific button, or clicking on some white area but not everywhere as that could be annoying) could rezoom to the right spot.

**Comment by paloknapo** [comment]
It already does it if user clicks on description or comment. Maybe highlighting on more-over to give user a feedback would help.

**Comment by carmenfan** [comment]
As pavol said there's a way. What you ideally want is probably a camera icon or something right next to them so the user knows where the click.
