### ISSUE TITLE
Object selection doesn't work as expected in Safari 10.1.2

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#482]
Clicking and double clicking on objects does not necessarily select or zoom into the expected object. Incorrect selections appear to be consistently wrong.

E.g. the meta data is wrong here when the guy's face is clicked

![screenshot 2017-09-15 11 08 48](https://user-images.githubusercontent.com/1438332/30490543-2dbd3f52-9a32-11e7-957f-2ffcd33dbae2.png)

**Comment by paloknapo** [comment]
See Product Backlog:
https://github.com/orgs/3drepo/projects/6#card-4706457
