### ISSUE TITLE
Issues comment positioning problem when screenshots presented in Safari 10.1.2

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#484]
Comment text within issues have a positioning problem when screenshots also appear in the comments. Comment text appears overlapped with images.

![screenshot 2017-09-15 11 08 48](https://user-images.githubusercontent.com/1438332/30491020-c106d22c-9a33-11e7-869c-1004930aa1ff.png)

**Comment by paloknapo** [comment]
See Product Backlog:
https://github.com/orgs/3drepo/projects/6#card-4706457
