### ISSUE TITLE
[2D MVP] Milestone 3: Unity changes to support manual Calibration

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#4857]
### Description

Support Manual Calibration as described in this ticket: https://github.com/3drepo/3D-Repo-Product-Team/issues/379

This PR for now is mainly to test the viewer modifications. It will be extended with the frontend changes as necessary.

### Goals

- TBD

### Tasks

- TBD

### Related Resources

Product Team: https://github.com/3drepo/3D-Repo-Product-Team/issues/379
Unity: https://github.com/3drepo/3drepounity/issues/518

**Comment by carmenfan** [comment]
merged into #4897
