### ISSUE TITLE
The teamspace is showing all license assigned if the subscription had 0 collaborators

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4891]
### Description
![image](https://github.com/3drepo/3drepo.io/assets/11945337/a80de9b6-5f23-4262-9638-6a1549a104a3)

When a teamspace is given a sub that contains 0 collaborator, we're showing inconsistent message and they cannot utilise the 5 seats that are given as a based sub.

### Steps to replicate
- give a sub to a teamspace with no collaborator entry

### Current Behaviour
Notice how the top banner shows there's 5 seats, but the bottom right footer shows there's unlimted seats, and the add user button is disabled thinking all licenses are assigned

### Expected Behaviour
there should be 5 available seats for the teamspace to utilise

**Comment by sanmont3drepo** [comment]
Seems to be a problem in both frontend and backend 
- Endpoints being called in the backend doesnt return consistent data:
![image](https://github.com/3drepo/3drepo.io/assets/42032433/61e425a0-cec8-4a9c-8b8e-9a7e022e2200)
![image](https://github.com/3drepo/3drepo.io/assets/42032433/40e296c5-c364-47d6-af5d-44b18e4b728d)

- The data in v4 seems to be used differently in 2 places in the frontend
<img width="248" alt="image" src="https://github.com/3drepo/3drepo.io/assets/42032433/96b48894-8487-4a4d-8e08-3183b752cf25">
