### ISSUE TITLE
Importing a comment labelled as "deleted" is still received by the frontend as not deleted 

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4892]
### Description
Deleted ticket comments imported via the API will result as normal messages, i.e., not deleted

- This is happening in: prod/**staging**/both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- Import a ticket with one deleted comment

### Current Behaviour
- The deleted flag is missing from the data received in the frontend

### Expected Behaviour
- The deleted flag should be kept

### Pictures/ Gifs of the error

https://github.com/3drepo/3drepo.io/assets/43547703/64221ddd-110e-48b0-81fb-cf1e57a0598c

**Comment by carmenfan** [comment]
@Amantini1997  hang on that's not a bug, that's not part of the schema 🙈 You can't import a deleted comment (doesn't really make a lot of sense to be able to)

**Comment by carmenfan** [comment]
Double checked the codebase - an imported comment cannot be modified or deleted so it's not possible to mark an imported comment as deleted.

So this is working as intended 👍
