### ISSUE TITLE
Issue should somehow display in a very obvious way if clipping plane is on

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#491]
As a user when I click on someone else's issue which zooms in really closely to the model but it has clipping plane on, I will suddenly lose half of my model without knowing what is going on (since my clipping plane card is off by default). So we need to somehow make it very obvious that the current issue has clipping plane on (if that is the case).

**Comment by jozefdobos** [comment]
Also, worthwhile considering is the idea of disabling the clipping plane altogether when exiting a single issue and going back to the list of issues. The only problem I can see is that if I deliberately set the clipping plane myself and it was not part of the issue I'm just exiting, it would become very annoying.

**Comment by carmenfan** [comment]
What we probably should do is force the clipping plane tab to pop up when we open an issue with clipping plane. then the user would know that a clipping plane is on and he/she can disable/modify it.

Also helps to keep the clipping plane state sane. At the moment it is in a curious scenario where clipping plane is only on if the tab is visible, but it is also on if you clicked on an issue with it


Having said that, all these probably would be a non-issue when/if move to gizmo style control for clipping plane. So whether it's worth fixing probably depends when we move onto this.
