### ISSUE TITLE
When measuring, double clicking does not select an object

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#493]
When in measuring mode, I wanted to see the metadata so I thought by double clicking I could highlight an object and get the card up which was not the case. I understand single clicking would not do it since clicking does measurements, but under normal circumstances, double clicking highlights and zooms to selected so I expected the same behaviour in measuring mode just as well.

**Comment by carmenfan** [comment]
double click never highlight objects. 

During measuring mode, metadata and highlighting is deliberately disabled, as most of the time metadata and highlighting is just distracting and unintended behaviour.
