### ISSUE TITLE
Issue attributes (priority, assign, type) remain disabled after issue reopened

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#494]
Scenario:

1. Close issue selected
2. Priority/assign/type become disabled
3. Issue is immediately reopened
4. Priority/assign/type remain disabled
5. User navigates back to issue list
6. User navigates back into the issue details
7. Priority/assign/type are now enabled

**Comment by paloknapo** [comment]
See issue:
https://github.com/3drepo/3drepo.io/issues/499
