### ISSUE TITLE
Unity appears to pause loading if window not in focus

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#495]
Unity appears to pause loading (red status bar) sometimes when 3D Repo is not the active window (e.g. user alt-tabs to different window). Loading resumes when user clicks on the 3D Repo window.

**Comment by carmenfan** [comment]
That's expected behaviour, there's an option on the unity build to pause when not focus, or keep rendering in the background. And we chose the former.

If we want it to continue loading when in background then we have to have it running 100% of the time

**Comment by carmenfan** [comment]
requires https://github.com/3drepo/3drepounity/issues/54
