### ISSUE TITLE
Cannot view screenshot on the view within the clash module

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#4955]
### Description
The thumbnail is showing within the property, but when you click on the image it comes up with the image not found icon

![24-05-08 07-54-39](https://github.com/3drepo/3drepo.io/assets/11945337/5c9e980d-0d14-4239-adb1-2ab7174c5ef5)

### Steps to replicate
- Go to this ticket: https://staging.dev.3drepo.io/v5/viewer/DevTeamWorkspace/7b6c7bd0-054a-11ee-ac5b-59e952832776/4f4353f5-b8bd-4bfe-837e-5437d7cfb226?ticketId=5dc80758-2b00-415c-86a1-ccc492aed18e
- Go to the `Clash View` in the clash module
- Click on the image

### Current Behaviour
- Gallery modal pops up with the image not found

### Expected Behaviour
- The image should show up in the gallery modal

**Comment by Amantini1997** [comment]
I can't reproduce it 

https://github.com/3drepo/3drepo.io/assets/43547703/caa40157-f777-4c53-8ce1-4df5cc912a18
