### ISSUE TITLE
[2D MVP] Milestone 2: Viewer side panel buttons no longer fit small screen sizes

### ISSUE THREAD

**Issue by The-Daniel** [3drepo/3drepo.io#4959]
### Description

With the addition of the Drawings card the buttons on the left side of the viewer no longer all fit if the user is using a small screen (I get this on my laptop when I have the bookmarks panel open). Perhaps there should be some level of shrink or gap reduction in order to accommodate smaller screens. 

- This is happening in: prod/**staging**/both 
- This requires a hotfix to production: yes/**no** 

### Steps to replicate
- Open the viewer with a small screen.
- Ensure the bookmarks panel is also open (Ctrl + Shift + B on Chrome)

### Current Behaviour
- The drawings button is half obscured out of screen

### Expected Behaviour
- All the buttons are visible without the need to zoom out

### Pictures/ Gifs of the error

![image](https://github.com/3drepo/3drepo.io/assets/62481250/649e9186-5277-4c66-866d-3a10daf277fc)

### Link to design
https://www.figma.com/design/yzsLESycxJwhzw4bqLOS0C/3D-Repo-UI-Components?node-id=901-2438&t=LXM4dd7D1w8Ud1yQ-0

**Comment by carmenfan** [comment]
The solution here might be to implement the new icon layout in figma
https://staging.dev.3drepo.io/storybook/?path=/docs/theme-typography--docs

It seems to have less padding in between the icons

**Comment by carmenfan** [comment]
@sanmont3drepo @AsiteZane  i'll put this down for 5.12 as that will become an issue for users when we introduce the additional icon for 2D sheets

**Comment by AsiteZane** [comment]
@carmenfan noted thanks - more incentive to remove the first two now :D

**Comment by carmenfan** [comment]
merged into #4833
