### ISSUE TITLE
Sometimes new issues do not appear on issue list (until browser refreshed)

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#496]
Sometimes new issues created by other users do not appear on issue list.

The problem appears to be random (perhaps didn't receive new issue event) and can be resolved with browser refresh.

Proposed solution: UI can compare checksum for issue list and refresh list if checksum inconsistent.

**Comment by paloknapo** [comment]
See issue:
https://github.com/3drepo/3drepo.io/issues/499
