### ISSUE TITLE
If User remove the Assignee in Asite CDE, due date still viewed in 3Drepo metadata

### ISSUE THREAD

**Issue by samipbabaria** [3drepo/3drepo.io#4964]
Platform : QA
Workspace : Any

### Description
It is noted that If the User removes the Assignee in Asite CDE, the due date is still viewed in 3Drepo metadata

### Steps to replicate
Remove the Assignee for any Issue from the Intermediate page or Issue manager 
Assignee changes to Unassigned, but the due date should not removed.
The due date should be removed as well.

### Current Behaviour
The user removes the Assignee in Asite CDE, but the due date is still viewed in 3Drepo metadata

### Expected Behaviour
In 3Drepo due date should also be removed.

If the user Assign the Assignee to the same issue once again, it should update accordingly

### Pictures/ Gifs of the error
![image (20)](https://github.com/3drepo/3drepo.io/assets/157123564/dfea6839-a240-4207-afe4-a777de5fcede)

**Comment by jmistri** [comment]
@samipbabaria 
I think this behaviour is for Asite not for 3DREPO. 
3DREPO supports unassigned issue with Due date. So if it keeps due date than nothing is wrong from 3DREPO side.
Closing this issue as won't fix.
