### ISSUE TITLE
Backend test updates

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#497]
> The X3DOM encoder is still in the backend code. We also rely on it for the Collaboration tests

**UPDATE** (carmen) I'm going to change this issue to the list of updates we need to do for backend auto testing:
- [ ] Remove X3DOM API test (when old VR is decommissioned)
- [x] Add Unity API Test
- [x] Update Database dump with the right model files
- [x] jobs.json needs to return colours

**Comment by carmenfan** [comment]
Just noting down what we discussed:

- Remove X3DDOM API test
- Add Unity API Test
- Update Database dump with the right model files

**Comment by JamesMilnerUK** [comment]
The unity models are available on the 'testuser' database that is in the tests data, available in staging now. This came in via #507 where we need the model data for the model page.

**Comment by carmenfan** [comment]
closing as this will be complete with #894
