### ISSUE TITLE
BCF import error

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#4978]
### Description
BCF import error

- This is happening in: prod/staging/both 
- This requires a hotfix to production: yes/no 

### Steps to replicate
- Import BCF (Internal link: https://asitesol.sharepoint.com/:u:/s/3DRepoTeamFolder/Ea3nq48gj4xJuHVj0810g1UB5qPKMOx_NRfoAZuAcPXA4A?e=aDgaip)

### Current Behaviour
- Error

### Expected Behaviour
- No error

### Pictures/ Gifs of the error
![image](https://github.com/3drepo/3drepo.io/assets/1438332/6c415759-b8a2-4190-b9df-7257ce140aa7)

**Comment by carmenfan** [comment]
This is due to the BCF data contains descriptions that exceed the maximum allowed length in 3D Repo.

We could increase the cap but it may be a forever moving goal post - on top of that, our UI doesn't really cater for this so we may want to review the UI with this in consideration.

**Comment by AsiteZane** [comment]
@carmenfan  - what is the maximum length for the description so we can advise them?

**Comment by carmenfan** [comment]
@AsiteZane  1200 (This is also the case for custom tickets so it's consistent when we move over)

**Comment by carmenfan** [comment]
closing as won't fix 

Re-open if the circumstance changes
