### ISSUE TITLE
[2D MVP] Milestone 3: refreshing the viewer while the drawingId is present in the URL should open up the drawings card 

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#4993]
### Description
We include the drawingId as a search param in the URL. When the user refreshes the page (or reaches it via a link) while the drawingId is part of the URL, the drawing card should open up.

### Tasks

- [ ] The drawing card should open up when refreshing a URL which includes the drawingId

**Comment by carmenfan** [comment]
merged into #4897
