### ISSUE TITLE
Concurrent User Access

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#500]
Figure out what is causing the system to crash / grind when we have more than 5 concurrent users.

**Comment by JamesMilnerUK** [comment]
First step is profiling the app calls. I have already done some work on benchmarking / profiling on this branch for someone else to pick up.

**Comment by carmenfan** [comment]
after stress testing we've established that it's not a immediately pressing issue and adding some extra cpus will give us some more room for growth. This will be addressed in a later release

**Comment by carmenfan** [comment]
closing this in favour of a backlog note. (will reference this issue should we need it)

I think reality is that this will require multiple issue to progressively improve it (and spans across dev and Ops) 

Concurrent access is more of a topic than a task.
