### ISSUE TITLE
Calling setParam in a useEffect cleanup messes up with search params

### ISSUE THREAD

**Issue by Amantini1997** [3drepo/3drepo.io#5003]
### Description
We created our own custom hook to handle search params (useSearchParams). The setter that we use, however, can mess up the search param when it is used inside a useEffect

- This is happening in: both 
- This requires a hotfix to production: no 

### Steps to replicate
- Open the viewer
- Expand a ticket (so the ticketId is appended as a search param)
- Expand an issue (so the issueId is appended as a search param)
- Close the ticket

### Current Behaviour
- Both the ticketId and the issueId are removed from the search params

### Expected Behaviour
- Only the ticketId should be removed from the search params

**Comment by carmenfan** [comment]
fixed as part of #4897
