### ISSUE TITLE
UI does not go to login page after session timeout unless page is refreshed

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#503]
If the model viewer is left open for long periods of time, it seems that the user's session expires. However, this is not indicated in the interface. When the user attempts to go back to the Teamspace, the teamspace list is blank and the user is not prompted to log in again.

If the page is refreshed, users are redirected to the login page. It would be nice for the user to be redirected to the login page automatically once their session expires (perhaps with an hourly check?).

**Comment by carmenfan** [comment]
this sounds very much like #383 so i'm closing it in favour of #383
