### ISSUE TITLE
[2D MVP] Milestone 4: Issues and risks pins 

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5094]
### Description
Product issue: https://github.com/3drepo/3D-Repo-Product-Team/issues/380
We are providing a way for the users to show and drop pins in the 2d area. 

- The pins shown for issues and risks with the issues and risks pin design.
- The pins that are shown in the 2d drawing are only the ones that are inside the limits of the 2d drawing.
- We should be able to drop issues and risks pins.

### Goals
- [ ] As a viewer+, I want to be able see all the pins of the issues and risks that are relevant to the drawing
- [ ] As a viewer+, I want to be able to click on the pin on 2D and it will show me the issue or risk information on the Tickets panel 

### Tasks
- [ ] 

### Related Resources
[MockUp](https://www.figma.com/design/uTWnaYZ8IyoTn2i2xKtdBo/2D---3D?node-id=11-11332&t=j1A2qZU5bKmgEQil-0)

**Comment by carmenfan** [comment]
As discussed with @AsiteZane  this will be out of scope for MVP

closing the ticket

**Comment by AsiteZane** [comment]
Sorry, closing this as unplanned so it doesn't give the illusion that we've done it when glancing through the issues :)
