### ISSUE TITLE
Pins are being added on the viewer even though they don't exist

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#516]
Issues with no pin is adding a pin into the viewer. 

See this project here (You know my password):
https://www.3drepo.io/carmen/f389ec02-9c92-4a6f-91f2-7df5192dcb55

![image](https://user-images.githubusercontent.com/11945337/31087188-0468012c-a794-11e7-820c-141e3ef24b49.png)

Only ISSUE no. 4 have a pin (you can verify with the position field within issues.json), and yet more than 1 pin is visible.

**Comment by carmenfan** [comment]
Also, sometimes pins don't show up when the model is loaded.

Seems to be an asynchronous problem, I've only seen it twice so far. Sometimes the model is loaded, issues are loaded but pins aren't. then the pins will magically appear when I click on an issue that has a pin! 

Pin drop event should only be called after the model started loading (don't wait it to finish though, as big models may take forever and there's no reason why people can't view issue pins while it's loaded) to prevent the whole rejected promise problem - I would've thought you've already coded it that way already, so maybe this is not the problem.

Probably not as urgent, as the pins seems to appear more often than not. If it's too much trouble, fix the first problem (so we can patch prod asap) and open a new issue with this one.

**Comment by JamesMilnerUK** [comment]
This should be fixed on the corresponding branch now.

**Comment by carmenfan** [comment]
I'll move pin no show as a new issue
