### ISSUE TITLE
sometimes pins don't show up when the model is loaded.

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#517]
Seems to be an asynchronous problem, I've only seen it 3 times so far. Sometimes the model is loaded, issues are loaded but pins aren't. then the pins will magically appear when I click on an issue that has a pin!

Pin drop event should only be called after the model started loading (don't wait it to finish though, as big models may take forever and there's no reason why people can't view issue pins while it's loaded) to prevent the whole rejected promise problem - I would've thought you've already coded it that way already, so maybe this is not the problem.

Probably not as urgent, as the pins seems to appear more often than not. If it's too much trouble, fix the first problem (so we can patch prod asap) and open a new issue with this one.

**Comment by JamesMilnerUK** [comment]
I can't replicate this unfortunately. Either @paloknapo or @Charence seen this at all?

**Comment by carmenfan** [comment]
I haven't seen this for the past 2 releases. might have been fixed from the refactoring of things/other fixes!
