### ISSUE TITLE
Make CI fail if the test coverage for backend drops below some percentage

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#523]
In order to ensure we keep the integrity of the API/app I recommend we stop ourselves dropping test coverage by making CI fail if test coverage drops below a given percentage.

@carmenfan  @Charence thoughts!

**Comment by carmenfan** [comment]
You'd only really want that on staging branch though.

**Comment by carmenfan** [comment]
dropping this in favour of coveralls
