### ISSUE TITLE
Routing broken on Sign Up page

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#526]
When on https://www.3drepo.io/signUp and clicking the 3D Repo logo at the top, the URL within the browser redirects to 3drepo.io as expected but the actual contents of the page stay unchanged. Tested on Chrome and FF.

![image](https://user-images.githubusercontent.com/3008807/31332188-49d35b96-acdd-11e7-9eb6-0846f4586c98.png)

**Comment by jozefdobos** [comment]
Also, it would be good to test the routing across the entire system just to make sure similar errors are not present elsewhere.

**Comment by carmenfan** [comment]
I think this is related to https://github.com/3drepo/3drepo.io/issues/510

**Comment by JamesMilnerUK** [comment]
It's the same bug I think, let me double check.

**Comment by JamesMilnerUK** [comment]
Closing in favour of #510 as it's more or less duplicate

**Comment by jozefdobos** [comment]
Ok but make sure this is addressed with the same fix.
