### ISSUE TITLE
Blank screen if root URL is not used

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#529]
If you load http://127.0.0.1, everything loads as normal.

However, if you load or refresh http://127.0.0.1/test4 (where test4 is a username) or something like http://127.0.0.1/test4/09c9aa08-ebbb-4e94-b700-020e2a5909ce, nothing loads.

The problem seems to be related to config.js:
![screenshot 2017-10-10 11 17 26](https://user-images.githubusercontent.com/1438332/31381600-f09fc052-adac-11e7-9f79-fa8717166b73.png)

Note the difference in the URL of config.js:
![screenshot 2017-10-10 11 17 57](https://user-images.githubusercontent.com/1438332/31381601-f0b8a7c0-adac-11e7-95c6-8da511bddd4f.png)
![screenshot 2017-10-10 11 18 20](https://user-images.githubusercontent.com/1438332/31381602-f0d36894-adac-11e7-9f1b-aefadedd3b44.png)

**Comment by carmenfan** [comment]
Pretty sure this is a bug from #522

**Comment by JamesMilnerUK** [comment]
Fixing this, unfortunately didn't get picked up by the automated tests for some reason.

**Comment by JamesMilnerUK** [comment]
Fixed in staging now !
