### ISSUE TITLE
Expose 4D sequence tag in frontend

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#530]
We need a way to update the sequence tag for the 4D VR feature. This will probably appear in model settings.

**Comment by carmenfan** [comment]
This has to be in model settings. The APIs in #417 is relying on its existence.

In #417 I've added a new field within modelsettings, so it should just be a matter of exposing it on the front end. (see [here](https://github.com/3drepo/3drepo.io/blob/f51a3c29f36f2863617848a606ed99447423c596/backend/models/modelSetting.js#L62))

**Comment by carmenfan** [comment]
Backend is not saving the sequence task tag. I'll fix this
