### ISSUE TITLE
When toy project fails, the error message is a bit revealing...

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#532]
![image](https://user-images.githubusercontent.com/11945337/31550941-e3214c7c-b02a-11e7-85c5-938944c8888b.png)

Thank god we masked the credentials...

**Comment by carmenfan** [comment]
I think this is what Henry wants sent to support via email, but we probably want to display a different message to the user.

Maybe we should write a different error for user into the database and only send this message to supprot (without writing it into the db, thus shouldn't show to user)

**Comment by JamesMilnerUK** [comment]
Oh wow. Yeah we can sort that out.

**Comment by carmenfan** [comment]
@Charence  is probably the best guy to do it, since he's pretty familiar with the import process on the backend now! :)

**Comment by Charence** [comment]
@carmenfan @JamesMilnerUK  What error message would you prefer? "Sample import failed"?
