### ISSUE TITLE
Pass an array of api URLs to unity

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#534]
Relies on https://github.com/3drepo/3drepounity/issues/40

Unity now takes a json object as follows instead of just a single string of URL host:
````js
{
    hostNames: [<apiURL1>, <apiURL2>,...]
}
````
i.e. - [this function](https://github.com/3drepo/3drepo.io/blob/master/frontend/components/viewer/js/globals/unity-util.js#L416) now expects the object above instead of a single string

Had a brief look at 3drepo.io and it seems like the api list is embeded instead a function passed by the backend's config.js (which I still don't understand why it does this...). The easiest way might be to just add an extra field within this config so we can just directly access this array?

**Comment by carmenfan** [comment]
@JamesMilnerUK  I've updated this branch with a version of unity with the change. Can you look into changing the front end?

**Comment by JamesMilnerUK** [comment]
I have pushed the changes for the frontend to the branch
