### ISSUE TITLE
Limit the number of concurrent web requests done by unity

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#539]
When we load a massive model, it seems to bring the server down. (federation of really big models can lead to many asset bundles being fetched.)

limiting the amount of concurrent requests should hopefully help relief this.

relies on https://github.com/3drepo/3drepounity/issues/63

**Comment by JamesMilnerUK** [comment]
I assume this is a short term fix? The problem seems to be deeper rooted, i.e. https://github.com/3drepo/3drepo.io/issues/500

**Comment by carmenfan** [comment]
it's part of effort that will stay. Matter of fact is there are models which launches like 140 requests simultaneously if we don't restrict it. 1. we don't want to DDOS ourselves and 2. I imagine this will cause mad context switching that's ineffective by nature

**Comment by JamesMilnerUK** [comment]
Fair points. I think it's worth experimenting at some point with different request limits to see if there is some sort of optimum.
