### ISSUE TITLE
End-to-end tests for viewer and issues page

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#549]
Having some basic support for model page will help ensure that there haven't been any obvious regressions, which should provide a bit more integrity to our CI tests. More in depth tests are needed for issues and tree.

- [x] Metadata button
- [x] Measure button
- [x] Clip button
- [x] Issues button
- [x] Tree button
- [x] Extent button
- [x] Navigation mode button
- [x] Revisions button and popup
 
Issues:

- [x] Issue list shows 
- [x] Add issue button exists 
- [x] Creating a comment works as intended
- [x] Editing an issue works as intended

**Comment by JamesMilnerUK** [comment]
Tempted to split this into two issues as E2E tests are so time consuming!

**Comment by JamesMilnerUK** [comment]
Let's call this done for now. Will reopen a new issue with additional tests at a later date.

**Comment by JamesMilnerUK** [comment]
Almost, I need to just double check it

**Comment by carmenfan** [comment]
Make sure you tagged it as staging when you've merged it or I won't know to tag the milestone/close the issue! :)
