### ISSUE TITLE
Display model or federation name instead of <root> in Tree

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#551]
![image](https://user-images.githubusercontent.com/760452/31990562-61d8b154-b96d-11e7-92a6-fee377b373cf.png)

**Comment by carmenfan** [comment]
This should only apply for federations, as it should not appear for individual models unless they named their root node as root. for e.g. sample model looks like this:
![image](https://user-images.githubusercontent.com/11945337/31990824-10d1a328-b96e-11e7-97b8-fe3484e525bf.png)
