### ISSUE TITLE
There is no available teamspace

### ISSUE THREAD

**Issue by garywangcn** [3drepo/3drepo.io#553]
After I install the 3drepo by following this readme:https://github.com/3drepo/3drepo.io/blob/master/README.md

And login to my local server with adminUser/admin, but there is no available teamspace, may I know how to setup my local server and configure user correctly?

![qq 20171026181344](https://user-images.githubusercontent.com/22828078/32047716-775aa476-ba79-11e7-9d69-dcfe22c27cdb.jpg)

**Comment by carmenfan** [comment]
Hi Gary,
Is adminUser your mongo administrator user? If that's the case it is not designed to be an active web user - the sole purpose of that account is to write to the database on behalf of all accounts.

You should go through the sign up procedure on the web server to properly create a user account to interact with the system. During the sign up procedure it will create your teamspace and sample project, provided you have the bouncer worker + queue service setup.

Unfortunately even if you managed to setup the infrastructure perfectly, I'm afraid the amount of operations you can do is limited as our unity bundle generator is closed source - thus you will not be able to upload new models and view it on your local instance.

To best try out our service I would strongly recommend you to create an account in our cloud service at https://www.3drepo.io. I understand you have problems with seeing reCaptcha, we can create an account for you and you can reset your password to bypass that. Please email support@3drepo.org for further assistance.
