### ISSUE TITLE
Meta Tab is popping up randomly

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#561]
* Go into project and look at some metadata:
![image](https://user-images.githubusercontent.com/11945337/32105802-9ad2799e-bb21-11e7-869a-9127eb636f59.png)

* Go to another model (or even the same model), meta tab persists:
![image](https://user-images.githubusercontent.com/11945337/32105844-c5abac8a-bb21-11e7-9bcd-9af1368ba254.png)

**Comment by JamesMilnerUK** [comment]
This has some reasonable refactoring to the DocsService
