### ISSUE TITLE
Move JavaScript over to TypeScript

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#567]
Adding in Angular 5 will be a big jump (#408). We can make that jump a lot smaller by moving over our JavaScript to TypeScript. We can also leverage the benefits of types (because lol JavaScript) going forward. 

I think I could convert the whole app in 2-3 days.

**Comment by JamesMilnerUK** [comment]
To clarify this shouldn't change the logic of the application in anyway, just the syntax and type checking at build time

**Comment by carmenfan** [comment]
You don't have to refactor anything?

**Comment by JamesMilnerUK** [comment]
Sorry, to clarify yes there would be refactoring. But there would be no changes to the actual logic, just the markup of the files. 

```javascript
(function () {
	"use strict";

	angular.module("3drepo")
		.component("someComponent", {
			controller: function(){
                               // Some logic
                        }),
			controllerAs: "vm",
			templateUrl: "templates/someComponent.html",
			bindings: {
				account: "<",
			}
		});

})();
```

would become:

```typescript
export const someComponent = {
  bindings: {
    hero: '<',
  },
  templateUrl: "templates/someComponent.html",
  controller: function() {

     // Logic stays the same

  }
};
```

The skeleton of the file would change but logic would remain the same. In short they compile to the same thing.

**Comment by carmenfan** [comment]
Just be careful and make sure you fully test everything you've change. I would suggest breaking it down to different issues per component (or groups of component) though. Would make it a lot easier to identify what broke things if any

**Comment by JamesMilnerUK** [comment]
The gulp tasks for creating JavaScript files and also a few folders have been moved over. Slowly we'll be over to TypeScript!
