### ISSUE TITLE
CorrelationID not assigned to Toy Models

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#568]
Normally, corID is set in model settings when the model/fed entry is created and removed once the processing has completed.

When opening a new account, two sample models and one sample federation are added.

The two sample models don't seem to get assigned a corID so the E-mail notification has an undefined corID.

**Comment by carmenfan** [comment]
@Charence  I have a feeling you added this when you did all the queue stuff?

**Comment by carmenfan** [comment]
closing in favour of v5
