### ISSUE TITLE
Permissions shortcut gives error message when changing permissions for other teamspace

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#576]
Model menu Permissions shortcut gives this error when changing permissions of a model from other teamspace, even if the user is project admin.
![image](https://user-images.githubusercontent.com/760452/32490344-bbbd35ae-c3aa-11e7-804e-1cc6b8c2ffa3.png)

**Comment by carmenfan** [comment]
Tried it as henry on my teamspace and it's erroring like mad!

![image](https://user-images.githubusercontent.com/11945337/32492382-fc20325c-c3b1-11e7-9e42-b457fe5362d5.png)

**Comment by carmenfan** [comment]
@JamesMilnerUK it's using the wrong teamspace (trying to access a BW model permission on my teamspace as Henry)
![image](https://user-images.githubusercontent.com/11945337/32492750-42fdd16a-c3b3-11e7-9ff1-4777730e19d7.png)
