### ISSUE TITLE
Teamspace admin isn't being shown as a project admin

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#577]
Logged in as henry, viewing my own teamspace:
![image](https://user-images.githubusercontent.com/11945337/32492309-c17c39b6-c3b1-11e7-82a0-33a079b117bb.png)

I'm obviously teamspace admin, but it's not showing a greyed out tick here.

**Comment by JamesMilnerUK** [comment]
Did you say this was fixed Carmen?

**Comment by carmenfan** [comment]
no, i fixed #575. This still happens.

I think this is because the project admin user doesn't have permissions to see who is a teamspace admin so it doesn't know about it

**Comment by carmenfan** [comment]
when I say #575 i mean #576 ....

**Comment by JamesMilnerUK** [comment]
Okaydokey
