### ISSUE TITLE
Allow changing of units on clipping plane

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#578]
If the units are in ft/inches, disable drop down.

if the units are m/cm/mm, have a drop down to allow user to use a different units.

Internal representation should always be in model units, the units should just be a display thing.

To test, ensure that 3m == 30cm == 300mm functions the same , i.e.:
* They clip on the same spot in the model
* The dragging bar is set to the same place
* dragging the bar should change the number appropriately on the number display

**Comment by JamesMilnerUK** [comment]
I'm implementing this on the same Issue as #579 because they are so related.
