### ISSUE TITLE
put yarn.lock on gitignore

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#587]
Continuous conflict on that file when i deploy to dev, prod.

James said it speed things put but ultimately it's slowing me down as the upgrade script keeps tripping on it!

**Comment by JamesMilnerUK** [comment]
Supposedly it's bad practice to put yarn.lock in .gitignore: https://stackoverflow.com/questions/39990017/should-i-commit-the-yarn-lock-file-and-what-is-it-for 

Specifically:

```
"Yarn resolves these issues around versioning and non-determinism by using lockfiles and an install algorithm that is deterministic and reliable. These lockfiles lock the installed dependencies to a specific version, and ensure that every install results in the exact same file structure in node_modules across all machines."
```

What is the error you get? Maybe we can find a way of fixing that first?

**Comment by carmenfan** [comment]
there's no error as such. But when yarn install is ran it writes to the lock file, meaning i keep getting merge conflict when I upgrade and have to manually reset the yarn lock file almost everytime. could be something in prod config that is not the same causing it to have a need to overwrite a lock file. 

sounds like this is a workaround for the shortcomings of people not setting their dependencies on package.jsons to specific versions?

**Comment by carmenfan** [comment]
![image](https://user-images.githubusercontent.com/11945337/32692669-2bb4e8d6-c714-11e7-9afb-385661479d1f.png)

**Comment by Charence** [comment]
@carmenfan @JamesMilnerUK I also get conflicts and build problems sometimes after pulling or merging. I get around this by removing the yarn.lock file and running 'yarn install', so the version on the repository isn't useful for me.

**Comment by carmenfan** [comment]
🙄

**Comment by JamesMilnerUK** [comment]
@carmenfan this should be less of a problem now we locked dependency versions. Also if you do yarn install when you get a conflict it will auto resolve the conflict (see https://code.facebook.com/posts/274518539716230)

**Comment by carmenfan** [comment]
it's not yarn install that we get a conflict on, but it's git pull

But after locking dependency i dont' think i've seen it on deployments so I'll let this go (for now)

**Comment by JamesMilnerUK** [comment]
@carmenfan what I mean is when you do the git pull (and get the conflict) then type yarn install and it will do the resolution for you :)

**Comment by carmenfan** [comment]
it won't though, because when you do git pull and you have local changes that conflict it won't even do the pull and produce the conflict file lol

either way. I'm fine with as is, we'll see what happens.
