### ISSUE TITLE
Error dialogue appears when all models are removed from a federation

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#591]
The error should not appear as this is expected behaviour.

![screenshot 2017-11-13 16 34 55](https://user-images.githubusercontent.com/1438332/32736959-af3fe6ce-c890-11e7-9de6-21606a6eb8dc.png)

**Comment by JamesMilnerUK** [comment]
I fixed the frontend inappropriately updating on failure. Need to check with @paloknapo and @carmenfan what the expected behaviour is around federations. Assuming empty federation is fine and this is a bug but good to confirm.
