### ISSUE TITLE
Upgrade to Unity 2017.2

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#595]
The latest unity is actually 2017.2, but this morning i failed to build a webgl version, so baby steps.

The index page look drastically different and it doesn't look like it uses a canvas anymore.  (see here: https://github.com/3drepo/3drepo.io/commit/724c74b36df2a70c51e2d97f51e86764755268d9#diff-85b1cc4ace803d59bde7665ffa364a66)

requires https://github.com/3drepo/3drepounity/issues/69

**Comment by JamesMilnerUK** [comment]
![image](https://user-images.githubusercontent.com/8822075/33024933-6233207a-ce04-11e7-88b3-95708df15b06.png)

**Comment by carmenfan** [comment]
upgraded to 2017.3 in #737
