### ISSUE TITLE
Groups are adding an entry in meshes

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#600]
Everytime we create a group, meshes which belongs in that group are modified with an entry with an array of group it belongs to.

This is redundant and I don't think we use it anywhere (also adding unncessary database queries), but need to check on this.

**Comment by carmenfan** [comment]
https://github.com/3drepo/3drepo.io/blob/master/backend/models/group.js#L84

**Comment by carmenfan** [comment]
This also relates to #599 if you want to look into it as well. My speculation is that because it's overwriting the obj, when you have 2 of the same you're overwriting one with a shared_id that's already converted, which is causing the a problem.

**Comment by Charence** [comment]
Closing this @carmenfan
