### ISSUE TITLE
Replace node.project to node.model in fulltree.json 

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#604]
This causes issues as the frontend is expecting node.model but the backend is providing node.project. This is also confusing for API users as a project is a project not a model now!

**Comment by JamesMilnerUK** [comment]
I have a unelegant fix in #563 which checks for node.model first and then node.project

**Comment by carmenfan** [comment]
to fix this properly we got to rename it on 3drepobouncer then do a massive migration.....

Not fond of it, we can do this when we have another need to regenerate the tree

**Comment by JamesMilnerUK** [comment]
Yeah sure, it's a nice to have I think

**Comment by carmenfan** [comment]
this is a bouncer issue if to be done.
