### ISSUE TITLE
Cannot reset recaptcha on signup page

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#605]
* Sign up with an existing username
* Gets error about user already exists
* Change username, sign up again
* it moans about invalid recaptcha 
![image](https://user-images.githubusercontent.com/11945337/33071802-e6ec980e-ceb4-11e7-921f-7f65328b04ff.png)

**Comment by JamesMilnerUK** [comment]
This issue also puts the signup page link on the signup button as per Jozef's request

**Comment by JamesMilnerUK** [comment]
Hard to test as ReCAPTCHA is only available on dev/prod, so probably worth pushing to dev and seeing if it works. As far as I can tell you just need to reset the captcha on failure (.catch) as we do with a success (.then)
