### ISSUE TITLE
Save viewpoint rotation centre with issues and issue comments

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#610]
Currently, the centre of rotation for viewpoints does not appear to be saved consistently along with issues or issue comments. Save it.

**Comment by carmenfan** [comment]
Pretty sure that's fixed in https://github.com/3drepo/3drepo.io/issues/582?

**Comment by Charence** [comment]
@carmenfan This is "in staging"?

**Comment by carmenfan** [comment]
nope, unless James fixed it.

It's in my to do to check why it stopped working. So i'll look into it in a bit.

**Comment by JamesMilnerUK** [comment]
Sorry got confused between this and the #583

**Comment by carmenfan** [comment]
this is now fixed in staging.
