### ISSUE TITLE
Use revision timestamp if there is no revision tag

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#613]
This makes it a little easier to understand in revisions/diff

**Comment by carmenfan** [comment]
Think we established that we should just display the timestamp if there's no tag on the front end.

The idea of tag came from github, only significant versions would be tagged (whilst in our use case it's increasing look like we're using it as a description of the commit...). 

We could do this, but this would require a db migration + a change on the bouncer. There is actually no change on the io side for this to happen.
