### ISSUE TITLE
Web server should not crash if there is an error with Mongo/Mongoose

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#614]
Not sure how to reproduce but some issue/connection with Mongo is bringing down the whole web server for me on local. First time I've seen it but in theory should never happen, so worth investigating.

![spectacle lh6514](https://user-images.githubusercontent.com/8822075/33368462-aa2e4b84-d4e9-11e7-81de-8c6cf2f44ab2.png)

**Comment by carmenfan** [comment]
Doesn't look like it's crashing if it's giving you session related log after the stack trace?

**Comment by JamesMilnerUK** [comment]
This is true, but the web server didn't return anything in the browser so it must be preventing requests from responding correctly.

**Comment by JamesMilnerUK** [comment]
Error is:

```sh
/home/james/Code/3drepo.io/backend/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^
MongoError: connection 13 to localhost:9000 timed out
    at Function.MongoError.create (/home/james/Code/3drepo.io/backend/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/home/james/Code/3drepo.io/backend/node_modules/mongodb-core/lib/connection/connection.js:184:20)
    at Socket.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:338:8)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Related:** 

https://stackoverflow.com/questions/29926210/2-line-nodejs-application-crashes-on-mongoose-connect-while-trying-to-connect

https://github.com/Automattic/mongoose/issues/4789

**Comment by JamesMilnerUK** [comment]
I'd recommend adding a error callback to mongoose and updating Mongoose/Mongo to latest versions on NPM

**Comment by carmenfan** [comment]
May have a fix for this. But i'd have to replicate a timeout somehow.

**Comment by JamesMilnerUK** [comment]
Perfecto

**Comment by carmenfan** [comment]
Latest mongodb driver we can use is 2.2.21. 

If we wish to upgrade (current version is 2.2.30, and there's a 3.0.0rc) I think we need #649
