### ISSUE TITLE
API to query supported plugin versions

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#615]
an api that will return you the list of supported plugin versions. Then we can have the plugins (navisworks, 3drepo4unity) to query this before doing anything and notify the user should they need an upgrade.

This will get rid of a lot of headache regarding to "I tried to log in but it's giving me a error 400" kind of scenario, simply because they're using an incompatible version.

**Comment by jozefdobos** [comment]
I'd say we should also split the API into versions so that we could run API v1 alongside v2 etc for graceful deprecation. And I understand sometimes there are DB upgrade scripts but that would be the hard cut-off point for which we would plan long in advance.

**Comment by carmenfan** [comment]
How much do we really care about this? It would save a lot of headache if we can just force the user to upgrade.

What you want is potentially a logistics nightmare. Running different versions of api literally means launching multiple instances of node with different versions of the code base. And if it is a plugin-breaking change chances are it's a different way of writing things to database or something that drastic. If it's just a rename of the api or something we could just support those deprecated apis for a while before we kill them off.

 I'd rather we stick with 1 version of api server, and utilising this api to give you 2 list, one with a list of versions that are fully supported and the other being a list of versions which is recommended for upgrade. so if the version is not on the list -> you can't use it until you upgrade; if it's recommended for upgrade, give warning about upgrading and still let the user use it.

**Comment by jozefdobos** [comment]
I would just do a bunch of routing calls in the express side of things designated as .
.../api/v1/,  
..../api/v2/, etc. 
does not need a separate server instance for sure.
