### ISSUE TITLE
Add explanations to Assign Permissions UI

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#620]
Currently, there is no explanation of what any of the settings in Permissions mean. For instance an admin on teamspace allows for different permissions to having an admin on model, etc:

![image](https://user-images.githubusercontent.com/3008807/33494985-c0f310a0-d6bc-11e7-96f3-a5b53645c897.png)

So what we need is in place descriptions for different settings like done in Wordpress back-end section:
![image](https://user-images.githubusercontent.com/3008807/33495056-f856f9bc-d6bc-11e7-955e-ca220491f99e.png)

**Comment by JamesMilnerUK** [comment]
I've made some improvements on this. Still need to discuss with Andrew / Pavol what we want everything to say.
