### ISSUE TITLE
Decommission slate and go for an automatic documentation generation tool

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#630]
As it stands, we're using [slate](https://github.com/lord/slate). As pretty as it is, it is done statically by creating .md files mapping to your program (see our sources [here](https://github.com/3drepo/3drepo.io/tree/master/backend/doc/source/includes))

Going forward (unless we hire a documentation guy...), we should get rid of that and use an autogenerated tool.  Had a brief look and [yuidoc ](http://yui.github.io/yuidoc/)seems to be a decent choic. [Syntax](http://yui.github.io/yuidoc/syntax/index.html) is almost identical to doxygen (which is the format of choice we use in the c# and c++ code), and the generation tool is on npm (doesn't look like we need ruby or anything crazy, unlike some of them - including slate!)

I have plans to refactor backend (or get the new guy to refactor backend, depending on what happens), which would be a good opportunity to add it in.

**Comment by JamesMilnerUK** [comment]
Maybe I'm missing something but those tools look like they document internal functions. I think we want to be exposing documentation for the external HTTP API, maybe something like http://apidocjs.com/ or https://www.npmjs.com/package/jsdoc-route-plugin might be more appropriate

**Comment by carmenfan** [comment]
Ideally we want both. (we really should also have something for front end as well)

If we can find one that can have a route tag so it knows to sort itself out then perfect. If not we technically have all routes in a routes folder so we just need to point the user in a particular section of the whole doc

**Comment by JamesMilnerUK** [comment]
Yeah, we could so something like this on all the routes using apiDoc?

```javascript
/**
 * @api {get} /user/:id Request User information
 * @apiName GetUser
 * @apiGroup User
 *
 * @apiParam {Number} id Users unique ID.
 *
 * @apiSuccess {String} firstname Firstname of the User.
 * @apiSuccess {String} lastname  Lastname of the User.
 */
```

Looks pretty clean

**Comment by carmenfan** [comment]
close in favour of #1230
