### ISSUE TITLE
Intermittent Unity error in console

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#631]
Probably passing some null variable into one of the UnityUtil functions at some point. Need to just log them all out and figure out which one.

```
ArgumentNullException: Argument cannot be null.
Parameter name: key

 
(Filename: currently not available on il2cpp Line: -1)
```

**Comment by carmenfan** [comment]
you are going to need to elaborate on how to produce that. This is a generic dictionary fail to find a matching key kind of behaviour.

**Comment by JamesMilnerUK** [comment]
That's sort of the problem, it's not easy to reproduce or pin down. It's not apparently obvious as sometimes it never occurs at all, other times it spams the console when models are just simply loading. The only case I've noticed when I saw it explicitly was with moving the clipping tool.

Essentially if you reload any model and interact with it you'll eventually see it occur in the console.

**Comment by JamesMilnerUK** [comment]
Putting 

```
	console.log(methodName, requireStatus, params);
``` 

in `UnityUtil.toUnity` appears to indicate `clearHighlight` is causing the error. The error appears intermittent however. Sometimes it doesn't occur at all, sometimes it spams the console.

**Comment by JamesMilnerUK** [comment]
I haven't seen this recently, might have just been that I didn't rebuild Unity! I'll close for now, can reopen if it comes back.
