### ISSUE TITLE
Example of using Viewer/UnityUtils standalone

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#640]

**Comment by carmenfan** [comment]
@JamesMilnerUK , just had a quick look at your demo html page commit

We need to do it in the assumption that the person is not pulling the code base off git (this is a sample demo of how people would integrate with our existing service), so the code that is script src needs to be from https://www.3drepo.io/...

Hence i would strip it down, they don't need pin.js, they don't need viewer.js. it should be sufficient to get the unity compiled scripts + unityutils for basic control. The rest of the things should be expected to be done on the integrator side.

**Comment by carmenfan** [comment]
Key points to demostrate in there would be how to login (can create a dummy account on prod to show), and how to load a model

**Comment by JamesMilnerUK** [comment]
We can compile a script that we can host on 3drepo.io which just includes UnityUtil but will probably need a little extra boilerplate in the demo file (not a big deal).

**Comment by JamesMilnerUK** [comment]
For Unity scripts we can actually point directly at 3drepo.io, not a problem
