### ISSUE TITLE
tree data structure refactoring

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#643]
Again, as we all know, there is a lot of junk in the tree data structure.

* We don't need the tree path within the tree node. As far as I know we never use it. we have ID to path as a separate API
* We don't need shared ID within the tree node. We can use the mapping from the new API that Desktop version uses.
* Do we even use ID to name anywhere? I believe we know have a ID to node mapping somewhere in the front end, we probably don't need this?

**Comment by JamesMilnerUK** [comment]
Sounds good! Should be fairly apparent if that removing any of those breaks anything in the frontend fairly quickly just by interacting with the tree, so we could just remove them one by one and make sure there's no unintended side effects / errors.
