### ISSUE TITLE
Change the way we authenticate

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#649]
the way we authenticate users is going to be deprecated (see [here](https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/admin.js#L244))

Seems like going forward we would have to do authenticate by separate connection

**Comment by JamesMilnerUK** [comment]
I see! How would we need to change it exactly?

**Comment by carmenfan** [comment]
Closing this. we'll change this when we upgrade mongo driver.
