### ISSUE TITLE
Vulnerability in Math.js

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#653]
Solution is to upgrade

**Comment by JamesMilnerUK** [comment]
Trawling the code it looks like we don't even use Math.js?

**Comment by JamesMilnerUK** [comment]
I lie, it's used in the x3dom_encoder.js file. Do we still need that @carmenfan ?

**Comment by carmenfan** [comment]
Yup we still need it for the people who use the dll for unity.

There are plans to move them across to asset bundle, but requires some work on my end. might worth just putting a note on the decomissioning x3d issue to remove math.js as well

**Comment by JamesMilnerUK** [comment]
I can't find the x3dom issue, is there one @carmenfan ?

**Comment by carmenfan** [comment]
closing in favour of #894
