### ISSUE TITLE
Units discrepancy between Quota available and Quota used

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#665]
For my account on dev, quota available is in MB and quota used is in GB

See here:
![image](https://user-images.githubusercontent.com/11945337/34518997-fb99f508-f079-11e7-997d-6a07374cc47f.png)

**Comment by jozefdobos** [comment]
We should also make it show increase in quota as the user adds more licences. At the moment it is very confusing because whenever I add or remove Users field, I would naturally expect to see increase (ie see what I'm about to buy type of thing).

**Comment by JamesMilnerUK** [comment]
I'm not sure this ever made it's way into staging...

**Comment by carmenfan** [comment]
![image](https://user-images.githubusercontent.com/11945337/36370404-ad6074e6-1556-11e8-8f9d-0ab02a5771c7.png)
unless you did the same fix again in some other places, doesn't look like it.
