### ISSUE TITLE
Entity Too Large error potentially when creating groups

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#671]
To replicate:

- find a large model
- select and isolate an object
- create and save issue

Result: Internal Server Error - request entity too large "entity.too.large"

Cause: Request payload for hiddenObjects becomes too large for groups to handle

Test case: A3 cooling tower, 15899 objects in hiddenObjects

**Comment by JamesMilnerUK** [comment]
This might be of interest:

https://stackoverflow.com/questions/19917401/error-request-entity-too-large

**Other potential solutions:** 

Change the data structure
Use something like MessagePack to decrease transfer size

**Comment by Charence** [comment]
Size limit increased for JSON bodyParser. Not sure if this is sufficient.
