### ISSUE TITLE
BCF Support

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#677]
- [x] Expose mandatory fields
- [x] Expose 'Due Date' field
- [x] Store IFC GUIDS in Groups
- [x] BCF import/export
- [x] Clean up Group code (#599 and #600)
- [x] Warning if orthogonal view in BCF
- [x] Remove own yauzl fork #506

**Comment by carmenfan** [comment]
while you at it, deal with https://github.com/3drepo/3drepo.io/issues/506 :)

yauzl is only used in BCFs

**Comment by Charence** [comment]
BCF only seems to have the following mandatory fields:

```
<Markup>
  <Topic Guid="xyz">
    <Title />
    <CreationDate />
    <CreationAuthor />
  </Topic>
</Markup>
```

@PavolKnapo @carmenfan

**Comment by JamesMilnerUK** [comment]
@Charence I think this is a good opportunity to fix this: https://github.com/3drepo/3drepo.io/issues/506

**Comment by carmenfan** [comment]
might worth looking at #600 and #599 while you're at it

**Comment by JamesMilnerUK** [comment]
I fixed the date order for the date picker to be UK centric

**Comment by Charence** [comment]
showOrthogonalView function added to issues.service - placeholder for user feedback when loading orthogonal view that currently leaves a console log.
