### ISSUE TITLE
Revision ID for sample project is wrong

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#684]
Writing a comment on sample project model/federation causes an error:

```json
{"message":"Model history not found","status":404,"code":"MODEL_HISTORY_NOT_FOUND","value":19,"place":"PUT /revision/a8be1dbd-ec0b-4710-804e-b46687089841/issues/a1f14e40-5a7c-11e7-afac-a1642d3e566d.json"}
```

**Comment by carmenfan** [comment]
This is actually a bouncer issue as the import script lives in the bouncer repo.

the script is here: https://github.com/3drepo/3drepobouncer/blob/master/tools/bouncer_worker/importToy.js

And actually it doesn't look like it changes the rev id at all. Maybe it's just an issue of a discrepancy on the exported data
