### ISSUE TITLE
Improve performance of teamspace page

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#690]
At the moment having lots of items in teamspace causes it to slow down quite considerably (also creates a websocket connection per item) so would be good to get this smarter.

Ideas:
1) Use ng-if rather than ng-show
2) Use virtual repeater

**Comment by JamesMilnerUK** [comment]
Covered Use ng-if rather than ng-show in #680

**Comment by carmenfan** [comment]
N/A due to react migration
