### ISSUE TITLE
Examine Tree performance (again)

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#705]
The tree still isn't quite perfect, especially with large models with issues with high quantities of nodes shown/hidden.

Things to think about:

1. Web Workers
2. Overall approach (data structure / algorithms)
3. Code profiling for offending functions
4. Over the wire transfer (see #689)

**Comment by JamesMilnerUK** [comment]
Highlighting and visibility in the Tree are reasonably fast now:

For example on the Skanska federation (/T_E_S_T/1c4df068-1373-4290-8702-5476fe4ccdc3):

Highlighting:
![screenshot_20180328_120259](https://user-images.githubusercontent.com/8822075/38025491-86ecfd10-3280-11e8-8fc5-ec47aa2bd7c1.png)

Visibility:
![screenshot_20180328_120046](https://user-images.githubusercontent.com/8822075/38025502-8dccd844-3280-11e8-94a0-4efd9015cc83.png)

It looks like the bottle neck for those is in lies in the Unity VM execution, which I'm not sure how much control we have over.

Regarding the bottle neck in #833 - It's slow but it's not crashing/close the window slow. I think a big problem is spent in traverseNodeAndPushId. Examining the function we don't do much to prevent traversing down tree nodes we've already examined so that could be a perf optimisation!

![spectacle m32665](https://user-images.githubusercontent.com/8822075/38025687-249a42ca-3281-11e8-9575-0ec34c4265ac.png)

Anyway one to think about in the long term.

**Comment by carmenfan** [comment]
closing this as it is too long term. Plus we've made heaps of progress since Feb!
