### ISSUE TITLE
Virtual Repeater doesn't always resize correctly in Tree panel

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#713]
![screenshot 2018-02-06 10 26 06](https://user-images.githubusercontent.com/1438332/35854544-85e307c2-0b28-11e8-8091-e76bb77e384f.png)
![screenshot 2018-02-06 10 26 24](https://user-images.githubusercontent.com/1438332/35854545-85f5f49a-0b28-11e8-94c3-5f13e0bb01e7.png)
![screenshot 2018-02-06 10 26 34](https://user-images.githubusercontent.com/1438332/35854546-86090742-0b28-11e8-963c-9ee4ce8f21ee.png)
![screenshot 2018-02-06 10 26 52](https://user-images.githubusercontent.com/1438332/35854547-861b8552-0b28-11e8-8fba-6eef6f5dabb9.png)
![screenshot 2018-02-06 10 27 19](https://user-images.githubusercontent.com/1438332/35854548-86377a5a-0b28-11e8-80eb-84f35628d941.png)
![screenshot 2018-02-06 10 27 32](https://user-images.githubusercontent.com/1438332/35854549-864c0c18-0b28-11e8-8296-b197cd532a2c.png)

**Comment by JamesMilnerUK** [comment]
This is very hard to fix. We use AngularJS Material which is no longer supported, and getting the virtual scroll box to resize effectively is quite problematic. 

See https://github.com/angular/material/issues/4314

I haven't tried this, but not sure if it's even the right solution: https://stackoverflow.com/questions/34912151/is-there-a-way-to-refresh-virtual-repeat-container

**Comment by Charence** [comment]
@JamesMilnerUK 

Case 1:

- Go to http://127.0.0.1/charence/15809152-e513-4f4d-9e06-247bfc40bf60 (a model with no issues)
- Open Tree panel
- Select an object in viewer

Case 2:

- Go to http://127.0.0.1/charence/f724a3ba-945e-4939-9c16-1c26f9279d5b (a fed with a few issues)
- Open Tree panel
- Select an object in viewer

Case 3:

- Go to http://127.0.0.1/charence/1556f6b2-7db9-4ce3-bb73-24b6ad82073c (a model with many issues)
- Close Issues panel
- Open Tree panel
- Select an object in viewer (the problem is most pronounced here when Issues panel has gone)

It seems like the positioning of the virtual repeater is somehow linked to the panel above it. In the above screenshots, you can see that the virtual repeater and its elements extends beyond the top of the Tree panel.

**Comment by JamesMilnerUK** [comment]
@Charence think I have a fix for this but also I'm blocked by #716. Can you take a look when you've got a second?
