### ISSUE TITLE
Error opening issue

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#716]
I went on this issue:

http://127.0.0.1/charence/f724a3ba-945e-4939-9c16-1c26f9279d5b

And recieved the follow errors: 
![spectacle nns310](https://user-images.githubusercontent.com/8822075/35867025-a2180442-0b50-11e8-8373-3d4efec32b17.png)

Checking the backend I got this error:
![spectacle m32704](https://user-images.githubusercontent.com/8822075/35867035-aaaf425a-0b50-11e8-9972-1fb7f72b8aef.png)

**Comment by JamesMilnerUK** [comment]
@Charence just had a thought; guessing this might be caused by the fact its a new issue but your BCF changes aren't in staging yet

**Comment by carmenfan** [comment]
@Charence  is this still a bug? or it's fixed somewhere?

**Comment by Charence** [comment]
@JamesMilnerUK @carmenfan There are errors because it's an issue with IFC GUID groups. It's not an issue.
