### ISSUE TITLE
Group element and DEF attributes in X3D are encoded with incorrect case for first node of scene

### ISSUE THREAD

**Issue by sebjf** [3drepo/3drepo.io#73]
The first group node under the scene of the head X3D is in some cases written as 'group' (not Group) with the DEF attribute 'def' not 'DEF'. W3C [specifies](http://www.w3.org/TR/html-markup/documents.html#case-insensitivity) that unlike html, xml elements and attributes are case sensitive and so this may cause problems for third party parsers.

This occurs at least in https://3drepo.io/api/buildingsmart/Office_S_20110811/revision/master/head.x3d.mp and https://3drepo.io/api/buildingsmart/Office_A_20110811/revision/master/head.x3d.mp

**Comment by timscully1983** [comment]
Fixed
