### ISSUE TITLE
optimise OSM fetches

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#739]
- [x] use a[ keep alive agent ](https://www.npmjs.com/package/keep-alive-agent)to keep socket connections - this should reduce timeouts
- [x] Remove previous unwanted requests from the queue of requests when we change zoom level (unity change)

**Comment by JamesMilnerUK** [comment]
Could we also cache the tiles?

**Comment by carmenfan** [comment]
Doesn't really make a lot of sense to cache it on the server, better off caching on the client.

In which case it's an optimisation on the unity side. It also doesn't really help the problem we have right now, which is reloading a whole load of tiles when we reach a new zoom level.

But yes we can cache it, but what do we cache is another question (do we cache the prev/next zoom level? do we cache the neighbouring tiles of the same zoom level? how much should we cache without risking the user getting closer to the memory limit, etc.) I wouldn't worry about it now unless it shows that it will solve our problems.

**Comment by JamesMilnerUK** [comment]
Yeah, we should add caching headers for the client as a minimum (if we haven't already). I've also got some other concerns which I'll take offline.
