### ISSUE TITLE
File upload/import

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#75]
Allow user to upload a 3D Model and process.

This is an issue related to https://github.com/3drepo/3drepobouncer/issues/26

What is needed:
- A UI to upload file
- API server to get the file from user and place in a predefined shared space
- implementation of a rabbitmq client to dispatch work to queue

**Comment by carmenfan** [comment]
Upload is now supported on the API service (merged in master).

It requires an extra object within the configuration json, cn_queue, to indicate the information about the queue or it will not function. (with error 404) 

To run it, you need the following:
- API service to have a configuration with cn_queue (see config_sample.js)
- A bouncer working active on the dedicated compute node (with the right configuration setup to talk to the queue
- A rabbitmq (or technically any queue supporting amqp protocol) instantiated with the config files of client + worker both connecting to it successfully)
- ensure the cn_queue.tmp_dir/cn_queue.storage_dir folders exists

Outstanding issues:
- no webservice support to call this API as of yet
- queueing needs more testing, may be fragile, not tested with multiple requests
- don't think I am closing the connection to the queue... but i'm forevering instantiating them... can't be that healthy.
- POST response actually waits for the file import to finish (which can potentially take hours... We need to think of when and what to send back to the user)

**Comment by timscully1983** [comment]
Complete
