### ISSUE TITLE
Automatically assign permissions on submodels

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#757]
When I add permissions on a federation, a pop-up appears notifying the user that they need to manually enable permissions on each submodel. Can we add a button that would just automatically set those if they user clicks it? The buttons could be something like: "Update All" and "I'll do it Later" or so.

![image](https://user-images.githubusercontent.com/3008807/36664752-9250da10-1add-11e8-95ab-9c0431b4e91e.png)

**Comment by carmenfan** [comment]
If we do that we probably need the same thing for mass revoke

**Comment by carmenfan** [comment]
Closing this as the new UI gives a different user journey which makes this process easier
