### ISSUE TITLE
reoccuring fatal error messages that doesn't seems to be fatal

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#758]
![image](https://user-images.githubusercontent.com/11945337/36668801-5d7be3ae-1aea-11e8-805b-b79934a41ef0.png)

seems to happen on both prod and dev (havent' checked my local but i think i've seen this before as well).

@JamesMilnerUK  any clues what this is complaining about? is it just some legacy things?

Can we remove it or at the very least, change its severity level to warning (As it doesn't stop the system from running correctly i don't think it should be under `fatal`)

**Comment by JamesMilnerUK** [comment]
Fixed in #750 . Issue was we were loading pug files for dynamic rendering, which we don't actually do any more.
