### ISSUE TITLE
"Quota used" does not seem to update

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#779]
Quota in billing does not seem to update even though I have deleted projects in order to clear space. This is observed on a free tier in production so worth checking also on accounts with several licences.

**Comment by carmenfan** [comment]
This looks like it's because deleting a project doesn't seem to deleting the underlying models. definitely a bug.

**Comment by carmenfan** [comment]
closing this in favour of putting it in the bug list https://github.com/3drepo/3drepo.io/issues/774#issuecomment-370832135

**Comment by carmenfan** [comment]
@jozefdobos this is fixed in #774 but you won't see update on the quota page unless you refresh - how important is this?

**Comment by jozefdobos** [comment]
As long as it goes out with the immediate release (whenever ready) that works for me. So far we had no one external complain about it.

**Comment by carmenfan** [comment]
It's going out with 2.8. I might fix the refresh thing on 2.10 (it's too close to all the subscription changes i'm making so i'd refrain from editing all that for 2.8 unless it's vital)

**Comment by carmenfan** [comment]
quota update is now done in #763
