### ISSUE TITLE
query string does not update when you click on the billing page link

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#793]
In license & job tab, when you have assigned all the licenses, the billing page link appears:

![image](https://user-images.githubusercontent.com/11945337/37202428-61cebd3c-2382-11e8-9a94-159c0aa5487d.png)

Clicking on this directs me to the billing page fine, but the query string does not update:
![image](https://user-images.githubusercontent.com/11945337/37202469-77ed69ce-2382-11e8-834f-e6ebea02973d.png)

**Comment by JamesMilnerUK** [comment]
Accidentally did on the same branch as #791 but they're on the same page so meh :P
