### ISSUE TITLE
2.7.9 Bug list

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#796]
- [x] Solibri BCF imports are missing highlighting
- [x] BCF import should overwrite status & flags
- [x] Add a comment -> change status -> the comment is missing from view
- [x] Add system messages indicating what has changed from the BCF import
- [ ] [Creating federation console error](https://github.com/3drepo/3drepo.io/issues/796#issuecomment-372283384)
- [x] BCF Import failed, but the UI still thinks it's importing

**Comment by paloknapo** [comment]
**Creating federation console error**

This appears with New Federation pop up
![image](https://user-images.githubusercontent.com/760452/37282110-33c3c138-25eb-11e8-9f9a-a631e19f0d01.png)

**Comment by carmenfan** [comment]
This needs merging into staging.
