### ISSUE TITLE
Merge 2.7.9 bug branch and Fix comment saving in TypeScript issue.component.ts

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#800]
There is a bug with screenshots disappearing on updating of an issue: https://github.com/3drepo/3drepo.io/issues/796

We need to update this in the TypeScript files

**Comment by carmenfan** [comment]
I also changed something on the issue front end in #796 (promise rejection wasn't being handled when BCF import failed)
This is the commit : https://github.com/3drepo/3drepo.io/commit/f20b0d23530af0c942a38f6489f4045f3c01eab8
