### ISSUE TITLE
Screenshot drawing error

### ISSUE THREAD

**Issue by horandago** [3drepo/3drepo.io#809]
![image](https://user-images.githubusercontent.com/23435379/37356775-a884db62-26de-11e8-8ae5-f597238c206a.png)

**Comment by carmenfan** [comment]
@horandago  @JamesMilnerUK  is this still applicable?

**Comment by JamesMilnerUK** [comment]
@horandago @carmenfan this should be fixed here: https://github.com/3drepo/3drepo.io/commit/7b982512b96c431f39b139f2e9a9b541c433692e#diff-d4bc3bfa36c7b83be5aac519a507ea30L180
