### ISSUE TITLE
Bugs 2.7.11

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#814]
- [x] Multiple clipping planes are not supported
- [x] Unity Broadcast is broken
- [x] Some BCF clipping plane are not represented properly
- [x] [Assigned job appears in Status list](https://github.com/3drepo/3drepo.io/issues/814#issuecomment-373001989)
- [x] [Imported status not shown in import message](https://github.com/3drepo/3drepo.io/issues/814#issuecomment-373004885)

**Comment by paloknapo** [comment]
**Assigned job appears in Status list**

1. Create new or open existing issue
2. If issue unassigned Status shows [], if assigned Job is listed
3. Un-assign  issue and Job stays in Status list

![image](https://user-images.githubusercontent.com/760452/37402035-f4ea4f02-2781-11e8-8f01-3be8ca3bca47.png)
![image](https://user-images.githubusercontent.com/760452/37402124-4b03c9fe-2782-11e8-9e32-b8e060371cb8.png)

**Comment by paloknapo** [comment]
**Imported status not shown in import message**
![image](https://user-images.githubusercontent.com/760452/37402550-eaf038de-2783-11e8-97f7-cc7447509b85.png)
