### ISSUE TITLE
Sample model behaves weirdly with map tiles on

### ISSUE THREAD

**Issue by jozefdobos** [3drepo/3drepo.io#820]
![image](https://user-images.githubusercontent.com/3008807/37491051-66fecd44-2894-11e8-9141-e9413d80d434.png)

Steps to reproduce:
- load sample model
- enable map tiles
- zoom out
- select sample 3D Diff issue

**Comment by carmenfan** [comment]
looks fine to me
![map](https://user-images.githubusercontent.com/11945337/37512813-0dc97e74-28fb-11e8-85df-fc420b17044d.gif)

**Comment by carmenfan** [comment]
pretty sure we addressed this before we released 2.8
