### ISSUE TITLE
New Federation pop up throws an error

### ISSUE THREAD

**Issue by paloknapo** [3drepo/3drepo.io#828]
Everything works fine, federation is created, just this is in console:

![image](https://user-images.githubusercontent.com/760452/37665539-67868dc8-2c55-11e8-9cdf-f665e4ddcb79.png)

**Comment by JamesMilnerUK** [comment]
Unfortunately this is a bug/design flaw in Angular Material: https://github.com/angular/material/issues/6820
I will look into a work around if I get the time.
