### ISSUE TITLE
Hanging when loading issues with many IFC components

### ISSUE THREAD

**Issue by Charence** [3drepo/3drepo.io#833]
21024 IfcGuids - crash (solibri BCF: c4eaf)
4542 IfcGuids - ok (skanska_solibri: 5074b)

**Comment by carmenfan** [comment]
I uploaded it here: 
https://dev.3drepo.io/carmen/cc456226-b935-4d82-ad32-96ff495aefdd

**Comment by carmenfan** [comment]
Problem is, once again, the tree.

so This is essentially #705

**Comment by carmenfan** [comment]
I'm closing this unless we see this again. Tree is migrated to React
