### ISSUE TITLE
Groups Refactoring and fixing BCF Imports/export

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#895]
- [x] Remove prune nodes
- [x] Change Group Schema from:
````js
{ {
    "_id" : LUUID("8d5d04f0-25fc-11e8-81c5-6f7910099fb1"),
    "objects" : [ 
        {
            "account" : "carmen",
            "model" :  <some model>,
            "shared_id" : sharedID1
        }, 
        {
            "account" : "carmen",
            "model" :  <some model>,
            "shared_id" : sharedID2
        }, 
        {
            "account" : "carmen",
            "model" :  <some model>,
            "shared_id" : sharedID3
        }
    ]
    ...
}}
````
to:
````js
{ {
    "_id" : LUUID("8d5d04f0-25fc-11e8-81c5-6f7910099fb1"),
    "objects" : [ 
        {
            "account" : "carmen",
            "model" :  <some model>,
            "shared_ids" : [sharedID1, sharedID2, SharedID3]
        }
    ]
    ...
}}
````
- [x] Change backend to support this schema
- [x] Change front end to support this schema
- [x] Create db migration script to change existing groups to this format
- [x] Create db migration script to unprune existing group nodes (might worth doing this in C++ for easiest expansion)
- [x] Add restrictions to reject group request in bad format (i.e. ensure groups are in the new schema format, and model/account name is not missing etc)
- [x] Remove groupTest check on schema migration script when done
- [x] Ensure highlighting/isolation issue saves are working
- [x] Ensure empty groups are not saved from issues (Groups tab is fine)

**Comment by JamesMilnerUK** [comment]
whilst we're here can we change `shared_id` to `sharedIds`?

**Comment by carmenfan** [comment]
Created a new user on dev called groupTest for this, so we don't ruin the group schema for other development/dev testing.

**Comment by Charence** [comment]
@carmenfan Are we sure we want to reject the request if model/account name is missing?
