### ISSUE TITLE
this.state.groups does always exist causing error and no rendering of groups

### ISSUE THREAD

**Issue by JamesMilnerUK** [3drepo/3drepo.io#937]
![spectacle m28087](https://user-images.githubusercontent.com/8822075/39373658-2c5813bc-4a40-11e8-8379-92e11ecfd1ef.png)

**Comment by carmenfan** [comment]
@Charence  is this not fixed or ? I see you made a pull request that was closed

**Comment by Charence** [comment]
@carmenfan It is not fixed. The error is "forEach is not a function" rather than something not being defined, which my change didn't address.

I haven't been able to reproduce this bug yet.

**Comment by JamesMilnerUK** [comment]
I haven't seen this on staging since this issue

**Comment by carmenfan** [comment]
I'm going to go ahead and close this then.
