### ISSUE TITLE
Do not try to delete  files after upload if correlation ID is undefined

### ISSUE THREAD

**Issue by carmenfan** [3drepo/3drepo.io#956]
### Description
On the server you can occasionally see errors where it tries to delete some parameter files for upload that doesn't exist.

I think this happens when the upload command was import sample model, which wouldn't have a parameter file and doesn't have a correlation ID it seems?

![image](https://user-images.githubusercontent.com/11945337/39577274-be528bca-4ed8-11e8-9184-ec344a0d04fc.png)

I believe we just need to check if correlation id is undefined, don't try to delete files.

### Steps to replicate
- Import sample model
- observe the log

**Comment by Charence** [comment]
Does this relate to #568 ?

**Comment by carmenfan** [comment]
Maybe, but I'm not sure if there's any files to delete anyway

**Comment by carmenfan** [comment]
N/A with V5
